import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import { authTables } from '@convex-dev/auth/server';

// ACE Child Grow — Convex schema.
// authTables provides `users`, `authSessions`, etc. (managed by Convex Auth).
// Every private table carries `userId` (the owning parent) and is queried only
// via `by_user` indexes filtered to the authenticated identity — the server-side
// equivalent of the P0 "no child data across accounts" guarantee.
export default defineSchema({
  ...authTables,
  // Convex Auth indexes verifiers by signature for the sign-in flow. Account
  // erasure also needs to remove every verifier belonging to a session without
  // scanning the whole auth table.
  authVerifiers: authTables.authVerifiers.index('sessionId', ['sessionId']),

  // Parent consent + preferences (one row per user).
  parentProfiles: defineTable({
    userId: v.id('users'),
    displayName: v.optional(v.string()),
    preferredLocale: v.union(v.literal('mm'), v.literal('en')),
    consentAcceptedAt: v.optional(v.number()),
    privacyNoticeVersion: v.optional(v.string()),
    // Staff flag for the Admin CMS. Granted by a super admin (or, in dev, via the
    // Convex dashboard). Content-workflow mutations require this to be true.
    isStaff: v.optional(v.boolean()),
    staffRole: v.optional(
      v.union(
        v.literal('owner'),
        v.literal('content_editor'),
        v.literal('language_reviewer'),
        v.literal('evidence_reviewer'),
        v.literal('clinical_reviewer'),
        // Runs the review workflow: sees the whole priority queue, triages
        // Class D/E, confirms required dimensions and requests reviews. It
        // records NO review decision and cannot publish — managing the queue
        // and signing off on content are deliberately different powers.
        v.literal('review_manager'),
        v.literal('support'),
      ),
    ),
    staffQualification: v.optional(v.string()),
    parentTourCompletedVersion: v.optional(v.number()),
    staffTourCompletedVersion: v.optional(v.number()),
  })
    .index('by_user', ['userId'])
    .index('by_is_staff', ['isStaff'])
    .index('by_staff_role', ['staffRole']),

  // Invite-only staff onboarding. The raw invitation code is returned once to
  // the owner and never stored; only its SHA-256 digest is persisted.
  staffInvites: defineTable({
    email: v.string(),
    displayName: v.string(),
    role: v.union(
      v.literal('owner'),
      v.literal('content_editor'),
      v.literal('language_reviewer'),
      v.literal('evidence_reviewer'),
      v.literal('clinical_reviewer'),
      v.literal('review_manager'),
      v.literal('support'),
    ),
    reviewerQualification: v.optional(v.string()),
    codeHash: v.string(),
    // Existing accounts are bound immediately. Pre-signup invitations remain
    // email-bound until the invited person creates an account and claims them.
    targetUserId: v.optional(v.id('users')),
    status: v.union(v.literal('pending'), v.literal('accepted'), v.literal('revoked'), v.literal('expired')),
    invitedBy: v.id('users'),
    invitedAt: v.number(),
    expiresAt: v.number(),
    acceptedBy: v.optional(v.id('users')),
    acceptedAt: v.optional(v.number()),
  })
    .index('by_email', ['email'])
    .index('by_code_hash', ['codeHash'])
    .index('by_status', ['status'])
    .index('by_target_user', ['targetUserId'])
    .index('by_invited_by', ['invitedBy'])
    .index('by_accepted_by', ['acceptedBy']),

  // Billing-provider-neutral subscription state. Stripe (or another provider)
  // can be connected later without changing parent or child records.
  subscriptions: defineTable({
    userId: v.id('users'),
    planKey: v.union(v.literal('free'), v.literal('premium'), v.literal('family')),
    status: v.union(
      v.literal('active'),
      v.literal('trialing'),
      v.literal('past_due'),
      v.literal('canceled'),
      v.literal('paused'),
    ),
    provider: v.optional(v.string()),
    providerCustomerId: v.optional(v.string()),
    providerSubscriptionId: v.optional(v.string()),
    currentPeriodEnd: v.optional(v.number()),
    cancelAtPeriodEnd: v.optional(v.boolean()),
    trialStartedAt: v.optional(v.number()),
    trialUsedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_user', ['userId'])
    .index('by_status_period_end', ['status', 'currentPeriodEnd'])
    .index('by_provider_subscription', ['provider', 'providerSubscriptionId']),

  // Shareable, revocable referral codes. Codes contain no email, user id, or
  // other personal information and may be regenerated by the account owner.
  referralCodes: defineTable({
    userId: v.id('users'),
    code: v.string(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_user', ['userId'])
    .index('by_code', ['code']),

  // A member can be attributed to one referrer only. Reward/payment policy is
  // deliberately separate from attribution so the owner can change campaigns
  // later without rewriting signup history.
  referrals: defineTable({
    referrerUserId: v.id('users'),
    referredUserId: v.id('users'),
    referralCodeId: v.id('referralCodes'),
    code: v.string(),
    status: v.union(
      v.literal('registered'),
      v.literal('qualified'),
      v.literal('rewarded'),
      v.literal('rejected'),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
    reviewedAt: v.optional(v.number()),
    reviewedBy: v.optional(v.id('users')),
  })
    .index('by_referred_user', ['referredUserId'])
    .index('by_referrer_user', ['referrerUserId'])
    .index('by_reviewed_by', ['reviewedBy'])
    .index('by_status', ['status']),

  // Owner-configured prices. No amount or payment destination is shipped in
  // the frontend bundle; production configuration lives in Convex.
  subscriptionPlans: defineTable({
    planKey: v.union(v.literal('premium'), v.literal('family')),
    nameMm: v.string(),
    nameEn: v.string(),
    descriptionMm: v.optional(v.string()),
    descriptionEn: v.optional(v.string()),
    amount: v.number(),
    currency: v.string(),
    interval: v.union(v.literal('month'), v.literal('year')),
    features: v.array(v.string()),
    isActive: v.boolean(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_plan_key', ['planKey'])
    .index('by_plan_key_interval', ['planKey', 'interval'])
    .index('by_active_and_sort_order', ['isActive', 'sortOrder']),

  // Configurable local/manual payment destinations (e.g. a merchant wallet or
  // bank transfer). Secrets are never stored here.
  paymentMethods: defineTable({
    nameMm: v.string(),
    nameEn: v.string(),
    accountName: v.string(),
    accountIdentifier: v.string(),
    instructionsMm: v.optional(v.string()),
    instructionsEn: v.optional(v.string()),
    isActive: v.boolean(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_active_and_sort_order', ['isActive', 'sortOrder']),

  paymentRequests: defineTable({
    userId: v.id('users'),
    planKey: v.union(v.literal('premium'), v.literal('family')),
    planId: v.optional(v.id('subscriptionPlans')),
    paymentMethodId: v.id('paymentMethods'),
    amount: v.number(),
    currency: v.string(),
    paymentReference: v.string(),
    proofStorageId: v.optional(v.id('_storage')),
    status: v.union(v.literal('pending'), v.literal('approved'), v.literal('rejected'), v.literal('canceled')),
    reviewedBy: v.optional(v.id('users')),
    reviewNote: v.optional(v.string()),
    reviewedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_user', ['userId'])
    .index('by_reviewed_by', ['reviewedBy'])
    .index('by_status', ['status']),

  // Myan Myan Pay transactions are kept separate from the legacy/manual
  // screenshot-review flow above. Provider credentials live only in Convex
  // environment variables; this table contains non-secret reconciliation data.
  mmpayTransactions: defineTable({
    userId: v.id('users'),
    planKey: v.union(v.literal('premium'), v.literal('family')),
    planId: v.optional(v.id('subscriptionPlans')),
    planInterval: v.optional(v.union(v.literal('month'), v.literal('year'))),
    environment: v.union(v.literal('sandbox'), v.literal('production')),
    orderId: v.string(),
    amount: v.number(),
    currency: v.literal('MMK'),
    status: v.union(
      v.literal('INITIATING'),
      v.literal('PENDING'),
      v.literal('SUCCESS'),
      v.literal('FAILED'),
      v.literal('REFUNDED'),
      v.literal('CANCELLED'),
      v.literal('EXPIRED'),
    ),
    condition: v.optional(v.union(v.literal('PRISTINE'), v.literal('TOUCHED'), v.literal('DIRTY'), v.literal('EXPIRED'))),
    qrPayload: v.optional(v.string()),
    checkoutUrl: v.optional(v.string()),
    vendor: v.optional(v.string()),
    method: v.optional(v.union(v.literal('QR'), v.literal('PIN'), v.literal('PWA'), v.literal('CARD'))),
    vendorQrRefId: v.optional(v.string()),
    transactionRefId: v.optional(v.string()),
    failureReason: v.optional(v.string()),
    callbackReceivedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    lastSyncedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_order_id', ['orderId'])
    .index('by_user', ['userId'])
    .index('by_status', ['status'])
    .index('by_transaction_ref_id', ['transactionRefId']),

  // A signed callback can be delivered more than once. Persisting a digest of
  // its nonce makes processing idempotent without retaining the raw nonce.
  mmpayWebhookEvents: defineTable({
    nonceHash: v.string(),
    orderId: v.string(),
    status: v.string(),
    receivedAt: v.number(),
  })
    .index('by_nonce_hash', ['nonceHash'])
    .index('by_order_id', ['orderId']),

  // Saved (favourite) activities — private to the parent.
  favorites: defineTable({
    userId: v.id('users'),
    activityKey: v.string(),
  })
    .index('by_user', ['userId'])
    .index('by_user_activity', ['userId', 'activityKey']),

  // Per-parent notifications (e.g. review reminders). Private.
  notifications: defineTable({
    userId: v.id('users'),
    titleMm: v.string(),
    titleEn: v.string(),
    bodyMm: v.optional(v.string()),
    bodyEn: v.optional(v.string()),
    readAt: v.optional(v.number()),
  }).index('by_user', ['userId']),

  // Admin CMS content items carrying review-workflow state. Readable by any
  // authenticated user only when 'published'; staff see all and can transition.
  contentItems: defineTable({
    kind: v.string(), // milestone | activity | awareness | lesson
    titleMm: v.string(),
    titleEn: v.string(),
    reviewStatus: v.string(), // matches src/domain/content/workflow.ts states
    // Optional translation-review fields (side-by-side en/mm editing).
    bodyMm: v.optional(v.string()),
    bodyEn: v.optional(v.string()),
    translationStatus: v.optional(v.string()), // draft | submitted | approved | changes_requested
    translationNote: v.optional(v.string()),
    reviewerQualification: v.optional(v.string()),
    reviewerId: v.optional(v.id('users')),
    reviewScope: v.optional(v.union(v.literal('education'), v.literal('clinical'))),
  })
    .index('by_status', ['reviewStatus'])
    .index('by_reviewer', ['reviewerId']),

  // Verified healthcare facilities. NEVER seeded with invented data. Only
  // active + verified rows are shown to parents (directory.listPublic).
  healthcareFacilities: defineTable({
    country: v.string(),
    region: v.optional(v.string()),
    township: v.optional(v.string()),
    name: v.string(),
    facilityType: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    services: v.optional(v.string()),
    source: v.optional(v.string()),
    lastVerifiedAt: v.optional(v.number()),
    nextVerificationAt: v.optional(v.number()),
    verifiedBy: v.optional(v.id('users')),
    isActive: v.boolean(), // inactive until verified
  })
    .index('by_active', ['isActive'])
    .index('by_name', ['name'])
    .index('by_verified_by', ['verifiedBy']),

  // Immutable audit trail. Insert-only; readable by staff/super-admin. Listed via
  // the implicit _creationTime order (newest first), so no extra index is needed.
  auditLogs: defineTable({
    actorId: v.optional(v.id('users')),
    action: v.string(),
    entityTable: v.optional(v.string()),
    entityId: v.optional(v.string()),
    summary: v.optional(v.string()),
    // A refused action is the one most worth recording: an attempt to approve a
    // reference that may not be approved is a fact about the review process,
    // not a non-event. 'ok' | 'rejected' | 'failed'. All three fields are
    // optional so existing rows stay valid — this is an additive change.
    result: v.optional(v.string()),
    before: v.optional(v.string()),
    after: v.optional(v.string()),
  })
    .index('by_action', ['action'])
    .index('by_result', ['result']),

  // ------------------------------------------------------------------
  // Content Library (database-driven; nothing hardcoded in components).
  // One row per content item across all types (milestone/guide/activity/
  // lesson/special_need/story/printable). Type-specific structure lives in
  // `data`; first-class columns carry the searchable/indexed metadata and the
  // review lifecycle. `clinicalStatus` is a legacy field name; ordinary content
  // follows education-scoped review and only risk-triggered wording needs a
  // clinical decision. Nothing is 'published' until required reviews approve it.
  // ------------------------------------------------------------------
  libraryContent: defineTable({
    type: v.string(),
    slug: v.string(),
    ageGroupKey: v.optional(v.string()),
    domainKey: v.optional(v.string()),
    category: v.optional(v.string()),
    titleMm: v.string(),
    titleEn: v.string(),
    summaryMm: v.optional(v.string()),
    summaryEn: v.optional(v.string()),
    tags: v.array(v.string()),
    difficulty: v.optional(v.string()),
    durationMinutes: v.optional(v.number()),
    offline: v.optional(v.boolean()),
    data: v.any(), // type-specific bilingual payload
    source: v.string(),
    version: v.number(),
    reviewRevision: v.optional(v.number()),
    clinicalStatus: v.string(), // draft | clinical_review | published
    reviewerId: v.optional(v.id('users')),
    reviewerQualification: v.optional(v.string()),
    reviewerDisplayName: v.optional(v.string()),
    reviewScope: v.optional(v.union(v.literal('education'), v.literal('clinical'))),
    reviewedAt: v.optional(v.number()),
    nextReviewAt: v.optional(v.number()),
    reviewNote: v.optional(v.string()),
    // Agent-assisted publication is a separate, explicitly disclosed lane.
    // These fields never substitute for reviewerId/reviewerQualification or
    // rows in contentReviews; they bind the visible item to an append-only AI
    // audit run while preserving the human review history unchanged.
    aiPublicationReleaseId: v.optional(v.string()),
    aiPublishedAt: v.optional(v.number()),
    // ------------------------------------------------------------------
    // Owner-priority governance (all OPTIONAL and additive — existing rows,
    // including every Production row, remain valid without them). These fields
    // are advisory workflow metadata: none of them publishes, unpublishes,
    // archives, approves, or changes reviewScope. They are written only by the
    // owner-priority workspace mutations and (in a future, separately
    // confirmed task) the classification importer.
    // ------------------------------------------------------------------
    riskClassification: v.optional(
      v.union(v.literal('A'), v.literal('B'), v.literal('C'), v.literal('D'), v.literal('E')),
    ),
    ownerPriority: v.optional(
      v.union(v.literal('P0'), v.literal('P1'), v.literal('P2'), v.literal('P3')),
    ),
    riskReasons: v.optional(v.array(v.string())),
    // CONFIRMED requirements only — written by an explicit manager decision.
    // Class D/E rows carry none until triaged, so nothing can look scoped.
    requiredReviewDimensions: v.optional(v.array(v.string())),
    // Dimensions that have merely been ASKED FOR. Not an assignment and not a
    // confirmed requirement; kept separate so neither can be mistaken for the
    // other in a count or a label.
    requestedReviewDimensions: v.optional(v.array(v.string())),
    classificationSource: v.optional(v.string()),
    classificationRunId: v.optional(v.string()),
    classifiedAt: v.optional(v.number()),
    classifiedBy: v.optional(v.string()),
    classificationConfirmedAt: v.optional(v.number()),
    classificationConfirmedBy: v.optional(v.id('users')),
    // A recommendation flag only. Acting on it (actually hiding content) is a
    // separate, explicitly human publication decision — never automated here.
    temporarilyHideRecommended: v.optional(v.boolean()),
    priorityStatus: v.optional(
      v.union(
        v.literal('unreviewed'),
        v.literal('confirmed'),
        v.literal('manual_triage_required'),
        v.literal('correction_needed'),
        v.literal('review_requested'),
        v.literal('assigned'),
        v.literal('in_review'),
        v.literal('corrected'),
        v.literal('ready_for_recheck'),
        v.literal('triage_complete'),
        v.literal('completed'),
      ),
    ),
    ownerNote: v.optional(v.string()),
    searchText: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_slug', ['slug'])
    .index('by_type', ['type'])
    .index('by_type_age', ['type', 'ageGroupKey'])
    .index('by_type_domain', ['type', 'domainKey'])
    .index('by_type_category', ['type', 'category'])
    .index('by_status', ['clinicalStatus'])
    .index('by_reviewer', ['reviewerId'])
    // Account erasure must be able to find every row a staff member confirmed a
    // classification on, not just the ones they reviewed, without scanning the
    // whole catalogue.
    .index('by_classification_confirmed_by', ['classificationConfirmedBy']),

  // Human review decisions are append-only and separate from the content document,
  // so every intermediate decision survives later decisions and edits. A decision
  // applies only to the exact contentVersion it reviewed. Editing an item increments
  // its review revision and makes older approvals visibly stale instead of silently reusing them.
  contentReviews: defineTable({
    contentSlug: v.string(),
    contentVersion: v.number(),
    dimension: v.union(
      v.literal('english'),
      v.literal('native_myanmar'),
      v.literal('child_development'),
      v.literal('evidence'),
      v.literal('safety'),
      v.literal('clinical'),
    ),
    decision: v.union(
      v.literal('in_review'),
      v.literal('approved'),
      v.literal('changes_requested'),
      v.literal('not_applicable'),
    ),
    note: v.optional(v.string()),
    reviewerId: v.id('users'),
    reviewerDisplayName: v.string(),
    reviewerQualification: v.optional(v.string()),
    reviewerRole: v.union(
      v.literal('owner'),
      v.literal('content_editor'),
      v.literal('language_reviewer'),
      v.literal('evidence_reviewer'),
      v.literal('clinical_reviewer'),
      v.literal('review_manager'),
      v.literal('support'),
    ),
    reviewedAt: v.number(),
    // Explicit binding to the libraryContent.reviewRevision the decision was
    // recorded against. Historically `contentVersion` carried this value while
    // libraryContent.version stayed at its imported value, which read as a
    // mismatch in audits. New rows record both, identically; old rows stay
    // valid without it. A decision NEVER applies to any other revision.
    reviewRevision: v.optional(v.number()),
    // Optional/additive: deterministic idempotency for bounded clinical-review
    // batches. Historical rows remain valid and carry neither field.
    decisionKey: v.optional(v.string()),
    clinicalReviewBatchId: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_content_dimension_version', ['contentSlug', 'dimension', 'contentVersion'])
    .index('by_content', ['contentSlug'])
    .index('by_reviewer', ['reviewerId'])
    .index('by_decision_key', ['decisionKey'])
    .index('by_clinical_review_batch_and_content', ['clinicalReviewBatchId', 'contentSlug']),

  // ------------------------------------------------------------------
  // Advisory AI audit provenance. These append-only records are deliberately
  // separate from human review decisions and can never represent clinical or
  // evidence approval. A narrowly allowlisted AI-publication lane may read
  // them, but only when every exact content/link/source snapshot still matches.
  // ------------------------------------------------------------------
  aiAuditRuns: defineTable({
    runId: v.string(),
    releaseId: v.string(),
    status: v.union(v.literal('completed'), v.literal('failed')),
    provider: v.string(),
    model: v.string(),
    modelVersion: v.optional(v.string()),
    policyVersion: v.string(),
    gitCommit: v.string(),
    targetCount: v.number(),
    summary: v.string(),
    limitations: v.array(v.string()),
    startedAt: v.number(),
    completedAt: v.number(),
    outputHash: v.string(),
  })
    .index('by_run_id', ['runId'])
    .index('by_release_id', ['releaseId'])
    .index('by_status', ['status']),

  aiEvidenceAudits: defineTable({
    runId: v.string(),
    sourceId: v.string(),
    sourceUpdatedAt: v.number(),
    sourceSnapshotHash: v.string(),
    verdict: v.union(
      v.literal('pass'),
      v.literal('needs_changes'),
      v.literal('insufficient_evidence'),
      v.literal('blocked'),
    ),
    claimScope: v.string(),
    urlsChecked: v.array(v.string()),
    findings: v.array(v.string()),
    limitations: v.array(v.string()),
    auditedAt: v.number(),
    nextAuditDate: v.string(),
    outputHash: v.string(),
  })
    .index('by_run_id', ['runId'])
    .index('by_source_and_updated_at', ['sourceId', 'sourceUpdatedAt']),

  aiContentAudits: defineTable({
    runId: v.string(),
    contentSlug: v.string(),
    contentType: v.string(),
    reviewRevision: v.number(),
    contentUpdatedAt: v.number(),
    contentSnapshotHash: v.string(),
    evidenceLinkUpdatedAt: v.number(),
    evidenceLinkSnapshotHash: v.string(),
    sourceIds: v.array(v.string()),
    verdict: v.union(
      v.literal('pass'),
      v.literal('needs_changes'),
      v.literal('insufficient_evidence'),
      v.literal('blocked'),
    ),
    checks: v.array(v.string()),
    limitations: v.array(v.string()),
    auditedAt: v.number(),
    nextAuditDate: v.string(),
    outputHash: v.string(),
  })
    .index('by_run_id', ['runId'])
    .index('by_content_revision_and_updated_at', [
      'contentSlug',
      'reviewRevision',
      'contentUpdatedAt',
    ]),

  // Default-off operational switch. Both this singleton and the server-side
  // environment flag must be enabled before an AI-audited release is visible.
  // Configuration can disable releases but cannot extend the compile-time
  // three-item allowlist.
  aiPublicationConfig: defineTable({
    key: v.literal('global'),
    enabled: v.boolean(),
    generation: v.number(),
    reason: v.string(),
    operator: v.string(),
    updatedAt: v.number(),
  }).index('by_key', ['key']),

  // Immutable release snapshots for the separate AI-audited parent lane.
  // Revocation appends state to the release row; it never rewrites an AI audit
  // into a human approval or changes contentReviews/evidenceSources decisions.
  aiPublicationReleases: defineTable({
    releaseId: v.string(),
    targetKey: v.string(),
    contentId: v.id('libraryContent'),
    contentType: v.string(),
    contentSlug: v.string(),
    status: v.union(v.literal('active'), v.literal('revoked')),
    reviewRevision: v.number(),
    contentUpdatedAt: v.number(),
    contentSnapshotHash: v.string(),
    evidenceLinkUpdatedAt: v.number(),
    evidenceLinkSnapshotHash: v.string(),
    sourceSnapshots: v.array(v.object({
      sourceId: v.string(),
      sourceUpdatedAt: v.number(),
      sourceSnapshotHash: v.string(),
      evidenceAuditRunId: v.string(),
    })),
    contentAuditRunId: v.string(),
    auditArtifactHash: v.string(),
    policyVersion: v.string(),
    gitCommit: v.string(),
    operator: v.string(),
    createdAt: v.number(),
    expiresAt: v.number(),
    revokedAt: v.optional(v.number()),
    revokeReason: v.optional(v.string()),
  })
    .index('by_release_id', ['releaseId'])
    .index('by_target_key', ['targetKey'])
    .index('by_status', ['status']),

  // Append-only field-level edit history for the reviewer workspace. Full
  // content snapshots can exceed Convex's document limit, so each row stores a
  // bounded set of before/after previews plus an explicit truncation marker.
  contentEditLogs: defineTable({
    contentId: v.id('libraryContent'),
    contentSlug: v.string(),
    fromVersion: v.number(),
    toVersion: v.number(),
    editorId: v.id('users'),
    editorDisplayName: v.string(),
    editorRole: v.union(
      v.literal('owner'),
      v.literal('content_editor'),
      v.literal('language_reviewer'),
      v.literal('evidence_reviewer'),
      v.literal('clinical_reviewer'),
      v.literal('review_manager'),
      v.literal('support'),
    ),
    editedAt: v.number(),
    totalChanges: v.number(),
    logTruncated: v.boolean(),
    changes: v.array(
      v.object({
        path: v.string(),
        before: v.string(),
        after: v.string(),
        truncated: v.boolean(),
      }),
    ),
  })
    .index('by_content', ['contentSlug'])
    .index('by_editor', ['editorId']),

  // Media architecture for library content. Only architecture + placeholders are
  // seeded; real assets are attached later via the CMS media system.
  libraryMedia: defineTable({
    contentSlug: v.string(),
    kind: v.string(), // illustration | animation | audio | video | pdf | download | offline_bundle
    url: v.optional(v.string()),
    storageId: v.optional(v.id('_storage')),
    mimeType: v.optional(v.string()),
    altMm: v.optional(v.string()),
    altEn: v.optional(v.string()),
    captionMm: v.optional(v.string()),
    captionEn: v.optional(v.string()),
    placeholder: v.boolean(),
    offline: v.optional(v.boolean()),
    note: v.optional(v.string()),
    durationSeconds: v.optional(v.number()),
    transcriptMm: v.optional(v.string()),
    transcriptEn: v.optional(v.string()),
    rightsOwner: v.optional(v.string()),
    rightsSourceUrl: v.optional(v.string()),
    licenseType: v.optional(v.string()),
    attributionMm: v.optional(v.string()),
    attributionEn: v.optional(v.string()),
    reviewStatus: v.optional(
      v.union(v.literal('planned'), v.literal('in_review'), v.literal('approved'), v.literal('retired')),
    ),
    reviewedBy: v.optional(v.id('users')),
    reviewerQualification: v.optional(v.string()),
    reviewedAt: v.optional(v.number()),
    nextReviewAt: v.optional(v.number()),
    accessLevel: v.optional(v.union(v.literal('free_sample'), v.literal('premium'))),
    sortOrder: v.optional(v.number()),
  })
    .index('by_content', ['contentSlug'])
    .index('by_kind', ['kind'])
    .index('by_reviewed_by', ['reviewedBy']),

  // ------------------------------------------------------------------
  // Evidence Base. Every knowledge item in the library must be traceable to a
  // reference a human can open. Records here are metadata READ OFF a publisher
  // page — never inferred. A record that cannot be verified carries
  // reviewStatus 'evidence_required' and is not citable.
  // ------------------------------------------------------------------
  evidenceSources: defineTable({
    sourceId: v.string(), // stable slug, the foreign key used by evidenceLinks
    org: v.string(),
    orgKey: v.string(),
    title: v.string(),
    authors: v.union(v.string(), v.null()),
    year: v.union(v.number(), v.null()),
    edition: v.union(v.string(), v.null()),
    country: v.union(v.string(), v.null()),
    language: v.string(),
    url: v.string(),
    doi: v.union(v.string(), v.null()),
    isbn: v.union(v.string(), v.null()),
    pmid: v.union(v.string(), v.null()),
    evidenceLevel: v.string(),
    reviewStatus: v.string(), // evidence_required | awaiting_review | in_review | approved | retired
    reviewer: v.union(v.string(), v.null()),
    // Professional qualification of the named reviewer (e.g. 'MBBS, MMedSc
    // (Paediatrics)'). Recorded alongside the audit identity so a specialist safety decision can
    // be audited: an approval with no stated qualification is not a sign-off.
    reviewerQualification: v.optional(v.string()),
    reviewDate: v.union(v.string(), v.null()),
    nextReviewDate: v.union(v.string(), v.null()),
    reviewNote: v.optional(v.string()),
    reviewerId: v.optional(v.id('users')),
    reviewScope: v.optional(v.union(v.literal('education'), v.literal('clinical'))),
    keywords: v.array(v.string()),
    topics: v.array(v.string()),
    ageMonthsMin: v.union(v.number(), v.null()),
    ageMonthsMax: v.union(v.number(), v.null()),
    verifiedOn: v.union(v.string(), v.null()),
    verifiedNote: v.string(),
    searchText: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_source_id', ['sourceId'])
    .index('by_org', ['orgKey'])
    .index('by_review_status', ['reviewStatus'])
    .index('by_level', ['evidenceLevel'])
    .index('by_reviewer', ['reviewerId']),

  // Content-to-reference edges. NO ORPHAN CONTENT: every content slug, urgent
  // safety rule and Hope Center topic must appear here with >= 1 sourceId.
  evidenceLinks: defineTable({
    kind: v.string(), // milestone | guide | activity | lesson | special_need | story | printable | safety_rule | hope_topic
    slug: v.string(),
    sourceIds: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_kind_slug', ['kind', 'slug'])
    .index('by_kind', ['kind'])
    .index('by_slug', ['slug']),

  children: defineTable({
    userId: v.id('users'),
    nickname: v.string(),
    birthDate: v.string(), // ISO yyyy-mm-dd
    sex: v.optional(v.union(v.literal('female'), v.literal('male'), v.literal('unspecified'))),
    gestationalWeeks: v.optional(v.number()),
    useCorrectedAge: v.boolean(),
    deletedAt: v.optional(v.number()),
  }).index('by_user', ['userId']),

  growthRecords: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    measuredOn: v.string(),
    weightKg: v.optional(v.number()),
    heightCm: v.optional(v.number()),
    headCircumferenceCm: v.optional(v.number()),
    inputWeightUnit: v.optional(v.string()),
    inputLengthUnit: v.optional(v.string()),
    notes: v.optional(v.string()),
  })
    .index('by_user', ['userId'])
    .index('by_child', ['childId']),

  sleepRecords: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    recordDate: v.string(),
    bedtime: v.optional(v.string()),
    wakeTime: v.optional(v.string()),
    napMinutes: v.number(),
    nightWakingCount: v.number(),
    breathingPauses: v.optional(v.boolean()),
    breathingDifficulty: v.optional(v.boolean()),
    notes: v.optional(v.string()),
  })
    .index('by_user', ['userId'])
    .index('by_child', ['childId']),

  // Parent-entered health history. These private records are for keeping and
  // sharing factual notes; the app never derives a diagnosis from them.
  healthRecords: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    recordDate: v.string(),
    category: v.union(
      v.literal('visit'),
      v.literal('illness'),
      v.literal('test'),
      v.literal('allergy'),
      v.literal('note'),
    ),
    title: v.string(),
    providerName: v.optional(v.string()),
    details: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    deletedAt: v.optional(v.number()),
  })
    .index('by_child_and_record_date', ['childId', 'recordDate'])
    .index('by_user_and_child', ['userId', 'childId']),

  vaccinationRecords: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    vaccineName: v.string(),
    doseLabel: v.optional(v.string()),
    scheduledOn: v.optional(v.string()),
    administeredOn: v.optional(v.string()),
    status: v.union(v.literal('scheduled'), v.literal('completed'), v.literal('missed')),
    providerName: v.optional(v.string()),
    facilityName: v.optional(v.string()),
    lotNumber: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    deletedAt: v.optional(v.number()),
  })
    .index('by_child_and_scheduled_on', ['childId', 'scheduledOn'])
    .index('by_user_and_child', ['userId', 'childId']),

  medicationRecords: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    medicineName: v.string(),
    purpose: v.optional(v.string()),
    dose: v.optional(v.string()),
    frequency: v.optional(v.string()),
    route: v.optional(v.string()),
    startedOn: v.string(),
    endedOn: v.optional(v.string()),
    lastGivenAt: v.optional(v.number()),
    prescribedBy: v.optional(v.string()),
    notes: v.optional(v.string()),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
    deletedAt: v.optional(v.number()),
  })
    .index('by_child_and_started_on', ['childId', 'startedOn'])
    .index('by_user_and_child', ['userId', 'childId']),

  milestoneSessions: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    ageGroupKey: v.optional(v.string()),
    completedAt: v.optional(v.number()),
    resultState: v.optional(
      v.union(v.literal('green'), v.literal('yellow'), v.literal('orange'), v.literal('red')),
    ),
    lostSkill: v.boolean(),
    resultSnapshot: v.optional(v.any()),
  })
    .index('by_user', ['userId'])
    .index('by_child', ['childId']),

  milestoneResponses: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    sessionId: v.id('milestoneSessions'),
    milestoneKey: v.string(),
    titleMm: v.optional(v.string()),
    titleEn: v.optional(v.string()),
    domain: v.string(),
    answer: v.union(
      v.literal('yes'),
      v.literal('sometimes'),
      v.literal('not_yet'),
      v.literal('not_sure'),
    ),
    note: v.optional(v.string()),
    // Parent-initiated, opt-in keepsake photo for an achieved milestone. A
    // deliberate exception to the app's default data-minimization stance
    // (see AddChild.tsx's "nickname only" comment) — not a reversal of it.
    photoStorageId: v.optional(v.id('_storage')),
    answeredAt: v.number(),
  })
    .index('by_session', ['sessionId'])
    .index('by_child', ['childId'])
    .index('by_user_and_child', ['userId', 'childId']),

  activityCompletions: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    contentSlug: v.string(),
    completedAt: v.number(),
    durationMinutes: v.optional(v.number()),
    note: v.optional(v.string()),
  })
    .index('by_child_and_completed_at', ['childId', 'completedAt'])
    .index('by_user_and_completed_at', ['userId', 'completedAt']),

  appointments: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    title: v.string(),
    providerName: v.optional(v.string()),
    appointmentAt: v.number(),
    questions: v.optional(v.string()),
    notes: v.optional(v.string()),
    reminderAt: v.optional(v.number()),
    status: v.union(v.literal('scheduled'), v.literal('completed'), v.literal('canceled')),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_user_and_appointment_at', ['userId', 'appointmentAt'])
    .index('by_child_and_appointment_at', ['childId', 'appointmentAt'])
    .index('by_reminder_at', ['reminderAt']),

  observations: defineTable({
    userId: v.id('users'),
    childId: v.id('children'),
    observedOn: v.string(),
    category: v.optional(v.union(
      v.literal('behavior'),
      v.literal('development'),
      v.literal('health'),
      v.literal('other'),
    )),
    note: v.string(),
    createdAt: v.number(),
  })
    .index('by_user_and_observed_on', ['userId', 'observedOn'])
    .index('by_child_and_observed_on', ['childId', 'observedOn']),

  familyCaregivers: defineTable({
    ownerId: v.id('users'),
    caregiverUserId: v.optional(v.id('users')),
    caregiverEmail: v.string(),
    displayName: v.optional(v.string()),
    status: v.union(v.literal('pending'), v.literal('active'), v.literal('revoked')),
    invitedAt: v.number(),
    acceptedAt: v.optional(v.number()),
    revokedAt: v.optional(v.number()),
  })
    .index('by_owner', ['ownerId'])
    .index('by_owner_and_email', ['ownerId', 'caregiverEmail'])
    .index('by_email_and_status', ['caregiverEmail', 'status'])
    .index('by_caregiver_user', ['caregiverUserId']),
});
