// Activity library — structured, low-cost, home-friendly activities with full
// metadata. This is a genuine starter set; the CMS + seed files extend it toward
// the full target catalogue. All clinical_review until approved.
import { activity, type SeedItem } from '../types';

const b = (mm: string, en: string) => ({ mm, en });

export const ACTIVITIES: SeedItem[] = [
  activity({
    slug: 'tummy_time_mirror', title: b('မှောက်လျက် မှန်ကြည့်ကစားခြင်း', 'Tummy-time mirror play'),
    summary: b('မှောက်လျက်နေစဉ် မှန်ဖြင့် ခေါင်းမော့ရန် အားပေးခြင်း။', 'Encourage head-lifting during tummy time with a mirror.'),
    ageGroupKey: 'birth_2m', domains: ['gross_motor', 'play'], difficulty: 'easy', durationMinutes: 5,
    materials: b('နူးညံ့ဖျာ၊ ကွဲမသွားသော မှန်။', 'Soft mat, shatter-proof mirror.'),
    setup: b('ကလေးကို မှောက်ချ၍ ရှေ့တွင် မှန်ထားပါ။', 'Place baby on tummy with a mirror in front.'),
    instructions: [b('ကလေးအား အသံပေး၍ ခေါင်းမော့ကြည့်ရန် ဆွဲဆောင်ပါ။', 'Talk to baby to encourage lifting the head to look.')],
    safety: b('အမြဲ ကြီးကြပ်ပါ။ ကလေးမောပါက ရပ်ပါ။', 'Always supervise; stop if baby tires.'),
    indoor: true, outdoor: false, oneChild: true, group: false, parentChild: true,
    outcomes: [b('လည်ပင်း/ကျောကြွက်သား ခိုင်မာမှု။', 'Neck and back strength.')],
    variations: [b('မှန်အစား အရောင်တောက်သော ကစားစရာ သုံးပါ။', 'Use a bright toy instead of a mirror.')],
  }),
  activity({
    slug: 'sound_tracking', title: b('အသံလိုက် လှည့်ကြည့်ကစားခြင်း', 'Sound-tracking play'),
    summary: b('ကွဲပြားသော အသံများဆီ လှည့်ကြည့်ရန် အားပေးခြင်း။', 'Encourage turning toward different sounds.'),
    ageGroupKey: '3_4m', domains: ['communication', 'cognitive'], difficulty: 'easy', durationMinutes: 5,
    materials: b('နူးညံ့ အသံထွက်ကစားစရာ။', 'Soft rattle or bell.'),
    setup: b('ကလေးကို ပက်လက်အနေအထားဖြင့်ထားပြီး ဘေးတစ်ဖက်မှ အသံတိုးတိုး ပြုပါ။', 'Lay baby down and make a soft sound to one side.'),
    instructions: [b('အသံဆီ လှည့်ကြည့်ပါက ပြုံး၍ ချီးမွမ်းပါ။', 'Praise with a smile when baby turns to the sound.')],
    safety: b('အသံ ကျယ်လွန်းခြင်း ရှောင်ပါ။', 'Avoid loud sounds.'),
    indoor: true, outdoor: false, oneChild: true, group: false, parentChild: true,
    outcomes: [b('အကြားအာရုံ၊ ဂရုပြုမှု။', 'Listening and attention.')],
  }),
  activity({
    slug: 'peekaboo', title: b('“ဘယ်မှာလဲ၊ ဒီမှာပါ” ကစားခြင်း', 'Peek-a-boo'),
    summary: b('မျက်နှာကို ခဏဖုံးပြီး ပြန်ဖော်ပြကာ မမြင်ရသော်လည်း ရှိနေဆဲဖြစ်ကြောင်း ကလေး နားလည်လာစေရန် ကစားခြင်း။', 'Teach object permanence through hide-and-reveal.'),
    ageGroupKey: '7_9m', domains: ['social', 'cognitive'], difficulty: 'easy', durationMinutes: 5,
    materials: b('စောင်/ပဝါ တစ်ထည်။', 'A cloth or scarf.'),
    setup: b('မျက်နှာချင်းဆိုင် ထိုင်ပါ။', 'Sit face-to-face.'),
    instructions: [b('မျက်နှာကို ဖုံး၍ “ဘယ်မှာလဲ… ဒီမှာ” ဟု ဖွင့်ပြပါ။', 'Hide your face, then reveal with “peek-a-boo”.')],
    safety: b('စောင်ကို ကလေး၏ မျက်နှာပေါ် မဖုံးထားပါနှင့်။', 'Never leave the cloth over baby’s face.'),
    indoor: true, outdoor: true, oneChild: true, group: true, parentChild: true,
    outcomes: [b('လူမှုချိတ်ဆက်မှု၊ မှတ်ဉာဏ်။', 'Social connection and memory.')],
  }),
  activity({
    slug: 'cup_stacking', title: b('ခွက်စီ ကစားခြင်း', 'Cup stacking and nesting'),
    summary: b('ခွက်များကို ထပ်စီခြင်းနှင့် တစ်ခုအတွင်းတစ်ခု ထည့်ခြင်းဖြင့် လက်ချောင်းလှုပ်ရှားမှုကို လေ့ကျင့်ပေးခြင်း။', 'Build fine-motor skill by stacking and nesting cups.'),
    ageGroupKey: '10_12m', domains: ['fine_motor', 'problem_solving'], difficulty: 'easy', durationMinutes: 10,
    materials: b('ပလတ်စတစ်ခွက် အရွယ်အမျိုးမျိုး။', 'Plastic cups of different sizes.'),
    setup: b('ခွက်များကို ကြမ်းပြင်ပေါ်တွင် ချထားပါ။', 'Place cups on the floor.'),
    instructions: [b('ခွက်များကို ထပ်စီပုံ၊ တစ်ခုအတွင်းတစ်ခု ထည့်ပုံ ပြသပြီး ကလေးကို လိုက်လုပ်စေပါ။', 'Show stacking/nesting and let the child copy.')],
    safety: b('ကွဲအက်နိုင်သော ခွက်များ ရှောင်ပါ။', 'Avoid breakable cups.'),
    indoor: true, outdoor: false, oneChild: true, group: false, parentChild: true,
    outcomes: [b('လက်ချောင်းလှုပ်ရှားမှုနှင့် အရွယ်အစား ကွာခြားပုံကို နားလည်နိုင်မှု။', 'Hand skill and size concepts.')],
  }),
  activity({
    slug: 'name_and_point', title: b('ပုံကို ညွှန်ပြီး အမည်ပြောကစားခြင်း', 'Name-and-point book time'),
    summary: b('ရုပ်ပုံစာအုပ်ကို အတူဖတ်၍ ဝေါဟာရ တိုးပွားစေခြင်း။', 'Grow vocabulary with shared picture-book reading.'),
    ageGroupKey: '13_18m', domains: ['language', 'communication'], difficulty: 'easy', durationMinutes: 10,
    materials: b('ရုပ်ပုံ စာအုပ်။', 'A picture book.'),
    setup: b('ကလေးကို ပေါင်ပေါ်တင်၍ စာအုပ်ဖွင့်ပါ။', 'Sit the child on your lap and open the book.'),
    instructions: [b('ပုံတစ်ပုံစီကို လက်ညှိုးဖြင့်ညွှန်ပြီး အမည်ပြောပေးပါ။ ကလေးကိုလည်း သိသည့်ပုံကို ညွှန်ပြစေပါ။', 'Point and name pictures; invite the child to point too.')],
    safety: b('စာရွက်အစွန်းများ ထက်နေခြင်း၊ စာရွက်ပြဲများရှိခြင်းကို စစ်ဆေးပါ။', 'Watch for paper edges.'),
    indoor: true, outdoor: false, oneChild: true, group: true, parentChild: true,
    outcomes: [b('ဝေါဟာရ၊ ပူးပေါင်း အာရုံစိုက်မှု။', 'Vocabulary and joint attention.')],
  }),
  activity({
    slug: 'copy_everyday_actions', title: b('နေ့စဉ်လုပ်ဆောင်မှု တုပကစားခြင်း', 'Copy everyday actions'),
    summary: b('ရိုးရှင်းသော နေ့စဉ်လုပ်ဆောင်မှုများကို အတူတုပြီး ဆက်သွယ်မှုနှင့် ဟန်ဆောင်ကစားမှုကို အားပေးခြင်း။', 'Copy simple everyday actions together to encourage communication and pretend play.'),
    ageGroupKey: '19_24m', domains: ['play', 'communication'], difficulty: 'easy', durationMinutes: 8,
    materials: b('သန့်ရှင်းသော ခွက်၊ ဇွန်း သို့မဟုတ် အဝတ်စကဲ့သို့ အိမ်သုံးပစ္စည်းကြီးများ။', 'Large, clean household items such as a cup, spoon, or cloth.'),
    setup: b('ဘေးကင်းသော ကြမ်းပြင်နေရာတွင် ကလေးနှင့် မျက်နှာချင်းဆိုင် ထိုင်ပါ။', 'Sit face-to-face with the child in a safe floor space.'),
    instructions: [
      b('ခွက်ဖြင့် သောက်ဟန် သို့မဟုတ် အဝတ်စဖြင့် သုတ်ဟန်ကို ဖြည်းဖြည်းပြပြီး ကလေးကို တုပစေပါ။', 'Slowly pretend to drink from the cup or wipe with the cloth and invite the child to copy.'),
      b('ကလေးလုပ်သည့်အရာကို စကားလုံးတိုတိုဖြင့် အမည်ပြောပေးပါ။', 'Name the child’s action with a short phrase.'),
    ],
    safety: b('ကျိုးပဲ့နိုင်သော သို့မဟုတ် မျိုချနိုင်သော ပစ္စည်းမသုံးပါနှင့်။ အနီးကပ် ကြီးကြပ်ပါ။', 'Do not use breakable or swallowable objects. Supervise closely.'),
    indoor: true, outdoor: false, oneChild: true, group: true, parentChild: true,
    outcomes: [b('ဟန်ဆောင်ကစားမှု၊ တုပနိုင်မှုနှင့် အလှည့်ကျ ဆက်သွယ်မှု။', 'Pretend play, imitation, and communication turn-taking.')],
    evidenceSummary: 'Topic-fit play and communication references are linked; evidence and safety review remains revision-bound.',
  }),
  activity({
    slug: 'obstacle_crawl', title: b('ခေါင်းအုံး အတားအဆီး တွားကစားခြင်း', 'Pillow obstacle crawl'),
    summary: b('ပျော့ပျောင်းသော ခေါင်းအုံးများကို ကျော်တွားစေပြီး ကိုယ်လက်လှုပ်ရှားမှုနှင့် ဟန်ချက်ကို လေ့ကျင့်ပေးခြင်း။', 'Gross-motor practice crawling over soft pillows.'),
    ageGroupKey: '10_12m', domains: ['gross_motor', 'play'], difficulty: 'medium', durationMinutes: 10,
    materials: b('ခေါင်းအုံး/စောင် အနည်းငယ်။', 'A few pillows and blankets.'),
    setup: b('ကြမ်းပြင်ပေါ်တွင် ခေါင်းအုံးများ စီထားပါ။', 'Arrange pillows into a soft course.'),
    instructions: [b('ကစားစရာကို တစ်ဖက်တွင်ထား၍ တွားလာရန် ဆွဲဆောင်ပါ။', 'Place a toy at the end to motivate crawling.')],
    safety: b('ခိုင်ခံ့မှုကို ကြည့်၍ ကြီးကြပ်ပါ။', 'Supervise and keep the course stable.'),
    indoor: true, outdoor: false, oneChild: true, group: true, parentChild: true,
    outcomes: [b('ရွေ့လျားမှု၊ ဟန်ချက်။', 'Mobility and balance.')],
  }),
  activity({
    slug: 'color_sort', title: b('အရောင်ခွဲ ကစားခြင်း', 'Color sorting'),
    summary: b('ပစ္စည်းများကို အရောင်ဖြင့် ခွဲ၍ အသိဉာဏ် လေ့ကျင့်ခြင်း။', 'Sort objects by color to build early thinking.'),
    ageGroupKey: '3y', domains: ['cognitive', 'problem_solving'], difficulty: 'medium', durationMinutes: 10,
    materials: b('အသက်အရွယ်သင့်၊ မျိုမချနိုင်လောက်အောင် ကြီးသော အရောင်စုံ ကစားတုံးကြီးများနှင့် ခွက်ကြီးနှစ်လုံး။', 'Large, age-rated, non-swallowable colored blocks and two large bowls.'),
    setup: b('အရောင်စုံ ပစ္စည်းများကို ရောထားပါ။', 'Mix the colorful objects together.'),
    instructions: [b('အရောင်တူ ပစ္စည်းများကို ခွက်တစ်လုံးစီ ခွဲထည့်စေပါ။', 'Have the child sort same colors into each bowl.')],
    safety: b('ပစ္စည်းငယ်များနှင့် ဖြုတ်ထွက်နိုင်သော အစိတ်အပိုင်းငယ်များကို လုံးဝ မသုံးပါနှင့်။ အသက်အရွယ်သင့် ကစားတုံးကြီးများကိုသာ သုံးပြီး ကြီးကြပ်ပါ။', 'Do not use small objects or detachable small parts. Use only large age-rated blocks and supervise.'),
    indoor: true, outdoor: false, oneChild: true, group: true, parentChild: true,
    outcomes: [b('အရောင်သိမှု၊ အမျိုးအစားခွဲမှု။', 'Color knowledge and categorizing.')],
  }),
  activity({
    slug: 'feeling_faces', title: b('ခံစားမှု မျက်နှာ ကစားခြင်း', 'Feeling-faces game'),
    summary: b('ကလေး၏ ခံစားချက်များကို စကားလုံးဖြင့် ပြောပြတတ်လာစေရန် ကူညီပေးခြင်း။', 'Help name and express emotions.'),
    ageGroupKey: '2_5y', domains: ['emotional', 'social'], difficulty: 'easy', durationMinutes: 10,
    materials: b('ခံစားမှု မျက်နှာ ပုံ ၄ ကွက် (ကိုယ်တိုင်ဆွဲ)။', 'Four hand-drawn feeling faces.'),
    setup: b('ပုံ ၄ ကွက်ကို စားပွဲပေါ်တွင် ချထားပါ။', 'Lay the four faces on a table.'),
    instructions: [b('“ဒီနေ့ ဘယ်လို ခံစားရလဲ” မေး၍ မျက်နှာ ရွေးစေပါ။', 'Ask “how do you feel?” and let the child choose a face.')],
    safety: b('ခံစားမှုတိုင်းကို အသိအမှတ်ပြုပါ — မှားသည်ဟု မဆိုပါနှင့်။', 'Accept every feeling; none is “wrong”.'),
    indoor: true, outdoor: false, oneChild: true, group: true, parentChild: true,
    outcomes: [b('ခံစားမှု ဝေါဟာရ၊ ကိုယ်ကိုထိန်းမှု။', 'Emotion vocabulary and self-regulation.')],
  }),
  activity({
    slug: 'follow_the_pattern', title: b('ပုံစံလိုက် စီကစားခြင်း', 'Follow the pattern'),
    summary: b('အရောင်နှစ်မျိုးကို အလှည့်ကျ စီ၍ သတိပြုခြင်းနှင့် ပုံစံလိုက်နိုင်မှုကို ကစားရင်း လေ့ကျင့်ခြင်း။', 'Practise noticing and copying a simple two-color pattern through play.'),
    ageGroupKey: '3_5y', domains: ['cognitive', 'problem_solving'], difficulty: 'medium', durationMinutes: 10,
    materials: b('မျိုမချနိုင်လောက်အောင် ကြီးသော အရောင်နှစ်မျိုးပါ ကစားတုံးများ။', 'Large blocks in two colors that cannot be swallowed.'),
    setup: b('ကစားတုံးများကို မြင်သာသော စားပွဲ သို့မဟုတ် ကြမ်းပြင်ပေါ် ချထားပါ။', 'Place the blocks on a clear table or floor space.'),
    instructions: [
      b('အရောင်နှစ်မျိုးကို တစ်လှည့်စီဖြင့် သုံးခု စီပြပါ။', 'Make a three-block pattern by alternating two colors.'),
      b('ကလေးကို တူညီသောပုံစံ စီစေပြီး သူ့ဘာသာ ပုံစံသစ်လုပ်ခွင့်ပေးပါ။', 'Invite the child to copy it, then make a new pattern of their own.'),
    ],
    safety: b('အသက်အရွယ်နှင့် သင့်တော်သော ကစားတုံးကြီးများကိုသာ သုံးပြီး ကြီးကြပ်ပါ။', 'Use only age-appropriate large blocks and supervise.'),
    indoor: true, outdoor: false, oneChild: true, group: true, parentChild: true,
    outcomes: [b('ပုံစံသိမှု၊ အစီအစဉ်နှင့် ပြဿနာဖြေရှင်းမှု။', 'Pattern recognition, sequencing, and problem-solving.')],
    evidenceSummary: 'Topic-fit play and developmental references are linked; evidence and safety review remains revision-bound.',
  }),
  activity({
    slug: 'water_pouring', title: b('ရေ လောင်း/ကူးကစားခြင်း', 'Water pouring play'),
    summary: b('ခွက်တစ်လုံးမှ တစ်လုံးသို့ ရေလောင်းကာ လက်ထိန်းချုပ်မှုနှင့် ပြဿနာဖြေရှင်းနိုင်စွမ်းကို လေ့ကျင့်ပေးခြင်း။', 'Build fine-motor and problem-solving by pouring water.'),
    ageGroupKey: '2y', domains: ['fine_motor', 'problem_solving'], difficulty: 'medium', durationMinutes: 15,
    materials: b('ခွက် ၂ လုံး၊ ရေ၊ ပန်းကန်ဗန်း။', 'Two cups, water, a tray.'),
    setup: b('ဗန်းပေါ်တွင် ရေအနည်းငယ်ထည့်၍ ကစားပါ။', 'Set up on a tray with a little water.'),
    instructions: [b('ခွက်တစ်လုံးမှ တစ်လုံးသို့ ရေ လောင်းစေပါ။', 'Let the child pour water between cups.')],
    safety: b('ရေအနီး အမြဲ ကြီးကြပ်ပါ။ ကြမ်းပြင် ချောနေ၍ လဲနိုင်သည်။', 'Always supervise near water; watch slippery floors.'),
    indoor: true, outdoor: true, oneChild: true, group: false, parentChild: true,
    outcomes: [b('ထိန်းချုပ်မှု၊ အတိုင်းအတာ နားလည်မှု။', 'Control and volume concepts.')],
  }),
  activity({
    slug: 'obstacle_course', title: b('အတားအဆီး ကျော်ကစားခြင်း', 'Backyard obstacle course'),
    summary: b('ခုန်ခြင်း၊ ကျော်ခြင်းနှင့် တွားခြင်းတို့ဖြင့် ကိုယ်လက်လှုပ်ရှားမှုနှင့် ဟန်ချက်ကို လေ့ကျင့်ပေးခြင်း။', 'Gross-motor and balance through jumping, climbing, crawling.'),
    ageGroupKey: '4y', domains: ['gross_motor', 'play'], difficulty: 'medium', durationMinutes: 20,
    materials: b('ကြိုး၊ ဘူးခွံ၊ ခုံ (ဘေးကင်း)။', 'Rope, boxes, low bench (safe).'),
    setup: b('ဥယျာဉ်/အခန်းတွင် အဆင့်များ တည်ဆောက်ပါ။', 'Set up stations in a yard or room.'),
    instructions: [b('ခုန်၊ ကျော်၊ တွား အဆင့်တစ်ခုစီ ဖြတ်စေပါ။', 'Guide the child through jump, climb, crawl stations.')],
    safety: b('ခိုင်ခံ့မှုနှင့် ကြမ်းပြင်ကို စစ်ဆေးပြီး ကြီးကြပ်ပါ။', 'Check stability and surface; supervise.'),
    indoor: true, outdoor: true, oneChild: true, group: true, parentChild: true,
    outcomes: [b('ဟန်ချက်၊ ညှိနှိုင်းမှု၊ ယုံကြည်မှု။', 'Balance, coordination, confidence.')],
  }),
  activity({
    slug: 'story_sequence', title: b('ဇာတ်လမ်း အစီအစဉ် ပြန်ပြောကစားခြင်း', 'Story-sequence retelling'),
    summary: b('ဖတ်ပြီးသော ပုံပြင်ကို အစီအစဉ်တကျ ပြန်ပြောစေခြင်း။', 'Retell a story in order to build language and memory.'),
    ageGroupKey: '4y', domains: ['language', 'cognitive'], difficulty: 'medium', durationMinutes: 15,
    materials: b('ပုံပြင်စာအုပ်။', 'A story book.'),
    setup: b('ပုံပြင်တစ်ပုဒ် အတူဖတ်ပါ။', 'Read a story together.'),
    instructions: [b('“ပထမ ဘာဖြစ်လဲ၊ ပြီးတော့” ဟု အစီအစဉ်ဖြင့် မေးပါ။', 'Ask “what happened first, then?” in order.')],
    safety: b('အထူးသတိပြုရန် မရှိပါ။', 'None specific.'),
    indoor: true, outdoor: false, oneChild: true, group: true, parentChild: true,
    outcomes: [b('ဘာသာစကား၊ အစီအစဉ် တွေးခေါ်မှု။', 'Language and sequencing.')],
  }),
  activity({
    slug: 'draw_and_tell', title: b('ပုံဆွဲပြီး ပြောပြကစားခြင်း', 'Draw and tell'),
    summary: b('မိမိဆွဲသောပုံအကြောင်း ပြောပြစေ၍ တီထွင်ဖန်တီးမှုနှင့် ဘာသာစကားကို အတူအားပေးခြင်း။', 'Encourage creativity and language by talking about a child’s own drawing.'),
    ageGroupKey: '4_5y', domains: ['communication', 'fine_motor'], difficulty: 'easy', durationMinutes: 15,
    materials: b('အဆိပ်မရှိသော ခဲတံရောင်ကြီးများနှင့် စက္ကူ။', 'Large non-toxic crayons and paper.'),
    setup: b('စာရွက်နှင့် ခဲတံရောင်များကို တည်ငြိမ်သော စားပွဲပေါ် ချထားပါ။', 'Set paper and crayons on a stable table.'),
    instructions: [
      b('ကလေးစိတ်ကြိုက် ပုံတစ်ပုံ ဆွဲခွင့်ပေးပါ။', 'Let the child draw anything they choose.'),
      b('“ပုံထဲမှာ ဘာဖြစ်နေလဲ” ဟု မေးပြီး အဖြေကို အနှောင့်အယှက်မပေးဘဲ နားထောင်ပါ။', 'Ask “what is happening in your picture?” and listen without interrupting.'),
    ],
    safety: b('အဆိပ်မရှိသော အသက်အရွယ်သင့် ပစ္စည်းများကိုသာ သုံးပြီး ပါးစပ်ထဲမထည့်ရန် ကြီးကြပ်ပါ။', 'Use only non-toxic, age-appropriate materials and supervise to prevent mouthing.'),
    indoor: true, outdoor: true, oneChild: true, group: true, parentChild: true,
    outcomes: [b('တီထွင်ဖန်တီးမှု၊ လက်ထိန်းချုပ်မှုနှင့် ဇာတ်ကြောင်းပြောဆိုမှု။', 'Creativity, hand control, and narrative communication.')],
    evidenceSummary: 'Topic-fit play and early-literacy references are linked; evidence and safety review remains revision-bound.',
  }),
  activity({
    slug: 'name_writing', title: b('နာမည် ခြစ်ရေးကစားခြင်း', 'Name tracing play'),
    summary: b('မိမိနာမည်ကို ခြစ်ရေး၍ ရေးသားမှု အခြေခံ လေ့ကျင့်ခြင်း။', 'Practice pre-writing by tracing one’s name.'),
    ageGroupKey: '5y', domains: ['fine_motor', 'school_readiness'], difficulty: 'medium', durationMinutes: 15,
    materials: b('ခဲတံ၊ စက္ကူ။', 'Crayon and paper.'),
    setup: b('နာမည်ကို အကြီးဖြင့် ရေးပြထားပါ။', 'Write the child’s name in large letters.'),
    instructions: [b('စာလုံးများကို ခြစ်၍ ကူးရေးစေပါ။', 'Let the child trace over the letters.')],
    safety: b('ခဲတံ ချွန်ကို သတိထားပါ။', 'Watch sharp pencil tips.'),
    indoor: true, outdoor: false, oneChild: true, group: true, parentChild: true,
    outcomes: [b('ရေးသားမှု အခြေခံ၊ အက္ခရာသိမှု။', 'Pre-writing and letter recognition.')],
  }),
];
