// Per-domain parent guides. Each covers the full sub-item set requested:
// why it matters, observation questions, activities (daily/weekly/indoor/outdoor/
// low-cost), materials, safety, common mistakes, tips, FAQ, red flags, referral
// guidance, and strengths-based encouragement. General guidance, clinical_review.
import { guide, type SeedItem } from '../types';

const b = (mm: string, en: string) => ({ mm, en });

export const GUIDES: SeedItem[] = [
  guide('7_9m', 'gross_motor', {
    title: b('၇–၉ လ — ကြွက်သားကြီး လှုပ်ရှားမှု', '7–9 months — Gross Motor'),
    why: b('ထိုင်ခြင်း၊ တွားခြင်းသည် ကလေးအား လက်နှစ်ဖက်ဖြင့် ကစားရန်နှင့် ပတ်ဝန်းကျင်ကို စူးစမ်းရန် လွတ်လပ်စေသည်။', 'Sitting and crawling free a baby to explore and use both hands.'),
    observationQuestions: [
      b('အထောက်မပါဘဲ ခဏထိုင်နိုင်ပါသလား။', 'Sits without support briefly?'),
      b('ရှေ့သို့ ရောက်ရန် လှုပ်ရှားရန် ကြိုးစားပါသလား။', 'Tries to move forward to reach a toy?'),
    ],
    dailyActivities: [
      b('မှောက်လျက် ကစားချိန်ကို နေ့စဉ် အနည်းငယ်စီ ပေးပါ။', 'Offer short tummy-time each day.'),
      b('ကစားစရာကို အနည်းငယ်ဝေးရာတွင်ထား၍ လှမ်းယူစေပါ။', 'Place a toy just out of reach to encourage reaching.'),
    ],
    weeklyActivities: [b('ကြမ်းပြင်ပေါ်တွင် လွတ်လပ်စွာ လှုပ်ရှားချိန် ပေးပါ။', 'Give supervised floor-play time on a firm surface.')],
    indoor: [b('ခေါင်းအုံးများဖြင့် တွားဖို့ အတားအဆီး ဖန်တီးပါ။', 'Build a soft pillow obstacle to crawl over.')],
    outdoor: [b('သန့်ရှင်းသော ဖျာပေါ်တွင် အပြင်ထွက် ကစားပါ။', 'Play on a clean mat outdoors.')],
    lowCost: [b('အိမ်သုံး ခေါင်းအုံး/စောင်များကို ကစားကိရိယာအဖြစ် သုံးပါ။', 'Use home pillows and blankets as play props.')],
    materials: b('နူးညံ့ဖျာ၊ ခေါင်းအုံး၊ ပေါ့ပါးသော ကစားစရာ။', 'Soft mat, pillows, light toys.'),
    safety: b('ကစားနေစဉ် အမြဲ စောင့်ကြည့်ပါ။ ခေါင်းအုံးဖြင့် အိပ်ရာမထားပါနှင့်။', 'Always supervise; do not leave pillows in the sleep space.'),
    commonMistakes: [b('ကလေးအား နာရီရှည် ထိုင်ခုံ/ကားထိုင်ခုံတွင် ထားခြင်း။', 'Keeping the baby in seats for long periods.')],
    parentTips: [b('ကလေး၏ အရှိန်ကို လိုက်ပါ — တွန်းအားမပေးပါနှင့်။', 'Follow the baby’s pace — do not force positions.')],
    faq: [{ q: b('တွားခြင်း ကျော်၍ လမ်းလျှောက်ရင် ပြဿနာလား။', 'Is skipping crawling a problem?'), a: b('ကလေးအချို့ တွားခြင်းကို ကျော်တတ်သည် — ရွေ့လျားမှု တိုးတက်နေလျှင် ပုံမှန်ဖြစ်နိုင်သည်။', 'Some babies skip crawling; if mobility is progressing it can be normal.') }],
    redFlags: [b('၉ လတွင် ခေါင်းကို မထိန်းနိုင်သေးခြင်း သို့မဟုတ် ကြွက်သား အလွန်နူးညံ့/တောင့်တင်းခြင်း။', 'By 9 months: no head control, or very floppy/stiff muscles.')],
    referral: b('အထက်ပါ ကိုယ်လက်လှုပ်ရှားမှုဆိုင်ရာ စိုးရိမ်စရာများ တွေ့ပါက ကလေးဆရာဝန် သို့မဟုတ် ကိုယ်လက်လှုပ်ရှားမှု ပြန်လည်သန်စွမ်းရေးပညာရှင်နှင့် တိုင်ပင်ပါ။', 'If you see these motor concerns, consult a pediatrician or physiotherapist.'),
    encouragement: b('ကလေးတိုင်း မိမိအရှိန်ဖြင့် ကြီးထွားသည် — သင့်ကလေး၏ ကြိုးစားမှုတိုင်းကို ချီးမွမ်းပါ။', 'Every child grows at their own pace — celebrate each effort.'),
  }),

  guide('13_18m', 'fine_motor', {
    title: b('၁၃–၁၈ လ — လက်ချောင်းငယ် လှုပ်ရှားမှု', '13–18 months — Fine Motor'),
    why: b('လက်ချောင်းငယ် ကျွမ်းကျင်မှုသည် ကိုယ်တိုင်စားခြင်း၊ ဝတ်ဆင်ခြင်းနှင့် နောင်ရေးသားခြင်းအတွက် အခြေခံဖြစ်သည်။', 'Fine-motor skill underlies self-feeding, dressing, and later writing.'),
    observationQuestions: [
      b('အသက်အရွယ်နှင့် ကိုက်ညီအောင် နူးညံ့စွာ ပြင်ဆင်ထားသော အစားအစာအပိုင်းကို လက်မနှင့် လက်ညှိုးဖြင့် ကောက်နိုင်ပါသလား။', 'Can the child pick up a soft piece of food prepared in an age-appropriate shape and texture with the thumb and finger?'),
      b('ခွက်ထဲ ပစ္စည်းထည့်/ထုတ် လုပ်ပါသလား။', 'Puts objects in and out of a cup?'),
    ],
    dailyActivities: [
      b('အသက်အရွယ်နှင့် ကိုက်ညီအောင် နူးညံ့စွာ ပြင်ဆင်ထားသော လက်ဖြင့်ကိုင်စားနိုင်သည့် အစားအစာများကို ကိုယ်တိုင် ကောက်စားစေပါ။', 'Let them finger-feed safe, soft foods prepared in an age-appropriate shape and texture.'),
      b('ခွက်ထဲသို့ ပါးစပ်ထဲ မဝင်နိုင်လောက်အောင် ကြီးသော ပစ္စည်းများကို ထည့်/ထုတ် ကစားပါ။', 'Play filling and emptying a cup with objects too large to fit in the mouth.'),
    ],
    indoor: [b('မျိုမချနိုင်လောက်အောင် ကြီးသော ကစားတုံးများကို အတူတူ စီကစားပါ။', 'Stack large blocks.')],
    outdoor: [b('လူကြီးနှင့်အတူ ပါးစပ်ထဲ မဝင်နိုင်လောက်အောင် ကြီးသော သန့်ရှင်းသည့် ကစားပစ္စည်းများကို ပုံးထဲ ထည့်ကစားပါ။', 'With an adult, collect clean play objects that are too large to fit in the mouth into a basket.')],
    lowCost: [b('ပလတ်စတစ်ခွက်နှင့် ပါးစပ်ထဲ မဝင်နိုင်လောက်အောင် ကြီးသော ကစားပစ္စည်းများ။', 'Plastic cups and play objects too large to fit in the mouth.')],
    materials: b('ခွက်များ၊ ကစားတုံးကြီးများနှင့် ဘေးကင်းသော ပစ္စည်းအကြီးများ။', 'Cups, big blocks, safe large objects.'),
    safety: b('နှာခေါင်း သို့မဟုတ် ပါးစပ်ထဲ ဝင်နိုင်သော ပစ္စည်းငယ်များကို မသုံးပါနှင့်။ အသက်ရှူလမ်းကြောင်း ပိတ်ဆို့နိုင်သည်။ ကစားနေစဉ် အနီးကပ် စောင့်ကြည့်ပါ။', 'Avoid small objects that can choke; supervise closely.'),
    commonMistakes: [b('ကလေးမလုပ်နိုင်သေးသည်ကို အတင်း လုပ်ခိုင်းခြင်း။', 'Pushing skills the child is not ready for.')],
    parentTips: [b('သန့်ရှင်းမှု ပျက်စီးမှုကို လက်ခံပါ — ဤသည်မှာ သင်ယူခြင်းဖြစ်သည်။', 'Allow mess — it is part of learning.')],
    faq: [{ q: b('ဘယ်လက်/ညာလက် ဘယ်တော့ ရွေးမလဲ။', 'When does hand preference appear?'), a: b('များသောအားဖြင့် ၂–၄ နှစ်တွင် ပေါ်လာသည် — စောစီးစွာ တွန်းအားမပေးပါနှင့်။', 'Usually 2–4 years; do not force it early.') }],
    redFlags: [b('၁၈ လတွင် ပစ္စည်းများကို လုံးဝ မကိုင်တွယ်ခြင်း သို့မဟုတ် လက်တစ်ဖက်ကိုသာ အမြဲသုံးခြင်း။', 'By 18 months: not grasping at all, or always ignoring one hand.')],
    referral: b('စိုးရိမ်စရာ ရှိပါက ကလေးဆရာဝန် သို့မဟုတ် နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ပြန်လည်လေ့ကျင့်ပေးသည့် ပညာရှင်နှင့် တိုင်ပင်ပါ။', 'If concerned, consult a pediatrician or occupational therapist.'),
    encouragement: b('လက်ချောင်းငယ် ကျွမ်းကျင်မှုသည် ကစားရင်း တဖြည်းဖြည်း တိုးတက်လာသည်။', 'Fine-motor skill grows steadily through everyday play.'),
  }),

  guide('19_24m', 'speech', {
    title: b('၁၉–၂၄ လ — စကားသံ ထွက်ဆိုမှု', '19–24 months — Speech'),
    why: b('ဤအရွယ်တွင် စကားလုံးအရေအတွက် လျင်မြန်စွာ တိုးလာသည် — ပတ်ဝန်းကျင်၏ စကားပြောမှုက ဤအရာကို အားဖြည့်ပေးသည်။', 'Vocabulary grows fast now; everyday talk fuels it.'),
    observationQuestions: [
      b('စကားလုံး အသစ်များ တစ်ပတ်လျှင် ထပ်တိုးပါသလား။', 'Adds new words most weeks?'),
      b('စကားလုံး နှစ်လုံး ပေါင်း၍ ပြောပါသလား။', 'Combines two words?'),
    ],
    dailyActivities: [
      b('နေ့စဉ်လုပ်ဆောင်ချက်များကို စကားဖြင့် ရှင်းပြပါ (“ရေ လောင်းမယ်”)။', 'Narrate daily actions (“pouring water”).'),
      b('ကလေးပြောသည်ကို ထပ်ဆင့်၍ ပိုရှည်အောင် ပြန်ပြောပါ။', 'Expand what the child says into a longer phrase.'),
    ],
    indoor: [b('ရုပ်ပုံစာအုပ်ကို အတူဖတ်ပြီး ပုံထဲမှ အရာများ၏ အမည်ကို ပြောပေးပါ။', 'Read picture books and name things together.')],
    outdoor: [b('လမ်းလျှောက်ရင်း မြင်တွေ့သည့် အရာများ၏ အမည်ကို ပြောပေးပါ။', 'Name what you see on a walk.')],
    lowCost: [b('အိမ်သုံးပစ္စည်းများကို ပြသပြီး အမည်ပြောကစားပါ။ ပစ္စည်းအသစ်ဝယ်ရန် မလိုပါ။', 'Name household objects — no cost needed.')],
    materials: b('ရုပ်ပုံစာအုပ်၊ နေ့စဉ်သုံးပစ္စည်းများ။', 'Picture books, everyday objects.'),
    safety: b("ကလေးနှင့် မျက်နှာချင်းဆိုင် စကားပြောပါ။ ဖုန်း သို့မဟုတ် ရုပ်မြင်သံကြားက လူချင်းအပြန်အလှန် ပြောဆိုမှုကို အစားမထိုးနိုင်ပါ။ အစာတစ်ဆို့ခြင်း အန္တရာယ်သည် အသက် ၄ နှစ်အထိ ဆက်ရှိပါသည် — လမ်းလျှောက်တတ်၊ စကားပြောတတ်ပြီဆိုသော်လည်း အန္တရာယ် မကုန်သေးပါ။ စပျစ်သီးနှင့် ချယ်ရီခရမ်းချဉ်သီးများကို အလျားလိုက် လေးစိတ် ခွဲပေးပါ။ အခွံမာသီး အလုံးလိုက်၊ ပြောင်းဖူးပေါက်ပေါက်၊ မာကျောသော သကြားလုံး၊ အစေ့အဆန်များနှင့် မုန်လာဥနီ အစိမ်းများကို အသက် ၄ နှစ်အောက် ကလေးများအား မပေးပါနှင့်။ အမြဲ ထိုင်၍ စားခိုင်းပြီး စားနေစဉ် အနားတွင် ရှိပါ။", "Talk face-to-face; screens do not replace real talk. Choking remains a risk until about age 4 — walking and talking do not end it. Cut grapes and cherry tomatoes into quarters lengthwise. Do not give whole nuts, popcorn, hard sweets, seeds or raw carrot to a child under 4. Always have your child sit to eat, and stay with them while they eat."),
    commonMistakes: [b('ကလေးအတွက် အားလုံး ကြိုတင်လုပ်ပေးခြင်း — တောင်းဆိုရန် အခွင့်အလမ်း မပေးခြင်း။', 'Anticipating every need, so the child has no reason to ask.')],
    parentTips: [b('စကားပြောရန် အချိန်ပေးပါ — အမြန်မဖြေပါနှင့်။', 'Pause and wait, giving time to respond.')],
    faq: [{ q: b('ဘာသာစကား ၂ မျိုး သင်ပေးလို့ရလား။', 'Is raising bilingual okay?'), a: b('ရပါသည် — ဘာသာစကား ၂ မျိုးသည် ကလေးကို မရှုပ်ထွေးစေပါ။', 'Yes — two languages does not confuse children.') }],
    redFlags: [b('၂၄ လအရွယ်တွင် စကားလုံးနှစ်လုံးတွဲ မပြောသေးခြင်း၊ သုံးစွဲသော ဘာသာစကားအားလုံးတွင် စကားလုံးအလွန်နည်းခြင်း သို့မဟုတ် ယခင်သုံးခဲ့သော စကားလုံးများ ပျောက်သွားခြင်း။', 'By 24 months: no two-word combinations, a very small vocabulary across all languages used, or loss of words previously used.')],
    referral: b('ကလေး၏ စကားပြောဖွံ့ဖြိုးမှုအတွက် စိုးရိမ်ပါက ကလေးဆရာဝန် သို့မဟုတ် စကားပြောနှင့် ဘာသာစကားဆိုင်ရာ ပညာရှင်နှင့် တိုင်ပင်ပါ။', 'If worried about speech delay, consult a pediatrician or speech therapist.'),
    encouragement: b('စကားလုံးတိုင်းသည် အောင်မြင်မှုတစ်ခုဖြစ်သည် — အတူပြောဆိုမှုကို ပျော်ရွှင်စွာ ဆက်လုပ်ပါ။', 'Every word is a win — keep talking together joyfully.'),
  }),

  guide('2y', 'language', {
    title: b('၂ နှစ် — ဘာသာစကား နားလည်မှု', '2 years — Language'),
    why: b('နားလည်မှုသည် စကားပြောခြင်းထက် ရှေ့ကရောက်တတ်သည် — ညွှန်ကြားချက် လိုက်နာနိုင်မှုက ဤအရာကို ပြသည်။', 'Understanding often runs ahead of speaking; following directions shows it.'),
    observationQuestions: [
      b('အဆင့်တစ်ဆင့် ညွှန်ကြားချက်ကို လိုက်နာပါသလား။', 'Follows a one-step instruction?'),
      b('စာအုပ်ထဲ ပုံများကို ညွှန်ပြပါသလား။', 'Points to pictures in a book when named?'),
    ],
    dailyActivities: [b('ရိုးရှင်းသော ခိုင်းစေမှုများ ပေးပါ (“ဖိနပ် ယူခဲ့ပါ”)။', 'Give simple requests (“bring your shoe”).')],
    weeklyActivities: [b('သီချင်း/ကလေးကဗျာများ အတူ ဆိုပါ။', 'Sing songs and rhymes together.')],
    indoor: [b('ခန္ဓာကိုယ် အစိတ်အပိုင်း သီချင်းများ ဆိုပါ။', 'Sing body-part songs.')],
    outdoor: [b('အရောင်/အသံများ ရှာဖွေ ကစားပါ။', 'Play “find the color/sound” outside.')],
    lowCost: [b('မဂ္ဂဇင်းအဟောင်းမှ ပုံများကို ပြပြီး အမည်ပြောကစားပါ။', 'Use old magazine pictures to name things.')],
    materials: b('ရုပ်ပုံစာအုပ်၊ သီချင်း။', 'Picture books, songs.'),
    safety: b("စာဖတ်ချိန်ကို နူးညံ့သော နေရာတွင် ထားပါ။ အစာတစ်ဆို့ခြင်း အန္တရာယ်သည် အသက် ၄ နှစ်အထိ ဆက်ရှိပါသည် — လမ်းလျှောက်တတ်၊ စကားပြောတတ်ပြီဆိုသော်လည်း အန္တရာယ် မကုန်သေးပါ။ စပျစ်သီးနှင့် ချယ်ရီခရမ်းချဉ်သီးများကို အလျားလိုက် လေးစိတ် ခွဲပေးပါ။ အခွံမာသီး အလုံးလိုက်၊ ပြောင်းဖူးပေါက်ပေါက်၊ မာကျောသော သကြားလုံး၊ အစေ့အဆန်များနှင့် မုန်လာဥနီ အစိမ်းများကို အသက် ၄ နှစ်အောက် ကလေးများအား မပေးပါနှင့်။ အမြဲ ထိုင်၍ စားခိုင်းပြီး စားနေစဉ် အနားတွင် ရှိပါ။", "Keep reading time in a calm, safe spot. Choking remains a risk until about age 4 — walking and talking do not end it. Cut grapes and cherry tomatoes into quarters lengthwise. Do not give whole nuts, popcorn, hard sweets, seeds or raw carrot to a child under 4. Always have your child sit to eat, and stay with them while they eat."),
    commonMistakes: [b('တီဗွီ/ဖုန်းဖြင့် ဘာသာစကား သင်ကြားမည်ဟု ထင်ခြင်း။', 'Relying on screens to teach language.')],
    parentTips: [b('နေ့စဉ် ရုပ်ပုံစာအုပ် အတူဖတ်ခြင်းက အထိရောက်ဆုံးဖြစ်သည်။', 'Daily shared book-reading is the single best habit.')],
    faq: [{ q: b('စာအုပ် ဘယ်နှစ်အုပ် လိုအပ်လဲ။', 'How many books do we need?'), a: b('အနည်းငယ်ကို ထပ်ခါဖတ်ခြင်းက အသစ်များစွာထက် ပို၍ အကျိုးရှိသည်။', 'Re-reading a few is better than many new ones.') }],
    redFlags: [b('၂ နှစ်တွင် ရိုးရှင်းသော ညွှန်ကြားချက်ကို လုံးဝ နားမလည်ခြင်း။', 'By 2 years: cannot follow any simple direction.')],
    referral: b('နားလည်မှု စိုးရိမ်ပါက ကလေးကျန်းမာရေးဆရာဝန် (နှင့် လိုအပ်ပါက အကြားအာရုံစစ်ဆေးမှု) နှင့် တိုင်ပင်ပါ။', 'If concerned, consult a pediatrician (and a hearing check if advised).'),
    encouragement: b('သင့်အသံသည် ကလေး၏ အကောင်းဆုံး သင်ကြားကိရိယာဖြစ်သည်။', 'Your voice is your child’s best teaching tool.'),
  }),

  guide('10_12m', 'communication', {
    title: b('၁၀–၁၂ လ — ဆက်သွယ်ပြောဆိုမှု', '10–12 months — Communication'),
    why: b('လက်ညှိုးထိုးခြင်း၊ လက်ဝှေ့ခြင်းသည် စကားလုံးမတိုင်မီ ဆက်သွယ်မှုနည်းလမ်းများဖြစ်သည်။', 'Pointing and waving are communication before words.'),
    observationQuestions: [
      b('လက်ပြနှုတ်ဆက်ခြင်း သို့မဟုတ် လက်ခုပ်တီးခြင်း ပြုလုပ်ပါသလား။', 'Waves bye-bye or claps?'),
      b('အလိုရှိသည်ကို အသံ/လက်ဟန်ဖြင့် ပြသပါသလား။', 'Uses sounds or gestures to show wants?'),
    ],
    dailyActivities: [b('လက်ခုပ်တီးခြင်းနှင့် လက်ပြနှုတ်ဆက်ခြင်းကဲ့သို့ လက်ဟန်များကို အတူ လုပ်ပြပါ။', 'Practice gestures like clap and wave.')],
    indoor: [b('“ဘယ်မှာလဲ၊ ဒီမှာပါ” ဟု မျက်နှာဖုံးဖော် ကစားပါ။', 'Play peek-a-boo.')],
    outdoor: [b('မြင်တွေ့သည့် အရာများကို လက်ညှိုးဖြင့်ညွှန်ပြီး အမည်ပြောပေးပါ။', 'Point and name things you see.')],
    lowCost: [b('ပဝါ သို့မဟုတ် စောင်ပါးတစ်ထည်ဖြင့် မျက်နှာဖုံးဖော် ကစားနိုင်သည်။', 'Peek-a-boo with a cloth — no cost.')],
    materials: b('စောင်၊ ရုပ်ပုံ။', 'Cloth, pictures.'),
    safety: b('မျက်နှာချင်းဆိုင် အပြန်အလှန် ကစားချိန်ကို ဦးစားပေးပါ။', 'Prioritize face-to-face back-and-forth play.'),
    commonMistakes: [b('ကလေး၏ လက်ဟန်များကို လျစ်လျူရှုခြင်း — တုံ့ပြန်ပေးခြင်းက ဆက်သွယ်မှု သင်ယူရာတွင် အထောက်အကူပြုသည်။', 'Ignoring gestures — responding supports communication learning.')],
    parentTips: [b('ကလေး ညွှန်ပြသည့်အရာ၏ အမည်ကို ပြောပေးပါ။', 'Name whatever your child points at.')],
    faq: [{ q: b('လက်ဟန်များသည် စကားပြောခြင်းကို နှောင့်နှေးစေမလား။', 'Do gestures delay talking?'), a: b('မဟုတ်ပါ — လက်ဟန်များသည် စကားပြောခြင်းကို အားပေးသည်။', 'No — gestures support talking.') }],
    redFlags: [b('၁၂ လအရွယ်တွင် လက်ပြနှုတ်ဆက်ခြင်း မပြုခြင်း၊ မိဘ သို့မဟုတ် အုပ်ထိန်းသူကို “မေမေ”၊ “ဖေဖေ” သို့မဟုတ် အခြားအထူးအမည်ဖြင့် မခေါ်ခြင်း၊ သို့မဟုတ် “မလုပ်နဲ့” ဟူသော စကားကို နားမလည်ခြင်း။', 'By 12 months: does not wave bye-bye, call a parent or caregiver “mama”, “dada” or another special name, or understand “no”.')],
    referral: b('ဆက်သွယ်မှု လက္ခဏာများ မရှိပါက ကလေးကျန်းမာရေးဆရာဝန်နှင့် တိုင်ပင်ပါ။', 'If early communication signs are absent, consult a pediatrician.'),
    encouragement: b('ဆက်သွယ်မှုသည် စကားလုံးမတိုင်မီကပင် စတင်နေပြီ — အပြန်အလှန် တုံ့ပြန်မှုကို ဆက်လုပ်ပါ။', 'Communication starts before words — keep responding.'),
  }),

  guide('3y', 'cognitive', {
    title: b('၃ နှစ် — အသိဉာဏ် ဖွံ့ဖြိုးမှု', '3 years — Cognitive'),
    why: b('အရောင်၊ ပုံသဏ္ဌာန်၊ အရေအတွက် သိရှိခြင်းသည် ကျောင်းသင်ယူမှု၏ အခြေခံဖြစ်သည်။', 'Colors, shapes, and counting are the base for school learning.'),
    observationQuestions: [
      b('အရောင်အချို့၏ အမည်ကို ပြောနိုင်ပါသလား။', 'Names a few colors?'),
      b('“၃” အထိ ရေတွက်ပါသလား။', 'Counts to three?'),
    ],
    dailyActivities: [b('အဝတ်လျှော်ရင်း အရောင်ဖြင့် ခွဲစေပါ။', 'Sort laundry by color together.')],
    weeklyActivities: [b('ပုံသဏ္ဌာန် ရှာဖွေ ကစားပါ။', 'Play a shape-hunt.')],
    indoor: [b('ကစားတုံးများဖြင့် ပုံသဏ္ဌာန်အမျိုးမျိုး တည်ဆောက်ပါ။', 'Build shapes with blocks.')],
    outdoor: [b('သဘာဝ ပစ္စည်းများ (ကျောက်၊ အရွက်) ရေတွက်ပါ။', 'Count natural items outside.')],
    lowCost: [b('ဘူးခွံ/အဖုံးများဖြင့် အရောင်ခွဲ ကစားပါ။', 'Sort bottle caps by color.')],
    materials: b('ကစားတုံးများနှင့် အရောင်စုံပစ္စည်းများ။', 'Blocks, colorful objects.'),
    safety: b("ငယ်သောပစ္စည်းများကို ကြီးကြပ်လျက်သာ သုံးပါ။ အစာတစ်ဆို့ခြင်း အန္တရာယ်သည် အသက် ၄ နှစ်အထိ ဆက်ရှိပါသည် — လမ်းလျှောက်တတ်၊ စကားပြောတတ်ပြီဆိုသော်လည်း အန္တရာယ် မကုန်သေးပါ။ စပျစ်သီးနှင့် ချယ်ရီခရမ်းချဉ်သီးများကို အလျားလိုက် လေးစိတ် ခွဲပေးပါ။ အခွံမာသီး အလုံးလိုက်၊ ပြောင်းဖူးပေါက်ပေါက်၊ မာကျောသော သကြားလုံး၊ အစေ့အဆန်များနှင့် မုန်လာဥနီ အစိမ်းများကို အသက် ၄ နှစ်အောက် ကလေးများအား မပေးပါနှင့်။ အမြဲ ထိုင်၍ စားခိုင်းပြီး စားနေစဉ် အနားတွင် ရှိပါ။", "Supervise small counting objects. Choking remains a risk until about age 4 — walking and talking do not end it. Cut grapes and cherry tomatoes into quarters lengthwise. Do not give whole nuts, popcorn, hard sweets, seeds or raw carrot to a child under 4. Always have your child sit to eat, and stay with them while they eat."),
    commonMistakes: [b('ရုပ်ပုံကတ်များကိုသာ အလွတ်ကျက်စေခြင်း။ ကလေးသည် ကစားရင်း သင်ယူသည့်အခါ ပိုမို နားလည်လွယ်သည်။', 'Drilling flashcards — play-based learning works better.')],
    parentTips: [b('နေ့စဉ်လုပ်ငန်းများထဲ သင်ခန်းစာ ထည့်ပါ။', 'Fold learning into daily chores.')],
    faq: [{ q: b('အက္ခရာ ဘယ်တော့ စသင်ရမလဲ။', 'When to start letters?'), a: b('စိတ်ဝင်စားမှုကို လိုက်ပါ — အတင်း မလုပ်ခိုင်းပါနှင့်။', 'Follow interest; do not force.') }],
    redFlags: [b('၃ နှစ်တွင် ရိုးရှင်းသော ညွှန်ကြားချက်/ပုံ နားမလည်ခြင်း သို့မဟုတ် စွမ်းရည် ဆုတ်ယုတ်ခြင်း။', 'By 3 years: cannot understand simple directions, or loss of skills.')],
    referral: b('သင်ယူမှု စိုးရိမ်စရာ တွေ့ပါက ကလေးကျန်းမာရေးဆရာဝန်နှင့် တိုင်ပင်ပါ။', 'If concerned about learning, consult a pediatrician.'),
    encouragement: b('ကလေးများသည် ကစားရင်း အကောင်းဆုံး သင်ယူကြသည်။', 'Children learn best through play.'),
  }),

  guide('4y', 'problem_solving', {
    title: b('၄ နှစ် — ပြဿနာ ဖြေရှင်းခြင်း', '4 years — Problem Solving'),
    why: b('ပြဿနာ ဖြေရှင်းခြင်းသည် စိတ်ရှည်မှု၊ စီစဉ်မှုနှင့် ယုံကြည်မှုကို တည်ဆောက်ပေးသည်။', 'Problem solving builds patience, planning, and confidence.'),
    observationQuestions: [
      b('အခက်အခဲ ကြုံရင် နည်းလမ်း ရှာဖွေ ကြိုးစားပါသလား။', 'Tries different ways when stuck?'),
      b('ပဟေဠိ/ဆောက်လုပ်မှုကို ပြီးဆုံးအောင် လုပ်ပါသလား။', 'Completes a puzzle or build?'),
    ],
    dailyActivities: [b('“ဘာဖြစ်လို့လဲ” “ဘယ်လိုလုပ်မလဲ” မေးခွန်းများ မေးပါ။', 'Ask open “why/how” questions.')],
    indoor: [b('ရိုးရှင်းသော ပဟေဠိများ တပ်ဆင်ပါ။', 'Do simple puzzles.')],
    outdoor: [b('သဲ/ရေဖြင့် စမ်းသပ် ကစားပါ။', 'Experiment with sand and water.')],
    lowCost: [b('ဘူးခွံများဖြင့် တံတား/မျှော်စင် ဆောက်ပါ။', 'Build a tower/bridge from boxes.')],
    materials: b('ရုပ်ပုံဆက်ကစားစရာ၊ ကစားတုံးများနှင့် ဘူးခွံများ။', 'Puzzles, blocks, boxes.'),
    safety: b("ဆောက်လုပ်ရာတွင် ခိုင်ခံ့မှုကို ကြည့်ရှုပါ။ အစာတစ်ဆို့ခြင်း အန္တရာယ်သည် အသက် ၄ နှစ်အထိ ဆက်ရှိပါသည် — လမ်းလျှောက်တတ်၊ စကားပြောတတ်ပြီဆိုသော်လည်း အန္တရာယ် မကုန်သေးပါ။ စပျစ်သီးနှင့် ချယ်ရီခရမ်းချဉ်သီးများကို အလျားလိုက် လေးစိတ် ခွဲပေးပါ။ အခွံမာသီး အလုံးလိုက်၊ ပြောင်းဖူးပေါက်ပေါက်၊ မာကျောသော သကြားလုံး၊ အစေ့အဆန်များနှင့် မုန်လာဥနီ အစိမ်းများကို အသက် ၄ နှစ်အောက် ကလေးများအား မပေးပါနှင့်။ အမြဲ ထိုင်၍ စားခိုင်းပြီး စားနေစဉ် အနားတွင် ရှိပါ။", "Watch stability when building. Choking remains a risk until about age 4 — walking and talking do not end it. Cut grapes and cherry tomatoes into quarters lengthwise. Do not give whole nuts, popcorn, hard sweets, seeds or raw carrot to a child under 4. Always have your child sit to eat, and stay with them while they eat."),
    commonMistakes: [b('ချက်ချင်း ဝင်ကူညီခြင်း — ကြိုးစားခွင့် အရင်ပေးပါ။', 'Jumping in too fast — let them try first.')],
    parentTips: [b('အဖြေပေးမည့်အစား ဦးဆောင်မေးခွန်းများ မေးပါ။', 'Ask guiding questions instead of giving answers.')],
    faq: [{ q: b('စိတ်ပျက်ငိုရင် ဘယ်လိုလုပ်မလဲ။', 'What if they get frustrated?'), a: b('ခံစားမှုကို အသိအမှတ်ပြု၍ အနားယူပြီးမှ ပြန်ကြိုးစားစေပါ။', 'Acknowledge the feeling, take a break, then retry.') }],
    redFlags: [b('၄ နှစ်တွင် ရိုးရှင်းသော ပဟေဠိ/ညွှန်ကြားချက်များကို လုံးဝ မလုပ်နိုင်ခြင်း။', 'By 4 years: cannot manage any simple puzzle or 2-step direction.')],
    referral: b('စိုးရိမ်ပါက ကလေးကျန်းမာရေးဆရာဝန်နှင့် တိုင်ပင်ပါ။', 'If concerned, consult a pediatrician.'),
    encouragement: b('မှားယွင်းမှုတိုင်းသည် သင်ယူမှုတစ်ခုဖြစ်သည် — ကြိုးစားမှုကို ချီးမွမ်းပါ။', 'Every mistake is learning — praise the effort.'),
  }),

  guide('3y', 'social', {
    title: b('၃ နှစ် — လူမှုဆက်ဆံရေး', '3 years — Social'),
    why: b('အလှည့်ကျ ကစားခြင်းနှင့် ဝေမျှခြင်းသည် သူငယ်ချင်းဖွဲ့မှုနှင့် ကျောင်းဘဝအတွက် ပြင်ဆင်ပေးသည်။', 'Turn-taking and sharing prepare for friendships and school.'),
    observationQuestions: [
      b('အခြားကလေးများနှင့် အတူ ကစားပါသလား။', 'Plays alongside/with other children?'),
      b('အလှည့်စောင့်ရန် ကြိုးစားပါသလား။', 'Tries to take turns?'),
    ],
    dailyActivities: [b('အလှည့်ကျ ကစားနည်းများ (ဘောလုံးလှိမ့်) ကစားပါ။', 'Play turn-taking games (roll a ball back).')],
    weeklyActivities: [b('အခြားကလေးများနှင့် ကစားချိန် စီစဉ်ပါ။', 'Arrange playtime with other children.')],
    indoor: [b('အရုပ်ဖြင့် လူမှုအခြေအနေများ ဟန်ဆောင် ကစားပါ။', 'Role-play social scenes with dolls.')],
    outdoor: [b('အုပ်စုဖြင့် ရိုးရှင်းသော ကစားနည်းများ ကစားပါ။', 'Play simple group games outside.')],
    lowCost: [b('အိမ်တွင် လူ ၂–၃ ဦးဖြင့် အလှည့်ကျ ကစားပါ။', 'Turn-taking at home with family.')],
    materials: b('ဘောလုံး၊ အရုပ်။', 'Ball, dolls.'),
    safety: b("ကစားစဉ် ကြီးကြပ်၍ ဘေးကင်းစေပါ။ အစာတစ်ဆို့ခြင်း အန္တရာယ်သည် အသက် ၄ နှစ်အထိ ဆက်ရှိပါသည် — လမ်းလျှောက်တတ်၊ စကားပြောတတ်ပြီဆိုသော်လည်း အန္တရာယ် မကုန်သေးပါ။ စပျစ်သီးနှင့် ချယ်ရီခရမ်းချဉ်သီးများကို အလျားလိုက် လေးစိတ် ခွဲပေးပါ။ အခွံမာသီး အလုံးလိုက်၊ ပြောင်းဖူးပေါက်ပေါက်၊ မာကျောသော သကြားလုံး၊ အစေ့အဆန်များနှင့် မုန်လာဥနီ အစိမ်းများကို အသက် ၄ နှစ်အောက် ကလေးများအား မပေးပါနှင့်။ အမြဲ ထိုင်၍ စားခိုင်းပြီး စားနေစဉ် အနားတွင် ရှိပါ။", "Supervise group play for safety. Choking remains a risk until about age 4 — walking and talking do not end it. Cut grapes and cherry tomatoes into quarters lengthwise. Do not give whole nuts, popcorn, hard sweets, seeds or raw carrot to a child under 4. Always have your child sit to eat, and stay with them while they eat."),
    commonMistakes: [b('ဝေမျှခြင်းကို အတင်းအကျပ် ခိုင်းခြင်း — နမူနာပြခြင်းက ပိုကောင်းသည်။', 'Forcing sharing — modeling works better.')],
    parentTips: [b('ကြင်နာသော အပြုအမူကို တိတိကျကျ ချီးမွမ်း၍ အားပေးပါ။', 'Praise kind behavior specifically.')],
    faq: [{ q: b('တစ်ယောက်တည်း ကစားရင် ပြဿနာလား။', 'Is solo play a problem?'), a: b('မဟုတ်ပါ — တစ်ယောက်တည်း ကစားခြင်းသည်လည်း ကျန်းမာသော ဖွံ့ဖြိုးမှုဖြစ်သည်။', 'No — solo play is also healthy.') }],
    redFlags: [b('၃ နှစ်အရွယ်တွင် အခြားကလေးများကို သတိမပြုခြင်း သို့မဟုတ် ၎င်းတို့နှင့် ကစားရန် လုံးဝ မပါဝင်ခြင်း။', 'By 3 years: does not notice other children or join them to play.')],
    referral: b('လူမှုဆက်ဆံရေး စိုးရိမ်စရာ တွေ့ပါက ကလေးကျန်းမာရေးဆရာဝန်နှင့် တိုင်ပင်ပါ။', 'If concerned about social development, consult a pediatrician.'),
    encouragement: b('လူမှုကျွမ်းကျင်မှုသည် ကစားရင်း တဖြည်းဖြည်း သင်ယူရသော ကျွမ်းကျင်မှုဖြစ်သည်။', 'Social skills are learned gradually through play.'),
  }),

  guide('2_5y', 'emotional', {
    title: b('၂ နှစ်ခွဲ — စိတ်ခံစားမှု', '2.5 years — Emotional'),
    why: b('ခံစားချက်ကို စကားလုံးဖြင့် ဖော်ပြပြီး ထိန်းညှိနည်း သင်ယူခြင်းသည် စိတ်ခံစားမှု ကျန်းမာရေးအတွက် အရေးကြီးပါသည်။', 'Learning to name and cope with feelings is important for emotional health.'),
    observationQuestions: [
      b('ခံစားမှု အနည်းငယ်ကို စကားဖြင့် ပြောပါသလား။', 'Names a few feelings?'),
      b('စိတ်တိုငိုပြီးနောက် ပြန်ငြိမ်နိုင်ပါသလား။', 'Calms down after a tantrum?'),
    ],
    dailyActivities: [b('ကလေး၏ ခံစားချက်ကို စကားလုံးဖြင့် ပြောပြပေးပါ။ ဥပမာ—“သားသား စိတ်ဆိုးနေတယ်နော်”။', 'Name your child’s feelings (“you feel angry”).')],
    indoor: [b('ခံစားမှု မျက်နှာ ပုံများဖြင့် ကစားပါ။', 'Play with feeling-face cards.')],
    outdoor: [b('စွမ်းအင်ထုတ်ရန် ပြေးခုန် ကစားစေပါ။', 'Let them run to release energy.')],
    lowCost: [b('မျက်နှာ ပုံ ၄ မျိုးကို ကိုယ်တိုင်ဆွဲ၍ ကစားပါ။', 'Draw four feeling faces to play with.')],
    materials: b('ခံစားမှု ကတ်ပြား/ပုံ။', 'Feeling cards or drawings.'),
    safety: b('ကလေး စိတ်ခံစားမှု ပြင်းထန်နေစဉ် ဘေးကင်းအောင် ထားပါ။', 'Keep the child safe during big feelings.'),
    commonMistakes: [b('ခံစားမှုကို “မဖြစ်သင့်” ဟု ဆိုခြင်း — ခံစားမှုကို အသိအမှတ်ပြုပါ။', 'Dismissing feelings — acknowledge them instead.')],
    parentTips: [b('တည်ငြိမ်စွာ ရှိနေခြင်းက ကလေးကို ငြိမ်သက်ရန် သင်ပေးသည်။', 'Your calm teaches their calm.')],
    faq: [{ q: b('ကလေး စိတ်တိုပြီး ငိုကြွေးတတ်ခြင်းသည် ပုံမှန်လား။', 'Are tantrums normal?'), a: b('ဤအရွယ်တွင် မကြာခဏ တွေ့ရတတ်ပါသည်။ ကလေးသည် မိမိခံစားချက်ကို ထိန်းညှိနိုင်ရန် သင်ယူနေဆဲ ဖြစ်သည်။', 'Yes, at this age — they are practicing self-control.') }],
    redFlags: [b('မကြာခဏ ကိုယ်ကို/သူတစ်ပါးကို ထိခိုက်စေခြင်း သို့မဟုတ် လုံးဝ မငြိမ်နိုင်ခြင်း။', 'Frequent self-harm/harm to others, or never able to calm.')],
    referral: b('စိတ်ခံစားမှု ပြင်းထန်စွာ စိုးရိမ်ပါက ကလေးကျန်းမာရေးဆရာဝန် သို့မဟုတ် ကလေးစိတ်ပညာရှင်နှင့် တိုင်ပင်ပါ။', 'If very concerned, consult a pediatrician or child psychologist.'),
    encouragement: b('ခံစားမှုကို လက်ခံပေးခြင်းဖြင့် ကလေးသည် လုံခြုံစိတ်ချရသည်။', 'Accepting feelings helps a child feel safe.'),
  }),

  guide('13_18m', 'self_help', {
    title: b('၁၃–၁၈ လ — ကိုယ်တိုင် လုပ်ဆောင်နိုင်မှု', '13–18 months — Self Help'),
    why: b('ကိုယ်တိုင်စား၊ ကိုယ်တိုင်ဝတ်ရန် ကြိုးစားခြင်းသည် လွတ်လပ်မှုနှင့် ယုံကြည်မှုကို တည်ဆောက်သည်။', 'Trying to self-feed and dress builds independence and confidence.'),
    observationQuestions: [
      b('ဇွန်း/ခွက်ကို သုံးရန် ကြိုးစားပါသလား။', 'Tries to use a spoon or cup?'),
      b('ဝတ်စားခြင်းတွင် ကူညီပါသလား (လက်/ခြေ ဆန့်)။', 'Helps with dressing (holds out arm/leg)?'),
    ],
    dailyActivities: [b('စားချိန်တွင် ဇွန်း ကိုယ်တိုင်ကိုင်ခွင့် ပေးပါ။', 'Let them hold a spoon at mealtimes.')],
    indoor: [b('ဖိနပ်/ဦးထုပ် ကိုယ်တိုင်ဝတ် ကစားပါ။', 'Practice putting on hat/shoes.')],
    outdoor: [b('ကစားပြီးနောက် ကစားစရာ သိမ်းရန် ကူညီစေပါ။', 'Help tidy toys after outdoor play.')],
    lowCost: [b('အိမ်သုံး ခွက်/ဇွန်းများဖြင့်သာ လေ့ကျင့်ပါ။', 'Practice with ordinary home cups/spoons.')],
    materials: b('ကလေးခွက်၊ ဇွန်း၊ ဝတ်စရာ။', 'Child cup, spoon, clothes.'),
    safety: b('ကလေး စားနေစဉ် အမြဲ အနီးကပ်ကြီးကြပ်ပါ။ အစားအစာကြောင့် အသက်ရှူလမ်းကြောင်း ပိတ်ဆို့နိုင်သည့် အန္တရာယ်ကို သတိပြုပါ။', 'Always supervise eating (choking risk).'),
    commonMistakes: [b('အမြန်/သန့်ရှင်းစေရန် အားလုံး ကိုယ်တိုင်လုပ်ပေးခြင်း။', 'Doing everything for them to save time/mess.')],
    parentTips: [b('အချိန်ပို ၅ မိနစ် ပေးပြီး ကိုယ်တိုင် ကြိုးစားစေပါ။', 'Allow an extra 5 minutes for them to try.')],
    faq: [{ q: b('အိမ်သာသင်ခြင်း ဘယ်တော့ စရမလဲ။', 'When to start toilet training?'), a: b('အသက်တစ်ခုတည်းကို မူတည်မထားဘဲ ကလေး၏ ကိုယ်ခန္ဓာ၊ အပြုအမူနှင့် ဆက်သွယ်မှုဆိုင်ရာ အသင့်ဖြစ်မှု လက္ခဏာများ ပေါ်လာသည့်အခါ ဖိအားမပေးဘဲ စတင်ပါ။', 'Start without pressure when the child shows physical, behavioral, and communication readiness signs rather than using one fixed age.') }],
    redFlags: [b('ယခင်က ပြုလုပ်နိုင်ခဲ့သော ကိုယ်တိုင်လုပ်ဆောင်မှု ကျွမ်းကျင်မှု ပျောက်ဆုံးခြင်း သို့မဟုတ် အစာစား/မျိုရာတွင် ဆက်တိုက်ခက်ခဲခြင်း။', 'Loss of previously acquired self-help skills, or persistent difficulty eating or swallowing.')],
    referral: b('စိုးရိမ်ပါက ကလေးကျန်းမာရေးဆရာဝန်နှင့် တိုင်ပင်ပါ။', 'If concerned, consult a pediatrician.'),
    encouragement: b('“ကိုယ်တိုင်လုပ်မယ်” ဆိုသည့် စိတ်ကို အားပေးပါ — ဤသည်မှာ ကြီးထွားမှုဖြစ်သည်။', 'Encourage the “I can do it” spirit — that is growth.'),
  }),

  guide('5_6m', 'play', {
    title: b('၅–၆ လ — ကစားခြင်း', '5–6 months — Play'),
    why: b('ကစားခြင်းသည် ကလေး၏ သင်ယူမှု၊ လှုပ်ရှားမှုနှင့် ပြုစုစောင့်ရှောက်သူနှင့် ဆက်သွယ်မှုကို အထောက်အကူပြုပါသည်။', 'Play supports your baby’s learning, movement, and connection with caregivers.'),
    observationQuestions: [
      b('ကစားစရာများကို ကိုင်၍ ပါးစပ်ဖြင့်လည်း စူးစမ်းပါသလား။', 'Explores toys by holding and mouthing?'),
      b('အသံ/အရောင်များကို စိတ်ဝင်စားပါသလား။', 'Shows interest in sounds and colors?'),
    ],
    dailyActivities: [b('ကွဲပြားသော ဖွဲ့စည်းပုံ (ကြမ်း/နူး) ပစ္စည်းများ ပေးပါ။', 'Offer objects with different textures.')],
    indoor: [b('ဘေးကင်းသော မှန်ရှေ့တွင် ကိုယ်ကိုကြည့် ကစားပါ။', 'Play in front of a safe mirror.')],
    outdoor: [b('အရိပ်အောက်တွင် သဘာဝ အသံ/မြင်ကွင်း ခံစားစေပါ။', 'Enjoy nature sights/sounds in the shade.')],
    lowCost: [b('သန့်ရှင်းသော အိမ်သုံး ပလတ်စတစ်ခွက်နှင့် ဇွန်းများဖြင့် ကစားပါ။', 'Play with clean plastic cups and spoons.')],
    materials: b('ကွဲပြားသော ဖွဲ့စည်းပုံ ကစားစရာ၊ မှန်။', 'Textured toys, mirror.'),
    safety: b('ပါးစပ်ထဲဝင်နိုင်သော ငယ်သောပစ္စည်းများ ရှောင်ပါ။', 'Avoid small choking-risk objects.'),
    commonMistakes: [b('ကစားစရာ အများကြီးကို တစ်ပြိုင်နက်ပေးခြင်း — ဘေးကင်းသော ပစ္စည်းအနည်းငယ်ကို တစ်ခုချင်းစီ စူးစမ်းရန် အချိန်ပေးပါ။', 'Offering many toys at once — give time to explore a few safe objects one at a time.')],
    parentTips: [b('ဈေးကြီးသော ကစားစရာ မလိုပါ — သင်၏ နွေးထွေးသော တုံ့ပြန်မှုက အရေးပါပါသည်။', 'No expensive toys are needed — warm, responsive interaction matters.')],
    faq: [{ q: b('ဖုန်း သို့မဟုတ် ရုပ်မြင်သံကြား ကြည့်စေလို့ ရပါသလား။', 'Is screen time okay?'), a: b('ဤအသက်အရွယ်တွင် ဖန်သားပြင်အသုံးပြုမှုကို အလွန်ကန့်သတ်ထားပါ။ လူကြီးတစ်ဦးက ကလေး ပါဝင်ဆက်သွယ်နိုင်အောင် ကူညီပေးသော မိသားစုနှင့် တိုက်ရိုက် ဗီဒီယိုခေါ်ဆိုမှုကို အပြန်အလှန်ဆက်သွယ်မှုအဖြစ် အသုံးပြုနိုင်ပါသည်။ ဖန်သားပြင်က မျက်နှာချင်းဆိုင် ကစားပြောဆိုမှုကို အစားမထိုးစေပါနှင့်။', 'At this age, keep screen use very limited. A live video call with family can be interactive when an adult helps the baby take part. Do not let screens replace face-to-face play.') }],
    redFlags: [b('ကစားစရာ/လူများကို လုံးဝ စိတ်မဝင်စားခြင်း။', 'No interest in toys or people at all.')],
    referral: b('စိုးရိမ်ပါက ကလေးကျန်းမာရေးဆရာဝန်နှင့် တိုင်ပင်ပါ။', 'If concerned, consult a pediatrician.'),
    encouragement: b('သင်နှင့်အတူ ကစားချိန်သည် ကလေး၏ သင်ယူမှုနှင့် ဆက်ဆံရေးကို အထောက်အကူပြုပါသည်။', 'Playing with you supports your baby’s learning and connection.'),
  }),

  guide('5_6m', 'nutrition', {
    title: b('၅–၆ လ — အာဟာရ (အစိုင်အခဲ စတင်ခြင်း)', '5–6 months — Nutrition (starting solids)'),
    why: b('၆ လခန့်တွင် အစိုင်အခဲ စတင်ခြင်းသည် ကြီးထွားမှုနှင့် အရသာ သင်ယူမှုအတွက် အရေးကြီးသည်။', 'Around 6 months, starting solids supports growth and taste learning.'),
    observationQuestions: [
      b('ခေါင်းကို တည်ငြိမ်စွာ ထိန်း၍ အထောက်ဖြင့် ထိုင်နိုင်ပါသလား။', 'Holds head steady and sits with support?'),
      b('အစားအစာကို စိတ်ဝင်စား၍ ပါးစပ်ဟပါသလား။', 'Shows interest in food and opens mouth?'),
    ],
    dailyActivities: [b('ချောမွေ့သော အစားအစာ အနည်းငယ်မှ စတင်ပါ။', 'Begin with small amounts of smooth food.')],
    weeklyActivities: [b('အစားအစာ အသစ်တစ်မျိုးစီ ရက်အနည်းငယ်ခြား၍ မိတ်ဆက်ပါ။', 'Introduce one new food every few days.')],
    indoor: [b('မိသားစုနှင့်အတူ စားပွဲတွင် ထိုင်စားစေပါ။', 'Let baby join family mealtimes.')],
    lowCost: [b('ဒေသထွက် အသီးအနှံ/အသီးအရွက်များကို ချက်၍ ချေပါ။', 'Use local, affordable fruits/vegetables mashed.')],
    materials: b('နူးညံ့ဇွန်း၊ ခွက်၊ ဒေသထွက် အစားအစာ။', 'Soft spoon, bowl, local foods.'),
    safety: b('အသက် ၁ နှစ်မပြည့်သေးသော ကလေးကို ပျားရည် မပေးပါနှင့်။ အသက်ရှူလမ်းကြောင်း ပိတ်ဆို့စေနိုင်သည့် အရွယ်အစားနှင့် ပုံသဏ္ဌာန်ရှိသော အစားအစာများကို ရှောင်ပြီး စားနေစဉ် အမြဲ အနီးကပ်ကြီးကြပ်ပါ။', 'No honey under 1 year; avoid choking shapes; always supervise eating.'),
    commonMistakes: [b('ဆား/သကြား ထည့်ခြင်း သို့မဟုတ် နို့ပုလင်းဖြင့် ဖြည့်စွက်အစားအစာကို အစားထိုးခြင်း။', 'Adding salt/sugar, or replacing complementary foods with bottles.')],
    parentTips: [b('မိခင်နို့/နို့ကို ဆက်တိုက်ပေးရင်း အစိုင်အခဲကို ဖြည့်ပါ။', 'Continue breast/formula milk alongside solids.')],
    faq: [
      { q: b('အစားအစာ ငြင်းရင် ဘယ်လိုလုပ်မလဲ။', 'What if baby refuses food?'), a: b('ထပ်ခါ တင်ပြပါ — အသစ်တစ်ခုကို လက်ခံဖို့ အကြိမ်များစွာ လိုနိုင်သည်။', 'Keep offering — new foods often take many tries.') },
      {
        q: b('ဓာတ်မတည့်တတ်သော အစားအစာများ (ဥ၊ မြေပဲ၊ ငါး) ကို ရှောင်သင့်ပါသလား။', 'Should I avoid common allergy foods (egg, peanut, fish)?'),
        a: b(
          'ရှောင်ရန် မလိုပါ။ ကလေးသည် ဖြည့်စွက်အစားအစာ စတင်စားရန် အသင့်ဖြစ်သည့်အချိန် (များသောအားဖြင့် ခြောက်လခန့်တွင် ခေါင်းကို တည်ငြိမ်စွာ ထိန်းနိုင်ပြီး အကူအညီဖြင့် ထိုင်နိုင်ချိန်) ရောက်ပါက ဥ၊ ငါး၊ ချောမွေ့အောင် ဖျော်ထားသော မြေပဲထောပတ်နှင့် အချိုမပါ ပိုးသတ်အပူပေးထားသော ဒိန်ချဉ် သို့မဟုတ် ချိစ်ကဲ့သို့ နို့ထွက်အစားအစာများကို (နွားနို့ကို အသက် ၁၂ လမတိုင်မီ အဓိကသောက်စရာအဖြစ် မပေးဘဲ) တစ်မျိုးချင်း အနည်းငယ်စီ စတင်ပေးနိုင်ပါသည်။ အသက်ရှူလမ်းကြောင်း မပိတ်ဆို့စေရန် အစာကို ချောမွေ့နူးညံ့သော ပုံစံဖြင့်ပေးပြီး စားနေစဉ် အမြဲ အနီးကပ်ကြီးကြပ်ပါ။ အစားအစာအသစ် တစ်မျိုးပေးပြီးနောက် ရက်အနည်းငယ် စောင့်ကြည့်ပါ။ အရေပြားယားယံခြင်း၊ အဖုအပိန့်ထွက်ခြင်း သို့မဟုတ် အော့အန်ခြင်း ဖြစ်ပါက ဆက်မပေးဘဲ ကျန်းမာရေးဝန်ထမ်းနှင့် တိုင်ပင်ပါ။ နှုတ်ခမ်း သို့မဟုတ် မျက်နှာရောင်ခြင်း၊ အသက်ရှူခက်ခြင်း ဖြစ်ပါက အရေးပေါ် ဆေးကုသမှု ချက်ချင်းခံယူပါ။ ကလေးတွင် ပြင်းထန်သော အရေပြားရောင်ရမ်းနာ သို့မဟုတ် ဥနှင့် ဓာတ်မတည့်မှု ရှိပါက မြေပဲမစတင်မီ ဆရာဝန်နှင့် တိုင်ပင်ပါ။ သိရှိထားသော အစားအစာဓာတ်မတည့်မှု သို့မဟုတ် အစားအစာတစ်မျိုးကို ယခင်က တုံ့ပြန်မှု ဖြစ်ဖူးပါက ထိုအစားအစာကို ဘေးကင်းစွာ မိတ်ဆက်ပုံကို ဆရာဝန်အား မေးမြန်းပါ။',
          'There is no need to avoid them. Once your baby is developmentally ready for solids (around six months, holding the head steady and sitting with support), common allergen foods—egg, fish, smooth peanut paste, and pasteurized dairy foods such as plain yogurt or cheese (not cow’s milk as a main drink before 12 months)—can be introduced one at a time in small amounts. Offer them only in a smooth, soft, choking-safe texture and always supervise eating. Wait a few days after each new food. If you see a rash, hives or vomiting, stop and talk to a health worker. If the lips or face swell or breathing becomes difficult, seek emergency care immediately. If your child has severe eczema or egg allergy, talk with a doctor before introducing peanut. If your child has a known food allergy or has previously reacted to a food, ask a doctor how to introduce that food safely.',
        ),
      },
    ],
    redFlags: [
      b("ကိုယ်အလေးချိန် မတက်ခြင်း သို့မဟုတ် ကျဆင်းခြင်း။", "Weight not rising, or falling."),
      b("ထပ်ခါထပ်ခါ အန်ခြင်း သို့မဟုတ် ဝမ်းလျှောခြင်း။", "Repeated vomiting or diarrhoea."),
      b("မျိုချရ ခက်ခဲခြင်း၊ စားတိုင်း ချောင်းဆိုး/တစ်ဆို့ခြင်း။", "Difficulty swallowing, or coughing and choking at every feed."),
      b("ဆီးအရေအတွက် သိသိသာသာ လျော့ကျခြင်း၊ ပါးစပ် ခြောက်ခြင်း သို့မဟုတ် မျက်လုံး ချိုင့်ဝင်ခြင်း — ရေဓာတ်ခန်းခြောက်မှု လက္ခဏာများ ဖြစ်ပါသည်။", "A clear drop in the number of wet nappies, a dry mouth, or sunken eyes — these are signs of dehydration."),
    ],
    referral: b("အထက်ပါတို့ တွေ့ပါက ကျန်းမာရေးဝန်ထမ်းနှင့် အမြန်ဆုံး ပြသပါ — ရင်သွေးငယ်များတွင် ရေဓာတ်ခန်းခြောက်မှု လျင်မြန်စွာ ဖြစ်နိုင်ပါသည်။ ရေဓာတ်ခန်းခြောက်မှု လက္ခဏာ ပါလျှင် ချက်ချင်း ပြသပါ။", "See a health worker promptly if you notice any of these — dehydration develops quickly in infants. If there are signs of dehydration, seek care immediately."),
    encouragement: b('စားခြင်းကို ပျော်ရွှင်ဖွယ် ဖြစ်စေပါ — ဖိအားမပေးပါနှင့်။', 'Keep mealtimes happy — no pressure.'),
  }),

  guide('birth_2m', 'sleep', {
    title: b('မွေးကင်း–၂ လ — အိပ်စက်ခြင်း', 'Birth–2 months — Sleep'),
    why: b('အိပ်စက်ခြင်းသည် ဦးနှောက် ဖွံ့ဖြိုးမှုနှင့် ကြီးထွားမှုအတွက် မရှိမဖြစ်ဖြစ်သည်။ ဘေးကင်းသော အိပ်ရာက အသက်ကို ကာကွယ်သည်။', 'Sleep is essential for brain growth; safe sleep protects life.'),
    observationQuestions: [
      b('တစ်ရက်လျှင် ကြိမ်ဖန်များစွာ (၁၄–၁၇ နာရီခန့်) အိပ်ပါသလား။', 'Sleeps often through the day (about 14–17 hours total)?'),
      b('ကျောပေါ်လှန်၍ အိပ်ပါသလား။', 'Sleeps on the back?'),
    ],
    dailyActivities: [b('နေ့/ည ကွာခြားမှုကို အလင်း/အမှောင်ဖြင့် သိစေပါ။', 'Help day/night difference with light and dark.')],
    indoor: [b('တိတ်ဆိတ်၍ အေးမြသော အိပ်ခန်း ဖန်တီးပါ။', 'Keep a calm, cool sleep space.')],
    lowCost: [b('ကလေးအတွက် လူကြီးအိပ်ရာနှင့် သီးခြားဖြစ်သော ဘေးကင်းသည့် အိပ်စက်နေရာထားပါ။ မွေ့ရာသည် ခိုင်ခံ့၊ ပြားညီပြီး မစောင်းရပါ။', 'Give the baby a safe sleep space separate from the adult bed, with a firm, flat, non-inclined mattress.')],
    materials: b('ခိုင်ခံ့သော ပြားသော မွေ့ရာ။', 'Firm flat sleep surface.'),
    safety: b("ကျောပေါ်လှန်အိပ်ပါ။ မွေ့ရာပေါ်တွင် ခေါင်းအုံး၊ စောင်ပျော့၊ အရုပ် မထားပါနှင့်။ ဆေးလိပ်ငွေ့ ရှောင်ပါ။ ဤဘေးကင်းရေးအချက်များသည် ရုတ်တရက်သေဆုံးမှု (SIDS) အန္တရာယ်ကို လျှော့ချသည်။ အိပ်ချိန်နှင့် ညအိပ်ချိန်တွင် နို့သီးခေါင်း ပေးကြည့်နိုင်ပါသည် — ရုတ်တရက် သေဆုံးမှု အန္တရာယ် လျော့ကျစေကြောင်း တွေ့ရှိထားပါသည်။ နို့တိုက်နေပါက နို့တိုက်ခြင်း အသားကျပြီးမှ စတင်ပေးပါ။", "Back to sleep; no pillows, soft bedding, or toys in the sleep space; avoid smoke. These reduce SIDS risk. You can try offering a pacifier at nap time and bedtime — it is associated with a lower risk of SIDS. If you are breastfeeding, wait until feeding is well established before offering one."),
    commonMistakes: [b('ကလေးအား ဗိုက်လှန်/ဘေးစောင်း အိပ်စေခြင်း သို့မဟုတ် နူးညံ့ပစ္စည်းများ ထားခြင်း။', 'Placing baby on tummy/side or with soft items.'),
        b("အလေးချိန်ပါသော စောင်၊ အိပ်ဝတ်စုံ သို့မဟုတ် ပတ်ရစ်ပိတ်စများ သုံးခြင်း။", "Using weighted blankets, weighted sleepers or weighted swaddles."),
        b("အိမ်သုံး အသက်ရှူ/နှလုံးခုန် စောင့်ကြည့်စက်ကို ဘေးကင်းစွာ အိပ်စေခြင်း၏ အစား အားကိုးခြင်း — အန္တရာယ် လျှော့ချပေးသည်ဟု သက်သေ မရှိပါ။", "Relying on a home breathing or heart-rate monitor instead of a safe sleep space — these have not been shown to reduce the risk of SIDS."),
      ],
    parentTips: [b('ကလေးအိပ်ချိန်တွင် သင်လည်း အနားယူပါ။', 'Rest when your baby rests.')],
    faq: [{ q: b('ညတိုင်း အကြိမ်ကြိမ် နိုးတာ ပုံမှန်လား။', 'Is frequent night waking normal?'), a: b('ဤအရွယ်တွင် ပုံမှန်ဖြစ်သည် — မွေးကင်းစများ မကြာခဏ နို့စို့ရန် နိုးတတ်သည်။', 'Yes — newborns wake often to feed.') }],
    redFlags: [
        b("အသက်ရှူ ရပ်သွားခြင်း၊ အသက်ရှူ ခက်ခဲခြင်း သို့မဟုတ် အသက်ရှူသံ ညည်းသံလို ထွက်ခြင်း။", "Pauses in breathing, difficulty breathing, or grunting with each breath."),
        b("နှုတ်ခမ်း၊ လျှာ သို့မဟုတ် အသားအရေ ပြာနှမ်း/မီးခိုးရောင် ဖြစ်ခြင်း။", "Lips, tongue or skin turning blue or grey."),
        b("နိုးရ အလွန်ခက်ခြင်း သို့မဟုတ် လုံးဝ မနိုးခြင်း။", "Very hard to wake, or not waking at all."),
        b("ကိုယ်ခန္ဓာ အလွန် ပျော့ခွေခြင်း။", "A very floppy body."),
        b("အသက် ၃ လအောက် ဖျားခြင်း (၃၈°C နှင့်အထက်)။", "Any fever in a baby under 3 months (38°C / 100.4°F or above)."),
      ],
    referral: b("အထက်ပါတို့ တွေ့ပါက ချက်ချင်း အနီးဆုံး ဆေးရုံသို့ သွားပါ — စောင့်၍ မရပါ။ ဤသည်မှာ အရေးပေါ် ဖြစ်ပြီး ဤ app သည် အရေးပေါ် ဝန်ဆောင်မှု မဟုတ်ပါ။", "Go to the nearest hospital immediately if you notice any of these — do not wait. This is an emergency, and this app is not an emergency service."),
    encouragement: b('အိပ်ရေးပုံစံသည် တဖြည်းဖြည်း တည်ငြိမ်လာမည် — သည်းခံပါ။', 'Sleep patterns settle with time — be patient with yourself.'),
  }),

  guide('10_12m', 'safety', {
    title: b('၁၀–၁၂ လ — ဘေးကင်းလုံခြုံရေး', '10–12 months — Safety'),
    why: b('ကလေး ရွေ့လျားလာသည်နှင့်အမျှ အိမ်ကို ဘေးကင်းအောင် ပြင်ဆင်ခြင်းက ထိခိုက်ဒဏ်ရာရနိုင်ခြေကို လျှော့ချရန် အထောက်အကူပြုပါသည်။', 'As babies become mobile, preparing a safer home helps reduce the risk of injury.'),
    observationQuestions: [
      b('ပရိဘောဂကိုကိုင်၍ ရွေ့လျား/ရပ်ပါသလား။', 'Pulls up and moves along furniture?'),
      b('ပစ္စည်းငယ်များကို ကောက်၍ ပါးစပ်သို့ ယူပါသလား။', 'Picks up small items and mouths them?'),
    ],
    dailyActivities: [b('ကြမ်းပြင်ပေါ်ရှိ ငယ်သောပစ္စည်းများ/အန္တရာယ်ရှိအရာများ ဖယ်ရှားပါ။', 'Clear small or hazardous objects from the floor.')],
    indoor: [b('လှေကားဂိတ်၊ ပလပ်ခေါင်းအဖုံး တပ်ဆင်ပါ။', 'Use stair gates and socket covers.')],
    outdoor: [b('ရေ/ရေကန်အနီး အမြဲ ကြီးကြပ်ပါ။', 'Always supervise near water.')],
    lowCost: [b('ကလေးလက်လှမ်းမီသော ဆွဲအံနှင့် ဗီရိုများတွင် ကလေးမဖွင့်နိုင်သော လုံခြုံရေးချိတ် သို့မဟုတ် သော့ကို စနစ်တကျ တပ်ပါ။ ဆေးဝါးနှင့် ဓာတုပစ္စည်းများကို ကလေး မမြင်နိုင်၊ မလှမ်းမီသော သော့ခတ်ထားသည့် ဗီရိုတွင် သိမ်းပါ။', 'Install a properly fitted child-resistant latch or lock on accessible drawers and cupboards. Store medicines and chemicals in a locked cabinet out of sight and reach.')],
    materials: b('လှေကားဂိတ်၊ ပလပ်အဖုံး၊ ဆေးဗူး သော့ခတ်နေရာ။', 'Stair gate, socket covers, locked medicine box.'),
    safety: b('ဆေးဝါးများ၊ ဓာတုပစ္စည်းများနှင့် ပူသောအရည်များကို ကလေးလက်လှမ်းမမီသည့် နေရာတွင် ထားပါ။ အသက်ရှူလမ်းကြောင်း ပိတ်ဆို့စေနိုင်သည့် အစားအစာနှင့် ပစ္စည်းငယ်များကို ဖယ်ရှားထားပါ။', 'Keep medicines, chemicals, hot liquids out of reach; avoid choking hazards.'),
    commonMistakes: [b('ကလေးအား ရေ/လှေကားအနီး ခဏမျှ တစ်ယောက်တည်း ထားခြင်း။', 'Leaving the child alone near water/stairs even briefly.')],
    parentTips: [b('ကလေး၏ အမြင့်မှ အိမ်ကို လေ့လာ၍ အန္တရာယ်များ ရှာပါ။', 'Get down to your child’s level to spot hazards.')],
    faq: [{ q: b('အရေးပေါ် ဘာလုပ်ရမလဲ။', 'What about emergencies?'), a: b('ဒေသအလိုက် အရေးပေါ်ဖုန်းနံပါတ်နှင့် အနီးဆုံး ဆေးခန်းကို ကြိုတင် သိထားပါ။', 'Know your local emergency number and nearest clinic in advance.') }],
    redFlags: [b('ကြီးမားသော ထိခိုက်မှု၊ မေ့မြောခြင်း၊ ဆက်တိုက်အန်ခြင်း — အရေးပေါ် ကုသမှု ခံယူပါ။', 'Serious injury, loss of consciousness, or repeated vomiting — seek emergency care.')],
    referral: b('ပြင်းထန်သော ထိခိုက်မှု သို့မဟုတ် အဆိပ်ဖြစ်နိုင်သော ပစ္စည်းနှင့် ထိတွေ့/မျိုချမိသည်ဟု သံသယရှိပါက အရေးပေါ် ဆေးဘက်ဆိုင်ရာ အကြံဉာဏ်ကို ချက်ချင်း ရယူပါ။ ကလေး သတိလစ်ခြင်း၊ အသက်မရှူခြင်း သို့မဟုတ် တက်ခြင်းရှိပါက ဒေသအရေးပေါ်နံပါတ်ကို ချက်ချင်းခေါ်ပါ။ အန်အောင် မလုပ်ပါနှင့်။', 'For a serious injury or suspected poison exposure or ingestion, get urgent medical advice immediately. If the child is unconscious, not breathing, or having a seizure, call the local emergency number now. Do not induce vomiting.'),
    encouragement: b('ဘေးကင်းသော ပတ်ဝန်းကျင်သည် ကလေးကို လွတ်လပ်စွာ စူးစမ်းခွင့် ပေးသည်။', 'A safe space lets your child explore freely.'),
  }),

  guide('2y', 'daily_routine', {
    title: b('၂ နှစ် — နေ့စဉ် လုပ်ရိုးလုပ်စဉ်', '2 years — Daily Routine'),
    why: b('ကြိုတင်ခန့်မှန်းနိုင်သော နေ့စဉ်လုပ်ရိုးလုပ်စဉ်များက ကလေးကို လုံခြုံစိတ်ချစေပြီး နေ့စဉ်အကူးအပြောင်းများတွင် ပူးပေါင်းပါဝင်ရန် အထောက်အကူပြုနိုင်ပါသည်။', 'Predictable routines can help children feel secure and support cooperation during daily transitions.'),
    observationQuestions: [
      b('နေ့စဉ်လုပ်ငန်း အစီအစဉ်ကို သိရှိ/မျှော်လင့်ပါသလား။', 'Anticipates what comes next in the day?'),
      b('အိပ်ချိန်/စားချိန် ပုံမှန် ရှိပါသလား။', 'Has fairly regular sleep and meal times?'),
    ],
    dailyActivities: [b('ရေချိုး–စာဖတ်–အိပ် ကဲ့သို့ ည အစီအစဉ် တည်ဆောက်ပါ။', 'Build a bath–book–bed evening routine.')],
    weeklyActivities: [b('နေ့စဉ်လုပ်ရိုးလုပ်စဉ်ကို ရုပ်ပုံများဖြင့် အစီအစဉ်ဇယား ပြုလုပ်ပေးပါ။', 'Use a picture schedule for the day.')],
    indoor: [b('ကစားပြီး သိမ်းဆည်းချိန်ကို လုပ်ရိုးဖြစ်အောင် ထည့်ပါ။', 'Make clean-up a routine after play.')],
    lowCost: [b('ကိုယ်တိုင်ဆွဲသော ပုံ ၄ ကွက်ဖြင့် အစီအစဉ် ပြပါ။', 'Draw a 4-picture routine chart yourself.')],
    materials: b('ပုံရိပ် အစီအစဉ်ဇယား။', 'Picture schedule.'),
    safety: b("အစီအစဉ်ကို ပြောင်းလဲရပါက ကြိုတင် ပြောပြပါ။ အစာတစ်ဆို့ခြင်း အန္တရာယ်သည် အသက် ၄ နှစ်အထိ ဆက်ရှိပါသည် — လမ်းလျှောက်တတ်၊ စကားပြောတတ်ပြီဆိုသော်လည်း အန္တရာယ် မကုန်သေးပါ။ စပျစ်သီးနှင့် ချယ်ရီခရမ်းချဉ်သီးများကို အလျားလိုက် လေးစိတ် ခွဲပေးပါ။ အခွံမာသီး အလုံးလိုက်၊ ပြောင်းဖူးပေါက်ပေါက်၊ မာကျောသော သကြားလုံး၊ အစေ့အဆန်များနှင့် မုန်လာဥနီ အစိမ်းများကို အသက် ၄ နှစ်အောက် ကလေးများအား မပေးပါနှင့်။ အမြဲ ထိုင်၍ စားခိုင်းပြီး စားနေစဉ် အနားတွင် ရှိပါ။", "Warn ahead of routine changes. Choking remains a risk until about age 4 — walking and talking do not end it. Cut grapes and cherry tomatoes into quarters lengthwise. Do not give whole nuts, popcorn, hard sweets, seeds or raw carrot to a child under 4. Always have your child sit to eat, and stay with them while they eat."),
    commonMistakes: [b('အစီအစဉ် လုံးဝမရှိခြင်း သို့မဟုတ် အလွန်တင်းကျပ်ခြင်း — ဟန်ချက်ညီပါ။', 'No routine, or an overly rigid one — aim for balance.')],
    parentTips: [b('ပြောင်းလဲမှုမတိုင်မီ “နောက် ၅ မိနစ်” ကဲ့သို့ ကြိုသတိပေးပါ။', 'Give a “5 more minutes” warning before transitions.')],
    faq: [{ q: b('ခရီးသွားချိန် အစီအစဉ် ပျက်ရင် ဘယ်လိုလုပ်မလဲ။', 'What if travel breaks the routine?'), a: b('ပြန်ရောက်လျှင် ယခင်အစီအစဉ်သို့ တဖြည်းဖြည်း ပြန်လည်ချိန်ညှိပါ။', 'Ease back into the routine when you return.') }],
    redFlags: [b('အစီအစဉ် အနည်းငယ်ပြောင်းရုံဖြင့် အလွန်ပြင်းထန်စွာ တုံ့ပြန်ခြင်း (ဖွံ့ဖြိုးမှု အခြားစိုးရိမ်စရာများနှင့်အတူ)။', 'Extreme distress at tiny changes, alongside other developmental concerns.')],
    referral: b('စိုးရိမ်ပါက ကလေးကျန်းမာရေးဆရာဝန်နှင့် တိုင်ပင်ပါ။', 'If concerned, consult a pediatrician.'),
    encouragement: b('တသမတ်တည်း ရှိသော နေ့စဉ်ဘဝသည် ကလေးအတွက် အကောင်းဆုံး လက်ဆောင်ဖြစ်သည်။', 'A steady daily rhythm is a gift to your child.'),
  }),

  guide('4y', 'school_readiness', {
    title: b('၄ နှစ် — ကျောင်းအတွက် အသင့်ဖြစ်မှု', '4 years — School Readiness'),
    why: b('ကျောင်းအသင့်ဖြစ်မှုသည် စာဖတ်တတ်ခြင်းထက် — အလှည့်စောင့်ခြင်း၊ ခွဲနေနိုင်ခြင်းနှင့် ကိုယ်ကိုထိန်းချုပ်နိုင်ခြင်းက ပို၍ အရေးကြီးသည်။', 'Readiness is less about reading and more about turn-taking, coping with separation, and self-control.'),
    observationQuestions: [
      b('မိဘနှင့် ခဏခွဲ၍ နေနိုင်ပါသလား။', 'Copes with brief separation?'),
      b('ရိုးရှင်းသော အုပ်စု စည်းကမ်းများ လိုက်နာပါသလား။', 'Follows simple group rules?'),
    ],
    dailyActivities: [b('“ကျေးဇူးတင်ပါတယ်” “ကျေးဇူးပြု၍” ကဲ့သို့ ယဉ်ကျေးမှုများ လေ့ကျင့်ပါ။', 'Practice “please/thank you” and turn-taking.')],
    weeklyActivities: [b('အခြားကလေးများနှင့် အုပ်စု ကစားချိန် စီစဉ်ပါ။', 'Arrange group play with peers.')],
    indoor: [b('“ကျောင်း” ဟန်ဆောင် ကစားပါ။', 'Play pretend “school”.')],
    outdoor: [b('အုပ်စု ကစားနည်းများဖြင့် အလှည့်စောင့်ခြင်း လေ့ကျင့်ပါ။', 'Practice turn-taking in group games.')],
    lowCost: [b('အိမ်တွင် ပုံပြင်ဖတ်၍ မေးခွန်းများ မေးပါ။', 'Read and ask questions at home.')],
    materials: b('ခဲတံ၊ စက္ကူ၊ ပုံပြင်စာအုပ်။', 'Crayons, paper, story books.'),
    safety: b("ကျောင်းအကြောင်း အပြုသဘော စကားဖြင့် ပြောပါ — ကြောက်စိတ် မဖြစ်စေပါနှင့်။ အစာတစ်ဆို့ခြင်း အန္တရာယ်သည် အသက် ၄ နှစ်အထိ ဆက်ရှိပါသည် — လမ်းလျှောက်တတ်၊ စကားပြောတတ်ပြီဆိုသော်လည်း အန္တရာယ် မကုန်သေးပါ။ စပျစ်သီးနှင့် ချယ်ရီခရမ်းချဉ်သီးများကို အလျားလိုက် လေးစိတ် ခွဲပေးပါ။ အခွံမာသီး အလုံးလိုက်၊ ပြောင်းဖူးပေါက်ပေါက်၊ မာကျောသော သကြားလုံး၊ အစေ့အဆန်များနှင့် မုန်လာဥနီ အစိမ်းများကို အသက် ၄ နှစ်အောက် ကလေးများအား မပေးပါနှင့်။ အမြဲ ထိုင်၍ စားခိုင်းပြီး စားနေစဉ် အနားတွင် ရှိပါ။", "Speak positively about school to reduce anxiety. Choking remains a risk until about age 4 — walking and talking do not end it. Cut grapes and cherry tomatoes into quarters lengthwise. Do not give whole nuts, popcorn, hard sweets, seeds or raw carrot to a child under 4. Always have your child sit to eat, and stay with them while they eat."),
    commonMistakes: [b('စာသင်ခန်း အတတ်ပညာကိုသာ အာရုံစိုက်ပြီး လူမှု/ခံစားမှု ကျွမ်းကျင်မှုကို မေ့ခြင်း။', 'Focusing on academics while neglecting social-emotional skills.')],
    parentTips: [b('ကျောင်းစတက်မီ လမ်းကြောင်း/ဆရာမကို ကြိုမိတ်ဆက်ပေးပါ။', 'Visit the school and meet the teacher beforehand.')],
    faq: [{ q: b('ကလေး ကျောင်းအတွက် အသင့်ဖြစ်မဖြစ် ဘယ်လိုသိမလဲ။', 'How do I know if my child is ready?'), a: b('စာတတ်မှုထက် လူမှု/ခံစားမှု အသင့်ဖြစ်မှုကို ကြည့်ပါ — ဆရာမနှင့်လည်း တိုင်ပင်ပါ။', 'Look at social-emotional readiness more than academics; talk with the teacher.') }],
    redFlags: [b('စကားပြော/နားလည်မှု၊ လူမှုဆက်ဆံရေး သို့မဟုတ် အပြုအမူတွင် သိသာသော အခက်အခဲ။', 'Marked difficulty in speech/understanding, social interaction, or behavior.')],
    referral: b('ကျောင်းအသင့်ဖြစ်မှု စိုးရိမ်ပါက ကလေးကျန်းမာရေးဆရာဝန် သို့မဟုတ် ဖွံ့ဖြိုးမှုကျွမ်းကျင်သူနှင့် တိုင်ပင်ပါ။', 'If concerned about readiness, consult a pediatrician or developmental specialist.'),
    encouragement: b('ကလေးတိုင်း မိမိအရှိန်ဖြင့် အသင့်ဖြစ်လာမည် — ယုံကြည်မှုကို တည်ဆောက်ပေးပါ။', 'Every child gets ready in their own time — build their confidence.'),
  }),
];
