// Parent Learning Academy — short lessons. Starter curriculum covering every
// category; the CMS extends toward the full target. General parenting guidance,
// clinical_review until approved. Simple language, no medical jargon.
import { lesson, type SeedItem } from '../types';

const b = (mm: string, en: string) => ({ mm, en });
const q = (question: string, qEn: string, opts: [string, string][], answerIndex: number) => ({
  q: b(question, qEn),
  options: opts.map(([mm, en]) => b(mm, en)),
  answerIndex,
});

export const LESSONS: SeedItem[] = [
  lesson({
    slug: 'what_is_development', category: 'understanding_development',
    title: b('ဖွံ့ဖြိုးမှုဆိုတာ ဘာလဲ', 'What is child development?'),
    summary: b('ကလေးများ မတူညီသော နယ်ပယ်များတွင် မိမိအရှိန်ဖြင့် ကြီးထွားပုံ။', 'How children grow across areas at their own pace.'),
    objectives: [b('ဖွံ့ဖြိုးမှု နယ်ပယ်များကို သိရှိရန်။', 'Know the areas of development.'), b('“ပုံမှန်” အကွာအဝေး ကျယ်ပြန့်ကြောင်း နားလည်ရန်။', 'Understand the wide normal range.')],
    readingMinutes: 3,
    body: b('ကလေးဖွံ့ဖြိုးမှုဆိုသည်မှာ လှုပ်ရှားမှု၊ ဘာသာစကား၊ တွေးခေါ်မှု၊ ခံစားမှုနှင့် လူမှုဆက်ဆံရေး တို့တွင် တဖြည်းဖြည်း ကြီးထွားလာခြင်းဖြစ်သည်။ ကလေးတိုင်း မတူညီသော အရှိန်ဖြင့် ကြီးထွားကြသည်။ အမှတ်တိုင် (milestone) များသည် လမ်းညွှန်များသာဖြစ်၍ တင်းကျပ်သော စာမေးပွဲ မဟုတ်ပါ။', 'Child development is steady growth in movement, language, thinking, feelings, and social skills. Every child grows at their own pace. Milestones are guides, not a strict test.'),
    quiz: [q('အမှတ်တိုင်များသည် —', 'Milestones are —', [['တင်းကျပ်သော စာမေးပွဲ', 'a strict test'], ['လမ်းညွှန်များ', 'general guides']], 1)],
    takeaway: b('ကလေး၏ ကိုယ်ပိုင်အရှိန်ကို လေးစားပါ။', 'Respect your child’s own pace.'),
    actionToday: b('ယနေ့ ကလေးနှင့် ၁၀ မိနစ် အာရုံစိုက်၍ ကစားပါ။', 'Spend 10 focused minutes playing today.'),
  }),
  lesson({
    slug: 'power_of_play', category: 'learning_through_play',
    title: b('ကစားခြင်း၏ တန်ခိုး', 'The power of play'),
    summary: b('ကစားခြင်းသည် ကလေး၏ အဓိက သင်ယူနည်းဖြစ်ကြောင်း။', 'Play is how young children learn best.'),
    objectives: [b('ကစားခြင်း၏ အကျိုးကို သိရှိရန်။', 'Know the benefits of play.')],
    readingMinutes: 3,
    body: b('ကစားခြင်းသည် ကလေးအတွက် “အလုပ်” ဖြစ်သည်။ ကစားရင်း ဦးနှောက်၊ ဘာသာစကား၊ ခန္ဓာကိုယ်နှင့် ဆက်ဆံရေးများ ဖွံ့ဖြိုးသည်။ အဈေးကြီး ကစားစရာ မလိုပါ — သင်၏ အာရုံစိုက်မှုနှင့် အိမ်သုံးပစ္စည်းများ လုံလောက်သည်။', 'Play is a child’s work. Through play, the brain, language, body, and relationships grow. Expensive toys are not needed — your attention and household objects are enough.'),
    quiz: [q('ကစားရန် အဈေးကြီး ကစားစရာ —', 'Expensive toys are —', [['မဖြစ်မနေ လိုအပ်', 'essential'], ['မလိုအပ်', 'not needed']], 1)],
    takeaway: b('သင်နှင့်အတူ ကစားခြင်းက အကောင်းဆုံးဖြစ်သည်။', 'Playing with you is best.'),
    actionToday: b('အိမ်သုံးပစ္စည်းတစ်ခုဖြင့် ကစားနည်းတစ်ခု ဖန်တီးပါ။', 'Invent one game with a household object.'),
  }),
  lesson({
    slug: 'talk_more', category: 'speech_development',
    title: b('စကားပြောများများ ပြောပါ', 'Talk more, every day'),
    summary: b('နေ့စဉ် စကားပြောခြင်းက စကားသံ ဖွံ့ဖြိုးမှုကို အားဖြည့်သည်။', 'Everyday talk fuels speech development.'),
    objectives: [b('စကားသံ တိုးတက်စေမည့် နည်းလမ်းများ သိရှိရန်။', 'Learn ways to boost speech.')],
    readingMinutes: 3,
    body: b('ကလေးနှင့် နေ့စဉ်လုပ်ဆောင်ချက်များကို စကားဖြင့် ရှင်းပြပါ။ ကလေးပြောသည်ကို ထပ်ဆင့်၍ ပိုရှည်အောင် ပြန်ပြောပါ။ မျက်နှာချင်းဆိုင်၍ ပြောခြင်းက screen ထက် အဆများစွာ ပို၍ ထိရောက်သည်။', 'Narrate daily actions. Expand on what your child says. Face-to-face talk is far more effective than screens.'),
    quiz: [q('စကားသံ အတွက် အထိရောက်ဆုံး —', 'Best for speech —', [['မျက်နှာချင်းဆိုင် စကားပြော', 'face-to-face talk'], ['screen ကြည့်ခြင်း', 'screen time']], 0)],
    takeaway: b('သင့်အသံသည် အကောင်းဆုံး သင်ကြားကိရိယာ။', 'Your voice is the best teacher.'),
    actionToday: b('ကလေးနှင့် စကားပြောစဉ် ၃ ကြိမ် အချိန်ပေး၍ စောင့်ဆိုင်းပါ။', 'Pause and wait three times in a conversation.'),
  }),
  lesson({
    slug: 'reading_together', category: 'reading',
    title: b('အတူတူ စာဖတ်ခြင်း', 'Reading together'),
    summary: b('နေ့စဉ် ရုပ်ပုံစာအုပ်ဖတ်ခြင်း၏ တန်ဖိုး။', 'The value of daily shared reading.'),
    objectives: [b('စာဖတ်ချိန်ကို ပျော်ရွှင်ဖွယ် ဖြစ်စေရန်။', 'Make reading time joyful.')],
    readingMinutes: 3,
    body: b('နေ့စဉ် ရုပ်ပုံစာအုပ် အတူဖတ်ခြင်းသည် ဝေါဟာရ၊ စိတ်ကူးဉာဏ်နှင့် ချစ်ခင်မှုကို ကြီးထွားစေသည်။ စာအုပ်အသစ်များစွာထက် အနှစ်သက်ဆုံး စာအုပ်အနည်းငယ်ကို ထပ်ခါဖတ်ခြင်းက ပို၍ အကျိုးရှိသည်။', 'Daily shared picture-book reading grows vocabulary, imagination, and closeness. Re-reading a few favorites beats many new books.'),
    quiz: [q('စာဖတ်ခြင်းအတွက် ကောင်းသည်မှာ —', 'For reading, better to —', [['အနှစ်သက်ဆုံးကို ထပ်ခါဖတ်', 're-read favorites'], ['အသစ်များစွာ ဝယ်', 'buy many new books']], 0)],
    takeaway: b('တစ်နေ့ စာအုပ်တစ်အုပ် — အလေ့အထ ကောင်းတစ်ခု။', 'A book a day — a great habit.'),
    actionToday: b('ယနေ့ည အိပ်ရာမဝင်မီ ပုံပြင်တစ်ပုဒ် ဖတ်ပါ။', 'Read one story before bed tonight.'),
  }),
  lesson({
    slug: 'gentle_discipline', category: 'positive_parenting',
    title: b('နူးညံ့သော စည်းကမ်း', 'Positive, gentle discipline'),
    summary: b('ပြစ်ဒဏ်မဟုတ်ဘဲ လမ်းညွှန်ခြင်းဖြင့် အပြုအမူ သင်ကြားခြင်း။', 'Guiding behavior with connection, not punishment.'),
    objectives: [b('အပြုသဘော စည်းကမ်းနည်းများ သိရှိရန်။', 'Learn positive discipline tools.')],
    readingMinutes: 4,
    body: b('ကလေးများသည် ဆက်ဆံရေးမှတစ်ဆင့် အကောင်းဆုံး သင်ယူကြသည်။ ရိုက်ခြင်း/ဟစ်အော်ခြင်းအစား ရှင်းလင်းသော နယ်နိမိတ်များ၊ တသမတ်တည်း လုပ်ရိုးလုပ်စဉ်နှင့် ကောင်းသောအပြုအမူကို ချီးမွမ်းခြင်းက ပို၍ ထိရောက်သည်။ သင် တည်ငြိမ်စွာ ရှိနေခြင်းက ကလေးကို ငြိမ်သက်ရန် သင်ပေးသည်။', 'Children learn best through relationship. Instead of hitting or yelling, clear limits, steady routines, and praising good behavior work better. Your calm teaches their calm.'),
    quiz: [q('အပြုသဘော စည်းကမ်းတွင် အဓိကမှာ —', 'Positive discipline centers on —', [['ပြစ်ဒဏ်', 'punishment'], ['ဆက်ဆံရေးနှင့် လမ်းညွှန်မှု', 'connection and guidance']], 1)],
    takeaway: b('တည်ငြိမ်မှုနှင့် တသမတ်တည်းရှိမှုက အဓိကဖြစ်သည်။', 'Calm and consistency matter most.'),
    actionToday: b('ယနေ့ ကလေး၏ ကောင်းသောအပြုအမူ တစ်ခုကို တိကျစွာ ချီးမွမ်းပါ။', 'Praise one specific good behavior today.'),
  }),
  lesson({
    slug: 'balanced_meals', category: 'nutrition',
    title: b('မျှတသော အစားအစာ', 'Balanced meals for little ones'),
    summary: b('ကလေးများအတွက် ကျန်းမာသော အစားအသောက် အခြေခံ။', 'Healthy eating basics for young children.'),
    objectives: [b('မျှတသော အစားအစာ ပုံစံ သိရှိရန်။', 'Know what a balanced plate looks like.')],
    readingMinutes: 3,
    body: b('ကလေးများအတွက် အသီးအနှံ၊ အသီးအရွက်၊ ကောက်နှံ၊ ပရိုတင်းနှင့် နို့ထွက်ပစ္စည်းများ မျှတစွာ လိုအပ်သည်။ ဆား/သကြား များများ ရှောင်ပါ။ စားခြင်းကို ဖိအားမပေးဘဲ ပျော်ရွှင်ဖွယ် ဖြစ်စေပါ။ အသစ်တစ်ခုကို လက်ခံရန် အကြိမ်များစွာ လိုနိုင်သည်။', 'Children need a balance of fruit, vegetables, grains, protein, and dairy. Limit salt and sugar. Keep meals pressure-free and pleasant. New foods often take many tries to accept.'),
    quiz: [q('အစားအစာ အသစ်ကို ကလေး ငြင်းရင် —', 'If a child refuses a new food —', [['ထပ်ခါ တင်ပြပါ', 'keep offering gently'], ['ထိုအစားအစာ ရပ်ပါ', 'stop that food forever']], 0)],
    takeaway: b('စားခြင်းကို တိုက်ပွဲ မဖြစ်စေပါနှင့်။', 'Don’t make meals a battle.'),
    actionToday: b('ယနေ့ အစားအစာ အရောင် ၃ မျိုး ပန်းကန်ထဲ ထည့်ပါ။', 'Put three food colors on the plate today.'),
  }),
  lesson({
    slug: 'healthy_sleep', category: 'sleep',
    title: b('ကျန်းမာသော အိပ်စက်မှု', 'Healthy sleep habits'),
    summary: b('တသမတ်တည်း အိပ်ချိန်နှင့် ဘေးကင်းသော အိပ်ရာ။', 'Consistent bedtimes and safe sleep.'),
    objectives: [b('အိပ်ရေးအလေ့အထ ကောင်းများ သိရှိရန်။', 'Learn good sleep habits.')],
    readingMinutes: 3,
    body: b('တသမတ်တည်း အိပ်ချိန်နှင့် နူးညံ့သော ည အစီအစဉ် (ရေချိုး–စာဖတ်–အိပ်) က အိပ်ရေးကို ကူညီသည်။ ၂ နှစ်အောက် ကလေးများကို ကျောပေါ်လှန်၍ ခိုင်ခံ့ပြားသော နေရာတွင် အိပ်စေပါ။ အိပ်ခန်းကို အမှောင်၊ တိတ်ဆိတ်၍ အေးမြစေပါ။', 'Consistent bedtimes and a calm routine (bath–book–bed) help sleep. Babies sleep on the back on a firm flat surface. Keep the room dark, quiet, and cool.'),
    quiz: [q('မွေးကင်းစကို အိပ်စေရမည့် ပုံစံ —', 'Newborns should sleep —', [['ကျောပေါ်လှန်၍', 'on the back'], ['ဗိုက်လှန်၍', 'on the tummy']], 0)],
    takeaway: b('တသမတ်တည်း ည အစီအစဉ်က အဓိကဖြစ်သည်။', 'A steady bedtime routine is key.'),
    actionToday: b('ယနေ့ည အိပ်ချိန်ကို ၁၅ မိနစ် စောစေပါ။', 'Move bedtime 15 minutes earlier tonight.'),
  }),
  lesson({
    slug: 'home_safety', category: 'safety',
    title: b('အိမ်တွင်း ဘေးကင်းရေး', 'Home safety essentials'),
    summary: b('ရွေ့လျားနိုင်သော ကလေးအတွက် အိမ်ကို ဘေးကင်းအောင် ပြင်ဆင်ခြင်း။', 'Baby-proofing for a mobile child.'),
    objectives: [b('အဓိက အိမ်တွင်း အန္တရာယ်များ သိရှိရန်။', 'Know the main home hazards.')],
    readingMinutes: 3,
    body: b('ဆေး၊ ဓာတုပစ္စည်း၊ ချက်ပြုတ်ဆီ၊ ရေနွေးများကို ကလေး လက်လှမ်းမမီရာ ထားပါ။ ပလပ်ခေါင်း၊ လှေကား၊ ရေအိုးအနီး သတိထားပါ။ choking အန္တရာယ်ရှိသော ငယ်သောပစ္စည်းများ ဖယ်ရှားပါ။ ဒေသ အရေးပေါ် ဖုန်းနံပါတ်ကို ကြိုတင် သိထားပါ။', 'Keep medicines, chemicals, hot liquids out of reach. Watch sockets, stairs, and water. Remove small choking hazards. Know your local emergency number in advance.'),
    quiz: [q('ဆေးဗူးများကို —', 'Medicines should be —', [['ကလေး လက်လှမ်းမမီရာ သော့ခတ်', 'locked out of reach'], ['စားပွဲပေါ်', 'left on the table']], 0)],
    takeaway: b('ဘေးကင်းသော အိမ်က လွတ်လပ်စွာ စူးစမ်းခွင့် ပေးသည်။', 'A safe home lets children explore freely.'),
    actionToday: b('ယနေ့ အခန်းတစ်ခန်းကို ကလေး၏ အမြင့်မှ စစ်ဆေးပါ။', 'Check one room from your child’s eye level today.'),
  }),
  lesson({
    slug: 'screen_time', category: 'screen_time',
    title: b('screen အချိန် ဟန်ချက်ညီစေခြင်း', 'Balancing screen time'),
    summary: b('အသက်အလိုက် screen လမ်းညွှန်နှင့် ပိုကောင်းသော ရွေးချယ်စရာများ။', 'Age guidance and better alternatives.'),
    objectives: [b('screen အသုံးပြုမှု လမ်းညွှန် သိရှိရန်။', 'Know screen-use guidance.')],
    readingMinutes: 3,
    body: b('၂ နှစ်အောက် ကလေးများအတွက် screen ကို တတ်နိုင်သမျှ ရှောင်ရန် အကြံပြုသည် (ဗီဒီယိုခေါ်ဆိုမှု မှလွဲ၍)။ ပိုကြီးသော ကလေးများအတွက်လည်း အချိန်ကို ကန့်သတ်၍ အရည်အသွေးကောင်း အကြောင်းအရာကို ရွေးပါ။ မျက်နှာချင်းဆိုင် ကစားခြင်းနှင့် စကားပြောခြင်းက ဖွံ့ဖြိုးမှုအတွက် ပို၍ အကျိုးရှိသည်။', 'Under 2, avoid screens as much as possible (video calls aside). For older children, limit time and choose quality content. Real play and talk are far better for development.'),
    quiz: [q('၂ နှစ်အောက်အတွက် screen —', 'Under 2, screens —', [['တတ်နိုင်သမျှ ရှောင်', 'best avoided'], ['များများ ကြည့်သင့်', 'encouraged a lot']], 0)],
    takeaway: b('မျက်နှာချင်းဆိုင် ကစားခြင်းက အမြဲ ပိုကောင်းသည်။', 'Real interaction always wins.'),
    actionToday: b('ယနေ့ screen အစား ကစားနည်းတစ်ခု အစားထိုးပါ။', 'Swap one screen slot for play today.'),
  }),
  lesson({
    slug: 'big_feelings', category: 'emotional_development',
    title: b('ကြီးမားသော ခံစားမှုများ', 'Helping with big feelings'),
    summary: b('ကလေးများ ခံစားမှုကို ထိန်းရန် ကူညီနည်း။', 'Help children handle strong emotions.'),
    objectives: [b('ခံစားမှု ထိန်းချုပ်မှုကို အားပေးရန်။', 'Support emotional regulation.')],
    readingMinutes: 3,
    body: b('ကလေးများသည် ခံစားမှုကို ထိန်းရန် လေ့ကျင့်နေဆဲဖြစ်သည်။ ခံစားမှုကို အမည်တပ်ပေးပါ (“စိတ်ဆိုးနေတယ်နော်”)၊ တည်ငြိမ်စွာ ရှိနေပါ၊ ဘေးကင်းစေပါ။ ခံစားမှုကို “မဖြစ်သင့်” ဟု မဆိုပါနှင့် — အသိအမှတ်ပြုခြင်းက ကလေးကို ငြိမ်သက်စေသည်။', 'Children are still learning to manage feelings. Name the feeling, stay calm, keep them safe. Don’t dismiss feelings — acknowledging them helps a child settle.'),
    quiz: [q('ကလေး စိတ်တိုနေရင် အရင်ဆုံး —', 'When a child is upset, first —', [['ခံစားမှုကို အမည်တပ်၍ တည်ငြိမ်စွာနေ', 'name it and stay calm'], ['ချက်ချင်း ပြစ်တင်', 'scold immediately']], 0)],
    takeaway: b('သင်၏ တည်ငြိမ်မှုက ကလေးကို ငြိမ်သက်ရန် သင်ပေးသည်။', 'Your calm teaches their calm.'),
    actionToday: b('ယနေ့ ကလေး၏ ခံစားမှုတစ်ခုကို အမည်တပ်ပေးပါ။', 'Name one of your child’s feelings today.'),
  }),
  lesson({
    slug: 'making_friends', category: 'social_skills',
    title: b('သူငယ်ချင်း ဖွဲ့ခြင်း', 'Building social skills'),
    summary: b('အလှည့်စောင့်ခြင်း၊ ဝေမျှခြင်း သင်ကြားခြင်း။', 'Teaching turn-taking and sharing.'),
    objectives: [b('လူမှုကျွမ်းကျင်မှု သင်နည်း သိရှိရန်။', 'Learn to nurture social skills.')],
    readingMinutes: 3,
    body: b('လူမှုကျွမ်းကျင်မှုများသည် ကစားရင်း တဖြည်းဖြည်း သင်ယူရသည်။ အလှည့်ကျ ကစားနည်းများ၊ နမူနာပြခြင်းနှင့် ကောင်းသောအပြုအမူကို ချီးမွမ်းခြင်းဖြင့် သင်ကြားပါ။ ဝေမျှခြင်းကို အတင်းအကျပ် မခိုင်းပါနှင့် — အချိန်ပေးပါ။', 'Social skills are learned gradually through play. Teach with turn-taking games, modeling, and praise. Don’t force sharing — give it time.'),
    quiz: [q('ဝေမျှခြင်းကို —', 'Sharing is best —', [['အတင်းအကျပ် ခိုင်း', 'forced'], ['နမူနာပြ၍ အားပေး', 'modeled and encouraged']], 1)],
    takeaway: b('နမူနာပြခြင်းက အကောင်းဆုံး သင်ကြားနည်းဖြစ်သည်။', 'Modeling is the best teacher.'),
    actionToday: b('ယနေ့ အလှည့်ကျ ကစားနည်းတစ်ခု ကစားပါ။', 'Play one turn-taking game today.'),
  }),
  lesson({
    slug: 'early_math', category: 'early_mathematics',
    title: b('အစောပိုင်း သင်္ချာ', 'Everyday early math'),
    summary: b('နေ့စဉ်ဘဝထဲ ရေတွက်ခြင်း၊ ပုံသဏ္ဌာန်၊ နှိုင်းယှဉ်ခြင်း။', 'Counting, shapes, and comparing in daily life.'),
    objectives: [b('နေ့စဉ်ဘဝ သင်္ချာ နည်းလမ်းများ သိရှိရန်။', 'Learn everyday math moments.')],
    readingMinutes: 3,
    body: b('သင်္ချာသည် စာအုပ်ထဲသာ မဟုတ်ပါ။ လှေကားထစ် ရေတွက်ခြင်း၊ ပန်းကန် ခွဲဝေခြင်း၊ “ပိုကြီး/ပိုငယ်” နှိုင်းယှဉ်ခြင်းဖြင့် နေ့စဉ်ဘဝထဲ သင်္ချာ သင်ပေးနိုင်သည်။', 'Math is not only in books. Count stairs, share out plates, compare “bigger/smaller” — teach math in daily life.'),
    quiz: [q('အစောပိုင်း သင်္ချာကို —', 'Early math is best taught —', [['နေ့စဉ်ဘဝထဲ', 'in daily life'], ['flashcard ဖြင့်သာ', 'only with flashcards']], 0)],
    takeaway: b('ရေတွက်ခြင်းကို နေ့စဉ်ဘဝထဲ ထည့်ပါ။', 'Weave counting into your day.'),
    actionToday: b('ယနေ့ ကလေးနှင့်အတူ အရာ ၅ ခု ရေတွက်ပါ။', 'Count five things together today.'),
  }),
  lesson({
    slug: 'creativity', category: 'creativity',
    title: b('တီထွင်ဖန်တီးမှု အားပေးခြင်း', 'Nurturing creativity'),
    summary: b('လွတ်လပ်စွာ ဆွဲ/တည်ဆောက်/ဟန်ဆောင် ကစားခြင်း အားပေးခြင်း။', 'Encourage open-ended art, building, and pretend play.'),
    objectives: [b('တီထွင်ဖန်တီးမှု အားပေးနည်း သိရှိရန်။', 'Learn to support creativity.')],
    readingMinutes: 3,
    body: b('တီထွင်ဖန်တီးမှုသည် အဖြေမှန်တစ်ခုတည်း မရှိသော ကစားခြင်းမှ ကြီးထွားသည်။ ရလဒ်ထက် လုပ်ငန်းစဉ်ကို ချီးမွမ်းပါ (“အရောင်တွေ ရောသုံးထားတာ တွေ့တယ်”)။ ကလေး၏ စိတ်ကူးကို ဦးဆောင်ခွင့် ပေးပါ။', 'Creativity grows from open-ended play with no single right answer. Praise the process, not the result. Let the child lead their ideas.'),
    quiz: [q('တီထွင်မှုအတွက် ချီးမွမ်းသင့်သည်မှာ —', 'For creativity, praise the —', [['လုပ်ငန်းစဉ်', 'process'], ['ရလဒ်သာ', 'result only']], 0)],
    takeaway: b('“မှန်/မှား” မရှိသော ကစားခြင်းက တီထွင်မှုကို မွေးသည်။', 'Open-ended play breeds creativity.'),
    actionToday: b('ယနေ့ ကလေးကို ခဲတံ/စက္ကူဖြင့် လွတ်လပ်စွာ ဆွဲစေပါ။', 'Let your child draw freely today.'),
  }),
  lesson({
    slug: 'problem_solving_parenting', category: 'problem_solving',
    title: b('ပြဿနာ ဖြေရှင်းမှု အားပေးခြင်း', 'Coaching problem solving'),
    summary: b('အဖြေမပေးဘဲ တွေးခေါ်ရန် ကူညီခြင်း။', 'Help children think it through instead of giving answers.'),
    objectives: [b('ပြဿနာဖြေရှင်းမှု အားပေးနည်း သိရှိရန်။', 'Learn to coach problem solving.')],
    readingMinutes: 3,
    body: b('ကလေး အခက်အခဲ ကြုံရင် ချက်ချင်း အဖြေ မပေးပါနှင့်။ “ဘယ်လို လုပ်ကြည့်မလဲ” ဟု မေးပါ။ ကြိုးစားခွင့် ပေး၍ မှားလည်း သင်ယူမှုဟု မှတ်ယူပါ။ ဤသည်က စိတ်ရှည်မှုနှင့် ယုံကြည်မှုကို တည်ဆောက်သည်။', 'When a child is stuck, don’t rush the answer. Ask “what could you try?” Let them attempt; mistakes are learning. This builds patience and confidence.'),
    quiz: [q('ကလေး အခက်အခဲ ကြုံရင် —', 'When stuck, better to —', [['ဦးဆောင်မေးခွန်း မေး', 'ask a guiding question'], ['အဖြေ ချက်ချင်းပေး', 'give the answer at once']], 0)],
    takeaway: b('မှားယွင်းမှုတိုင်းသည် သင်ယူမှုဖြစ်သည်။', 'Every mistake is learning.'),
    actionToday: b('ယနေ့ ဦးဆောင်မေးခွန်းတစ်ခုဖြင့် ကူညီပါ။', 'Help with one guiding question today.'),
  }),
  lesson({
    slug: 'special_needs_awareness', category: 'special_needs_awareness',
    title: b('အထူးလိုအပ်ချက် သိရှိနားလည်မှု', 'Special-needs awareness'),
    summary: b('ကွဲပြားမှုကို လေးစား၍ အားသာချက်အခြေခံ ချဉ်းကပ်ခြင်း။', 'Respecting difference with a strengths-based view.'),
    objectives: [b('အားသာချက်အခြေခံ သဘောထား သိရှိရန်။', 'Understand a strengths-based approach.')],
    readingMinutes: 4,
    body: b('ကလေးတိုင်းတွင် အားသာချက်များ ရှိသည်။ အထူးလိုအပ်ချက်ရှိသော ကလေးများကို “ချို့ယွင်း” ဟု မမြင်ဘဲ ကွဲပြားစွာ သင်ယူ/ကြီးထွားသူများအဖြစ် မြင်ပါ။ ဤအက်ပ်သည် ရောဂါ မဖော်ထုတ်ပါ — စိုးရိမ်ပါက ကျွမ်းကျင်ပညာရှင်နှင့် တိုင်ပင်ရန် လမ်းညွှန်ပေးသည်။ စောစီးစွာ ပံ့ပိုးမှုက များစွာ ကူညီနိုင်သည်။', 'Every child has strengths. See children with special needs not as “broken” but as learning and growing differently. This app does not diagnose — if concerned, it guides you to a professional. Early support can help a lot.'),
    quiz: [q('ဤအက်ပ်သည် —', 'This app —', [['ရောဂါ မဖော်ထုတ်ပါ', 'does not diagnose'], ['ရောဂါ ဖော်ထုတ်ပေးသည်', 'gives a diagnosis']], 0)],
    takeaway: b('ကွဲပြားမှုကို လေးစားပါ — အားသာချက်ကို မြင်ပါ။', 'Respect difference; see strengths.'),
    actionToday: b('ယနေ့ ကလေး၏ အားသာချက်တစ်ခုကို ချီးမွမ်းပါ။', 'Praise one of your child’s strengths today.'),
  }),
  lesson({
    slug: 'prepare_preschool', category: 'preparing_for_preschool',
    title: b('မူကြိုအတွက် ပြင်ဆင်ခြင်း', 'Getting ready for preschool'),
    summary: b('ခွဲနေခြင်း၊ လုပ်ရိုးလုပ်စဉ်နှင့် ကိုယ်တိုင်လုပ်နိုင်မှု လေ့ကျင့်ခြင်း။', 'Practice separation, routines, and self-help.'),
    objectives: [b('မူကြိုအသင့်ဖြစ်မှု အခြေခံ သိရှိရန်။', 'Know preschool readiness basics.')],
    readingMinutes: 3,
    body: b('မူကြိုအတွက် အသင့်ဖြစ်မှုသည် စာတတ်မှုထက် — ခဏခွဲနေနိုင်ခြင်း၊ လုပ်ရိုးလုပ်စဉ် လိုက်နာနိုင်ခြင်းနှင့် ကိုယ်တိုင် အခြေခံ လုပ်နိုင်ခြင်းက ပို၍ အရေးကြီးသည်။ မူကြိုအကြောင်း အပြုသဘော စကားဖြင့် ပြောပါ။', 'Preschool readiness is less about academics and more about brief separation, following routines, and basic self-help. Talk about preschool positively.'),
    quiz: [q('မူကြိုအသင့်ဖြစ်မှုတွင် အရေးကြီးဆုံး —', 'Most important for readiness —', [['လူမှု/ကိုယ်တိုင်လုပ်နိုင်မှု', 'social/self-help skills'], ['အက္ခရာ အားလုံးတတ်', 'knowing all letters']], 0)],
    takeaway: b('လူမှု/ခံစားမှု ကျွမ်းကျင်မှုက အဓိကဖြစ်သည်။', 'Social-emotional skills matter most.'),
    actionToday: b('ယနေ့ ကလေးကို ကိုယ်တိုင် ဖိနပ်ဝတ်စေပါ။', 'Let your child put on their own shoes today.'),
  }),
  lesson({
    slug: 'prepare_school', category: 'preparing_for_school',
    title: b('ကျောင်းအတွက် ပြင်ဆင်ခြင်း', 'Getting ready for school'),
    summary: b('အာရုံစိုက်မှု၊ လွတ်လပ်မှုနှင့် စာဖတ်စိတ်ဝင်စားမှု တည်ဆောက်ခြင်း။', 'Build attention, independence, and love of reading.'),
    objectives: [b('ကျောင်းအသင့်ဖြစ်မှု တည်ဆောက်နည်း သိရှိရန်။', 'Learn to build school readiness.')],
    readingMinutes: 3,
    body: b('ကျောင်းအတွက် ကလေးကို အာရုံစိုက်မှု၊ လွတ်လပ်စွာ လုပ်ဆောင်နိုင်မှုနှင့် စာဖတ်စိတ်ဝင်စားမှုဖြင့် ပြင်ဆင်ပါ။ တသမတ်တည်း လုပ်ရိုးလုပ်စဉ်နှင့် အိပ်ရေးဝမှုက သင်ယူမှုကို ကူညီသည်။ ကျောင်းအကြောင်း ကြောက်စိတ်မဖြစ်စေဘဲ ရင်းနှီးစေပါ။', 'Prepare with attention, independence, and a love of reading. Steady routines and enough sleep help learning. Make school feel familiar, not frightening.'),
    quiz: [q('ကျောင်းအသင့်ဖြစ်မှုကို ကူညီသည်မှာ —', 'What helps readiness —', [['အိပ်ရေးဝ၍ တသမတ်တည်း လုပ်ရိုးလုပ်စဉ်', 'sleep and steady routines'], ['screen များများ', 'lots of screens']], 0)],
    takeaway: b('အာရုံစိုက်မှုနှင့် လွတ်လပ်မှုက ကျောင်းကို ကူညီသည်။', 'Attention and independence help school.'),
    actionToday: b('ယနေ့ ကလေးကို လုပ်ငန်းတစ်ခု အစအဆုံး တစ်ယောက်တည်း လုပ်စေပါ။', 'Let your child finish one task alone today.'),
  }),
  lesson({
    slug: 'doctor_visits', category: 'doctor_visits',
    title: b('ဆရာဝန်ပြသခြင်း ပြင်ဆင်နည်း', 'Making the most of doctor visits'),
    summary: b('မေးခွန်းများ ပြင်ဆင်၍ စိုးရိမ်စရာများ မှတ်သားခြင်း။', 'Prepare questions and note concerns.'),
    objectives: [b('ဆရာဝန်ပြသချိန်ကို ထိရောက်စေရန်။', 'Make visits effective.')],
    readingMinutes: 3,
    body: b('ဆရာဝန်မပြမီ ကလေး၏ အစား၊ အိပ်၊ ဖွံ့ဖြိုးမှုနှင့် စိုးရိမ်စရာများကို မှတ်သားထားပါ။ မေးလိုသည့် မေးခွန်း ၂–၃ ခုကို ကြိုရေးထားပါ။ ကာကွယ်ဆေး မှတ်တမ်းကို ယူသွားပါ။ ဤအက်ပ်၏ “ဆရာဝန်ပြသ ပြင်ဆင်ချက်” ကို ထုတ်ယူ၍ သွားနိုင်သည်။', 'Before a visit, note your child’s eating, sleep, development, and concerns. Write 2–3 questions in advance. Bring the vaccination record. You can export this app’s doctor-visit prep to take along.'),
    quiz: [q('ဆရာဝန်မပြမီ ကောင်းသည်မှာ —', 'Before a visit, it helps to —', [['မေးခွန်းများ ကြိုရေးထား', 'write questions ahead'], ['ဘာမှ မပြင်ဆင်', 'prepare nothing']], 0)],
    takeaway: b('ကြိုတင်ပြင်ဆင်မှုက ပြသချိန်ကို တန်ဖိုးရှိစေသည်။', 'Preparation makes visits count.'),
    actionToday: b('ယနေ့ ဆရာဝန်ကို မေးလိုသည့် မေးခွန်းတစ်ခု ရေးထားပါ။', 'Write one question for the doctor today.'),
  }),
  lesson({
    slug: 'parent_wellbeing', category: 'parent_mental_health',
    title: b('မိဘ၏ စိတ်ကျန်းမာရေး', 'Caring for your own wellbeing'),
    summary: b('မိဘ ကိုယ်တိုင် ဂရုစိုက်ခြင်းသည် ကလေးကိုပါ အကျိုးပြုသည်။', 'Caring for yourself helps your child too.'),
    objectives: [b('မိဘ စိတ်ကျန်းမာရေး၏ အရေးပါမှု သိရှိရန်။', 'Value your own wellbeing.')],
    readingMinutes: 3,
    body: b('မိဘဖြစ်ခြင်းသည် ပင်ပန်းနိုင်သည်။ သင်ကိုယ်တိုင် အနားယူ၊ အထောက်အပံ့ရှာ၊ ခံစားမှုကို မျှဝေခြင်းက သင့်ကလေးအတွက်ပါ အကျိုးရှိသည်။ အမြဲ ဝမ်းနည်း/စိုးရိမ်နေရ၊ နေ့စဉ်ဘဝ ထိခိုက်နေပါက ကူညီမှု ရှာဖွေရန် အားနည်းချက် မဟုတ်ပါ — ကျန်းမာရေးပညာရှင် သို့မဟုတ် ယုံကြည်ရသူနှင့် ပြောဆိုပါ။', 'Parenting can be exhausting. Rest, seeking support, and sharing your feelings help your child too. If you feel persistently low or anxious and daily life is affected, reaching out is a strength — talk to a health professional or someone you trust.'),
    quiz: [q('မိဘ ကိုယ်တိုင် ဂရုစိုက်ခြင်းသည် —', 'Caring for yourself is —', [['ကလေးအတွက်ပါ အကျိုးရှိ', 'good for your child too'], ['တစ်ကိုယ်ကောင်းဆန်ခြင်း', 'selfish']], 0)],
    takeaway: b('သင် ကောင်းမွန်မှသာ ကလေးကို ကောင်းစွာ ဂရုစိုက်နိုင်သည်။', 'You care best when you’re cared for.'),
    actionToday: b('ယနေ့ သင့်အတွက် ၁၀ မိနစ် အနားယူပါ။', 'Take 10 minutes for yourself today.'),
  }),
  lesson({
    slug: 'language_rich_home', category: 'language_development',
    title: b('ဘာသာစကား ကြွယ်ဝသော အိမ်', 'A language-rich home'),
    summary: b('သီချင်း၊ ပုံပြင်နှင့် စကားပြောဖြင့် ဘာသာစကား တည်ဆောက်ခြင်း။', 'Build language with songs, stories, and talk.'),
    objectives: [b('ဘာသာစကား ကြွယ်ဝစေမည့် အလေ့အထ သိရှိရန်။', 'Learn language-building habits.')],
    readingMinutes: 3,
    body: b('သီချင်းဆိုခြင်း၊ ပုံပြင်ပြောခြင်း၊ နေ့စဉ်လုပ်ဆောင်ချက်များကို စကားဖြင့် ရှင်းပြခြင်းက ဘာသာစကားကို ကြွယ်ဝစေသည်။ ဘာသာစကား ၂ မျိုး သင်ခြင်းသည် ကလေးကို မရှုပ်ထွေးစေပါ — အားသာချက် တစ်ခုပင်ဖြစ်သည်။', 'Singing, storytelling, and narrating daily actions enrich language. Two languages do not confuse a child — it is an asset.'),
    quiz: [q('ဘာသာစကား ၂ မျိုး သင်ခြင်းသည် —', 'Raising bilingual is —', [['အားသာချက်တစ်ခု', 'an asset'], ['ရှုပ်ထွေးစေ', 'confusing']], 0)],
    takeaway: b('စကားပြော၊ သီချင်းဆို၊ ပုံပြင်ပြော — နေ့စဉ်လုပ်ပါ။', 'Talk, sing, tell stories — daily.'),
    actionToday: b('ယနေ့ ကလေးနှင့်အတူ သီချင်းတစ်ပုဒ် ဆိုပါ။', 'Sing one song with your child today.'),
  }),
];
