// Parent Learning Academy — short lessons. Starter curriculum covering every
// category; the CMS extends toward the full target. General parenting guidance,
// clinical_review until approved. Simple language, no medical jargon.
import { lesson, type SeedItem } from '../types';

const b = (mm: string, en: string) => ({ mm, en });
const q = (question: string, qEn: string, opts: [string, string][], answerIndex: number) => ({
  q: b(question, qEn),
  options: opts.map(([mm, en]) => b(mm, en)),
  answerIndex,
});

export const LESSONS: SeedItem[] = [
  lesson({
    slug: 'what_is_development', category: 'understanding_development',
    title: b('ဖွံ့ဖြိုးမှုဆိုတာ ဘာလဲ', 'What is child development?'),
    summary: b('ကလေးဖွံ့ဖြိုးမှုနှင့် အကြံဉာဏ်တောင်းခံသင့်သည့်အချိန်ကို နားလည်ခြင်း။', 'Understanding development and when to ask for advice.'),
    objectives: [b('ဖွံ့ဖြိုးမှု နယ်ပယ်များကို သိရှိရန်။', 'Know the areas of development.'), b('ဖွံ့ဖြိုးမှုအကြောင်း အကြံဉာဏ်တောင်းခံသင့်သည့်အချိန်ကို သိရှိရန်။', 'Know when to ask for advice about development.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nကလေးဖွံ့ဖြိုးမှုတွင် လှုပ်ရှားခြင်း၊ ဆက်သွယ်ပြောဆိုခြင်း၊ စဉ်းစားခြင်း၊ သင်ယူခြင်းနှင့် အခြားသူများနှင့် ဆက်ဆံခြင်းတို့၌ ပြောင်းလဲလာမှုများ ပါဝင်ပါသည်။ ဖွံ့ဖြိုးမှုမှတ်တိုင် စာရင်းများက တိုးတက်မှုကို သတိပြုရန်နှင့် စိုးရိမ်ချက်များကို ဆွေးနွေးရန် အထောက်အကူပြုသော်လည်း ရောဂါဖော်ထုတ်ချက် မဟုတ်သကဲ့သို့ ဖွံ့ဖြိုးမှုစစ်ဆေးခြင်းကိုလည်း အစားမထိုးနိုင်ပါ။ ကလေး၏ ဖွံ့ဖြိုးမှုနှင့်ပတ်သက်၍ စိုးရိမ်ပါက စောင့်မနေဘဲ သက်ဆိုင်ရာ ကျန်းမာရေးပညာရှင်နှင့် ဆွေးနွေးပါ။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nChild development includes changes in how children move, communicate, think, learn, and relate to others. Milestone checklists help you notice progress and discuss concerns; they are not a diagnosis or a substitute for developmental screening. If you are concerned about your child’s development, talk with a qualified health professional rather than waiting.'),
    quiz: [q('ဖွံ့ဖြိုးမှုမှတ်တိုင် စာရင်းများက စောင့်ရှောက်သူများကို —', 'Milestone checklists help caregivers —', [['မိမိဘာသာ ရောဂါဖော်ထုတ်နိုင်စေသည်', 'diagnose a condition on their own'], ['တိုးတက်မှုကို သတိပြု၍ စိုးရိမ်ချက်များကို ဆွေးနွေးနိုင်စေသည်', 'notice progress and discuss concerns']], 1)],
    takeaway: b('တိုးတက်မှုကို သတိပြု၍ စိုးရိမ်ပါက အကြံဉာဏ်တောင်းခံပါ။', 'Notice progress and ask for advice when concerned.'),
    actionToday: b('ယနေ့ ကလေး ကစားပုံ သို့မဟုတ် ဆက်သွယ်ပြောဆိုပုံကို သတိပြု၍ ကျန်းမာရေးပညာရှင်နှင့် ဆွေးနွေးလိုသော မေးခွန်းများရှိပါက ချရေးထားပါ။', 'Notice how your child plays or communicates today, and write down any questions to discuss with a health professional.'),
  }),
  lesson({
    slug: 'power_of_play', category: 'learning_through_play',
    title: b('ကစားခြင်း၏ အကျိုးကျေးဇူးများ', 'The power of play'),
    summary: b('ကစားခြင်းက သင်ယူမှုနှင့် ရင်းနှီးဆက်ဆံမှုအတွက် အခွင့်အလမ်းများ ပေးနိုင်ပါသည်။', 'Play offers opportunities for learning and connection.'),
    objectives: [b('ကစားခြင်းက ကလေးဖွံ့ဖြိုးမှုကို မည်သို့ အထောက်အကူပြုသည်ကို သိရှိရန်။', 'Know the benefits of play.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nကစားခြင်းက ဘာသာစကား၊ သင်ယူမှုနှင့် ပြုစုစောင့်ရှောက်သူနှင့် နွေးထွေးစွာ အပြန်အလှန်ဆက်ဆံမှုအတွက် အခွင့်အလမ်းများ ပေးနိုင်ပါသည်။ ကလေး၏ စိတ်ဝင်စားမှုနှင့် စွမ်းရည်တို့နှင့် ကိုက်ညီသော ကစားနည်းကို ရွေးပါ။ ကလေး၏ အသံ၊ အမူအရာ သို့မဟုတ် စကားများကို သတိပြု၍ တုံ့ပြန်ပြီး ခဏနားချိန်များ ပေးပါ။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nPlay can offer opportunities for language, learning, and warm interaction with a caregiver. Choose play that fits your child’s interests and abilities. Notice and respond to their sounds, gestures, or words, and allow pauses.'),
    quiz: [q('ပျော်ရွှင်ဖွယ် ကစားချိန်ကို အထောက်အကူပြုသည့် နည်းလမ်းမှာ —', 'Which approach supports enjoyable play?', [['ကလေး၏ တုံ့ပြန်မှုကို သတိပြု၍ ပြန်လည်တုံ့ပြန်ခြင်း', 'notice and respond to the child'], ['ကလေး၏ တုံ့ပြန်မှုများကို လျစ်လျူရှုခြင်း', 'ignore the child’s responses']], 0)],
    takeaway: b('ပျော်ရွှင်ဖွယ် အပြန်အလှန်ကစားခြင်းက ရင်းနှီးဆက်ဆံမှုနှင့် သင်ယူမှုကို အထောက်အကူပြုနိုင်ပါသည်။', 'Enjoyable back-and-forth play can support connection and learning.'),
    actionToday: b('ယနေ့ ကလေးစိတ်ဝင်စားသည့်အရာကို သတိပြုပြီး အသံ၊ အမူအရာ သို့မဟုတ် စကားဖြင့် တုံ့ပြန်ပါ။', 'Today, notice what interests your child and respond with a sound, gesture, or words.'),
  }),
  lesson({
    slug: 'talk_more', category: 'speech_development',
    title: b('ကလေးနှင့် နေ့စဉ် စကားပြောပါ', 'Talk more, every day'),
    summary: b('နေ့စဉ် အပြန်အလှန် စကားပြောခြင်းက ဘာသာစကားသင်ယူမှုကို အထောက်အကူပြုနိုင်ပါသည်။', 'Everyday back-and-forth talk can support language learning.'),
    objectives: [b('အပြန်အလှန် စကားပြောရာတွင် ကလေးကို တုံ့ပြန်ပေးနိုင်သည့် ရိုးရှင်းသော နည်းလမ်းများကို သိရှိရန်။', 'Learn simple ways to support back-and-forth talk.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nကလေးနှင့် အတူလုပ်နေသည့်အရာကို စကားဖြင့် ဖော်ပြပါ။ ကလေး၏ အသံ၊ အမူအရာ သို့မဟုတ် စကားလုံးများကို သတိပြုနားထောင်ပြီး တုံ့ပြန်ပါ။ ကလေးက စကားတိုတစ်ခု ပြောပါက အနည်းငယ်ပိုရှည်သော စကားဖြင့် ပြန်ပြောပေးနိုင်ပါသည်။ ပြန်ဖြေရန် အချိန်ပေး၍ ခဏစောင့်ပါ။ ဤအချက်များသည် သင်ယူမှုကို အားပေးရန် အထွေထွေ အကြံပြုချက်များသာ ဖြစ်ပြီး စကားပြော သို့မဟုတ် ဘာသာစကား စစ်ဆေးအကဲဖြတ်မှု မဟုတ်ပါ။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nTalk about what you and your child are doing. Listen for their sounds, gestures, or words and respond. If your child uses a short phrase, you can reply with a slightly longer one. Pause and give them time to answer. These are general learning ideas, not a speech or language assessment.'),
    quiz: [q('အပြန်အလှန် စကားပြောခြင်းကို မည်သည့်နည်းက အထောက်အကူပြုပါသလဲ။', 'Which approach supports back-and-forth talk?', [['နားထောင်၊ တုံ့ပြန်ပြီး ခဏစောင့်ခြင်း', 'listen, respond, and pause'], ['ကလေးတုံ့ပြန်ရန် မစောင့်ဘဲ ဆက်တိုက်ပြောခြင်း', 'keep talking without waiting']], 0)],
    takeaway: b('သတိပြု၊ တုံ့ပြန်ပြီး အချိန်ပေးပါ။', 'Notice, respond, and allow time.'),
    actionToday: b('နေ့စဉ်လုပ်ရိုးလုပ်စဉ်တစ်ခုကို စကားဖြင့် ဖော်ပြပြီး မေးခွန်းတစ်ခုမေးကာ ကလေးတုံ့ပြန်ရန် ခဏစောင့်ပါ။', 'Describe one daily routine, ask one question, and pause for your child to respond.'),
  }),
  lesson({
    slug: 'reading_together', category: 'reading',
    title: b('အတူတူ စာဖတ်ခြင်း', 'Reading together'),
    summary: b('ပျော်ရွှင်စွာ အတူစာဖတ်ခြင်း၏ တန်ဖိုး။', 'The value of enjoyable shared reading.'),
    objectives: [b('စာဖတ်ချိန်ကို ပျော်ရွှင်ဖွယ် ဖြစ်စေရန်။', 'Make reading time joyful.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nရုပ်ပုံစာအုပ်ကို အတူဖတ်ခြင်းက ဘာသာစကား၊ စကားပြောဆိုမှုနှင့် ချစ်ခင်ရင်းနှီးမှုတို့ကို အားပေးနိုင်ပါသည်။ ရင်းနှီးပြီးသား အကြိုက်ဆုံးစာအုပ်ကို ပြန်ဖတ်နိုင်သလို စာအုပ်အသစ်ကိုလည်း ဖတ်ရှုနိုင်ပြီး ကလေးစိတ်ဝင်စားသည့်အရာကို လိုက်၍ ခဏရပ်ကာ စကားပြောပါ။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nShared picture-book reading can support language, conversation, and warm connection. Enjoy familiar favorites or explore new books, and pause to follow your child’s interest.'),
    quiz: [q('အတူစာဖတ်ချိန်ကို အထောက်အကူပြုသည့် နည်းလမ်းမှာ —', 'Which approach supports shared reading?', [['ကလေးစိတ်ဝင်စားရာကို လိုက်၍ ပုံများအကြောင်း စကားပြောခြင်း', 'follow the child’s interest and talk about the pictures'], ['ကလေးတုံ့ပြန်မှုကို မစောင့်ဘဲ အမြန်ဖတ်ပြီးသွားခြင်း', 'rush to finish without responding']], 0)],
    takeaway: b('ပျော်ရွှင်ဖွယ် အတူစာဖတ်ချိန် မိနစ်အနည်းငယ်ကပင် အသုံးဝင်သော အလေ့အထတစ်ခု ဖြစ်လာနိုင်ပါသည်။', 'A few enjoyable minutes of shared reading can be a useful routine.'),
    actionToday: b('ယနေ့ စာအုပ်တစ်အုပ်ရွေးပြီး ပုံများကြည့်ခြင်း၊ စကားပြောခြင်း သို့မဟုတ် အတူဖတ်ခြင်းကို ပျော်ရွှင်စွာ မိနစ်အနည်းငယ် ပြုလုပ်ပါ။', 'Choose a book and spend a few enjoyable minutes looking, talking, or reading together today.'),
  }),
  lesson({
    slug: 'gentle_discipline', category: 'positive_parenting',
    title: b('နူးညံ့သော စည်းကမ်း', 'Positive, gentle discipline'),
    summary: b('ပြစ်ဒဏ်မဟုတ်ဘဲ လမ်းညွှန်ခြင်းဖြင့် အပြုအမူ သင်ကြားခြင်း။', 'Guiding behavior with connection, not punishment.'),
    objectives: [b('အပြုသဘော စည်းကမ်းနည်းများ သိရှိရန်။', 'Learn positive discipline tools.')],
    readingMinutes: 4,
    body: b('ကလေးများသည် ဆက်ဆံရေးမှတစ်ဆင့် အကောင်းဆုံး သင်ယူကြသည်။ ရိုက်ခြင်း/ဟစ်အော်ခြင်းအစား ရှင်းလင်းသော နယ်နိမိတ်များ၊ တသမတ်တည်း လုပ်ရိုးလုပ်စဉ်နှင့် ကောင်းသောအပြုအမူကို ချီးမွမ်းခြင်းက ပို၍ ထိရောက်သည်။ သင် တည်ငြိမ်စွာ ရှိနေခြင်းက ကလေးကို ငြိမ်သက်ရန် သင်ပေးသည်။', 'Children learn best through relationship. Instead of hitting or yelling, clear limits, steady routines, and praising good behavior work better. Your calm teaches their calm.'),
    quiz: [q('အပြုသဘော စည်းကမ်းတွင် အဓိကမှာ —', 'Positive discipline centers on —', [['ပြစ်ဒဏ်', 'punishment'], ['ဆက်ဆံရေးနှင့် လမ်းညွှန်မှု', 'connection and guidance']], 1)],
    takeaway: b('တည်ငြိမ်မှုနှင့် တသမတ်တည်းရှိမှုက အဓိကဖြစ်သည်။', 'Calm and consistency matter most.'),
    actionToday: b('ယနေ့ ကလေး၏ ကောင်းသောအပြုအမူ တစ်ခုကို တိကျစွာ ချီးမွမ်းပါ။', 'Praise one specific good behavior today.'),
  }),
  lesson({
    slug: 'balanced_meals', category: 'nutrition',
    title: b('မျှတသော အစားအစာ', 'Balanced meals for little ones'),
    summary: b('ကလေးများအတွက် ကျန်းမာသော အစားအသောက် အခြေခံ။', 'Healthy eating basics for young children.'),
    objectives: [b('မျှတသော အစားအစာ ပုံစံ သိရှိရန်။', 'Know what a balanced plate looks like.')],
    readingMinutes: 3,
    body: b('ကလေးများအတွက် အသီးအနှံ၊ အသီးအရွက်၊ ကောက်နှံ၊ ပရိုတင်းနှင့် နို့ထွက်ပစ္စည်းများ မျှတစွာ လိုအပ်သည်။ ဆား/သကြား များများ ရှောင်ပါ။ စားခြင်းကို ဖိအားမပေးဘဲ ပျော်ရွှင်ဖွယ် ဖြစ်စေပါ။ အသစ်တစ်ခုကို လက်ခံရန် အကြိမ်များစွာ လိုနိုင်သည်။', 'Children need a balance of fruit, vegetables, grains, protein, and dairy. Limit salt and sugar. Keep meals pressure-free and pleasant. New foods often take many tries to accept.'),
    quiz: [q('အစားအစာ အသစ်ကို ကလေး ငြင်းရင် —', 'If a child refuses a new food —', [['ထပ်ခါ တင်ပြပါ', 'keep offering gently'], ['ထိုအစားအစာ ရပ်ပါ', 'stop that food forever']], 0)],
    takeaway: b('စားခြင်းကို တိုက်ပွဲ မဖြစ်စေပါနှင့်။', 'Don’t make meals a battle.'),
    actionToday: b('ယနေ့ အစားအစာ အရောင် ၃ မျိုး ပန်းကန်ထဲ ထည့်ပါ။', 'Put three food colors on the plate today.'),
  }),
  lesson({
    slug: 'healthy_sleep', category: 'sleep',
    title: b('ကျန်းမာသော အိပ်စက်မှု', 'Healthy sleep habits'),
    summary: b('တသမတ်တည်း အိပ်ချိန်နှင့် ဘေးကင်းသော အိပ်ရာ။', 'Consistent bedtimes and safe sleep.'),
    objectives: [b('အိပ်ရေးအလေ့အထ ကောင်းများ သိရှိရန်။', 'Learn good sleep habits.')],
    readingMinutes: 3,
    body: b('နေ့စဉ် အိပ်ရာဝင်ချိန်ကို တတ်နိုင်သမျှ တူညီအောင်ထားပြီး ရေချိုးခြင်း၊ စာဖတ်ခြင်း၊ အိပ်ရာဝင်ခြင်းတို့ကို အစဉ်လိုက် ငြိမ်သက်စွာ လုပ်ပေးခြင်းက အိပ်စက်မှုကို ကူညီနိုင်သည်။ အိပ်ရာမဝင်မီ မျက်နှာပြင်ကြည့်ခြင်းကို ရှောင်ပြီး အလင်းရောင်လျှော့ကာ စာဖတ်ခြင်း သို့မဟုတ် သီချင်းဆိုခြင်းကဲ့သို့ ငြိမ်သက်သော လုပ်ဆောင်ချက်ကို ရွေးပါ။ အသက် ၁ နှစ်မပြည့်သေးသော ကလေးကို နေ့အိပ်ချိန်နှင့် ညအိပ်ချိန်တိုင်း ကျောပေါ်လှန်၍ မစောင်းသော မာကျောညီညာသည့် အိပ်ရာမျက်နှာပြင်ပေါ်တွင် အိပ်စေပါ။ တင်းကျပ်စွာ ခင်းထားသော အိပ်ရာခင်းမှလွဲ၍ ကလေးအိပ်ရာထဲတွင် ခေါင်းအုံး၊ စောင်၊ ဘေးကာ၊ အရုပ်ပျော့ သို့မဟုတ် အဝတ်ပျော့များ မထားပါနှင့်။ အနည်းဆုံး ပထမ ၆ လအထိ မိဘများအိပ်သည့် အခန်းထဲရှိ ကလေး၏ သီးခြားအိပ်ရာတွင် အိပ်စေပါ။ အခန်းကို မှောင်မှောင်၊ တိတ်တိတ်နှင့် သက်သောင့်သက်သာ အေးမြအောင် ထားပါ။', 'Consistent bedtimes and a calm routine (bath–book–bed) may help sleep. Before bed, avoid screens, dim the lights, and choose a quiet activity such as reading or singing. For every nap and overnight sleep until age 1, place the baby on their back on a firm, flat, non-inclined sleep surface. Keep only a fitted sheet in the sleep space—no pillow, blanket, bumper, soft toy, or loose cloth. For at least the first 6 months, keep the baby’s own separate sleep space in the parents’ room. Keep the room dark, quiet, and comfortably cool.'),
    quiz: [q('မွေးကင်းစကို အိပ်စေရမည့် ပုံစံ —', 'Newborns should sleep —', [['ကျောပေါ်လှန်၍', 'on the back'], ['ဗိုက်လှန်၍', 'on the tummy']], 0)],
    takeaway: b('တည်ငြိမ်သော အိပ်ရာဝင်လုပ်ရိုးလုပ်စဉ်က အထောက်အကူပြုနိုင်သည်။', 'A steady bedtime routine may help.'),
    actionToday: b('ယနေ့ည တည်ငြိမ်သော အိပ်ရာဝင်လုပ်ရိုးလုပ်စဉ်တိုတစ်ခုကို လုပ်ကြည့်ပါ။', 'Try one short, calm bedtime routine tonight.'),
  }),
  lesson({
    slug: 'home_safety', category: 'safety',
    title: b('ကလေးငယ်အတွက် အိမ်တွင်းဘေးကင်းရေး', 'Home safety essentials'),
    summary: b('ကလေး စတင်လှုပ်ရှားသွားလာချိန်တွင် အိမ်ကို ဘေးကင်းအောင် ကြိုတင်ပြင်ဆင်ပါ။', 'Baby-proofing for a mobile child.'),
    objectives: [b('အိမ်တွင်းတွင် ဖြစ်ပေါ်နိုင်သည့် အဓိကအန္တရာယ်များကို သိရှိရန်။', 'Know the main home hazards.')],
    readingMinutes: 3,
    body: b('ဆေးဝါးနှင့် သန့်ရှင်းရေးသုံး ဓာတုပစ္စည်းများကို ကလေးမမြင်နိုင်၊ လက်လှမ်းမမီသည့် သော့ခတ်ထားသော နေရာတွင် သိမ်းပါ။ ပူသောအရည်များကို ကလေးလက်လှမ်းမမီအောင် ထားပါ။ အသုံးမပြုသည့် လျှပ်စစ်ပလပ်ပေါက်များတွင် ကလေးမဖြုတ်နိုင်၊ မျိုမချနိုင်သော လုံခြုံရေးအဖုံး တပ်ပါ။ လှေကား၊ ရေပုံး၊ ရေချိုးကန်နှင့် အခြားရေနေရာများအနီး ကလေးကို အနီးကပ်ကြီးကြပ်ပါ။ တစ်ဆို့စေနိုင်သော ပစ္စည်းငယ်များကို ဖယ်ရှားထားပြီး ဒေသအရေးပေါ်ဖုန်းနံပါတ်ကို ကြိုတင်သိထားပါ။', 'Store medicines and cleaning chemicals locked, out of sight and reach. Keep hot liquids out of reach. Fit child-resistant, non-choking covers to unused electrical outlets. Closely supervise children near stairs, buckets, bathtubs, and other water. Remove small choking hazards and know your local emergency number in advance.'),
    quiz: [q('ဆေးဝါးများကို မည်သည့်နေရာတွင် သိမ်းဆည်းသင့်သနည်း။', 'Medicines should be —', [['ကလေးလက်လှမ်းမမီသည့် သော့ခတ်ထားသောနေရာတွင်', 'locked out of reach'], ['စားပွဲပေါ်တွင်', 'left on the table']], 0)],
    takeaway: b('ဘေးကင်းအောင် ပြင်ဆင်ထားသော အိမ်တွင် ကလေးသည် ပိုမိုလုံခြုံစွာ စူးစမ်းသင်ယူနိုင်သည်။', 'A safe home lets children explore freely.'),
    actionToday: b('ယနေ့ အခန်းတစ်ခန်းကို ကလေး၏ မျက်စိအမြင့်မှ ကြည့်ပြီး အန္တရာယ်ရှိနိုင်သည့် အရာများကို စစ်ဆေးပါ။', 'Check one room from your child’s eye level today.'),
  }),
  lesson({
    slug: 'screen_time', category: 'screen_time',
    title: b('ဖန်သားပြင်ကြည့်ချိန်ကို သင့်တင့်စွာ စီမံခြင်း', 'Balancing screen time'),
    summary: b('အသက်အရွယ်အလိုက် ဖန်သားပြင်အသုံးပြုမှုနှင့် အစားထိုးလုပ်ဆောင်နိုင်သည့် နည်းလမ်းများ။', 'Age guidance and better alternatives.'),
    objectives: [b('ကလေးများအတွက် ဖန်သားပြင်အသုံးပြုမှု လမ်းညွှန်ချက်များကို သိရှိရန်။', 'Know screen-use guidance.')],
    readingMinutes: 3,
    body: b('ကမ္ဘာ့ကျန်းမာရေးအဖွဲ့၏ လမ်းညွှန်ချက်အရ အသက် ၂ နှစ်အောက်တွင် အထိုင်လုပ်ဆောင်သည့် ဖန်သားပြင်ကြည့်ချိန်ကို ရှောင်ရန်နှင့် အသက် ၂ နှစ်မှ ၄ နှစ်အထိ တစ်နေ့ ၁ နာရီထက် မကျော်စေရန် (ပိုနည်းလေ ပိုကောင်းလေ) အကြံပြုထားသည်။ မိသားစုနှင့် တိုက်ရိုက် ဗီဒီယိုခေါ်ဆိုမှုကို လူကြီးတစ်ဦးက ကလေး ပါဝင်ဆက်သွယ်နိုင်အောင် ကူညီပေးလျှင် သာမန် တစ်ယောက်တည်းကြည့်ရှုမှုနှင့် ကွာခြားသော အပြန်အလှန်ဆက်သွယ်မှု ဖြစ်နိုင်ပါသည်။ ဖန်သားပြင်သုံးမည်ဆိုလျှင် ကလေး၏ အသက်နှင့် ဖွံ့ဖြိုးမှုကို စဉ်းစားပြီး အရည်အသွေးကောင်းသော အကြောင်းအရာကို ရွေးချယ်ကာ အတူကြည့်၊ အတူပြောပါ။ ဖန်သားပြင်အသုံးပြုမှုကြောင့် အိပ်စက်ချိန်၊ ကိုယ်လက်လှုပ်ရှားမှု၊ စာဖတ်ချိန်၊ ကစားချိန်နှင့် မျက်နှာချင်းဆိုင် ဆက်ဆံချိန် မလျော့နည်းစေရန် စီမံပါ။', 'WHO guidance advises avoiding sedentary screen time under age 2 and limiting it to no more than 1 hour a day from ages 2 to 4 (less is better). A live video call with family can be an interactive experience different from solo viewing when an adult helps the child take part. When media is used, consider the child’s age and development, choose high-quality content, and watch and talk together. Plan media use so it does not crowd out sleep, movement, reading, play, or face-to-face interaction.'),
    quiz: [q('အသက် ၂ နှစ်အောက် ကလေးများအတွက် အထိုင်လုပ်ဆောင်သည့် ဖန်သားပြင်ကြည့်ချိန်ကို —', 'For children under 2, sedentary screen time is —', [['ရှောင်ရန် အကြံပြုထားသည်', 'not recommended'], ['များများ ကြည့်စေသင့်သည်', 'encouraged a lot']], 0)],
    takeaway: b('အချိန်ပမာဏတစ်ခုတည်းကို မကြည့်ဘဲ ကလေး၊ အကြောင်းအရာ၊ အတူအသုံးပြုပုံနှင့် ဖန်သားပြင်ကြောင့် လျော့နည်းသွားနိုင်သော အရေးကြီးလုပ်ဆောင်မှုများကို အတူ စဉ်းစားပါ။', 'Look beyond minutes alone: consider the child, the content, co-use, and what media may crowd out.'),
    actionToday: b('ယနေ့ ဖန်သားပြင်ကြည့်ချိန်တစ်ချိန်ကို ပြန်ကြည့်ပြီး ကလေးနှင့် အတူကြည့်ပြောဆိုရန် သို့မဟုတ် ကစားခြင်း၊ စာဖတ်ခြင်း၊ လှုပ်ရှားခြင်းဖြင့် အစားထိုးရန် ရွေးချယ်ပါ။', 'Review one media slot today: co-use and talk about it, or replace it with play, reading, or movement.'),
  }),
  lesson({
    slug: 'big_feelings', category: 'emotional_development',
    title: b('ပြင်းထန်သော ခံစားမှုများ ရှိချိန်တွင် ကူညီပံ့ပိုးခြင်း', 'Helping with big feelings'),
    summary: b('ပြင်းထန်သော ခံစားမှုများ ရှိချိန်တွင် နွေးထွေးစွာ အပြန်အလှန်ဆက်ဆံ၍ ပံ့ပိုးပေးခြင်း။', 'Warm, supportive interactions during strong emotions.'),
    objectives: [b('နွေးထွေး၍ ပံ့ပိုးပေးသော အပြန်အလှန်ဆက်ဆံမှုအကြောင်း သိရှိရန်။', 'Learn about warm, supportive interactions.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nဘေးကင်း၍ တည်ငြိမ်ပြီး နွေးထွေးစွာ ပြုစုစောင့်ရှောက်ပေးသော ဆက်ဆံရေးများက ကလေးများ ခံစားမှုဆိုင်ရာ ကျွမ်းကျင်မှုများကို သင်ယူရာတွင် အထောက်အကူပြုနိုင်ပါသည်။ နွေးထွေးစွာ အာရုံစိုက်ပေးပြီး ကလေးက ဆက်သွယ်ဖော်ပြနေသည့်အရာကို တုံ့ပြန်ပါ။ ဤအပြန်အလှန်ဆက်ဆံမှုများသည် ရင်းနှီးဆက်ဆံရန်နှင့် သင်ယူရန် အခွင့်အလမ်းများသာ ဖြစ်ပြီး ကလေးက ချက်ချင်း ငြိမ်သက်လာမည်ဟု အာမခံခြင်း မဟုတ်ပါ။ ဤသင်ခန်းစာသည် ကလေး မသက်မသာဖြစ်နေသည့် အကြောင်းရင်းကို စစ်ဆေးအကဲဖြတ်ခြင်း မပြုပါ။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nSafe, stable and nurturing relationships can support children as they learn emotional skills. Offer warm attention and respond to what your child is communicating. These interactions are opportunities for connection and learning, not a promise that a child will become calm immediately. This lesson does not assess the cause of a child’s distress.'),
    quiz: [q('ဤသင်ခန်းစာက မည်သည့်အရာကို အားပေးပါသလဲ။', 'What does this lesson encourage?', [['နွေးထွေး၍ ပံ့ပိုးပေးသော အပြန်အလှန်ဆက်ဆံမှု', 'warm, supportive interaction'], ['ကလေးတိုင်းက ချက်ချင်း ငြိမ်သက်လာမည်ဟု မျှော်လင့်ခြင်း', 'expecting every child to become calm immediately']], 0)],
    takeaway: b('ရင်းနှီးဆက်ဆံမှုသည် ပံ့ပိုးမှုကို ပေးနိုင်သော်လည်း ငြိမ်သက်လာမည်ဟု အာမခံခြင်း မဟုတ်ပါ။', 'Connection offers support, not a guaranteed calming result.'),
    actionToday: b('ယနေ့ ကလေးက ဆက်သွယ်ဖော်ပြနေသည့်အရာကို သတိပြုပြီး နွေးထွေးစွာ တုံ့ပြန်ပါ။', 'Today, notice what your child is communicating and respond warmly.'),
  }),
  lesson({
    slug: 'making_friends', category: 'social_skills',
    title: b('သူငယ်ချင်း ဖွဲ့ခြင်း', 'Building social skills'),
    summary: b('မူကြိုအရွယ်ကလေးများသည် ကစားရင်း အလှည့်စောင့်ခြင်းနှင့် အတူတကွ အဆင်ပြေစွာ ကစားခြင်းကို လေ့ကျင့်နိုင်ပါသည်။', 'Preschoolers can practise turn-taking and getting along through play.'),
    objectives: [b('ကစားချိန်တွင် လူမှုကျွမ်းကျင်မှုများကို အားပေးနိုင်သည့် ရိုးရှင်းသော နည်းလမ်းများကို သိရှိရန်။', 'Learn simple ways to encourage social skills during play.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nလူမှုကျွမ်းကျင်မှုများသည် အချိန်ကြာလာသည်နှင့်အမျှ ဖွံ့ဖြိုးလာပါသည်။ ကစားချိန်တွင် အလှည့်စောင့်ခြင်း၊ လိုချင်သည့်အရာကို စကားဖြင့် ပြောခြင်းနှင့် ကလေးနှစ်ယောက်က ပစ္စည်းတစ်ခုတည်းကို လိုချင်သည့်အခါ ငြိမ်းချမ်းသော ဖြေရှင်းနည်းကို စမ်းသုံးခြင်းတို့ကို နမူနာပြ၍ အားပေးပါ။ ကလေးများကို လေ့ကျင့်ရန် အချိန်ပေးပါ။ တစ်ကြိမ်တည်း ကစားရာတွင် အခက်အခဲရှိခြင်းဖြင့် လူမှုရေး သို့မဟုတ် ဖွံ့ဖြိုးမှုဆိုင်ရာ အခြေအနေတစ်ခုကို ရောဂါဖော်ထုတ်၍ မရပါ။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nSocial skills develop over time. During play, show and encourage simple steps such as taking turns, using words, and trying a peaceful solution when two children want the same thing. Give children time to practise. One difficult play moment does not diagnose a social or developmental condition.'),
    quiz: [q('ကလေးနှစ်ယောက်က ကစားစရာတစ်ခုတည်းကို လိုချင်သည့်အခါ စောင့်ရှောက်သူက မည်သို့ ကူညီနိုင်ပါသလဲ။', 'When two children want the same toy, what can a caregiver try?', [['အလှည့်ကျ ကစားရန် သို့မဟုတ် အခြားကစားနည်း ရွေးရန် ကူညီခြင်း', 'help them take turns or choose another activity'], ['လမ်းညွှန်မှုမပေးဘဲ ချက်ချင်း ဝေမျှရန် တောင်းဆိုခြင်း', 'demand immediate sharing without guidance']], 0)],
    takeaway: b('အလှည့်စောင့်ခြင်းကို နမူနာပြ၍ အားပေးပါ။', 'Model and encourage turn-taking.'),
    actionToday: b('ယနေ့ အလှည့်ကျ ကစားနည်းတစ်ခု ကစားပါ။', 'Play one turn-taking game today.'),
  }),
  lesson({
    slug: 'early_math', category: 'early_mathematics',
    title: b('အစောပိုင်း သင်္ချာ', 'Everyday early math'),
    summary: b('နေ့စဉ်ဘဝထဲ ရေတွက်ခြင်း၊ ပုံသဏ္ဌာန်၊ နှိုင်းယှဉ်ခြင်း။', 'Counting, shapes, and comparing in daily life.'),
    objectives: [b('နေ့စဉ်ဘဝ သင်္ချာ နည်းလမ်းများ သိရှိရန်။', 'Learn everyday math moments.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nသင်္ချာသည် စာအုပ်ထဲသာ မဟုတ်ပါ။ နေ့စဉ်တွေ့ရသော အရာများကို အတူရေတွက်ခြင်း၊ ပုံသဏ္ဌာန်များကို ရှာဖွေခြင်း၊ “ပိုကြီး/ပိုငယ်” ဟု နှိုင်းယှဉ်ခြင်းဖြင့် အစောပိုင်း သင်္ချာအယူအဆများကို အတူလေ့ကျင့်နိုင်ပါသည်။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nMath is not only in books. Count everyday things together, look for shapes, and compare “bigger/smaller” to practise early math ideas.'),
    quiz: [q('အစောပိုင်း သင်္ချာလေ့ကျင့်မှုကို ပျော်ရွှင်ဖွယ် ဖြစ်စေရန် ဘယ်လိုလုပ်နိုင်ပါသလဲ။', 'How can you keep early math playful?', [['အတူရေတွက်ပြီး ကလေး၏ စိတ်ဝင်စားမှုအတိုင်း လိုက်ပါ။', 'Count together and follow the child’s interest.'], ['အကြိမ်တိုင်း အဖြေမှန်ရရန် ဖိအားပေးပါ။', 'Insist on a correct answer every time.']], 0)],
    takeaway: b('ရေတွက်ခြင်းကို နေ့စဉ်ဘဝထဲ ထည့်ပါ။', 'Weave counting into your day.'),
    actionToday: b('ကလေး စိတ်ဝင်စားပါက ယနေ့ ပုံအနည်းငယ်ကို အတူရေတွက်ကြည့်ပါ။ ကလေးက ပါဝင်လိုလျှင် ပါဝင်နိုင်သလို ကြည့်နေရုံလည်း ရပါသည်။ စိတ်မဝင်စားတော့လျှင် ရပ်ပါ။', 'If your child is interested, count a few pictures together today. Your child can join in or simply watch; stop when they lose interest.'),
  }),
  lesson({
    slug: 'creativity', category: 'creativity',
    title: b('တီထွင်ဖန်တီးမှု အားပေးခြင်း', 'Nurturing creativity'),
    summary: b('ရိုးရှင်းသော ပစ္စည်းများ ပေး၍ ကလေးကို ဖန်တီးမှုရှိသော ကစားနည်းကို ဦးဆောင်စေပါ။', 'Offer simple materials and let your child lead creative play.'),
    objectives: [b('ကလေးဦးဆောင်သော ဖန်တီးမှုရှိသည့် ကစားနည်းကို အားပေးပုံ သိရှိရန်။', 'Learn how to support child-led creative play.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nအဖြေတစ်မျိုးတည်း မသတ်မှတ်ထားသော ကလေးဦးဆောင်သည့် ကစားနည်းများက ဖန်တီးမှုနှင့် ပြဿနာဖြေရှင်းမှုကို လေ့ကျင့်ရန် အခွင့်အလမ်းများ ပေးနိုင်ပါသည်။ ရိုးရှင်းပြီး အသက်အရွယ်နှင့် သင့်လျော်သော ပစ္စည်းများ ပေး၍ ဘာလုပ်မည်၊ မည်သို့လုပ်မည်ကို ကလေးရွေးချယ်စေပါ။ ကလေး၏ စိတ်ကူးများကို သတိပြုပြီး တစ်ပုံစံတည်းသော အပြီးသတ်ရလဒ်ကို မတောင်းဆိုဘဲ အတူပါဝင်ပါ။ ဤသင်ခန်းစာသည် ဖန်တီးနိုင်စွမ်းကို တိုင်းတာခြင်း သို့မဟုတ် အနာဂတ်စွမ်းရည်ကို ခန့်မှန်းခြင်း မပြုပါ။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nOpen-ended, child-led play can offer opportunities for creativity and problem-solving. Offer simple, age-appropriate materials and let your child choose what and how to make. Notice their ideas and join without requiring one exact finished result. This lesson does not measure creativity or predict ability.'),
    quiz: [q('ဖန်တီးမှုရှိသော ကစားနည်းကို ကလေးဦးဆောင်စေရန် မည်သည့်နည်းက သင့်လျော်ပါသလဲ။', 'Which approach keeps creative play child-led?', [['ဘာလုပ်မည်နှင့် မည်သို့လုပ်မည်ကို ကလေးရွေးချယ်စေခြင်း', 'let the child choose what and how to make'], ['သတ်မှတ်ထားသော ရလဒ်တစ်ခုကို တိတိကျကျ ကူးလုပ်ရန် တောင်းဆိုခြင်း', 'require an exact copy of one result']], 0)],
    takeaway: b('စိတ်ကူးကို ကလေးဦးဆောင်စေပါ။', 'Let your child lead the idea.'),
    actionToday: b('စာရွက်နှင့် အသက်အရွယ်နှင့် သင့်လျော်သော ပုံဆွဲကိရိယာတစ်ခု ပေး၍ ဘာလုပ်မည်ကို ကလေးဆုံးဖြတ်စေပါ။', 'Offer paper and one age-appropriate drawing tool, and let your child decide what to make.'),
  }),
  lesson({
    slug: 'problem_solving_parenting', category: 'problem_solving',
    title: b('ပြဿနာ ဖြေရှင်းမှု အားပေးခြင်း', 'Coaching problem solving'),
    summary: b('အဖြေမပေးဘဲ တွေးခေါ်ရန် ကူညီခြင်း။', 'Help children think it through instead of giving answers.'),
    objectives: [b('ပြဿနာဖြေရှင်းမှု အားပေးနည်း သိရှိရန်။', 'Learn to coach problem solving.')],
    readingMinutes: 3,
    body: b('ကလေး အခက်အခဲ ကြုံရင် ချက်ချင်း အဖြေ မပေးပါနှင့်။ “ဘယ်လို လုပ်ကြည့်မလဲ” ဟု မေးပါ။ ကြိုးစားခွင့် ပေး၍ မှားလည်း သင်ယူမှုဟု မှတ်ယူပါ။ ဤသည်က စိတ်ရှည်မှုနှင့် ယုံကြည်မှုကို တည်ဆောက်သည်။', 'When a child is stuck, don’t rush the answer. Ask “what could you try?” Let them attempt; mistakes are learning. This builds patience and confidence.'),
    quiz: [q('ကလေး အခက်အခဲ ကြုံရင် —', 'When stuck, better to —', [['ဦးဆောင်မေးခွန်း မေး', 'ask a guiding question'], ['အဖြေ ချက်ချင်းပေး', 'give the answer at once']], 0)],
    takeaway: b('မှားယွင်းမှုတိုင်းသည် သင်ယူမှုဖြစ်သည်။', 'Every mistake is learning.'),
    actionToday: b('ယနေ့ ဦးဆောင်မေးခွန်းတစ်ခုဖြင့် ကူညီပါ။', 'Help with one guiding question today.'),
  }),
  lesson({
    slug: 'special_needs_awareness', category: 'special_needs_awareness',
    title: b('အထူးလိုအပ်ချက် သိရှိနားလည်မှု', 'Special-needs awareness'),
    summary: b('ကွဲပြားမှုကို လေးစား၍ အားသာချက်အခြေခံ ချဉ်းကပ်ခြင်း။', 'Respecting difference with a strengths-based view.'),
    objectives: [b('အားသာချက်အခြေခံ သဘောထား သိရှိရန်။', 'Understand a strengths-based approach.')],
    readingMinutes: 4,
    body: b('ကလေးတိုင်းတွင် အားသာချက်များ ရှိသည်။ အထူးလိုအပ်ချက်ရှိသော ကလေးများကို “ချို့ယွင်း” ဟု မမြင်ဘဲ ကွဲပြားစွာ သင်ယူ/ကြီးထွားသူများအဖြစ် မြင်ပါ။ ဤအက်ပ်သည် ရောဂါ မဖော်ထုတ်ပါ — စိုးရိမ်ပါက ကျွမ်းကျင်ပညာရှင်နှင့် တိုင်ပင်ရန် လမ်းညွှန်ပေးသည်။ စောစီးစွာ ပံ့ပိုးမှုက များစွာ ကူညီနိုင်သည်။', 'Every child has strengths. See children with special needs not as “broken” but as learning and growing differently. This app does not diagnose — if concerned, it guides you to a professional. Early support can help a lot.'),
    quiz: [q('ဤအက်ပ်သည် —', 'This app —', [['ရောဂါ မဖော်ထုတ်ပါ', 'does not diagnose'], ['ရောဂါ ဖော်ထုတ်ပေးသည်', 'gives a diagnosis']], 0)],
    takeaway: b('ကွဲပြားမှုကို လေးစားပါ — အားသာချက်ကို မြင်ပါ။', 'Respect difference; see strengths.'),
    actionToday: b('ယနေ့ ကလေး၏ အားသာချက်တစ်ခုကို ချီးမွမ်းပါ။', 'Praise one of your child’s strengths today.'),
  }),
  lesson({
    slug: 'prepare_preschool', category: 'preparing_for_preschool',
    title: b('မူကြိုအတွက် ပြင်ဆင်ခြင်း', 'Getting ready for preschool'),
    summary: b('မူကြိုကျောင်းကို ရင်းနှီးလာစေရန် ကူညီပြီး ဘေးကင်းသော ကိုယ်တိုင်လုပ်ဆောင်မှု တစ်ဆင့်ကို လေ့ကျင့်ပါ။', 'Help preschool feel familiar and practise one safe self-help step.'),
    objectives: [b('နေရာအသစ်အတွက် ပြင်ဆင်ပေးပြီး ကိုယ်တိုင်လုပ်ဆောင်နိုင်မှုကို အားပေးသည့် ရိုးရှင်းသော နည်းလမ်းများကို သိရှိရန်။', 'Learn simple ways to prepare for a new place and support independence.')],
    readingMinutes: 3,
    body: b('AI စစ်ဆေးမှု အသိပေးချက် — ဤအကြောင်းအရာကို AI ဖြင့် စစ်ဆေးထားသော်လည်း ဆေးဘက်ပညာရှင် သို့မဟုတ် မြန်မာဘာသာကို မိခင်ဘာသာစကားအဖြစ် အသုံးပြုသော စာတည်းဖြတ်သူက အတည်ပြုထားခြင်း မရှိပါ။ အထွေထွေပညာပေးအတွက်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ အကြံပြုချက်၊ ကလေးဖွံ့ဖြိုးမှု စစ်ဆေးချက် သို့မဟုတ် ရောဂါဖော်ထုတ်ချက် မဟုတ်ပါ။\n\nမူကြိုကျောင်းအတွက် အသင့်ဖြစ်မှုတွင် အပိုင်းတစ်ခုထက်မက ပါဝင်ပါသည်။ နေရာအသစ်တွင် ဖြစ်နိုင်သည့်အရာများအကြောင်း ပုံပြင်ဖတ်ခြင်း သို့မဟုတ် ဟန်ဆောင်ကစားခြင်းဖြင့် ကလေးကို ရင်းနှီးလာစေရန် ကူညီပါ။ အဝတ်အစား ဝတ်ရာတွင် ဘေးကင်းပြီး အသက်အရွယ်နှင့် သင့်လျော်သော ကိုယ်တိုင်လုပ်ဆောင်မှုအခွင့်အလမ်းများ ပေးပါ။ ကလေးတစ်ဦးနှင့်တစ်ဦး ကွာခြားပြီး ဤသင်ခန်းစာသည် မူကြိုအသင့်ဖြစ်မှု စစ်ဆေးချက် မဟုတ်ပါ။ ဖွံ့ဖြိုးမှု သို့မဟုတ် မူကြိုစတင်ခြင်းနှင့်ပတ်သက်၍ စိုးရိမ်ပါက ဆရာ/ဆရာမ သို့မဟုတ် သက်ဆိုင်ရာ ကျန်းမာရေးပညာရှင်နှင့် ဆွေးနွေးပါ။', 'AI review notice — This content was reviewed by AI but has not been approved by a clinician or native Myanmar-language editor. It is for general education only and is not medical advice, developmental screening, or diagnosis.\n\nPreschool readiness has more than one part. Help your child get familiar with a new place by reading a story or role-playing what may happen. Offer safe, age-appropriate chances to help with dressing. Children vary, and this lesson is not a readiness test. If you are concerned about development or starting preschool, talk with the teacher or a qualified health professional.'),
    quiz: [q('ကလေးကို မူကြိုကျောင်းအတွက် ပြင်ဆင်ရာတွင် မည်သည့်အရာက အထောက်အကူပြုနိုင်ပါသလဲ။', 'Which practice can help a child prepare for preschool?', [['နေရာအသစ်အကြောင်း ဟန်ဆောင်ကစားပြီး ဘေးကင်းသော ကိုယ်တိုင်လုပ်ဆောင်မှုတစ်ဆင့်ကို လေ့ကျင့်ခြင်း', 'role-play a new place and practise a safe self-help step'], ['မစတင်မီ အက္ခရာအားလုံးကို သိထားရန် တောင်းဆိုခြင်း', 'require knowing every letter before starting']], 0)],
    takeaway: b('နေရာအသစ်အတွက် လုပ်ရိုးလုပ်စဉ်တစ်ခုနှင့် ဘေးကင်းသော ကိုယ်တိုင်လုပ်ဆောင်မှုတစ်ဆင့်ကို လေ့ကျင့်ပါ။', 'Practise a new-place routine and one safe self-help step.'),
    actionToday: b('လွယ်ကူသော အဝတ်အစားဝတ်ခြင်း အဆင့်တစ်ဆင့်ကို လေ့ကျင့်ပြီး လိုအပ်ပါက ကူညီပေးပါ။', 'Practise one easy dressing step, offering help if needed.'),
  }),
  lesson({
    slug: 'prepare_school', category: 'preparing_for_school',
    title: b('ကျောင်းအတွက် ပြင်ဆင်ခြင်း', 'Getting ready for school'),
    summary: b('အာရုံစိုက်မှု၊ လွတ်လပ်မှုနှင့် စာဖတ်စိတ်ဝင်စားမှု တည်ဆောက်ခြင်း။', 'Build attention, independence, and love of reading.'),
    objectives: [b('ကျောင်းအသင့်ဖြစ်မှု တည်ဆောက်နည်း သိရှိရန်။', 'Learn to build school readiness.')],
    readingMinutes: 3,
    body: b('ကျောင်းအတွက် ကလေးကို အာရုံစိုက်မှု၊ လွတ်လပ်စွာ လုပ်ဆောင်နိုင်မှုနှင့် စာဖတ်စိတ်ဝင်စားမှုဖြင့် ပြင်ဆင်ပါ။ တသမတ်တည်း လုပ်ရိုးလုပ်စဉ်နှင့် အိပ်ရေးဝမှုက သင်ယူမှုကို ကူညီသည်။ ကျောင်းအကြောင်း ကြောက်စိတ်မဖြစ်စေဘဲ ရင်းနှီးစေပါ။', 'Prepare with attention, independence, and a love of reading. Steady routines and enough sleep help learning. Make school feel familiar, not frightening.'),
    quiz: [q('ကျောင်းတက်ရန် အသင့်ဖြစ်စေဖို့ ကူညီပေးသည်မှာ —', 'What helps readiness —', [['အိပ်ရေးဝခြင်းနှင့် တည်ငြိမ်သော နေ့စဉ်လုပ်ရိုးလုပ်စဉ်', 'sleep and steady routines'], ['ဖုန်းနှင့် ရုပ်မြင်သံကြား များများကြည့်ခြင်း', 'lots of screens']], 0)],
    takeaway: b('အာရုံစိုက်မှုနှင့် လွတ်လပ်မှုက ကျောင်းကို ကူညီသည်။', 'Attention and independence help school.'),
    actionToday: b('ယနေ့ ကလေးကို လုပ်ငန်းတစ်ခု အစအဆုံး တစ်ယောက်တည်း လုပ်စေပါ။', 'Let your child finish one task alone today.'),
  }),
  lesson({
    slug: 'doctor_visits', category: 'doctor_visits',
    title: b('ဆရာဝန်ပြသခြင်း ပြင်ဆင်နည်း', 'Making the most of doctor visits'),
    summary: b('မေးခွန်းများ ပြင်ဆင်၍ စိုးရိမ်စရာများ မှတ်သားခြင်း။', 'Prepare questions and note concerns.'),
    objectives: [b('ဆရာဝန်ပြသချိန်ကို ထိရောက်စေရန်။', 'Make visits effective.')],
    readingMinutes: 3,
    body: b('ဆရာဝန်မပြမီ ကလေး၏ အစား၊ အိပ်၊ ဖွံ့ဖြိုးမှုနှင့် စိုးရိမ်စရာများကို မှတ်သားထားပါ။ မေးလိုသည့် မေးခွန်း ၂–၃ ခုကို ကြိုရေးထားပါ။ ကာကွယ်ဆေး မှတ်တမ်းကို ယူသွားပါ။ ဤအက်ပ်၏ “ဆရာဝန်ပြသ ပြင်ဆင်ချက်” ကို ထုတ်ယူ၍ သွားနိုင်သည်။', 'Before a visit, note your child’s eating, sleep, development, and concerns. Write 2–3 questions in advance. Bring the vaccination record. You can export this app’s doctor-visit prep to take along.'),
    quiz: [q('ဆရာဝန်မပြမီ ကောင်းသည်မှာ —', 'Before a visit, it helps to —', [['မေးခွန်းများ ကြိုရေးထား', 'write questions ahead'], ['ဘာမှ မပြင်ဆင်', 'prepare nothing']], 0)],
    takeaway: b('ကြိုတင်ပြင်ဆင်မှုက ပြသချိန်ကို တန်ဖိုးရှိစေသည်။', 'Preparation makes visits count.'),
    actionToday: b('ယနေ့ ဆရာဝန်ကို မေးလိုသည့် မေးခွန်းတစ်ခု ရေးထားပါ။', 'Write one question for the doctor today.'),
  }),
  lesson({
    slug: 'parent_wellbeing', category: 'parent_mental_health',
    title: b('မိဘ၏ စိတ်ကျန်းမာရေး', 'Caring for your own wellbeing'),
    summary: b('မိဘ ကိုယ်တိုင် ဂရုစိုက်ခြင်းသည် ကလေးကိုပါ အကျိုးပြုသည်။', 'Caring for yourself helps your child too.'),
    objectives: [b('မိဘ စိတ်ကျန်းမာရေး၏ အရေးပါမှု သိရှိရန်။', 'Value your own wellbeing.')],
    readingMinutes: 3,
    body: b('မိဘဖြစ်ခြင်းသည် ပင်ပန်းနိုင်သည်။ သင်ကိုယ်တိုင် အနားယူ၊ အထောက်အပံ့ရှာ၊ ခံစားမှုကို မျှဝေခြင်းက သင့်ကလေးအတွက်ပါ အကျိုးရှိသည်။ အမြဲ ဝမ်းနည်း/စိုးရိမ်နေရ၊ နေ့စဉ်ဘဝ ထိခိုက်နေပါက ကူညီမှု ရှာဖွေရန် အားနည်းချက် မဟုတ်ပါ — ကျန်းမာရေးပညာရှင် သို့မဟုတ် ယုံကြည်ရသူနှင့် ပြောဆိုပါ။', 'Parenting can be exhausting. Rest, seeking support, and sharing your feelings help your child too. If you feel persistently low or anxious and daily life is affected, reaching out is a strength — talk to a health professional or someone you trust.'),
    quiz: [q('မိဘ ကိုယ်တိုင် ဂရုစိုက်ခြင်းသည် —', 'Caring for yourself is —', [['ကလေးအတွက်ပါ အကျိုးရှိ', 'good for your child too'], ['တစ်ကိုယ်ကောင်းဆန်ခြင်း', 'selfish']], 0)],
    takeaway: b('သင် ကောင်းမွန်မှသာ ကလေးကို ကောင်းစွာ ဂရုစိုက်နိုင်သည်။', 'You care best when you’re cared for.'),
    actionToday: b('ယနေ့ သင့်အတွက် ၁၀ မိနစ် အနားယူပါ။', 'Take 10 minutes for yourself today.'),
  }),
  lesson({
    slug: 'language_rich_home', category: 'language_development',
    title: b('ဘာသာစကား ကြွယ်ဝသော အိမ်', 'A language-rich home'),
    summary: b('သီချင်း၊ ပုံပြင်နှင့် စကားပြောဖြင့် ဘာသာစကား တည်ဆောက်ခြင်း။', 'Build language with songs, stories, and talk.'),
    objectives: [b('ဘာသာစကား ကြွယ်ဝစေမည့် အလေ့အထ သိရှိရန်။', 'Learn language-building habits.')],
    readingMinutes: 3,
    body: b('သီချင်းဆိုခြင်း၊ ပုံပြင်ပြောခြင်း၊ နေ့စဉ်လုပ်ဆောင်ချက်များကို စကားဖြင့် ရှင်းပြခြင်းက ဘာသာစကားကို ကြွယ်ဝစေသည်။ ဘာသာစကား ၂ မျိုး သင်ခြင်းသည် ကလေးကို မရှုပ်ထွေးစေပါ — အားသာချက် တစ်ခုပင်ဖြစ်သည်။', 'Singing, storytelling, and narrating daily actions enrich language. Two languages do not confuse a child — it is an asset.'),
    quiz: [q('ဘာသာစကား ၂ မျိုး သင်ခြင်းသည် —', 'Raising bilingual is —', [['အားသာချက်တစ်ခု', 'an asset'], ['ရှုပ်ထွေးစေ', 'confusing']], 0)],
    takeaway: b('စကားပြော၊ သီချင်းဆို၊ ပုံပြင်ပြော — နေ့စဉ်လုပ်ပါ။', 'Talk, sing, tell stories — daily.'),
    actionToday: b('ယနေ့ ကလေးနှင့်အတူ သီချင်းတစ်ပုဒ် ဆိုပါ။', 'Sing one song with your child today.'),
  }),
];
