// Parent Learning Academy — short lessons. Starter curriculum covering every
// category; the CMS extends toward the full target. General parenting guidance,
// clinical_review until approved. Simple language, no medical jargon.
import { lesson, type SeedItem } from '../types';

const b = (mm: string, en: string) => ({ mm, en });
const q = (question: string, qEn: string, opts: [string, string][], answerIndex: number) => ({
  q: b(question, qEn),
  options: opts.map(([mm, en]) => b(mm, en)),
  answerIndex,
});

export const LESSONS: SeedItem[] = [
  lesson({
    slug: 'what_is_development', category: 'understanding_development',
    title: b('ဖွံ့ဖြိုးမှုဆိုတာ ဘာလဲ', 'What is child development?'),
    summary: b('ကလေးများ မတူညီသော နယ်ပယ်များတွင် မိမိအရှိန်ဖြင့် ကြီးထွားပုံ။', 'How children grow across areas at their own pace.'),
    objectives: [b('ဖွံ့ဖြိုးမှု နယ်ပယ်များကို သိရှိရန်။', 'Know the areas of development.'), b('“ပုံမှန်” အကွာအဝေး ကျယ်ပြန့်ကြောင်း နားလည်ရန်။', 'Understand the wide normal range.')],
    readingMinutes: 3,
    body: b('ကလေးဖွံ့ဖြိုးမှုဆိုသည်မှာ ကိုယ်လက်လှုပ်ရှားမှု၊ ဘာသာစကား၊ စဉ်းစားတွေးခေါ်မှု၊ စိတ်ခံစားမှုနှင့် လူမှုဆက်ဆံရေးတို့ တဖြည်းဖြည်း တိုးတက်လာခြင်း ဖြစ်သည်။ ကလေးတစ်ဦးနှင့်တစ်ဦး ဖွံ့ဖြိုးသည့်အချိန်နှင့် အရှိန် ကွာခြားနိုင်သည်။ ဖွံ့ဖြိုးမှုအဆင့်များသည် ယေဘုယျလမ်းညွှန်ချက်များသာဖြစ်ပြီး အောင်မြင်၊ မအောင်မြင် ဆုံးဖြတ်သည့် စာမေးပွဲ မဟုတ်ပါ။', 'Child development is steady growth in movement, language, thinking, feelings, and social skills. Every child grows at their own pace. Milestones are guides, not a strict test.'),
    quiz: [q('မှတ်တိုင်များသည် —', 'Milestones are —', [['တင်းကျပ်သော စာမေးပွဲ', 'a strict test'], ['လမ်းညွှန်များ', 'general guides']], 1)],
    takeaway: b('ကလေး၏ ကိုယ်ပိုင်အရှိန်ကို လေးစားပါ။', 'Respect your child’s own pace.'),
    actionToday: b('ယနေ့ ကလေးနှင့် ၁၀ မိနစ် အာရုံစိုက်၍ ကစားပါ။', 'Spend 10 focused minutes playing today.'),
  }),
  lesson({
    slug: 'power_of_play', category: 'learning_through_play',
    title: b('ကစားခြင်း၏ အကျိုးကျေးဇူးများ', 'The power of play'),
    summary: b('ကစားခြင်းသည် ကလေးငယ်များ သင်ယူရာတွင် အရေးပါသော နည်းလမ်းတစ်ခု ဖြစ်သည်။', 'Play is an important way young children learn.'),
    objectives: [b('ကစားခြင်းက ကလေးဖွံ့ဖြိုးမှုကို မည်သို့ အထောက်အကူပြုသည်ကို သိရှိရန်။', 'Know the benefits of play.')],
    readingMinutes: 3,
    body: b('ကစားခြင်းသည် ကလေးငယ်များအတွက် အရေးပါသော သင်ယူနည်းတစ်ခု ဖြစ်သည်။ ကစားနေစဉ် စဉ်းစားတွေးခေါ်နိုင်စွမ်း၊ ဘာသာစကား၊ ကိုယ်လက်လှုပ်ရှားမှုနှင့် လူမှုဆက်ဆံရေးတို့ တဖြည်းဖြည်း ဖွံ့ဖြိုးလာနိုင်သည်။ ဈေးကြီးသော ကစားစရာများ မလိုအပ်ပါ။ မိဘ၏ အာရုံစိုက်ပေးမှုနှင့် ဘေးကင်းသော အိမ်သုံးပစ္စည်းများက ကစားခြင်းနှင့် သင်ယူမှုကို အထောက်အကူပြုနိုင်ပါသည်။', 'Play is an important way young children learn. Through play, thinking, language, movement, and relationships can develop gradually. Expensive toys are not needed; caregiver attention and safe household objects can support play and learning.'),
    quiz: [q('ကလေးနှင့် ကစားရန် ဈေးကြီးသော ကစားစရာများ —', 'Expensive toys are —', [['မဖြစ်မနေ လိုအပ်သည်', 'essential'], ['မလိုအပ်ပါ', 'not needed']], 1)],
    takeaway: b('မိဘနှင့်အတူ ကစားချိန်သည် ကလေးအတွက် အဖိုးတန်သော သင်ယူချိန် ဖြစ်သည်။', 'Playing with you is valuable learning time for your child.'),
    actionToday: b('ယနေ့ အိမ်တွင်ရှိသော ဘေးကင်းသည့် ပစ္စည်းတစ်ခုကို အသုံးပြုပြီး ကလေးနှင့်အတူ ကစားပါ။', 'Today, use one safe household object to play with your child.'),
  }),
  lesson({
    slug: 'talk_more', category: 'speech_development',
    title: b('ကလေးနှင့် နေ့စဉ် စကားပြောပါ', 'Talk more, every day'),
    summary: b('နေ့စဉ် အပြန်အလှန် စကားပြောခြင်းက ကလေး၏ ဘာသာစကားဖွံ့ဖြိုးမှုကို အထောက်အကူပြုသည်။', 'Everyday talk fuels speech development.'),
    objectives: [b('ကလေး၏ ဘာသာစကားဖွံ့ဖြိုးမှုကို အားပေးနိုင်သည့် နည်းလမ်းများကို သိရှိရန်။', 'Learn ways to boost speech.')],
    readingMinutes: 3,
    body: b('နေ့စဉ်လုပ်ဆောင်နေသည့် အရာများကို ကလေးအား စကားဖြင့် ရှင်းပြပါ။ ကလေးပြောသည့် စကားတိုကို စကားလုံးအနည်းငယ် ထပ်ဖြည့်ပြီး ပြန်ပြောပေးပါ။ မျက်နှာချင်းဆိုင် အပြန်အလှန် စကားပြောခြင်းသည် ဖုန်း သို့မဟုတ် ရုပ်မြင်သံကြား ကြည့်ခြင်းထက် ဘာသာစကားဖွံ့ဖြိုးမှုကို ပိုမို အထောက်အကူပြုသည်။', 'Narrate daily actions. Expand on what your child says. Face-to-face talk is far more effective than screens.'),
    quiz: [q('ကလေး၏ ဘာသာစကားဖွံ့ဖြိုးမှုအတွက် ပိုမိုအကျိုးရှိသည်မှာ —', 'Best for speech —', [['မျက်နှာချင်းဆိုင် အပြန်အလှန် စကားပြောခြင်း', 'face-to-face talk'], ['ဖုန်း သို့မဟုတ် ရုပ်မြင်သံကြား ကြည့်ခြင်း', 'screen time']], 0)],
    takeaway: b('မိဘ၏အသံနှင့် အပြန်အလှန်ပြောဆိုမှုသည် ကလေးအတွက် အဖိုးတန်သော သင်ယူမှုဖြစ်သည်။', 'Your voice is the best teacher.'),
    actionToday: b('ကလေးနှင့် စကားပြောစဉ် ၃ ကြိမ် အချိန်ပေး၍ စောင့်ဆိုင်းပါ။', 'Pause and wait three times in a conversation.'),
  }),
  lesson({
    slug: 'reading_together', category: 'reading',
    title: b('အတူတူ စာဖတ်ခြင်း', 'Reading together'),
    summary: b('နေ့စဉ် ရုပ်ပုံစာအုပ်ဖတ်ခြင်း၏ တန်ဖိုး။', 'The value of daily shared reading.'),
    objectives: [b('စာဖတ်ချိန်ကို ပျော်ရွှင်ဖွယ် ဖြစ်စေရန်။', 'Make reading time joyful.')],
    readingMinutes: 3,
    body: b('နေ့စဉ် ရုပ်ပုံစာအုပ် အတူဖတ်ခြင်းသည် ဝေါဟာရ၊ စိတ်ကူးဉာဏ်နှင့် ချစ်ခင်မှုကို ကြီးထွားစေသည်။ စာအုပ်အသစ်များစွာထက် အနှစ်သက်ဆုံး စာအုပ်အနည်းငယ်ကို ထပ်ခါဖတ်ခြင်းက ပို၍ အကျိုးရှိသည်။', 'Daily shared picture-book reading grows vocabulary, imagination, and closeness. Re-reading a few favorites beats many new books.'),
    quiz: [q('စာဖတ်ခြင်းအတွက် ကောင်းသည်မှာ —', 'For reading, better to —', [['အနှစ်သက်ဆုံးကို ထပ်ခါဖတ်', 're-read favorites'], ['အသစ်များစွာ ဝယ်', 'buy many new books']], 0)],
    takeaway: b('တစ်နေ့ စာအုပ်တစ်အုပ် — အလေ့အထ ကောင်းတစ်ခု။', 'A book a day — a great habit.'),
    actionToday: b('ယနေ့ည အိပ်ရာမဝင်မီ ပုံပြင်တစ်ပုဒ် ဖတ်ပါ။', 'Read one story before bed tonight.'),
  }),
  lesson({
    slug: 'gentle_discipline', category: 'positive_parenting',
    title: b('နူးညံ့သော စည်းကမ်း', 'Positive, gentle discipline'),
    summary: b('ပြစ်ဒဏ်မဟုတ်ဘဲ လမ်းညွှန်ခြင်းဖြင့် အပြုအမူ သင်ကြားခြင်း။', 'Guiding behavior with connection, not punishment.'),
    objectives: [b('အပြုသဘော စည်းကမ်းနည်းများ သိရှိရန်။', 'Learn positive discipline tools.')],
    readingMinutes: 4,
    body: b('ကလေးများသည် ဆက်ဆံရေးမှတစ်ဆင့် အကောင်းဆုံး သင်ယူကြသည်။ ရိုက်ခြင်း/ဟစ်အော်ခြင်းအစား ရှင်းလင်းသော နယ်နိမိတ်များ၊ တသမတ်တည်း လုပ်ရိုးလုပ်စဉ်နှင့် ကောင်းသောအပြုအမူကို ချီးမွမ်းခြင်းက ပို၍ ထိရောက်သည်။ သင် တည်ငြိမ်စွာ ရှိနေခြင်းက ကလေးကို ငြိမ်သက်ရန် သင်ပေးသည်။', 'Children learn best through relationship. Instead of hitting or yelling, clear limits, steady routines, and praising good behavior work better. Your calm teaches their calm.'),
    quiz: [q('အပြုသဘော စည်းကမ်းတွင် အဓိကမှာ —', 'Positive discipline centers on —', [['ပြစ်ဒဏ်', 'punishment'], ['ဆက်ဆံရေးနှင့် လမ်းညွှန်မှု', 'connection and guidance']], 1)],
    takeaway: b('တည်ငြိမ်မှုနှင့် တသမတ်တည်းရှိမှုက အဓိကဖြစ်သည်။', 'Calm and consistency matter most.'),
    actionToday: b('ယနေ့ ကလေး၏ ကောင်းသောအပြုအမူ တစ်ခုကို တိကျစွာ ချီးမွမ်းပါ။', 'Praise one specific good behavior today.'),
  }),
  lesson({
    slug: 'balanced_meals', category: 'nutrition',
    title: b('မျှတသော အစားအစာ', 'Balanced meals for little ones'),
    summary: b('ကလေးများအတွက် ကျန်းမာသော အစားအသောက် အခြေခံ။', 'Healthy eating basics for young children.'),
    objectives: [b('မျှတသော အစားအစာ ပုံစံ သိရှိရန်။', 'Know what a balanced plate looks like.')],
    readingMinutes: 3,
    body: b('ကလေးများအတွက် အသီးအနှံ၊ အသီးအရွက်၊ ကောက်နှံ၊ ပရိုတင်းနှင့် နို့ထွက်ပစ္စည်းများ မျှတစွာ လိုအပ်သည်။ ဆား/သကြား များများ ရှောင်ပါ။ စားခြင်းကို ဖိအားမပေးဘဲ ပျော်ရွှင်ဖွယ် ဖြစ်စေပါ။ အသစ်တစ်ခုကို လက်ခံရန် အကြိမ်များစွာ လိုနိုင်သည်။', 'Children need a balance of fruit, vegetables, grains, protein, and dairy. Limit salt and sugar. Keep meals pressure-free and pleasant. New foods often take many tries to accept.'),
    quiz: [q('အစားအစာ အသစ်ကို ကလေး ငြင်းရင် —', 'If a child refuses a new food —', [['ထပ်ခါ တင်ပြပါ', 'keep offering gently'], ['ထိုအစားအစာ ရပ်ပါ', 'stop that food forever']], 0)],
    takeaway: b('စားခြင်းကို တိုက်ပွဲ မဖြစ်စေပါနှင့်။', 'Don’t make meals a battle.'),
    actionToday: b('ယနေ့ အစားအစာ အရောင် ၃ မျိုး ပန်းကန်ထဲ ထည့်ပါ။', 'Put three food colors on the plate today.'),
  }),
  lesson({
    slug: 'healthy_sleep', category: 'sleep',
    title: b('ကျန်းမာသော အိပ်စက်မှု', 'Healthy sleep habits'),
    summary: b('တသမတ်တည်း အိပ်ချိန်နှင့် ဘေးကင်းသော အိပ်ရာ။', 'Consistent bedtimes and safe sleep.'),
    objectives: [b('အိပ်ရေးအလေ့အထ ကောင်းများ သိရှိရန်။', 'Learn good sleep habits.')],
    readingMinutes: 3,
    body: b('နေ့စဉ် အိပ်ရာဝင်ချိန်ကို တတ်နိုင်သမျှ တူညီအောင်ထားပြီး ရေချိုးခြင်း၊ စာဖတ်ခြင်း၊ အိပ်ရာဝင်ခြင်းတို့ကို အစဉ်လိုက် ငြိမ်သက်စွာ လုပ်ပေးခြင်းက အိပ်စက်မှုကို ကူညီနိုင်သည်။ အသက် ၁ နှစ်မပြည့်သေးသော ကလေးကို နေ့အိပ်ချိန်နှင့် ညအိပ်ချိန်တိုင်း ကျောပေါ်လှန်၍ မစောင်းသော မာကျောညီညာသည့် အိပ်ရာမျက်နှာပြင်ပေါ်တွင် အိပ်စေပါ။ တင်းကျပ်စွာ ခင်းထားသော အိပ်ရာခင်းမှလွဲ၍ ကလေးအိပ်ရာထဲတွင် ခေါင်းအုံး၊ စောင်၊ ဘေးကာ၊ အရုပ်ပျော့ သို့မဟုတ် အဝတ်ပျော့များ မထားပါနှင့်။ အနည်းဆုံး ပထမ ၆ လအထိ မိဘများအိပ်သည့် အခန်းထဲရှိ ကလေး၏ သီးခြားအိပ်ရာတွင် အိပ်စေပါ။ အခန်းကို မှောင်မှောင်၊ တိတ်တိတ်နှင့် သက်သောင့်သက်သာ အေးမြအောင် ထားပါ။', 'Consistent bedtimes and a calm routine (bath–book–bed) may help sleep. For every nap and overnight sleep until age 1, place the baby on their back on a firm, flat, non-inclined sleep surface. Keep only a fitted sheet in the sleep space—no pillow, blanket, bumper, soft toy, or loose cloth. For at least the first 6 months, keep the baby’s own separate sleep space in the parents’ room. Keep the room dark, quiet, and comfortably cool.'),
    quiz: [q('မွေးကင်းစကို အိပ်စေရမည့် ပုံစံ —', 'Newborns should sleep —', [['ကျောပေါ်လှန်၍', 'on the back'], ['ဗိုက်လှန်၍', 'on the tummy']], 0)],
    takeaway: b('တည်ငြိမ်သော အိပ်ရာဝင်လုပ်ရိုးလုပ်စဉ်က အထောက်အကူပြုနိုင်သည်။', 'A steady bedtime routine may help.'),
    actionToday: b('ယနေ့ည တည်ငြိမ်သော အိပ်ရာဝင်လုပ်ရိုးလုပ်စဉ်တိုတစ်ခုကို လုပ်ကြည့်ပါ။', 'Try one short, calm bedtime routine tonight.'),
  }),
  lesson({
    slug: 'home_safety', category: 'safety',
    title: b('ကလေးငယ်အတွက် အိမ်တွင်းဘေးကင်းရေး', 'Home safety essentials'),
    summary: b('ကလေး စတင်လှုပ်ရှားသွားလာချိန်တွင် အိမ်ကို ဘေးကင်းအောင် ကြိုတင်ပြင်ဆင်ပါ။', 'Baby-proofing for a mobile child.'),
    objectives: [b('အိမ်တွင်းတွင် ဖြစ်ပေါ်နိုင်သည့် အဓိကအန္တရာယ်များကို သိရှိရန်။', 'Know the main home hazards.')],
    readingMinutes: 3,
    body: b('ဆေးဝါးများ၊ သန့်ရှင်းရေးသုံး ဓာတုပစ္စည်းများနှင့် ပူသောအရည်များကို ကလေးလက်လှမ်းမမီသည့် သော့ခတ်ထားသော နေရာတွင် သိမ်းဆည်းပါ။ လျှပ်စစ်ပလပ်ပေါက်များကို ဖုံးအုပ်ထားပြီး လှေကား၊ ရေထည့်ထားသော ပုံးနှင့် ရေချိုးခန်းအနီးတွင် ကလေးကို အမြဲ အနီးကပ်ကြီးကြပ်ပါ။ အသက်ရှူလမ်းကြောင်း ပိတ်ဆို့စေနိုင်သည့် ပစ္စည်းငယ်များကို ဖယ်ရှားထားပါ။ အရေးပေါ်အခြေအနေတွင် ဆက်သွယ်ရမည့် ဒေသဆိုင်ရာ ဖုန်းနံပါတ်များကို ကြိုတင်မှတ်သားထားပါ။', 'Keep medicines, chemicals, hot liquids out of reach. Watch sockets, stairs, and water. Remove small choking hazards. Know your local emergency number in advance.'),
    quiz: [q('ဆေးဝါးများကို မည်သည့်နေရာတွင် သိမ်းဆည်းသင့်သနည်း။', 'Medicines should be —', [['ကလေးလက်လှမ်းမမီသည့် သော့ခတ်ထားသောနေရာတွင်', 'locked out of reach'], ['စားပွဲပေါ်တွင်', 'left on the table']], 0)],
    takeaway: b('ဘေးကင်းအောင် ပြင်ဆင်ထားသော အိမ်တွင် ကလေးသည် ပိုမိုလုံခြုံစွာ စူးစမ်းသင်ယူနိုင်သည်။', 'A safe home lets children explore freely.'),
    actionToday: b('ယနေ့ အခန်းတစ်ခန်းကို ကလေး၏ မျက်စိအမြင့်မှ ကြည့်ပြီး အန္တရာယ်ရှိနိုင်သည့် အရာများကို စစ်ဆေးပါ။', 'Check one room from your child’s eye level today.'),
  }),
  lesson({
    slug: 'screen_time', category: 'screen_time',
    title: b('ဖန်သားပြင်ကြည့်ချိန်ကို သင့်တင့်စွာ စီမံခြင်း', 'Balancing screen time'),
    summary: b('အသက်အရွယ်အလိုက် ဖန်သားပြင်အသုံးပြုမှုနှင့် အစားထိုးလုပ်ဆောင်နိုင်သည့် နည်းလမ်းများ။', 'Age guidance and better alternatives.'),
    objectives: [b('ကလေးများအတွက် ဖန်သားပြင်အသုံးပြုမှု လမ်းညွှန်ချက်များကို သိရှိရန်။', 'Know screen-use guidance.')],
    readingMinutes: 3,
    body: b('ကမ္ဘာ့ကျန်းမာရေးအဖွဲ့၏ လမ်းညွှန်ချက်အရ အသက် ၂ နှစ်အောက်တွင် အထိုင်လုပ်ဆောင်သည့် ဖန်သားပြင်ကြည့်ချိန်ကို ရှောင်ရန်နှင့် အသက် ၂ နှစ်မှ ၄ နှစ်အထိ တစ်နေ့ ၁ နာရီထက် မကျော်စေရန် (ပိုနည်းလေ ပိုကောင်းလေ) အကြံပြုထားသည်။ မိသားစုနှင့် တိုက်ရိုက် ဗီဒီယိုခေါ်ဆိုမှုကို လူကြီးတစ်ဦးက ကလေး ပါဝင်ဆက်သွယ်နိုင်အောင် ကူညီပေးလျှင် သာမန် တစ်ယောက်တည်းကြည့်ရှုမှုနှင့် ကွာခြားသော အပြန်အလှန်ဆက်သွယ်မှု ဖြစ်နိုင်ပါသည်။ ဖန်သားပြင်သုံးမည်ဆိုလျှင် ကလေး၏ အသက်နှင့် ဖွံ့ဖြိုးမှုကို စဉ်းစားပြီး အရည်အသွေးကောင်းသော အကြောင်းအရာကို ရွေးချယ်ကာ အတူကြည့်၊ အတူပြောပါ။ ဖန်သားပြင်အသုံးပြုမှုကြောင့် အိပ်စက်ချိန်၊ ကိုယ်လက်လှုပ်ရှားမှု၊ စာဖတ်ချိန်၊ ကစားချိန်နှင့် မျက်နှာချင်းဆိုင် ဆက်ဆံချိန် မလျော့နည်းစေရန် စီမံပါ။', 'WHO guidance advises avoiding sedentary screen time under age 2 and limiting it to no more than 1 hour a day from ages 2 to 4 (less is better). A live video call with family can be an interactive experience different from solo viewing when an adult helps the child take part. When media is used, consider the child’s age and development, choose high-quality content, and watch and talk together. Plan media use so it does not crowd out sleep, movement, reading, play, or face-to-face interaction.'),
    quiz: [q('အသက် ၂ နှစ်အောက် ကလေးများအတွက် အထိုင်လုပ်ဆောင်သည့် ဖန်သားပြင်ကြည့်ချိန်ကို —', 'For children under 2, sedentary screen time is —', [['ရှောင်ရန် အကြံပြုထားသည်', 'not recommended'], ['များများ ကြည့်စေသင့်သည်', 'encouraged a lot']], 0)],
    takeaway: b('အချိန်ပမာဏတစ်ခုတည်းကို မကြည့်ဘဲ ကလေး၊ အကြောင်းအရာ၊ အတူအသုံးပြုပုံနှင့် ဖန်သားပြင်ကြောင့် လျော့နည်းသွားနိုင်သော အရေးကြီးလုပ်ဆောင်မှုများကို အတူ စဉ်းစားပါ။', 'Look beyond minutes alone: consider the child, the content, co-use, and what media may crowd out.'),
    actionToday: b('ယနေ့ ဖန်သားပြင်ကြည့်ချိန်တစ်ချိန်ကို ပြန်ကြည့်ပြီး ကလေးနှင့် အတူကြည့်ပြောဆိုရန် သို့မဟုတ် ကစားခြင်း၊ စာဖတ်ခြင်း၊ လှုပ်ရှားခြင်းဖြင့် အစားထိုးရန် ရွေးချယ်ပါ။', 'Review one media slot today: co-use and talk about it, or replace it with play, reading, or movement.'),
  }),
  lesson({
    slug: 'big_feelings', category: 'emotional_development',
    title: b('ကြီးမားသော ခံစားမှုများ', 'Helping with big feelings'),
    summary: b('ကလေးများ ခံစားမှုကို ထိန်းရန် ကူညီနည်း။', 'Help children handle strong emotions.'),
    objectives: [b('ခံစားမှု ထိန်းချုပ်မှုကို အားပေးရန်။', 'Support emotional regulation.')],
    readingMinutes: 3,
    body: b('ကလေးများသည် ခံစားမှုကို ထိန်းရန် လေ့ကျင့်နေဆဲဖြစ်သည်။ ခံစားမှုကို အမည်တပ်ပေးပါ (“စိတ်ဆိုးနေတယ်နော်”)၊ တည်ငြိမ်စွာ ရှိနေပါ၊ ဘေးကင်းစေပါ။ ခံစားမှုကို “မဖြစ်သင့်” ဟု မဆိုပါနှင့် — အသိအမှတ်ပြုခြင်းက ကလေးကို ငြိမ်သက်စေသည်။', 'Children are still learning to manage feelings. Name the feeling, stay calm, keep them safe. Don’t dismiss feelings — acknowledging them helps a child settle.'),
    quiz: [q('ကလေး စိတ်တိုနေရင် အရင်ဆုံး —', 'When a child is upset, first —', [['ခံစားမှုကို အမည်တပ်၍ တည်ငြိမ်စွာနေ', 'name it and stay calm'], ['ချက်ချင်း ပြစ်တင်', 'scold immediately']], 0)],
    takeaway: b('သင်၏ တည်ငြိမ်မှုက ကလေး စိတ်ပြန်တည်ငြိမ်ရန် အထောက်အကူပြုနိုင်သည်။', 'Your calm can help your child settle.'),
    actionToday: b('ယနေ့ ကလေး၏ ခံစားမှုတစ်ခုကို အမည်တပ်ပေးပါ။', 'Name one of your child’s feelings today.'),
  }),
  lesson({
    slug: 'making_friends', category: 'social_skills',
    title: b('သူငယ်ချင်း ဖွဲ့ခြင်း', 'Building social skills'),
    summary: b('အလှည့်စောင့်ခြင်း၊ ဝေမျှခြင်း သင်ကြားခြင်း။', 'Teaching turn-taking and sharing.'),
    objectives: [b('လူမှုကျွမ်းကျင်မှု သင်နည်း သိရှိရန်။', 'Learn to nurture social skills.')],
    readingMinutes: 3,
    body: b('လူမှုကျွမ်းကျင်မှုများသည် ကစားရင်း တဖြည်းဖြည်း သင်ယူရသည်။ အလှည့်ကျ ကစားနည်းများ၊ နမူနာပြခြင်းနှင့် ကောင်းသောအပြုအမူကို ချီးမွမ်းခြင်းဖြင့် သင်ကြားပါ။ ဝေမျှခြင်းကို အတင်းအကျပ် မခိုင်းပါနှင့် — အချိန်ပေးပါ။', 'Social skills are learned gradually through play. Teach with turn-taking games, modeling, and praise. Don’t force sharing — give it time.'),
    quiz: [q('ဝေမျှခြင်းကို —', 'Sharing is best —', [['အတင်းအကျပ် ခိုင်း', 'forced'], ['နမူနာပြ၍ အားပေး', 'modeled and encouraged']], 1)],
    takeaway: b('အားပေးလိုသော လူမှုအပြုအမူကို ကိုယ်တိုင် နမူနာပြပါ။', 'Model the social behavior you want to encourage.'),
    actionToday: b('ယနေ့ အလှည့်ကျ ကစားနည်းတစ်ခု ကစားပါ။', 'Play one turn-taking game today.'),
  }),
  lesson({
    slug: 'early_math', category: 'early_mathematics',
    title: b('အစောပိုင်း သင်္ချာ', 'Everyday early math'),
    summary: b('နေ့စဉ်ဘဝထဲ ရေတွက်ခြင်း၊ ပုံသဏ္ဌာန်၊ နှိုင်းယှဉ်ခြင်း။', 'Counting, shapes, and comparing in daily life.'),
    objectives: [b('နေ့စဉ်ဘဝ သင်္ချာ နည်းလမ်းများ သိရှိရန်။', 'Learn everyday math moments.')],
    readingMinutes: 3,
    body: b('သင်္ချာသည် စာအုပ်ထဲသာ မဟုတ်ပါ။ လှေကားထစ် ရေတွက်ခြင်း၊ ပန်းကန် ခွဲဝေခြင်း၊ “ပိုကြီး/ပိုငယ်” နှိုင်းယှဉ်ခြင်းဖြင့် နေ့စဉ်ဘဝထဲ သင်္ချာ သင်ပေးနိုင်သည်။', 'Math is not only in books. Count stairs, share out plates, compare “bigger/smaller” — teach math in daily life.'),
    quiz: [q('ကလေးကို သင်္ချာအခြေခံ သင်ပေးရန် အကောင်းဆုံးနည်းမှာ —', 'Early math is best taught —', [['နေ့စဉ်ဘဝထဲတွင် ရေတွက်ကစားခြင်း', 'in daily life'], ['ရုပ်ပုံကတ်များကိုသာ အလွတ်ကျက်စေခြင်း', 'only with flashcards']], 0)],
    takeaway: b('ရေတွက်ခြင်းကို နေ့စဉ်ဘဝထဲ ထည့်ပါ။', 'Weave counting into your day.'),
    actionToday: b('ယနေ့ ကလေးနှင့်အတူ အရာ ၅ ခု ရေတွက်ပါ။', 'Count five things together today.'),
  }),
  lesson({
    slug: 'creativity', category: 'creativity',
    title: b('တီထွင်ဖန်တီးမှု အားပေးခြင်း', 'Nurturing creativity'),
    summary: b('လွတ်လပ်စွာ ဆွဲ/တည်ဆောက်/ဟန်ဆောင် ကစားခြင်း အားပေးခြင်း။', 'Encourage open-ended art, building, and pretend play.'),
    objectives: [b('တီထွင်ဖန်တီးမှု အားပေးနည်း သိရှိရန်။', 'Learn to support creativity.')],
    readingMinutes: 3,
    body: b('တီထွင်ဖန်တီးမှုသည် အဖြေမှန်တစ်ခုတည်း မရှိသော ကစားခြင်းမှ ကြီးထွားသည်။ ရလဒ်ထက် လုပ်ငန်းစဉ်ကို ချီးမွမ်းပါ (“အရောင်တွေ ရောသုံးထားတာ တွေ့တယ်”)။ ကလေး၏ စိတ်ကူးကို ဦးဆောင်ခွင့် ပေးပါ။', 'Creativity grows from open-ended play with no single right answer. Praise the process, not the result. Let the child lead their ideas.'),
    quiz: [q('တီထွင်မှုအတွက် ချီးမွမ်းသင့်သည်မှာ —', 'For creativity, praise the —', [['လုပ်ငန်းစဉ်', 'process'], ['ရလဒ်သာ', 'result only']], 0)],
    takeaway: b('“မှန်/မှား” မရှိသော ကစားခြင်းက တီထွင်မှုကို မွေးသည်။', 'Open-ended play breeds creativity.'),
    actionToday: b('ယနေ့ ကလေးကို ခဲတံ/စက္ကူဖြင့် လွတ်လပ်စွာ ဆွဲစေပါ။', 'Let your child draw freely today.'),
  }),
  lesson({
    slug: 'problem_solving_parenting', category: 'problem_solving',
    title: b('ပြဿနာ ဖြေရှင်းမှု အားပေးခြင်း', 'Coaching problem solving'),
    summary: b('အဖြေမပေးဘဲ တွေးခေါ်ရန် ကူညီခြင်း။', 'Help children think it through instead of giving answers.'),
    objectives: [b('ပြဿနာဖြေရှင်းမှု အားပေးနည်း သိရှိရန်။', 'Learn to coach problem solving.')],
    readingMinutes: 3,
    body: b('ကလေး အခက်အခဲ ကြုံရင် ချက်ချင်း အဖြေ မပေးပါနှင့်။ “ဘယ်လို လုပ်ကြည့်မလဲ” ဟု မေးပါ။ ကြိုးစားခွင့် ပေး၍ မှားလည်း သင်ယူမှုဟု မှတ်ယူပါ။ ဤသည်က စိတ်ရှည်မှုနှင့် ယုံကြည်မှုကို တည်ဆောက်သည်။', 'When a child is stuck, don’t rush the answer. Ask “what could you try?” Let them attempt; mistakes are learning. This builds patience and confidence.'),
    quiz: [q('ကလေး အခက်အခဲ ကြုံရင် —', 'When stuck, better to —', [['ဦးဆောင်မေးခွန်း မေး', 'ask a guiding question'], ['အဖြေ ချက်ချင်းပေး', 'give the answer at once']], 0)],
    takeaway: b('မှားယွင်းမှုတိုင်းသည် သင်ယူမှုဖြစ်သည်။', 'Every mistake is learning.'),
    actionToday: b('ယနေ့ ဦးဆောင်မေးခွန်းတစ်ခုဖြင့် ကူညီပါ။', 'Help with one guiding question today.'),
  }),
  lesson({
    slug: 'special_needs_awareness', category: 'special_needs_awareness',
    title: b('အထူးလိုအပ်ချက် သိရှိနားလည်မှု', 'Special-needs awareness'),
    summary: b('ကွဲပြားမှုကို လေးစား၍ အားသာချက်အခြေခံ ချဉ်းကပ်ခြင်း။', 'Respecting difference with a strengths-based view.'),
    objectives: [b('အားသာချက်အခြေခံ သဘောထား သိရှိရန်။', 'Understand a strengths-based approach.')],
    readingMinutes: 4,
    body: b('ကလေးတိုင်းတွင် အားသာချက်များ ရှိသည်။ အထူးလိုအပ်ချက်ရှိသော ကလေးများကို “ချို့ယွင်း” ဟု မမြင်ဘဲ ကွဲပြားစွာ သင်ယူ/ကြီးထွားသူများအဖြစ် မြင်ပါ။ ဤအက်ပ်သည် ရောဂါ မဖော်ထုတ်ပါ — စိုးရိမ်ပါက ကျွမ်းကျင်ပညာရှင်နှင့် တိုင်ပင်ရန် လမ်းညွှန်ပေးသည်။ စောစီးစွာ ပံ့ပိုးမှုက များစွာ ကူညီနိုင်သည်။', 'Every child has strengths. See children with special needs not as “broken” but as learning and growing differently. This app does not diagnose — if concerned, it guides you to a professional. Early support can help a lot.'),
    quiz: [q('ဤအက်ပ်သည် —', 'This app —', [['ရောဂါ မဖော်ထုတ်ပါ', 'does not diagnose'], ['ရောဂါ ဖော်ထုတ်ပေးသည်', 'gives a diagnosis']], 0)],
    takeaway: b('ကွဲပြားမှုကို လေးစားပါ — အားသာချက်ကို မြင်ပါ။', 'Respect difference; see strengths.'),
    actionToday: b('ယနေ့ ကလေး၏ အားသာချက်တစ်ခုကို ချီးမွမ်းပါ။', 'Praise one of your child’s strengths today.'),
  }),
  lesson({
    slug: 'prepare_preschool', category: 'preparing_for_preschool',
    title: b('မူကြိုအတွက် ပြင်ဆင်ခြင်း', 'Getting ready for preschool'),
    summary: b('ခွဲနေခြင်း၊ လုပ်ရိုးလုပ်စဉ်နှင့် ကိုယ်တိုင်လုပ်နိုင်မှု လေ့ကျင့်ခြင်း။', 'Practice separation, routines, and self-help.'),
    objectives: [b('မူကြိုအသင့်ဖြစ်မှု အခြေခံ သိရှိရန်။', 'Know preschool readiness basics.')],
    readingMinutes: 3,
    body: b('မူကြိုအသင့်ဖြစ်မှုတွင် အစောပိုင်း သင်ယူမှုအပြင် ခဏခွဲနေနိုင်ခြင်း၊ လုပ်ရိုးလုပ်စဉ် လိုက်နာခြင်း၊ လူမှု-စိတ်ခံစားမှုနှင့် ကိုယ်တိုင်လုပ်ဆောင်နိုင်မှုများလည်း ပါဝင်ပါသည်။ မူကြိုအကြောင်း အပြုသဘောဖြင့် ပြောပြီး လုပ်ရိုးလုပ်စဉ်များကို ကြိုတင် လေ့ကျင့်ပေးပါ။', 'Preschool readiness includes early learning as well as managing brief separation, following routines, social-emotional skills, and basic self-help. Talk positively about preschool and practise routines in advance.'),
    quiz: [q('မူကြိုအသင့်ဖြစ်မှုတွင် ပါဝင်သော အချက်တစ်ခုမှာ —', 'One part of preschool readiness is —', [['လူမှု-စိတ်ခံစားမှုနှင့် ကိုယ်တိုင်လုပ်ဆောင်နိုင်မှု', 'social-emotional and self-help skills'], ['မစတက်မီ အက္ခရာအားလုံး တတ်ထားရမည်', 'knowing every letter before starting']], 0)],
    takeaway: b('လူမှု-စိတ်ခံစားမှုနှင့် ကိုယ်တိုင်လုပ်ဆောင်နိုင်မှုများသည် မူကြိုအသင့်ဖြစ်မှု၏ အရေးကြီးသော အစိတ်အပိုင်းများ ဖြစ်သည်။', 'Social-emotional and self-help skills are important parts of preschool readiness.'),
    actionToday: b('ယနေ့ ကလေးကို ကိုယ်တိုင် ဖိနပ်ဝတ်စေပါ။', 'Let your child put on their own shoes today.'),
  }),
  lesson({
    slug: 'prepare_school', category: 'preparing_for_school',
    title: b('ကျောင်းအတွက် ပြင်ဆင်ခြင်း', 'Getting ready for school'),
    summary: b('အာရုံစိုက်မှု၊ လွတ်လပ်မှုနှင့် စာဖတ်စိတ်ဝင်စားမှု တည်ဆောက်ခြင်း။', 'Build attention, independence, and love of reading.'),
    objectives: [b('ကျောင်းအသင့်ဖြစ်မှု တည်ဆောက်နည်း သိရှိရန်။', 'Learn to build school readiness.')],
    readingMinutes: 3,
    body: b('ကျောင်းအတွက် ကလေးကို အာရုံစိုက်မှု၊ လွတ်လပ်စွာ လုပ်ဆောင်နိုင်မှုနှင့် စာဖတ်စိတ်ဝင်စားမှုဖြင့် ပြင်ဆင်ပါ။ တသမတ်တည်း လုပ်ရိုးလုပ်စဉ်နှင့် အိပ်ရေးဝမှုက သင်ယူမှုကို ကူညီသည်။ ကျောင်းအကြောင်း ကြောက်စိတ်မဖြစ်စေဘဲ ရင်းနှီးစေပါ။', 'Prepare with attention, independence, and a love of reading. Steady routines and enough sleep help learning. Make school feel familiar, not frightening.'),
    quiz: [q('ကျောင်းတက်ရန် အသင့်ဖြစ်စေဖို့ ကူညီပေးသည်မှာ —', 'What helps readiness —', [['အိပ်ရေးဝခြင်းနှင့် တည်ငြိမ်သော နေ့စဉ်လုပ်ရိုးလုပ်စဉ်', 'sleep and steady routines'], ['ဖုန်းနှင့် ရုပ်မြင်သံကြား များများကြည့်ခြင်း', 'lots of screens']], 0)],
    takeaway: b('အာရုံစိုက်မှုနှင့် လွတ်လပ်မှုက ကျောင်းကို ကူညီသည်။', 'Attention and independence help school.'),
    actionToday: b('ယနေ့ ကလေးကို လုပ်ငန်းတစ်ခု အစအဆုံး တစ်ယောက်တည်း လုပ်စေပါ။', 'Let your child finish one task alone today.'),
  }),
  lesson({
    slug: 'doctor_visits', category: 'doctor_visits',
    title: b('ဆရာဝန်ပြသခြင်း ပြင်ဆင်နည်း', 'Making the most of doctor visits'),
    summary: b('မေးခွန်းများ ပြင်ဆင်၍ စိုးရိမ်စရာများ မှတ်သားခြင်း။', 'Prepare questions and note concerns.'),
    objectives: [b('ဆရာဝန်ပြသချိန်ကို ထိရောက်စေရန်။', 'Make visits effective.')],
    readingMinutes: 3,
    body: b('ဆရာဝန်မပြမီ ကလေး၏ အစား၊ အိပ်၊ ဖွံ့ဖြိုးမှုနှင့် စိုးရိမ်စရာများကို မှတ်သားထားပါ။ မေးလိုသည့် မေးခွန်း ၂–၃ ခုကို ကြိုရေးထားပါ။ ကာကွယ်ဆေး မှတ်တမ်းကို ယူသွားပါ။ ဤအက်ပ်၏ “ဆရာဝန်ပြသ ပြင်ဆင်ချက်” ကို ထုတ်ယူ၍ သွားနိုင်သည်။', 'Before a visit, note your child’s eating, sleep, development, and concerns. Write 2–3 questions in advance. Bring the vaccination record. You can export this app’s doctor-visit prep to take along.'),
    quiz: [q('ဆရာဝန်မပြမီ ကောင်းသည်မှာ —', 'Before a visit, it helps to —', [['မေးခွန်းများ ကြိုရေးထား', 'write questions ahead'], ['ဘာမှ မပြင်ဆင်', 'prepare nothing']], 0)],
    takeaway: b('ကြိုတင်ပြင်ဆင်မှုက ပြသချိန်ကို တန်ဖိုးရှိစေသည်။', 'Preparation makes visits count.'),
    actionToday: b('ယနေ့ ဆရာဝန်ကို မေးလိုသည့် မေးခွန်းတစ်ခု ရေးထားပါ။', 'Write one question for the doctor today.'),
  }),
  lesson({
    slug: 'parent_wellbeing', category: 'parent_mental_health',
    title: b('မိဘ၏ စိတ်ကျန်းမာရေး', 'Caring for your own wellbeing'),
    summary: b('မိဘ ကိုယ်တိုင် ဂရုစိုက်ခြင်းသည် ကလေးကိုပါ အကျိုးပြုသည်။', 'Caring for yourself helps your child too.'),
    objectives: [b('မိဘ စိတ်ကျန်းမာရေး၏ အရေးပါမှု သိရှိရန်။', 'Value your own wellbeing.')],
    readingMinutes: 3,
    body: b('မိဘဖြစ်ခြင်းသည် ပင်ပန်းနိုင်သည်။ သင်ကိုယ်တိုင် အနားယူ၊ အထောက်အပံ့ရှာ၊ ခံစားမှုကို မျှဝေခြင်းက သင့်ကလေးအတွက်ပါ အကျိုးရှိသည်။ အမြဲ ဝမ်းနည်း/စိုးရိမ်နေရ၊ နေ့စဉ်ဘဝ ထိခိုက်နေပါက ကူညီမှု ရှာဖွေရန် အားနည်းချက် မဟုတ်ပါ — ကျန်းမာရေးပညာရှင် သို့မဟုတ် ယုံကြည်ရသူနှင့် ပြောဆိုပါ။', 'Parenting can be exhausting. Rest, seeking support, and sharing your feelings help your child too. If you feel persistently low or anxious and daily life is affected, reaching out is a strength — talk to a health professional or someone you trust.'),
    quiz: [q('မိဘ ကိုယ်တိုင် ဂရုစိုက်ခြင်းသည် —', 'Caring for yourself is —', [['ကလေးအတွက်ပါ အကျိုးရှိ', 'good for your child too'], ['တစ်ကိုယ်ကောင်းဆန်ခြင်း', 'selfish']], 0)],
    takeaway: b('သင် ကောင်းမွန်မှသာ ကလေးကို ကောင်းစွာ ဂရုစိုက်နိုင်သည်။', 'You care best when you’re cared for.'),
    actionToday: b('ယနေ့ သင့်အတွက် ၁၀ မိနစ် အနားယူပါ။', 'Take 10 minutes for yourself today.'),
  }),
  lesson({
    slug: 'language_rich_home', category: 'language_development',
    title: b('ဘာသာစကား ကြွယ်ဝသော အိမ်', 'A language-rich home'),
    summary: b('သီချင်း၊ ပုံပြင်နှင့် စကားပြောဖြင့် ဘာသာစကား တည်ဆောက်ခြင်း။', 'Build language with songs, stories, and talk.'),
    objectives: [b('ဘာသာစကား ကြွယ်ဝစေမည့် အလေ့အထ သိရှိရန်။', 'Learn language-building habits.')],
    readingMinutes: 3,
    body: b('သီချင်းဆိုခြင်း၊ ပုံပြင်ပြောခြင်း၊ နေ့စဉ်လုပ်ဆောင်ချက်များကို စကားဖြင့် ရှင်းပြခြင်းက ဘာသာစကားကို ကြွယ်ဝစေသည်။ ဘာသာစကား ၂ မျိုး သင်ခြင်းသည် ကလေးကို မရှုပ်ထွေးစေပါ — အားသာချက် တစ်ခုပင်ဖြစ်သည်။', 'Singing, storytelling, and narrating daily actions enrich language. Two languages do not confuse a child — it is an asset.'),
    quiz: [q('ဘာသာစကား ၂ မျိုး သင်ခြင်းသည် —', 'Raising bilingual is —', [['အားသာချက်တစ်ခု', 'an asset'], ['ရှုပ်ထွေးစေ', 'confusing']], 0)],
    takeaway: b('စကားပြော၊ သီချင်းဆို၊ ပုံပြင်ပြော — နေ့စဉ်လုပ်ပါ။', 'Talk, sing, tell stories — daily.'),
    actionToday: b('ယနေ့ ကလေးနှင့်အတူ သီချင်းတစ်ပုဒ် ဆိုပါ။', 'Sing one song with your child today.'),
  }),
];
