// Hope & Understanding Center — special-needs awareness. Strengths-based,
// respectful, and NON-DIAGNOSTIC. "Possible signs" are awareness points only —
// they never diagnose; the app always guides families to a qualified
// professional. The legacy clinical_review value keeps these rows unpublished.
//
// References now carry real citations, verified against public guidance and
// accepted by the product owner on 2026-07-31. Every record still ends its
// reference list with REF_SPECIALIST_REVIEW_REQUIRED. Verified sourcing does
// not turn diagnosis, treatment, individualized-advice or emergency wording
// into an endorsement. clinicalStatus stays 'clinical_review' so these records
// remain unavailable to parents until the focused safety boundary is complete.
import { specialNeed, type SeedItem } from '../types';

const b = (mm: string, en: string) => ({ mm, en });
const myth = (m: string, mEn: string, f: string, fEn: string) => ({ myth: b(m, mEn), fact: b(f, fEn) });
const qa = (q: string, qEn: string, a: string, aEn: string) => ({ q: b(q, qEn), a: b(a, aEn) });

const REF_SPECIALIST_REVIEW_REQUIRED = 'SPECIALIST REVIEW REQUIRED for any diagnosis, treatment, individualized-advice or emergency wording. Public guidance links are recorded; no individual clinician endorsement is claimed.';
const NOT_DIAGNOSIS_MM = 'ဤအချက်များသည် ရောဂါဖော်ထုတ်ခြင်း မဟုတ်ပါ — စိုးရိမ်ပါက ကျွမ်းကျင်ပညာရှင်နှင့် တိုင်ပင်ပါ။';
const NOT_DIAGNOSIS_EN = 'These are awareness points, not a diagnosis — if concerned, consult a professional.';

export const SPECIAL_NEEDS: SeedItem[] = [
  specialNeed({
    key: 'autism',
    title: b('အော်တစ်ဇင် (Autism) သိရှိနားလည်မှု', 'Understanding Autism'),
    overview: b("အော်တစ်ဇင် (Autism) သည် ကလေးငယ်များ ပတ်ဝန်းကျင်လောကကို နားလည်ခံစားပုံနှင့် ပြောဆိုဆက်သွယ်ပုံ ကွဲပြားသည့် သဘောသဘာဝ ဖြစ်ပါသည်။ ရောဂါတစ်ခု မဟုတ်ဘဲ ဖွံ့ဖြိုးမှု ကွဲပြားခြင်းသာ ဖြစ်ပါသည်။ လိုအပ်သော ပံ့ပိုးကူညီမှုမှာ ကလေးအလိုက် အလွန်ကွာခြားပါသည် — အနည်းငယ်သာ လိုအပ်သော ကလေးများရှိသလို နေ့စဉ်ဘဝတွင် များစွာ လိုအပ်သော ကလေးများလည်း ရှိပြီး ကလေးတစ်ဦးနှင့်တစ်ဦး မတူညီကြပါ။", "Autism is a different way of experiencing and communicating with the world. It is a developmental difference, not an illness. Support needs vary widely: some children need a little help, others need a great deal of daily support. Every child is unique."),
    strengths: [b('အသေးစိတ် သတိပြုနိုင်မှု', 'Strong attention to detail'), b('စိတ်ဝင်စားရာတွင် နက်နဲသော အာရုံစိုက်မှု', 'Deep focus on interests'), b('ရိုးသားမှုနှင့် ပုံစံကျ တွေးခေါ်မှု', 'Honesty and pattern thinking')],
    possibleSigns: [b("၉ လအရွယ်တွင် — ကိုယ့်နာမည်ခေါ်လျှင် မတုံ့ပြန်ခြင်း", "By 9 months: does not respond to their own name"), b("၁၂ လအရွယ်တွင် — လက်ဟန်ခြေဟန် အလွန်နည်းခြင်း (ဥပမာ — နှုတ်ဆက်ရာတွင် လက်မပြခြင်း)", "By 12 months: uses few or no gestures, for example does not wave goodbye"), b("၁၈ လအရွယ်တွင် — စိတ်ဝင်စားစရာကို ပြရန် လက်မညွှန်ခြင်း", "By 18 months: does not point to show you something interesting"), b("၂၄ လအရွယ်တွင် — သူတစ်ပါး နာကျင်/စိတ်မကောင်းဖြစ်နေသည်ကို မသတိထားခြင်း", "By 24 months: does not notice when others are hurt or upset"), b("အသက်မရွေး — ယခင်တတ်ခဲ့သော စကား၊ အသံ သို့မဟုတ် လူမှုဆက်ဆံရေး ကျွမ်းကျင်မှုများ ပျောက်သွားပါက စောင့်မနေဘဲ ကျန်းမာရေးဝန်ထမ်းနှင့် အမြန်ပြသပါ။", "At any age: loses speech, babbling or social skills they previously had — see a health professional promptly, do not wait"), b("အသံ၊ အနံ့၊ အရသာ၊ အမြင်၊ ထိတွေ့မှုတို့ကို ထူးခြားစွာ တုံ့ပြန်ခြင်း", "Unusual reactions to how things sound, smell, taste, look or feel"), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [
      myth('အော်တစ်ဇင်ကို ကာကွယ်ဆေးက ဖြစ်စေသည်', 'Vaccines cause autism', "မဟုတ်ပါ။ ကမ္ဘာ့ကျန်းမာရေးအဖွဲ့ (WHO) ၏ ကာကွယ်ဆေး ဘေးကင်းရေး ကော်မတီသည် ၂၀၁၀ မှ ၂၀၂၅ အတွင်း ထုတ်ဝေခဲ့သော လေ့လာမှု ၃၁ ခုကို ပြန်လည်သုံးသပ်ပြီး ဆက်စပ်မှု မရှိကြောင်း အတည်ပြုခဲ့ပါသည်။ ကလေး ၆၅၇,၄၆၁ ဦးအပေါ် ပြုလုပ်ခဲ့သော ကြီးမားသည့် လေ့လာမှုတစ်ခုကလည်း MMR ကာကွယ်ဆေးနှင့် အော်တစ်ဇင်အကြား မည်သည့်ဆက်စပ်မှုမျှ မတွေ့ရှိခဲ့ပါ။", "No. The World Health Organization’s vaccine-safety committee reviewed 31 studies published between 2010 and 2025 and confirmed there is no causal link. A study of 657,461 children found no link between the MMR vaccine and autism."),
      myth('အော်တစ်ဇင် ကလေးများသည် ချစ်ခင်ကြင်နာမှုကို မခံစားတတ်ကြပါ', 'Autistic children can’t feel love', 'မမှန်ပါ။ ကလေးများသည် ချစ်ခင်မှုကို မိမိတို့နည်းလမ်းဖြင့် ကွဲပြားစွာ ဖော်ပြတတ်ကြခြင်းသာ ဖြစ်ပါသည်။', 'False — they express affection in their own ways.'),
    ],
    homeSupport: [b('ရှင်းလင်းသော နေ့စဉ် လုပ်ရိုးလုပ်စဉ်နှင့် ရုပ်ပုံ အစီအစဉ်ဇယားများကို အသုံးပြုပါ။', 'Use clear routines and visual schedules.'), b('ကလေးငယ် စိတ်ဝင်စားသော အရာများမှတစ်ဆင့် ဆက်သွယ်ပြောဆိုပါ။', 'Connect through their interests.')],
    schoolSupport: [b('တည်ငြိမ်သော ပတ်ဝန်းကျင်နှင့် ကြိုတင် သတိပေးမှုများ ပေးပါ။', 'Provide a calm setting and advance warnings for changes.')],
    professionalSupport: [b('ကလေးဖွံ့ဖြိုးမှုဆိုင်ရာ ဆရာဝန်၊ စကားပြောနှင့် ဘာသာစကားဆိုင်ရာ ပညာရှင်၊ နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ပြန်လေ့ကျင့်ပေးသည့် ပညာရှင်တို့နှင့် တိုင်ပင်ပါ။', 'Work with a developmental pediatrician, speech and occupational therapists.')],
    activities: [b('စိတ်ဝင်စားရာ အကြောင်းအရာဖြင့် အလှည့်ကျ ကစားပါ။', 'Turn-taking games around a favorite topic.')],
    faq: [qa('စောစောစီးစီး ပံ့ပိုးကူညီပေးခြင်းက အကျိုးရှိပါသလား။', 'Does early support help?', 'အကျိုးရှိပါသည်။ စောစောစီးစီး ပံ့ပိုးကူညီပေးခြင်းသည် ပြောဆိုဆက်သွယ်မှုနှင့် နေ့စဉ် ကျွမ်းကျင်မှုစွမ်းရည်များ ဖွံ့ဖြိုးတိုးတက်စေရန် များစွာ အထောက်အကူပြုနိုင်ပါသည်။', 'Yes — early support can help communication and skills.')],
    relatedLessons: ['lsn_special_needs_awareness'], relatedActivities: ['act_feeling_faces'],
    references: [
      "CDC. Signs and Symptoms of Autism Spectrum Disorder. https://www.cdc.gov/autism/signs-symptoms/index.html (accessed 2026-07-31)",
      "WHO Global Advisory Committee on Vaccine Safety. Statement on vaccines and autism, 11 December 2025. https://www.who.int/news/item/11-12-2025-statement-gacvs-vaccines-autism",
      "Hviid A, Hansen JV, Frisch M, Melbye M. Measles, Mumps, Rubella Vaccination and Autism: A Nationwide Cohort Study. Ann Intern Med. 2019;170(8):513–520.",
      "Lipkin PH, Macias MM. Promoting Optimal Development… Developmental Surveillance and Screening. Pediatrics. 2020;145(1):e20193449.",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'speech_delay',
    title: b('စကားပြော နှောင့်နှေးမှု', 'Understanding Speech Delay'),
    overview: b('စကားပြောဖွံ့ဖြိုးမှု နှောင့်နှေးခြင်းဆိုသည်မှာ ကလေး၏ စကားသံနှင့် ဘာသာစကားဖွံ့ဖြိုးမှုသည် မျှော်မှန်းထားသည်ထက် နှေးနေခြင်း ဖြစ်သည်။ အကြောင်းရင်းအမျိုးမျိုး ရှိနိုင်ပြီး သင့်လျော်သော ပံ့ပိုးမှုဖြင့် တိုးတက်နိုင်ပါသည်။', 'Speech delay means a child’s speech/language is developing slower than expected. There are many causes and much room for progress.'),
    strengths: [b('လက်ဟန်/ပုံဖြင့် ဆက်သွယ်နိုင်မှု', 'Communicates well with gestures/pictures'), b('နားလည်မှု ကောင်းခြင်း', 'Often good understanding')],
    possibleSigns: [b("၁၂ လတွင် — လက်ပြနှုတ်ဆက်ခြင်း မပြုခြင်း၊ မိဘ သို့မဟုတ် အုပ်ထိန်းသူကို “မေမေ”၊ “ဖေဖေ” သို့မဟုတ် အခြားအထူးအမည်ဖြင့် မခေါ်ခြင်း၊ “မလုပ်နဲ့” ဟူသော စကားကို နားမလည်ခြင်း", "By 12 months: does not wave bye-bye, call a parent or caregiver “mama”, “dada” or another special name, or understand “no”"), b("၁၈ လတွင် — “မေမေ”၊ “ဖေဖေ” အပြင် အခြားစကားလုံး သုံးလုံးခန့် ပြောရန် မကြိုးစားခြင်း သို့မဟုတ် လက်ဟန်မပါသော အဆင့်တစ်ဆင့် ညွှန်ကြားချက်ကို မလိုက်နာနိုင်ခြင်း", "By 18 months: does not try to say about three words besides “mama” or “dada”, or follow a one-step direction without a gesture"), b("၂၄ လတွင် — စကားလုံးနှစ်လုံးတွဲ မပြောသေးခြင်း သို့မဟုတ် သုံးစွဲသော ဘာသာစကားအားလုံးတွင် စကားလုံးအလွန်နည်းခြင်း — စစ်ဆေးမှု ခံယူပါ", "By 24 months: does not combine two words, or has a very small vocabulary across all languages used—seek assessment"), b("ရိုးရှင်းသော ညွှန်ကြားချက်များ နားလည်ရန် ခက်ခဲခြင်း", "Difficulty understanding simple directions"), b("အသက်မရွေး — ယခင်သုံးခဲ့သော စကားလုံး သို့မဟုတ် အသံများ ပျောက်သွားပါက အမြန် ပြသပါ", "At any age: loses words or babbling they previously used — see someone promptly"), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ယောက်ျားလေးတွေက စကားပြော နောက်ကျတာ ပုံမှန်ပဲ၊ စောင့်ကြည့်ရုံပဲ', '“Boys just talk late — only wait”', 'အချို့ ကလေးငယ်များ စကားပြော နောက်ကျတတ်သော်လည်း စောင့်ကြည့်နေရုံသက်သက်ဖြင့် အကြားအာရုံ ချို့တဲ့မှု ပြဿနာများကို လက်လွတ်သွားနိုင်သဖြင့် အကြားအာရုံ စစ်ဆေးမှု ခံယူရန် အရေးကြီးပါသည်။', 'Some are later, but simply “waiting” can miss a hearing issue — checking hearing matters.')],
    homeSupport: [b('နေ့စဉ်လုပ်ဆောင်ချက်များကို စကားဖြင့် ရှင်းပြပြီး ကလေးနှင့် မကြာခဏ စကားပြောပါ။', 'Talk a lot and narrate daily actions.'), b('ကလေးပြောသည့် စကားတိုကို စကားလုံးအနည်းငယ် ထပ်ဖြည့်ပြီး ပြန်ပြောပေးပါ။', 'Expand on what your child says.')],
    schoolSupport: [b('ပုံရိပ်များ သုံး၍ ဆက်သွယ်မှုကို အားပေးပါ။', 'Support communication with pictures.')],
    professionalSupport: [b('စကားပြောနှင့် ဘာသာစကားဆိုင်ရာ ပညာရှင်နှင့် တိုင်ပင်ပြီး အကြားအာရုံ စစ်ဆေးမှုလည်း ခံယူပါ။', 'See a speech therapist; get a hearing check.')],
    activities: [b('ရုပ်ပုံစာအုပ်ကို အတူကြည့်ပြီး ပုံများ၏ အမည်ကို ပြောကစားပါ။', 'Name-and-point book play.')],
    faq: [qa('ဘာသာစကား ၂ မျိုးက စကားပြောကို နှေးစေသလား။', 'Does bilingualism cause delay?', "မဟုတ်ပါ။ ဘာသာစကား နှစ်မျိုး သင်ယူခြင်းသည် ကလေးကို ရှုပ်ထွေးမှု မဖြစ်စေသလို စကားပြော နှောင့်နှေးမှုကိုလည်း မဖြစ်စေပါ။ ဘာသာစကားနှစ်မျိုး သုံးသော ကလေးများသည် ပထမဆုံး စကားလုံးနှင့် နှစ်လုံးတွဲ စကားစုကို အခြားကလေးများနှင့် အလားတူ အရွယ်တွင် ရောက်ရှိပါသည်။ အိမ်တွင်း ဘာသာစကားကို ဆက်လက် ပြောဆိုပါ — ပထမဘာသာစကား ခိုင်မာမှုက ဒုတိယဘာသာစကား သင်ယူရာတွင် အထောက်အကူ ဖြစ်ပါသည်။ ကလေး စကားပြော နောက်ကျနေပါက ဘာသာစကားတစ်ခုကို ဖြတ်ချရန် အကြောင်းမဟုတ်ဘဲ — စစ်ဆေးမှု ခံယူရန် အကြောင်း ဖြစ်ပါသည်။", "No. Learning two languages does not confuse children and does not cause speech or language delay. Bilingual children reach their first words and two-word phrases at around the same age as other children. Keep speaking your home language with your child — a strong first language helps them learn the second one. If your child is a late talker, that is a reason to have them checked, not a reason to drop one language.")],
    relatedLessons: ['lsn_talk_more'], relatedActivities: ['act_name_and_point'],
    references: [
      "ASHA. Learning More Than One Language. https://www.asha.org/public/speech/development/learning-more-than-one-language/ (accessed 2026-07-31)",
      "ASHA. Late Language Emergence — practice portal. https://www.asha.org/practice-portal/clinical-topics/late-language-emergence/",
      "CDC. Developmental Milestones. https://www.cdc.gov/act-early/milestones/index.html (accessed 2026-08-18)",
      "CDC. About Hearing Loss in Children. https://www.cdc.gov/hearing-loss-children/about/index.html (accessed 2026-07-31)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'adhd',
    title: b('အာရုံစိုက်မှု/တက်ကြွမှု ကွဲပြားမှု (ADHD)', 'Understanding ADHD'),
    overview: b("ADHD (အာရုံစူးစိုက်မှုနှင့် လွန်ကဲစွာ တက်ကြွမှု ကွဲပြားခြင်း) သည် အာရုံစိုက်နိုင်စွမ်း၊ လှုပ်ရှားမှု ပမာဏနှင့် စိတ်လိုက်မာန်ပါ ထိန်းချုပ်နိုင်စွမ်းတို့အပေါ် သက်ရောက်မှုရှိသော ဖွံ့ဖြိုးမှု ကွဲပြားခြင်း ဖြစ်ပါသည်။ ADHD ကို အများအားဖြင့် အသက် ၄ နှစ်မပြည့်မီ ရောဂါအမည် အတည်မပြုပါ။ ၄ နှစ်အောက် ကလေးများတွင် လှုပ်ရှားမှုများခြင်းနှင့် အာရုံစိုက်ချိန် တိုတောင်းခြင်းသည် ပုံမှန် ဖွံ့ဖြိုးမှု၏ အစိတ်အပိုင်း ဖြစ်တတ်သော်လည်း စိုးရိမ်ပါက ကျန်းမာရေးဝန်ထမ်းနှင့် တိုင်ပင်သင့်ပါသည်။", "ADHD is a developmental difference affecting attention, activity level, and impulse control. ADHD is not usually diagnosed before age 4. In children under 4, high activity and short attention are very often part of normal development — but if you are worried, it is still right to talk to a health professional."),
    strengths: [b('စွမ်းအင်နှင့် စိတ်အားထက်သန်မှု', 'High energy and enthusiasm'), b('တီထွင်ဖန်တီးမှုနှင့် စိတ်ဝင်စားရာတွင် အာရုံစိုက်နိုင်မှု', 'Creativity and hyperfocus on interests')],
    possibleSigns: [b("အသက်တူ ကလေးများထက် လှုပ်ရှားမှု လွန်ကဲစွာ များပြားခြင်း သို့မဟုတ် စောင့်ဆိုင်းရန် ခက်ခဲခြင်း", "More movement or difficulty waiting than other children of the same age"), b("အာရုံ လွယ်လွယ်နှင့် ပျံ့လွင့်လွယ်ခြင်း", "Easily distracted"), b("အရေးကြီးသည် — ဤလက္ခဏာများသည် နေရာတစ်ခုတည်းတွင်သာ မဟုတ်ဘဲ နေရာနှစ်ခုနှင့်အထက် (ဥပမာ — အိမ်တွင်ရော ကျောင်း/ကလေးထိန်းစင်တာတွင်ပါ) ဖြစ်ပေါ်နေရပါမည်။", "Important: these must be present in more than one setting — for example both at home and at school or childcare — not in one place only."), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ADHD သည် မိဘများ၏ ပြုစုစောင့်ရှောက်ပုံ မမှန်ခြင်းကြောင့် ဖြစ်သည်', 'ADHD is caused by bad parenting', "မဟုတ်ပါ။ မိဘ ပြုစုစောင့်ရှောက်ပုံကြောင့် ADHD ဖြစ်လာခြင်း မဟုတ်ပါ။ အကြောင်းရင်း အတိအကျကို အပြည့်အဝ မသိရသေးသော်လည်း မျိုးရိုးဗီဇက အရေးကြီးသော အခန်းကဏ္ဍမှ ပါဝင်ပါသည်။", "No. Parenting does not cause ADHD. The exact cause is not known, but genes play an important role.")],
    homeSupport: [b('တိုတိုနှင့် ရှင်းလင်းသော ညွှန်ကြားချက်များ ပေးပါ၊ ပုံမှန် လုပ်ရိုးလုပ်စဉ်များ သတ်မှတ်ပေးပြီး ကလေးငယ်အတွက် ခေတ္တ ကိုယ်လက်လှုပ်ရှား အနားယူချိန်များ ပေးပါ။', 'Give short clear instructions, steady routines, and movement breaks.')],
    schoolSupport: [b('ကောင်းသောအပြုအမူကို ချီးမွမ်း၍ လုပ်ငန်းများ အပိုင်းလိုက် ခွဲပါ။', 'Praise good behavior; break tasks into small steps.')],
    professionalSupport: [b("ကလေးဖွံ့ဖြိုးမှုဆရာဝန်/ကလေးစိတ်ပညာရှင်နှင့် တိုင်ပင်ပါ။", "Consult a developmental pediatrician or child psychologist."), b("အသက် ၄ နှစ်မှ ၆ နှစ်မပြည့်မီ ကလေးများအတွက် ရရှိနိုင်ပါက အထောက်အထားခိုင်မာသော မိဘအပြုအမူစီမံနည်း လေ့ကျင့်မှုနှင့်/သို့မဟုတ် စာသင်ခန်းအတွင်း အပြုအမူပံ့ပိုးမှုကို ပထမဦးစားပေး ကုသမှုအဖြစ် အသုံးပြုပါသည်။ ထိုပံ့ပိုးမှုများဖြင့် သိသိသာသာ မတိုးတက်ဘဲ နေ့စဉ်လုပ်ဆောင်မှုအပေါ် အလယ်အလတ်မှ ပြင်းထန်သော ထိခိုက်မှု ဆက်ရှိပါက ဆရာဝန်က methylphenidate ကို စဉ်းစားနိုင်ပါသည်။ အထောက်အထားခိုင်မာသော အပြုအမူကုသမှု မရရှိနိုင်ပါက ဆရာဝန်က ဆေးစတင်ခြင်းနှင့် ကုသမှုနှောင့်နှေးခြင်း၏ အန္တရာယ်တို့ကို ချိန်ဆ၍ ဆုံးဖြတ်ရပါမည်။", "For children aged 4 years to under 6, evidence-based parent training in behavior management and/or behavioral classroom interventions are first-line when available. A clinician may consider methylphenidate if these interventions do not provide significant improvement and moderate-to-severe functional impairment continues. If evidence-based behavioral treatment is unavailable, the clinician should weigh the risks of starting medication against the harm of delaying treatment.")],
    activities: [b('ရုပ်ပိုင်း လှုပ်ရှားမှုများနှင့် အလှည့်ကျ ကစားနည်းများ။', 'Active games and turn-taking play.')],
    faq: [qa('ငယ်ရွယ်စဉ် အတည်ပြုနိုင်သလား။', 'Can it be confirmed early?', 'ငယ်ရွယ်စဉ် အတည်ပြုရ ခက်ခဲသည် — ကျွမ်းကျင်သူ၏ အကဲဖြတ်မှု လိုအပ်သည်။', 'It is hard to confirm early; a professional assessment is needed.')],
    relatedLessons: ['lsn_gentle_discipline'], relatedActivities: ['act_obstacle_course'],
    references: [
      "Wolraich ML et al. Clinical Practice Guideline for the Diagnosis, Evaluation, and Treatment of ADHD in Children and Adolescents. Pediatrics. 2019;144(4):e20192528.",
      "CDC. Clinical Care of ADHD in Children. https://www.cdc.gov/adhd/hcp/clinical-care/index.html (accessed 2026-08-18)",
      "CDC. About ADHD — causes and risk factors. https://www.cdc.gov/adhd/about/index.html (accessed 2026-07-31)",
      "CDC. ADHD — Signs and Symptoms. https://www.cdc.gov/adhd/signs-symptoms/index.html (accessed 2026-07-31)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'down_syndrome',
    title: b('ဒေါင်းစင်ဒရုမ်း (Down Syndrome)', 'Understanding Down Syndrome'),
    overview: b("ဒေါင်းစင်ဒရုမ်းသည် မွေးရာပါ မျိုးရိုးဗီဇ အခြေအနေဖြစ်ပြီး — ခရိုမိုဆုမ်း ၂၁ တွင် အပိုတစ်ခု ပါလာခြင်းကြောင့် ဖြစ်ပါသည် (trisomy 21 ဟုလည်း ခေါ်သည်)။ ကလေးများသည် မိမိအရှိန်ဖြင့် သင်ယူကြီးထွားပြီး ပျော်ရွှင်သော ဘဝကို ရှင်သန်နိုင်ပါသည်။", "Down syndrome is a genetic condition present from birth, caused by an extra copy of chromosome 21 (sometimes called trisomy 21). Children learn and grow at their own pace and can live happy, full lives."),
    strengths: [b('လူမှုဆက်ဆံရေး နွေးထွေးမှု', 'Warm social connection'), b('ကြိုးစားမှုနှင့် အတုယူ သင်ယူနိုင်မှု', 'Persistence and learning by imitation')],
    possibleSigns: [b('ကြွက်သား နူးညံ့မှုနှင့် ဖွံ့ဖြိုးမှု မှတ်တိုင်များ နှေးခြင်း', 'Low muscle tone and slower milestones'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ဒေါင်းစင်ဒရုမ်း ကလေးများသည် မည်သည့်အရာကိုမျှ မသင်ယူနိုင်ကြပါ', 'Children with Down syndrome can’t learn', 'မမှန်ပါ။ သင့်လျော်သော ပံ့ပိုးကူညီမှုနှင့် စိတ်ရှည်စွာ သင်ကြားပေးမှုဖြင့် အရာများစွာကို ကောင်းစွာ သင်ယူတိုးတက်နိုင်ကြပါသည်။', 'False — with support they learn a great deal.')],
    homeSupport: [b("ဤစစ်ဆေးမှုများအကြောင်း ကလေး၏ ဆရာဝန်ကို မေးမြန်းပါ — ဒေါင်းစင်ဒရုမ်း ရှိသော ကလေးတိုင်းအတွက် အကြံပြုထားပါသည်။ ဤစစ်ဆေးမှုများသည် လက္ခဏာမထင်ရှားမီ အရေးကြီးသော ပြဿနာများကို ရှာဖွေတွေ့ရှိနိုင်ပါသည်။", "Ask your child’s doctor about these specific checks — they are recommended for every child with Down syndrome. These checks can identify important problems before symptoms are obvious."), b("နှလုံး — မွေးကင်းစကာလတွင် နှလုံး အာထရာဆောင်း (echocardiogram) ကို ကလေးနှလုံး အထူးကုက ဖတ်ရှုရန်။ ကိုယ်ဝန်ဆောင်စဉ်က စစ်ပြီးဖြစ်လျှင်လည်း ပြန်စစ်သင့်ပါသည်။", "Heart: an echocardiogram in the newborn period, read by a paediatric cardiologist — even if a scan was done during pregnancy."), b("အကြားအာရုံ — မွေးကင်းစတွင် စက်ကိရိယာဖြင့် အကြားအာရုံ စစ်ဆေးပါ။ စစ်ဆေးမှု အောင်မြင်ပါက ၆ လအရွယ်တွင် ထပ်မံ အတည်ပြုစစ်ဆေးပါ။ မအောင်မြင်ပါက ရောဂါရှာဖွေရေး အကြားအာရုံစစ်ဆေးမှုကို အမြန် ပြုလုပ်ပါ။ ထို့နောက် နားတစ်ဖက်ချင်းစီ၏ အကြားအာရုံ ပုံမှန်ဖြစ်ကြောင်း အတည်ပြုနိုင်သည်အထိ (များသောအားဖြင့် အသက် ၄ နှစ်ကျော်မှ) ၆ လတစ်ကြိမ် စစ်ဆေးပြီး၊ ထို့နောက် နှစ်စဉ် စစ်ဆေးပါ။", "Hearing: obtain objective hearing testing at birth. If the newborn screen is passed, rescreen at 6 months; if it is not passed, arrange prompt diagnostic hearing evaluation. Then obtain ear-specific hearing testing every 6 months until normal hearing is established in both ears, usually after age 4, and annually thereafter."), b("သိုင်းရွိုက် — ၆ လ၊ ၁၂ လနှင့် ထို့နောက် နှစ်စဉ် TSH သွေးစစ်ဆေးမှု ပြုလုပ်ရန်။", "Thyroid: a TSH blood test at 6 months, at 12 months, and then every year."), b("မျက်စိ — မျက်စိအထူးကုနှင့် ပုံမှန် စစ်ဆေးရန်။", "Eyes: regular eye checks with an eye specialist."), b("အိပ်စက်ခြင်း — ကလေး ဟောက်ခြင်း၊ အသက်ရှူခဏရပ်ခြင်း သို့မဟုတ် နေ့ဘက် အလွန်အိပ်ငိုက်ခြင်းရှိပါက ဆရာဝန်အား ပြောပြပါ။ ထင်ရှားသော လက္ခဏာ မရှိသော်လည်း ဒေါင်းစင်ဒရုမ်းရှိသော ကလေးတိုင်းကို အသက် ၃ နှစ်မှ ၄ နှစ်ကြားတွင် အိပ်စက်မှုစစ်ဆေးခြင်း (polysomnogram) ပြုလုပ်ရန် အကြံပြုထားပါသည်။", "Sleep: tell the doctor if your child snores, has pauses in breathing, or is very sleepy during the day. A sleep study (polysomnogram) is recommended for every child with Down syndrome between ages 3 and 4, even when there are no obvious symptoms."), b("စောစီးစွာ ကြားဝင်ပံ့ပိုးမှု ဝန်ဆောင်မှုကို အမြန်ဆုံး တောင်းခံပါ။", "Ask for early intervention services as soon as possible.")],
    schoolSupport: [b('ကလေးအားလုံး အတူပါဝင်နိုင်သော ပညာရေးပတ်ဝန်းကျင်နှင့် တစ်ဦးချင်းလိုအပ်ချက်အလိုက် ပံ့ပိုးမှုကို ရှာဖွေပါ။', 'Seek inclusive education and individual support.')],
    professionalSupport: [b('ကလေးဖွံ့ဖြိုးမှုဆိုင်ရာ ဆရာဝန်၊ ကိုယ်လက်လှုပ်ရှားမှု ပြန်လည်သန်စွမ်းရေးပညာရှင်နှင့် စကားပြောနှင့် ဘာသာစကားဆိုင်ရာ ပညာရှင်တို့နှင့် တိုင်ပင်ပါ။', 'Work with a pediatrician, physio and speech therapists.')],
    activities: [b('ကြွက်သားခိုင်မာမှုအတွက် ကစားနည်းများ (ကြီးကြပ်၍)။', 'Muscle-strengthening play (supervised).')],
    faq: [qa('ပြန်လည်သန်စွမ်းရေး လေ့ကျင့်မှုများက အကျိုးရှိပါသလား။', 'Does therapy help?', 'ရှိပါသည်။ ကိုယ်လက်လှုပ်ရှားမှုနှင့် စကားပြောဘာသာစကားဆိုင်ရာ လေ့ကျင့်ပေးမှုများက ကလေး၏ စွမ်းရည်တိုးတက်လာစေရန် ကူညီနိုင်သည်။', 'Yes — physio and speech therapy help build skills.')],
    relatedLessons: ['lsn_what_is_development'], relatedActivities: ['act_cup_stacking'],
    references: [
      "Bull MJ et al. Health Supervision for Children and Adolescents With Down Syndrome. Pediatrics. 2022;149(5):e2022057010.",
      "CDC. About Down Syndrome. https://www.cdc.gov/birth-defects/about/down-syndrome.html (accessed 2026-07-31)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'cerebral_palsy',
    title: b('ဦးနှောက်ဆိုင်ရာ လှုပ်ရှားမှု ကွဲပြားမှု (Cerebral Palsy)', 'Understanding Cerebral Palsy'),
    overview: b('ဦးနှောက်ဆိုင်ရာ လှုပ်ရှားမှုကွဲပြားခြင်းသည် ကိုယ်လက်လှုပ်ရှားမှုနှင့် ခန္ဓာကိုယ်အနေအထား ထိန်းချုပ်မှုကို သက်ရောက်စေသော အခြေအနေတစ်ခု ဖြစ်သည်။ သက်ရောက်မှုပုံစံနှင့် အတိုင်းအတာသည် ကလေးတစ်ဦးနှင့်တစ်ဦး ကွာခြားပြီး သင့်လျော်သော ပံ့ပိုးမှုဖြင့် တိုးတက်နိုင်ပါသည်။', 'Cerebral palsy affects movement and posture. It varies widely, and many children make progress with support.'),
    strengths: [b('ဇွဲ၊ လိုက်လျောညီထွေ ဖြေရှင်းနိုင်မှု', 'Determination and adaptability'), b('စိတ်ခံစားမှုနှင့် ဆက်ဆံရေး ကောင်းမွန်မှု (မကြာခဏ)', 'Often strong communication and connection')],
    possibleSigns: [b("ကြွက်သားများ ထူးခြားစွာ တင်းနေခြင်း သို့မဟုတ် ထူးခြားစွာ ပျော့နေခြင်း", "Muscles that feel unusually stiff or unusually floppy"), b("လှုပ်ရှားမှုများ ညှိနှိုင်းမှု မရှိဘဲ တုန်ခါနေခြင်း", "Movements that look uncoordinated or jerky"), b("၈ လတွင် ထိုင်၍ မရသေးခြင်း", "Not sitting by 8 months"), b("၁၈ လတွင် လမ်း၍ မရသေးခြင်း", "Not walking by 18 months"), b("၁၂ လမပြည့်မီ လက်တစ်ဖက်တည်းကိုသာ အားကိုးသုံးစွဲခြင်း", "Strongly preferring one hand before 12 months of age"), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('စီပီ (Cerebral Palsy) သည် ကူးစက်တတ်သည် သို့မဟုတ် အချိန်ကြာလာသည်နှင့်အမျှ ပိုဆိုးလာတတ်သည်', 'CP is contagious or gets worse over time', 'မမှန်ပါ။ စီပီသည် အခြားသူထံ ကူးစက်တတ်သော အခြေအနေ မဟုတ်သလို ဦးနှောက်ဆိုင်ရာ ထိခိုက်မှု ကိုယ်တိုင်လည်း အချိန်ကြာလာသည်နှင့်အမျှ ပိုဆိုးလာခြင်း မရှိပါ။', 'No — it is not contagious and not progressive.')],
    homeSupport: [b("ကလေး၏ ကာယကုထုံးပညာရှင်နှင့် သဘောတူထားသော လေ့ကျင့်ခန်းများနှင့် အကြိမ်ရေအတိုင်း လိုက်နာပါ။ ကလေး၏ လိုအပ်ချက် ပြောင်းလဲလာသည်နှင့်အမျှ အစီအစဉ်ကို ပြန်လည်သုံးသပ်သင့်ပါသည်။", "Follow the exercises and frequency agreed with your child’s physiotherapist. The plan should be reviewed as your child’s needs change."), b("ဗီဒီယို သို့မဟုတ် အခြားကလေး၏ အစီအစဉ်အပါအဝင် ဆန့်ထုတ်ခြင်း သို့မဟုတ် ကြွက်သားခိုင်မာရေး အစီအစဉ်ကို စတင်ခြင်း သို့မဟုတ် ပြောင်းလဲခြင်းမပြုမီ သင့်ကလေးအတွက် သင့်လျော်မှုရှိမရှိ ကုသရေးအဖွဲ့ကို မေးမြန်းပါ။ ကုသရေးအဖွဲ့က မတားမြစ်ထားလျှင် ကလေး၏ စွမ်းရည်နှင့်ကိုက်ညီသော ဘေးကင်းသည့် ကစားမှုနှင့် ကိုယ်လက်လှုပ်ရှားမှုကို ဆက်လုပ်ပါ။", "Before starting or changing a stretching or strengthening programme—including one from a video or another child—ask the care team whether it is suitable for your child. Unless the care team advises otherwise, continue safe play and physical activity appropriate to your child’s abilities.")],
    schoolSupport: [b('ဝင်ရောက်လွယ်ကူသော ပတ်ဝန်းကျင်နှင့် ကိရိယာ ပံ့ပိုးမှု ရှာဖွေပါ။', 'Seek accessible settings and assistive equipment.')],
    professionalSupport: [b("ကာယကုထုံး ပညာရှင်၊ နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ကုထုံး ပညာရှင်၊ စကားပြောနှင့် ဘာသာစကား ကုထုံး ပညာရှင်နှင့် ကလေးအထူးကု ဆရာဝန်တို့နှင့် လက်တွဲပါ။", "Work with a physiotherapist, an occupational therapist, a speech and language therapist and a paediatrician."), b("ကလေးသည် အစာကျွေးစဉ် ချောင်းဆိုးခြင်း၊ အစာတစ်ဆို့ခြင်း၊ ဒုက္ခရောက်ပုံရခြင်း သို့မဟုတ် အစာစားရန် အလွန်ကြာခြင်း ရှိပါက အဖွဲ့အား အသိပေးပါ — စကားပြောနှင့် ဘာသာစကား ကုထုံး ပညာရှင်သည် အစာမျိုချမှုကိုပါ စစ်ဆေးပေးပါသည်။", "Tell the team if your child coughs, chokes or seems distressed during feeding, or takes a very long time to finish a meal — a speech and language therapist also assesses swallowing.")],
    activities: [b('ကုသရေးအဖွဲ့ ညွှန်ကြားသော ဟန်ချက်/လှုပ်ရှားမှု ကစားနည်းများ။', 'Balance/movement play as advised by the care team.')],
    faq: [qa('စောစီးစွာ ကုသမှုက အရေးကြီးသလား။', 'Is early therapy important?', 'အရေးကြီးသည် — စောစီးစွာ ကုသမှုက လှုပ်ရှားမှုနှင့် လွတ်လပ်မှုကို အထောက်အကူပြုသည်။', 'Yes — early therapy supports movement and independence.')],
    relatedLessons: ['lsn_what_is_development'], relatedActivities: ['act_obstacle_crawl'],
    references: [
      "NHS. Cerebral palsy — Symptoms. https://www.nhs.uk/conditions/cerebral-palsy/symptoms/ (accessed 2026-08-18)",
      "NHS. Cerebral palsy — Treatment. https://www.nhs.uk/conditions/cerebral-palsy/treatment/ (accessed 2026-08-18)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'hearing_loss',
    title: b('အကြားအာရုံ ချို့တဲ့မှု', 'Understanding Hearing Loss'),
    overview: b('အကြားအာရုံ ချို့တဲ့မှုသည် ပြင်းအား အမျိုးမျိုး ရှိနိုင်သည်။ စောစီးစွာ ရှာဖွေတွေ့ရှိ၍ ပံ့ပိုးခြင်းက ဘာသာစကား ဖွံ့ဖြိုးမှုအတွက် အလွန်အရေးကြီးသည်။', 'Hearing loss ranges in degree. Early detection and support are very important for language development.'),
    strengths: [b('မျက်စိဖြင့် သတိပြု/လက်ဟန်ဖြင့် ဆက်သွယ်နိုင်မှု', 'Strong visual attention and gesture use')],
    possibleSigns: [b("ကျယ်လောင်သံကြားလျှင် မလန့်ခြင်း", "Does not startle at loud sounds"), b("၆ လကျော်ပြီးနောက် အသံလာရာဘက်သို့ လှည့်မကြည့်ခြင်း", "Does not turn toward where a sound comes from after 6 months"), b("၁ နှစ်တွင် “ဖေဖေ”၊ “မေမေ” ကဲ့သို့ စကားလုံးတစ်လုံးချင်း မပြောခြင်း", "Does not say single words such as “dada” or “mama” by 1 year"), b("သင့်ကို မြင်လျှင် ခေါင်းလှည့်သော်လည်း နောက်ကွယ်မှ နာမည်ခေါ်လျှင် မလှည့်ခြင်း", "Turns their head when they see you, but not when you call their name from behind"), b("စကားပြော ဖွံ့ဖြိုးမှု နှေးခြင်း", "Speech is developing slowly"), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကလေးက အသံကို တစ်ခါတလေ တုံ့ပြန်တတ်လျှင် အကြားအာရုံ ကောင်းသည်', 'If a child sometimes responds, hearing is fine', 'မမှန်ပါ။ အသံအချို့ကိုသာ ကြားနိုင်သော တစ်စိတ်တစ်ပိုင်း အကြားအာရုံ ချို့တဲ့မှု ရှိနေနိုင်သဖြင့် ကျွမ်းကျင်သူနှင့် စနစ်တကျ စစ်ဆေးရန် လိုအပ်ပါသည်။', 'No — partial hearing loss exists; a proper test is needed.')],
    homeSupport: [b('မျက်နှာချင်းဆိုင်၍ ရှင်းလင်းစွာ ပြောပါ။ လက်ဟန်/ပုံများ သုံးပါ။', 'Face the child, speak clearly, use gestures/pictures.')],
    schoolSupport: [b('ရှေ့တန်း ထိုင်ခုံနှင့် မျက်စိဖြင့် ပံ့ပိုးမှုများ ပေးပါ။', 'Front seating and visual supports.')],
    professionalSupport: [b("အကြားအာရုံ စစ်ဆေးမှုကို အကြားအာရုံ ကျွမ်းကျင်သူ (audiologist) နှင့် အမြန် ပြုလုပ်ပါ။", "Get a hearing test with an audiologist promptly."), b("အကြံပြု အချိန်ဇယားမှာ — အသက် ၁ လမပြည့်မီ အကြား စစ်ဆေးမှု၊ မအောင်မြင်ပါက ၃ လအတွင်း ပြည့်စုံသော အကြားစစ်ဆေးမှု၊ ၆ လအတွင်း ပံ့ပိုးမှု စတင်ရန် ဖြစ်ပါသည်။", "The recommended timetable is: hearing screening by 1 month of age; if not passed, a full hearing test by 3 months; and support started by 6 months."), b("သင့်ကလေး မွေးကင်းစတွင် အကြားစစ်ဆေးမှု မပြုလုပ်ရသေးပါက ယခုပင် တောင်းခံပါ — နောက်ကျပြီဟု မဆိုနိုင်သေးပါ။ ဤစစ်ဆေးမှုကို သင့်အနီးတွင် ဘယ်နေရာ၌ ရနိုင်သည်ကို ဆရာဝန်အား မေးမြန်းပါ။", "If your child did not have a newborn hearing screening, ask for one now — it is not too late. Ask your doctor where this test is available near you.")],
    activities: [b('မျက်စိဖြင့် သတိပြုစေသော ကစားနည်းများ။', 'Games that use visual attention.')],
    faq: [qa('စောစီးစွာ စစ်ဆေးမှုက အရေးကြီးသလား။', 'Is early testing important?', 'အလွန်အရေးကြီးပါသည် — အချိန်မီ တစ်ဦးချင်းလိုအပ်ချက်နှင့် ကိုက်ညီသော ပံ့ပိုးမှုက ဘာသာစကားနှင့် ဆက်သွယ်မှု ဖွံ့ဖြိုးတိုးတက်နိုင်ခြေကို ပိုမိုကောင်းမွန်စေပါသည်။', 'Very — timely, individualized support improves the likelihood of strong language and communication development.')],
    relatedLessons: ['lsn_language_rich_home'], relatedActivities: ['act_sound_tracking'],
    references: [
      "CDC. Early Hearing Detection and Intervention (EHDI) Partner Toolkit. https://www.cdc.gov/hearing-loss-children/php/ehdi-toolkit/index.html (accessed 2026-08-18)",
      "CDC. Treatment and Intervention for Hearing Loss. https://www.cdc.gov/hearing-loss-children/treatment/index.html (accessed 2026-08-18)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'visual_impairment',
    title: b('မျက်စိအမြင် ချို့တဲ့မှု', 'Understanding Visual Impairment'),
    overview: b('အမြင်အာရုံ အားနည်းမှုသည် ကလေးတစ်ဦးနှင့်တစ်ဦး အတိုင်းအတာ ကွာခြားနိုင်သည်။ စောစီးစွာ သိရှိပြီး သင့်လျော်သော ပံ့ပိုးမှုရရှိပါက ကလေးများ ကောင်းစွာ ဖွံ့ဖြိုးတိုးတက်နိုင်သည်။', 'Visual impairment varies in degree. With early detection and support, children thrive.'),
    strengths: [b('အကြားအာရုံနှင့် ထိတွေ့ခံစားမှု ကောင်းမွန်မှု', 'Strong hearing and touch senses')],
    possibleSigns: [b("မျက်လုံးဖြင့် အရာဝတ္ထု သို့မဟုတ် မျက်နှာကို မလိုက်ကြည့်ခြင်း", "Not following objects or faces with their eyes"), b("မျက်လုံး လှုပ်ရှားမှု ထူးခြားခြင်း", "Unusual eye movements"), b("အောက်ပါတို့ တွေ့ပါက ဆရာဝန်ထံ အမြန်ဆုံး ပြသပါ — မျက်သူငယ်အဝိုင်း ဖြူဖျော့ဖျော့/မီးခိုးရောင်/မှုန်ဝါးနေခြင်း (ဓာတ်ပုံ မီးလျှပ်ရိုက်ထားသည့် ပုံတွင် တွေ့ရသည်လည်း အပါအဝင်)၊ အသက် ၄ လကျော်ပြီးနောက် မျက်လုံးတစ်ဖက် အမြဲ အတွင်း/အပြင်သို့ စောင်းနေခြင်း၊ သို့မဟုတ် မျက်လုံးများ အလင်းကို အလွန်ခံနိုင်ရည်မရှိခြင်း/မျက်ရည် အမြဲယိုစီးခြင်း။ ဤအချက်များကို နောက်ထပ် ပုံမှန်ချိန်းဆိုမှုအထိ မစောင့်ဘဲ အမြန် စစ်ဆေးရန် လိုပါသည်။", "See a doctor urgently if you notice: a white, grey or cloudy pupil (including in flash photographs), an eye that constantly turns in or out after 4 months of age, or eyes that are very sensitive to light or watering constantly. These need to be checked quickly, not at the next routine visit."), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('မျက်မှန်တပ်ဆင်ခြင်းက မျက်စိကို ပိုမို အားနည်းစေသည်', 'Glasses make eyes weaker', 'မဟုတ်ပါ။ သင့်လျော်သော မျက်မှန်သည် အမြင်အာရုံ ကောင်းမွန်စေရန် ကူညီပါသည်။', 'No — the right glasses help vision.')],
    homeSupport: [b('အသံ/ထိတွေ့မှုဖြင့် ဆက်သွယ်၍ ဘေးကင်းသော ပတ်ဝန်းကျင် ဖန်တီးပါ။', 'Connect through sound/touch; keep a safe, predictable space.')],
    schoolSupport: [b('အလင်းရောင် ကောင်း၊ ကြီးမားသော စာလုံး/ထိတွေ့ပစ္စည်းများ ပေးပါ။', 'Good lighting, large print or tactile materials.')],
    professionalSupport: [b("မျက်စိအထူးကုနှင့် စောစီးစွာ ပံ့ပိုးရေး ဝန်ဆောင်မှုများနှင့် တိုင်ပင်ပါ။", "Consult an eye specialist and early-support services."), b("ကလေး ပုံမှန်ဟု ထင်ရသော်လည်း ပုံမှန် အမြင်အာရုံ စစ်ဆေးမှုကို တောင်းခံပါ — မွေးကင်းစတွင် red reflex စစ်ဆေးမှု အပါအဝင် မျက်စိစစ်ဆေးမှု၊ ၁၂ လမှ ၃ နှစ်အတွင်း ပုံမှန်ပြသချိန်များတွင် စစ်ဆေးမှု။ မျက်လုံးတစ်ဖက် ကောင်းပြီး တစ်ဖက် အားနည်းနေသော ကလေးသည် ပုံမှန်အတိုင်းပင် နေတတ်ပါသည် — ကုသချိန်မီ တွေ့ရှိရန် စစ်ဆေးမှုသာ နည်းလမ်း ဖြစ်ပါသည်။", "Ask for routine vision screening even if your child seems fine: a newborn eye check including the red reflex test, and from 12 months to 3 years a screening check at routine visits. A child who sees well with one eye and poorly with the other usually behaves completely normally — screening is how this is found in time to treat it.")],
    activities: [b('ထိတွေ့ခံစားမှုနှင့် အသံဖြင့် ကစားနည်းများ။', 'Touch-and-sound play.')],
    faq: [qa('စောစီးစွာ ရှာဖွေတွေ့ရှိမှုက ကူညီသလား။', 'Does early detection help?', 'ကူညီသည် — စောစီးစွာ ပံ့ပိုးမှုက ဖွံ့ဖြိုးမှုကို အထောက်အကူပြုသည်။', 'Yes — early support aids development.')],
    relatedLessons: ['lsn_power_of_play'], relatedActivities: ['act_sound_tracking'],
    references: [
      "Donahue SP, Nixon CN, et al. Visual System Assessment in Infants, Children, and Young Adults by Pediatricians. Pediatrics. 2016;137(1):e20153596.",
      "American Academy of Ophthalmology. Common Eye and Vision Myths. https://www.aao.org/eye-health/tips-prevention/common-eye-vision-myths-facts (accessed 2026-07-31)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'global_developmental_delay',
    title: b('ဘက်စုံ ဖွံ့ဖြိုးမှု နှောင့်နှေးမှု', 'Understanding Global Developmental Delay'),
    overview: b('ဤသည်မှာ ဖွံ့ဖြိုးမှု နယ်ပယ် အများအပြားတွင် မျှော်မှန်းထားသည်ထက် နှေးနေခြင်းဖြစ်သည်။ အကြောင်းရင်း ရှာဖွေ၍ စောစီးစွာ ပံ့ပိုးခြင်းက အရေးကြီးသည်။', 'This is slower-than-expected development across several areas. Finding the cause and starting early support matter.'),
    strengths: [b('ကိုယ်ပိုင်အရှိန်ဖြင့် တိုးတက်နိုင်မှု', 'Progress at their own pace')],
    possibleSigns: [b('လှုပ်ရှားမှု၊ ဘာသာစကား၊ တွေးခေါ်မှု အများအပြားတွင် နှေးခြင်း', 'Delays in movement, language, and thinking together'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('“ကလေးက ကြီးလာရင် သူ့အလိုလို ကောင်းသွားမှာပါ၊ စောင့်ကြည့်ရုံပဲ”', '“They’ll grow out of it — just wait”', 'မမှန်ပါ။ စောင့်ကြည့်နေရုံသက်သက်ဖြင့် အလွန်အကျိုးရှိသော စောစောစီးစီး ကြားဝင်ပံ့ပိုးမှု အခွင့်အလမ်းကောင်းများ ဆုံးရှုံးသွားနိုင်ပါသည်။', 'Simply waiting can miss the window for helpful early support.')],
    homeSupport: [b('နေ့စဉ်လုပ်ဆောင်ချက်များထဲ သင်ခန်းစာနှင့် ကစားခြင်း ထည့်ပါ။', 'Weave learning and play into daily routines.')],
    schoolSupport: [b('တစ်ဦးချင်း ပံ့ပိုးမှုနှင့် ပါဝင်စေသော ပတ်ဝန်းကျင် ရှာဖွေပါ။', 'Seek individual support and inclusive settings.')],
    professionalSupport: [b("ပုံမှန် ပြသချိန်များတွင် ဖွံ့ဖြိုးမှု စစ်ဆေးမှုကို တောင်းခံပါ — မည်သူမျှ စိုးရိမ်စရာ မတွေ့ရသေးသည့်အခါတွင်ပင် ၉ လ၊ ၁၈ လနှင့် ၃၀ လအရွယ်ခန့်တွင် စံသတ်မှတ် စစ်ဆေးမှု ပြုလုပ်ရန် အကြံပြုထားပါသည်။", "Ask for a developmental check at your child’s routine visits — a standard screening is recommended at around 9 months, 18 months and 30 months, even when nobody has raised a concern."), b("စိုးရိမ်ပါက ထိုအချိန်များကို မစောင့်ဘဲ မည်သည့်အချိန်တွင်မဆို စစ်ဆေးမှု တောင်းခံနိုင်ပါသည်။ နှောင့်နှေးမှု တွေ့ရှိပါက ကလေးဖွံ့ဖြိုးမှုဆိုင်ရာ ဆရာဝန်ထံ ညွှန်းပို့ပေးရန်နှင့် စောစီးစွာ ကြားဝင်ပံ့ပိုးမှု ဝန်ဆောင်မှုများကို တောင်းခံပါ။", "You can also ask for a screening at any time if you are worried. If a delay is found, ask for a referral to a developmental paediatrician and for early intervention services.")],
    activities: [b('အသက်အရွယ်နှင့်လိုက်လျော၍ ရိုးရှင်းသော ကစားနည်းများ။', 'Simple, developmentally-matched play.')],
    faq: [qa('အကြောင်းရင်း ရှာသင့်ပါသလား။', 'Should we look for a cause?', "သင့်ပါသည် — စစ်ဆေးမှုသည် အချို့ကလေးများတွင် အကြောင်းရင်းကို တွေ့ရှိစေပြီး သင့်လျော်သော ပံ့ပိုးမှုကို စီစဉ်ရာတွင် အထောက်အကူ ဖြစ်ပါသည်။ သို့သော် အဖြေရမှ ပံ့ပိုးမှု စတင်ရန် မစောင့်ပါနှင့်။ နှောင့်နှေးမှု တွေ့ရှိသည်နှင့် စစ်ဆေးမှုများနှင့် တစ်ပြိုင်နက် စောစီးစွာ ကြားဝင်ပံ့ပိုးမှုကို စတင်သင့်ပါသည်။ ကလေးများစွာတွင် အကြောင်းရင်း တစ်ခုတည်းကို ဘယ်တော့မှ မတွေ့ရှိရဘဲ ရှိတတ်ပြီး — ထိုအချက်က အထောက်အကူပြုသည့် အရာများကို မပြောင်းလဲစေပါ။", "Yes, an assessment is worth having — it can find a cause in some children and helps plan the right support. But do not wait for an answer before starting support. Early intervention should begin as soon as a delay is identified, at the same time as any tests. In many children no single cause is ever found, and that does not change what helps.")],
    relatedLessons: ['lsn_what_is_development'], relatedActivities: ['act_cup_stacking'],
    references: [
      "Lipkin PH, Macias MM. Promoting Optimal Development: Identifying Infants and Young Children With Developmental Disorders Through Developmental Surveillance and Screening. Pediatrics. 2020;145(1):e20193449.",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'learning_disability',
    title: b('သင်ယူမှု အခက်အခဲ (Specific Learning Difficulty)', 'Understanding Learning Difficulty (Specific Learning Disorder)'),
    overview: b('dyslexia၊ dyscalculia ကဲ့သို့ သင်ယူမှု အခက်အခဲသည် စာဖတ်ခြင်း၊ စာရေးခြင်း၊ သင်္ချာ စသည့် သီးသန့် ကျွမ်းကျင်မှုများကို သက်ရောက်ပါသည်။ ယေဘုယျ ဉာဏ်ရည်ကို မထိခိုက်ပါ။ ငယ်ရွယ်စဉ် အတည်ပြုရန် ခက်ခဲပြီး ကျောင်းနေအရွယ်တွင် ပိုရှင်းလာတတ်ပါသည်။ မှတ်ချက် — ၎င်းသည် ဉာဏ်ရည်ဖွံ့ဖြိုးမှုဆိုင်ရာ ချို့တဲ့မှု (intellectual disability) နှင့် မတူပါ။ ဉာဏ်ရည်ဖွံ့ဖြိုးမှုဆိုင်ရာ ချို့တဲ့မှုသည် ယေဘုယျ ဉာဏ်ရည်နှင့် နေ့စဉ်ဘဝ လိုက်လျောညီထွေ နေနိုင်စွမ်းကို သက်ရောက်ပြီး ဖွံ့ဖြိုးမှုကာလအတွင်း စတင်ပါသည်။ သို့သော် မွေးကင်းစကာလ၊ ကလေးဘဝ၊ ဆယ်ကျော်သက်အရွယ် သို့မဟုတ် ထိုထက်နောက်ပိုင်းတွင် သိရှိအတည်ပြုနိုင်ပါသည်။', 'A learning difficulty such as dyslexia or dyscalculia affects specific skills like reading, writing or maths. It does not affect general intelligence. It is hard to confirm at very young ages and usually becomes clearer at school age. Note: this differs from intellectual disability, which affects general intellectual and adaptive functioning and begins during the developmental period, but may be identified in infancy, childhood, adolescence, or later.'),
    strengths: [b('တီထွင်ဖန်တီးမှုနှင့် ပြဿနာ ဖြေရှင်းနိုင်မှု', 'Creativity and problem-solving')],
    possibleSigns: [b('ကျောင်းအရွယ်တွင် သီးခြား ကျွမ်းကျင်မှုတစ်ခု သင်ယူရ ဆက်တိုက် ခက်ခဲခြင်း', 'Ongoing difficulty with one specific skill at school age'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('သင်ယူမှု အခက်အခဲ ရှိရင် ဉာဏ်နည်းတယ်', 'A learning difficulty means low intelligence', 'မဟုတ်ပါ — ဉာဏ်ရည်နှင့် မသက်ဆိုင်ဘဲ သင်ယူပုံ ကွဲပြားခြင်းဖြစ်သည်။', 'No — it is unrelated to intelligence; just a different way of learning.')],
    homeSupport: [b('အားသာချက်ကို အသုံးပြု၍ သင်ကြားပါ။ ကြိုးစားမှုကို ချီးမွမ်းပါ။', 'Teach through strengths; praise effort.')],
    schoolSupport: [b('သင်ကြားမှု ပုံစံ ချိန်ညှိမှုနှင့် အချိန်ပို ပေးပါ။', 'Provide teaching adjustments and extra time.')],
    professionalSupport: [b('ကျောင်းအရွယ်တွင် ပညာရေးစိတ်ပညာရှင်နှင့် တိုင်ပင်ပါ။', 'At school age, consult an educational psychologist.')],
    activities: [b('ကစားရင်း သင်ယူသော အက္ခရာ/သင်္ချာ ကစားနည်းများ။', 'Playful letter/number games.')],
    faq: [qa('ငယ်ရွယ်စဉ် သိနိုင်သလား။', 'Can it be known early?', 'ငယ်ရွယ်စဉ် အတည်ပြုရ ခက်ခဲ၍ ကျောင်းအရွယ်တွင် ပို၍ ရှင်းလင်းလာတတ်သည်။', 'It is hard to confirm early; it usually becomes clearer at school age.')],
    relatedLessons: ['lsn_early_math'], relatedActivities: ['act_name_writing'],
    references: [
      "NHS. Learning disabilities. https://www.nhs.uk/conditions/learning-disabilities/ (accessed 2026-08-18)",
      "Mencap. What is a learning disability? https://www.mencap.org.uk/learning-disability-explained/what-learning-disability (accessed 2026-07-31)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'sensory_processing',
    title: b('အာရုံခံစားမှု စီမံဆောင်ရွက်မှု ကွဲပြားမှု', 'Understanding Sensory Processing Differences'),
    overview: b("အချို့ကလေးများသည် အသံ၊ အလင်း၊ ထိတွေ့မှု၊ လှုပ်ရှားမှုတို့ကို ပိုမို သို့မဟုတ် နည်းပါးစွာ ခံစားတတ်ပြီး နေ့စဉ်ဘဝကို သက်ရောက်နိုင်ပါသည်။ အရေးကြီးသည် — အာရုံခံစားမှု ကွဲပြားချက်သည် သီးသန့် အခြေအနေတစ်ခုအဖြစ်ထက် ပိုကြီးသော ပုံရိပ်တစ်ခု၏ အစိတ်အပိုင်း ဖြစ်လေ့ရှိပါသည် — အော်တစ်ဇင်၊ ADHD၊ လှုပ်ရှားမှု ညှိနှိုင်းမှု အခက်အခဲ သို့မဟုတ် စိုးရိမ်စိတ်တို့နှင့် အတူတွေ့ရလေ့ ရှိပါသည်။ ကလေး၏ နေ့စဉ်ဘဝကို သက်ရောက်နေပါက အာရုံခံစားမှု ကုထုံး တစ်ခုတည်းထက် ဘက်စုံ ဖွံ့ဖြိုးမှု စစ်ဆေးမှုကို ဦးစွာ တောင်းခံပါ။", "Some children feel sounds, light, touch, or movement more or less intensely, and this can affect daily life. Important: sensory differences are usually part of a wider picture rather than a condition on their own — they are often seen alongside autism, ADHD, coordination difficulties or anxiety. If sensory difficulties are affecting your child’s daily life, ask for a full developmental assessment first, rather than sensory therapy alone."),
    strengths: [b('အသေးစိတ် သတိပြုနိုင်မှုနှင့် ခံစားမှု ကြွယ်ဝမှု', 'Rich awareness and attention to detail')],
    possibleSigns: [b('အဝတ်အထည်/အသံ/အစားအစာ ဖွဲ့စည်းပုံကို ပြင်းထန်စွာ တုံ့ပြန်ခြင်း', 'Strong reactions to textures, sounds, or food'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကလေး အနိုင်ကျင့်နေတာ/ပျက်ပျက်လုပ်နေတာ', 'The child is just being difficult', 'မကြာခဏ ၎င်းသည် ခံစားမှု ကွဲပြားမှုကြောင့်ဖြစ်၍ အပြစ်တင်ခြင်းက အထောက်အကူ မဖြစ်ပါ။', 'Often it is a genuine sensory difference; blame does not help.')],
    homeSupport: [b('ခံစားမှု ပြင်းအားကို ချိန်ညှိပါ (တိတ်ဆိတ်နေရာ၊ နူးညံ့အဝတ်)။', 'Adjust the sensory load (quiet space, soft clothing).')],
    schoolSupport: [b('အနားယူ/ငြိမ်သက်နိုင်သော နေရာ ပေးပါ။', 'Offer a calm-down/break space.')],
    professionalSupport: [b("နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ပြန်လည်လေ့ကျင့်ပေးသည့် ပညာရှင်သည် ပိုကျယ်ပြန့်သော ပံ့ပိုးမှု အစီအစဉ်၏ အစိတ်အပိုင်းတစ်ခုအဖြစ် ကူညီနိုင်ပါသည်။", "An occupational therapist can help as one part of a wider support plan."), b("သိထားသင့်သည်မှာ — အာရုံခံစားမှု ပေါင်းစပ်ကုထုံး၏ ထိရောက်မှုအပေါ် သုတေသနမှာ အကန့်အသတ်ရှိပြီး တိကျသော ကောက်ချက် မချနိုင်သေးပါ။ ထို့ကြောင့် ကုထုံးပညာရှင်နှင့် ရည်မှန်းချက်နှင့် ပြန်လည်သုံးသပ်မည့် ရက်ကို ရှင်းလင်းစွာ သတ်မှတ်ပြီး — မည်သည့် ပြောင်းလဲမှုကို မည်မျှအချိန်အတွင်း မျှော်လင့်ရမည်ကို မေးမြန်းပါ။", "You should know that research on the effectiveness of sensory integration therapy is still limited and not conclusive — so agree clear goals and a review date with the therapist, and ask what change you should expect to see and by when.")],
    activities: [b('ကလေး အဆင်ပြေသည့်အတိုင်း မျက်နှာပြင်အထိအတွေ့ မတူညီသော ပစ္စည်းများဖြင့် ဖြည်းဖြည်းချင်း ကစားပါ။', 'Gentle textured play at the child’s comfort level.')],
    faq: [qa('ဤအခြေအနေ အမြဲတမ်း ဖြစ်နေမလား။', 'Is this permanent?', "အကြောင်းရင်းပေါ် မူတည်ပါသည်။ ကလေးများစွာသည် အချိန်နှင့် ပံ့ပိုးမှုနှင့်အမျှ ပိုကောင်းစွာ ရင်ဆိုင်နိုင်လာပါသည်။ အာရုံခံစားမှု အခက်အခဲသည် အခြားအခြေအနေတစ်ခု၏ အစိတ်အပိုင်း ဖြစ်တတ်သောကြောင့် — သင့်ကလေးအတွက် အဖြေကို စစ်ဆေးမှုက ပိုရှင်းစေပါသည်။", "It depends on what is causing it. Many children learn to cope better with time and support. Because sensory difficulties are often part of another condition, an assessment helps answer this question for your child specifically.")],
    relatedLessons: ['lsn_big_feelings'], relatedActivities: ['act_water_pouring'],
    references: [
      "AAP Section on Complementary and Integrative Medicine; Council on Children with Disabilities. Sensory Integration Therapies for Children With Developmental and Behavioral Disorders. Pediatrics. 2012;129(6):1186–1189.",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'dyslexia',
    title: b('စာဖတ်ခြင်း အခက်အခဲ (Dyslexia)', 'Understanding Dyslexia'),
    overview: b('ဒစ်စလက်စီယာ (Dyslexia) သည် စာဖတ်ခြင်းနှင့် စာလုံးပေါင်းသတ်ပုံ ရေးသားခြင်းတို့အပေါ် သက်ရောက်မှုရှိသော သင်ယူမှု ကွဲပြားခြင်း ဖြစ်ပါသည်။ ယင်းသည် ဉာဏ်ရည်ဉာဏ်သွေးနှင့် လုံးဝ မသက်ဆိုင်ဘဲ ကျောင်းနေအရွယ်သို့ ရောက်သောအခါ ပိုမိုထင်ရှားလာတတ်ပါသည်။', 'Dyslexia is a learning difference affecting reading/spelling. It is unrelated to intelligence and usually becomes clearer at school age.'),
    strengths: [b('ဖန်တီးမှု၊ ပုံရိပ်ဖြင့် တွေးခေါ်နိုင်မှု', 'Creativity and big-picture thinking')],
    possibleSigns: [b("ကျောင်းမတက်မီ အရွယ်တွင် — အခြားကလေးများထက် စကားပြော နောက်ကျခြင်း၊ ကာရန်ခံ စကားများ/သီချင်းများ/အက္ခရာ ကစားနည်းများကို စိတ်မဝင်စားခြင်း၊ စကားလုံးနှစ်လုံး ကာရန်ညီသည်ကို နားမခွဲခြားနိုင်ခြင်း", "Before school age: talking later than other children, not enjoying rhymes, songs or letter games, difficulty hearing that two words rhyme"), b("ကျောင်းနေအရွယ်တွင် — စာလုံးနှင့် အသံ ချိတ်ဆက်ရန် ခက်ခဲခြင်း၊ အသက်အရွယ်နှင့် လိုက်ဖက်သည့် အဆင့်ထက် စာဖတ် နိမ့်ခြင်း၊ အသံထွက်ဖတ်ရာတွင် နှေးခြင်း", "At school age: difficulty linking letters and sounds, reading below the level expected for their age, slow reading aloud"), b("ကျောင်းမတက်မီကတည်းက Dyslexia ဖြစ်နိုင်ခြေ လက္ခဏာများကို သတိပြုနိုင်သော်လည်း တရားဝင်စစ်ဆေးအတည်ပြုမည့် အချိန်သည် ကလေးအလိုက် ကွာခြားနိုင်ပါသည်။ စာအတူဖတ်ခြင်း၊ ကာရန်ခံစကားများနှင့် စာလုံး–အသံ ဆက်စပ်မှုကို ရှင်းလင်းစနစ်တကျ သင်ပေးခြင်းတို့ကဲ့သို့ အစောပိုင်း ဘာသာစကားနှင့် စာတတ်မြောက်မှု ပံ့ပိုးမှုသည် အထောက်အကူပြုနိုင်ပါသည်။ ကျောင်းတွင် အကြိမ်ကြိမ် အခက်အခဲကြုံမှသာ အကူအညီတောင်းရန် မစောင့်ပါနှင့်။", "Risk signs for dyslexia can be identified before school, although the timing of formal identification varies. Early language and literacy support—including shared reading, rhymes, and explicit teaching of letter–sound relationships—can help. Do not wait for repeated school failure before seeking support."), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('Dyslexia ဆိုတာ စာလုံးတွေ ပြောင်းပြန်မြင်တာပဲ', 'Dyslexia is just seeing letters backwards', "မဟုတ်ပါ။ စာလုံးကို ပြောင်းပြန်မြင်ခြင်း သို့မဟုတ် ရေးခြင်းတစ်ခုတည်းက Dyslexia ကို သတ်မှတ်ခြင်း မဟုတ်ပါ။ Dyslexia တွင် စကားလုံးကို မှန်ကန်စွာ သို့မဟုတ် သွက်လက်စွာ ဖတ်ခြင်းနှင့်/သို့မဟုတ် စာလုံးပေါင်းခြင်းတို့၌ ဆက်တိုက်အခက်အခဲ ရှိတတ်ပါသည်။ အသံ သို့မဟုတ် စကားလုံးဖွဲ့စည်းပုံ စီမံဆောင်ရွက်မှု အခက်အခဲများ မကြာခဏ တွေ့ရသော်လည်း လူတိုင်းတွင် မရှိပါ။", "No. Letter reversals alone do not define dyslexia. Dyslexia is characterized by persistent difficulty with accurate or fluent word reading and/or spelling. Phonological or morphological processing difficulties are common but not universal.")],
    homeSupport: [b('အသံ-စာလုံး ကစားနည်းများ၊ ကြားနာစာဖတ်ခြင်း လုပ်ပါ။', 'Play sound–letter games; read aloud together.')],
    schoolSupport: [b('အချိန်ပို၊ ကြားနာ/ပုံ ပံ့ပိုးမှုများ ပေးပါ။', 'Provide extra time and audio/visual supports.')],
    professionalSupport: [b('ပညာရေးစိတ်ပညာရှင်/စာဖတ်အထူးကုဆရာမနှင့် တိုင်ပင်ပါ။', 'Consult an educational psychologist or reading specialist.')],
    activities: [b('စကားလုံး ကာရန်/အသံ ကစားနည်းများ။', 'Rhyming and sound games.')],
    faq: [qa('စောစီးစွာ ပံ့ပိုးမှုက ကူညီသလား။', 'Does early support help?', 'ကူညီသည် — သင့်လျော်သော နည်းလမ်းများက စာဖတ်ခြင်းကို အထောက်အကူပြုသည်။', 'Yes — the right methods support reading.')],
    relatedLessons: ['lsn_reading_together'], relatedActivities: ['act_name_writing'],
    references: [
      "Sanfilippo J et al. Reintroducing Dyslexia: Early Identification and Implications for Pediatric Practice. Pediatrics. 2020;146(1):e20193046. doi:10.1542/peds.2019-3046.",
      "NHS. Dyslexia in children. https://www.nhs.uk/conditions/dyslexia-in-children/ (accessed 2026-08-18)",
      "International Dyslexia Association. Definition of Dyslexia. Adopted October 22, 2025. https://dyslexiaida.org/definition-of-dyslexia/ (accessed 2026-08-18)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'developmental_coordination_disorder',
    title: b('ဖွံ့ဖြိုးမှုဆိုင်ရာ လှုပ်ရှားမှု ညှိနှိုင်းခြင်း အခက်အခဲ (DCD)', 'Understanding Developmental Coordination Disorder (DCD)'),
    overview: b('DCD သည် အဝတ်ခလုတ်တပ်ခြင်း၊ ကတ်ကြေးဖြင့် ဖြတ်ခြင်းနှင့် ဘောလုံးဖမ်းခြင်းကဲ့သို့ ကိုယ်လက်လှုပ်ရှားမှု ညှိနှိုင်းခြင်းကို အဓိက သက်ရောက်စေပါသည်။ ယင်းသည် ကလေး၏ ဉာဏ်ရည်ကို တိုင်းတာသော အခြေအနေ မဟုတ်သော်လည်း အခြားသင်ယူမှု သို့မဟုတ် ဖွံ့ဖြိုးမှုဆိုင်ရာ အခြေအနေများနှင့် အတူရှိနိုင်ပါသည်။', 'DCD primarily affects motor coordination, such as buttoning, cutting and catching. It is not a measure of intelligence, although learning or developmental conditions can coexist.'),
    strengths: [b('ဇွဲနှင့် ကြိုးစားမှု', 'Persistence and effort')],
    possibleSigns: [b('အသက်အရွယ်ထက် လှုပ်ရှားမှု ကျွမ်းကျင်မှုများ နှေးခြင်း/မတိကျခြင်း', 'Motor skills slower or clumsier than peers'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကလေးက ပျင်းရိခြင်း သို့မဟုတ် ပေါ့ဆခြင်းကြောင့် မလုပ်နိုင်ခြင်း ဖြစ်သည်', 'The child is just lazy or careless', 'မမှန်ပါ။ ကလေး၏ စိတ်ဆန္ဒကြောင့် မဟုတ်ဘဲ အမှန်တကယ် ကိုယ်လက်လှုပ်ရှားမှု ညှိနှိုင်းနိုင်စွမ်း ကွဲပြားမှုကြောင့် ဖြစ်ပါသည်။', 'No — it is a real coordination difference.')],
    homeSupport: [b('လှုပ်ရှားမှု ကျွမ်းကျင်မှုများကို အပိုင်းလိုက် ခွဲ၍ လေ့ကျင့်ပေးပါ။', 'Break motor skills into small steps to practice.')],
    schoolSupport: [b('ရေးသားမှု/ကိုယ်လက်လှုပ်ရှားမှုတွင် အချိန်ပိုနှင့် ချိန်ညှိမှုများ ပေးပါ။', 'Allow extra time and adjustments for writing/PE.')],
    professionalSupport: [b('နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ပြန်လည်လေ့ကျင့်ပေးသည့် ပညာရှင် သို့မဟုတ် ကိုယ်လက်လှုပ်ရှားမှု ပြန်လည်သန်စွမ်းရေးပညာရှင်နှင့် တိုင်ပင်ပါ။', 'Consult an occupational therapist or physiotherapist.')],
    activities: [b('ဟန်ချက်နှင့် လက်-မျက်စိ ညှိနှိုင်းမှု ကစားနည်းများ။', 'Balance and hand–eye coordination play.')],
    faq: [qa('လေ့ကျင့်မှုက တိုးတက်စေသလား။', 'Does practice help?', 'ကူညီသည် — အပိုင်းလိုက် လေ့ကျင့်ခြင်းနှင့် ပံ့ပိုးမှုက ကျွမ်းကျင်မှုကို တိုးတက်စေသည်။', 'Yes — step-by-step practice and support build skills.')],
    relatedLessons: ['lsn_power_of_play'], relatedActivities: ['act_obstacle_course'],
    references: [
      "NHS. Diagnosis — Developmental co-ordination disorder (dyspraxia) in children. https://www.nhs.uk/conditions/developmental-coordination-disorder-dyspraxia/diagnosis/ (accessed 2026-08-18)",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
  specialNeed({
    key: 'selective_mutism',
    title: b('အခြေအနေအလိုက် စကားမပြောနိုင်ခြင်း (Selective Mutism)', 'Understanding Selective Mutism'),
    overview: b('အခြေအနေအလိုက် စကားမပြောနိုင်ခြင်းဆိုသည်မှာ ကလေးက အိမ်တွင် စကားပြောနိုင်သော်လည်း ကျောင်းကဲ့သို့ အချို့နေရာများတွင် စကားမပြောနိုင်ခြင်း ဖြစ်သည်။ ယင်းသည် ခေါင်းမာခြင်း မဟုတ်ဘဲ စိုးရိမ်ပူပန်မှုနှင့် ဆက်စပ်နိုင်သည်။', 'Selective mutism is when a child can speak at home but not in certain settings (e.g., school). It is not defiance — it is linked to anxiety.'),
    strengths: [b('ရင်းနှီးသော နေရာတွင် ဆက်သွယ်နိုင်မှု', 'Communicates well in comfortable settings')],
    possibleSigns: [b("အိမ်တွင် စကားပြောသော်လည်း ကျောင်း သို့မဟုတ် အများရှေ့တွင် အမြဲ တိတ်ဆိတ်နေခြင်း", "Speaks at home but is consistently silent at school or in public"), b("များသောအားဖြင့် အသက် ၂ နှစ်မှ ၄ နှစ်ကြားတွင် စတင်တတ်သည်", "Most often starts between the ages of 2 and 4"), b("အရေးကြီးသည် — ကလေးသည် အိမ်တွင်ပါ အခြေအနေအများစု၌ စကားအလွန်နည်းပါက ယင်းသည် အခြေအနေအလိုက် စကားမပြောနိုင်ခြင်း၏ ပုံမှန်လက္ခဏာပုံစံနှင့် မကိုက်နိုင်ပါ။ အကြားအာရုံ စစ်ဆေးမှုနှင့် စကားပြော/ဘာသာစကားဆိုင်ရာ အကဲဖြတ်မှု အပါအဝင် ကျွမ်းကျင်ပညာရှင်၏ စစ်ဆေးမှု ခံယူပါ။", "Important: if your child speaks very little in most settings, including at home, this may not fit the usual pattern of selective mutism. Seek professional assessment, including hearing and speech-language evaluation."), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကလေးက တမင်သက်သက် စကားမပြောဘဲ နေခြင်းဖြစ်သည်', 'The child is refusing to talk on purpose', 'မဟုတ်ပါ။ စိုးရိမ်ပူပန်မှုကြောင့် ဖြစ်ပြီး စကားပြောရန် ဖိအားပေးခြင်းက အခြေအနေကို ပိုမို ခက်ခဲစေနိုင်ပါသည်။', 'No — it is anxiety-driven; pressure makes it worse.')],
    homeSupport: [b("ကလေးကို စကားပြောရန် ဖိအားမပေးပါနှင့်။ စကားပြောမှ ဆုပေးမည်ဟု အပေးအယူ မလုပ်ပါနှင့်။ ကုသရေးအဖွဲ့က အဆင့်လိုက် အားပေးမှုအစီအစဉ် သတ်မှတ်ထားပါက ၎င်းတို့၏ လမ်းညွှန်ချက်အတိုင်း လိုက်နာပါ။", "Do not pressure or bargain with your child to make them speak. If the treatment team uses a planned, gradual reinforcement programme, follow their guidance."), b("သက်တောင့်သက်သာ ရှိသော အခြေအနေများကို တဖြည်းဖြည်း တည်ဆောက်ပေးပြီး — ကြားကာလတွင် အခြားနည်းလမ်းများဖြင့် ဆက်သွယ်ခွင့် ပေးပါ။", "Build up comfortable situations gradually, and let them communicate in other ways in the meantime.")],
    schoolSupport: [b('ဆရာမနှင့် ပူးပေါင်း၍ ဖိအားနည်းသော ဆက်သွယ်နည်းများ (ခေါင်းညိတ်/ရေး) ခွင့်ပြုပါ။', 'Work with the teacher; allow low-pressure communication (nod/write).')],
    professionalSupport: [b("ဆရာဝန်နှင့် တိုင်ပင်ပါ — စကားပြောနှင့် ဘာသာစကားဆိုင်ရာ ပညာရှင် သို့မဟုတ် ကလေးစိတ်ကျန်းမာရေးပညာရှင်ထံ ညွှန်းပို့နိုင်ပါသည်။ အဓိက ပံ့ပိုးကုသမှုသည် စကားပြောခြင်းနှင့် ဆက်စပ်သော စိုးရိမ်ပူပန်မှုကို လျှော့ချပြီး အဆင့်လိုက် ဆက်သွယ်ပြောဆိုနိုင်စေရန် ကူညီခြင်း ဖြစ်သည်။ တွဲဖက် စကားပြော/ဘာသာစကား အခက်အခဲရှိပါက ၎င်းကို သီးခြား အကဲဖြတ်ကုသနိုင်ပါသည်။", "Speak to your doctor, who can refer you to a speech-language professional or child mental health professional. The main treatment approach reduces anxiety around speaking and supports communication gradually. Any coexisting speech or language difficulty can be assessed and treated separately.")],
    activities: [b('ရင်းနှီးသူ အနည်းငယ်ဖြင့် ဖိအားနည်းသော ကစားနည်းများ။', 'Low-pressure play with a few familiar people.')],
    faq: [qa('စကားပြောဖို့ တွန်းအားပေးသင့်သလား။', 'Should we push them to talk?', 'မသင့်ပါ — ဖိအားက စိုးရိမ်စိတ်ကို ပိုစေသည်။ တဖြည်းဖြည်း ယုံကြည်မှု တည်ဆောက်ပါ။', 'No — pressure increases anxiety. Build confidence gradually.')],
    relatedLessons: ['lsn_big_feelings'], relatedActivities: ['act_feeling_faces'],
    references: [
      "World Health Organization. Anxiety disorders. https://www.who.int/news-room/fact-sheets/detail/anxiety-disorders (accessed 2026-08-18)",
      "World Health Organization. Clinical descriptions and diagnostic requirements for ICD-11 mental, behavioural and neurodevelopmental disorders. 2024. ISBN 9789240077263.",
      "NHS. Selective mutism. https://www.nhs.uk/mental-health/conditions/selective-mutism/ (accessed 2026-08-18)",
      "American Speech-Language-Hearing Association. Selective mutism [Practice Portal]. https://www.asha.org/practice-portal/clinical-topics/selective-mutism/ (accessed 2026-08-18)",
      "Hipolito G et al. A systematic review and meta-analysis of nonpharmacological interventions for children and adolescents with selective mutism. JCPP Adv. 2023;3(3):e12166. doi:10.1002/jcv2.12166.",
      REF_SPECIALIST_REVIEW_REQUIRED,
    ],
  }),
];
