// Hope & Understanding Center — special-needs awareness. Strengths-based,
// respectful, and NON-DIAGNOSTIC. "Possible signs" are awareness points only —
// they never diagnose; the app always guides families to a qualified
// professional. clinical_review until a reviewer approves. References are marked
// for a clinical reviewer to attach verified sources (no fabricated citations).
import { specialNeed, type SeedItem } from '../types';

const b = (mm: string, en: string) => ({ mm, en });
const myth = (m: string, mEn: string, f: string, fEn: string) => ({ myth: b(m, mEn), fact: b(f, fEn) });
const qa = (q: string, qEn: string, a: string, aEn: string) => ({ q: b(q, qEn), a: b(a, aEn) });

const REF_PENDING = 'Pending clinical reviewer: attach verified national/child-health references before publication.';
const NOT_DIAGNOSIS_MM = 'ဤအချက်များသည် ရောဂါဖော်ထုတ်ခြင်း မဟုတ်ပါ — စိုးရိမ်ပါက ကျွမ်းကျင်ပညာရှင်နှင့် တိုင်ပင်ပါ။';
const NOT_DIAGNOSIS_EN = 'These are awareness points, not a diagnosis — if concerned, consult a professional.';

export const SPECIAL_NEEDS: SeedItem[] = [
  specialNeed({
    key: 'autism',
    title: b('အော်တစ်ဇင် (Autism) သိရှိနားလည်မှု', 'Understanding Autism'),
    overview: b('အော်တစ်ဇင်သည် ကလေးက ကမ္ဘာကို ကွဲပြားစွာ ခံစား၊ ဆက်သွယ်ပုံဖြစ်သည်။ ရောဂါတစ်ခု မဟုတ်ဘဲ ဖွံ့ဖြိုးမှု ကွဲပြားမှုဖြစ်၍ ကလေးတိုင်း မတူပါ။', 'Autism is a different way of experiencing and communicating with the world. It is a developmental difference, not an illness, and every child is unique.'),
    strengths: [b('အသေးစိတ် သတိပြုနိုင်မှု', 'Strong attention to detail'), b('စိတ်ဝင်စားရာတွင် နက်နဲသော အာရုံစိုက်မှု', 'Deep focus on interests'), b('ရိုးသားမှုနှင့် ပုံစံကျ တွေးခေါ်မှု', 'Honesty and pattern thinking')],
    possibleSigns: [b('မျက်လုံးချင်းဆုံမှု/လက်ညွှန်ခြင်း အလွန်နည်းခြင်း', 'Very limited eye contact or pointing'), b('ထပ်ခါလုပ်သော လှုပ်ရှားမှုများ', 'Repeated movements or routines'), b('အသံ/အလင်း/ထိတွေ့မှုကို ခံစားမှု ကွဲပြားခြင်း', 'Strong reactions to sounds, light, or textures'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [
      myth('အော်တစ်ဇင်ကို ကာကွယ်ဆေးက ဖြစ်စေသည်', 'Vaccines cause autism', 'မဟုတ်ပါ — သိပ္ပံနည်းကျ သက်သေမပြနိုင်ပါ။', 'No — this is not supported by science.'),
      myth('အော်တစ်ဇင်ကလေးများ ချစ်ခြင်းမေတ္တာ မခံစားနိုင်', 'Autistic children can’t feel love', 'မှားပါသည် — သူတို့ ကွဲပြားစွာ ဖော်ပြတတ်ကြသည်။', 'False — they express affection in their own ways.'),
    ],
    homeSupport: [b('ရှင်းလင်းသော လုပ်ရိုးလုပ်စဉ်နှင့် ပုံရိပ် အစီအစဉ်ဇယား သုံးပါ။', 'Use clear routines and visual schedules.'), b('စိတ်ဝင်စားရာကို အသုံးပြု၍ ဆက်သွယ်ပါ။', 'Connect through their interests.')],
    schoolSupport: [b('တည်ငြိမ်သော ပတ်ဝန်းကျင်နှင့် ကြိုတင် သတိပေးမှုများ ပေးပါ။', 'Provide a calm setting and advance warnings for changes.')],
    professionalSupport: [b('ကလေးဖွံ့ဖြိုးမှုဆိုင်ရာ ဆရာဝန်၊ စကားပြောနှင့် ဘာသာစကားဆိုင်ရာ ပညာရှင်၊ နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ပြန်လည်လေ့ကျင့်ပေးသည့် ပညာရှင်တို့နှင့် တိုင်ပင်ပါ။', 'Work with a developmental pediatrician, speech and occupational therapists.')],
    activities: [b('စိတ်ဝင်စားရာ အကြောင်းအရာဖြင့် အလှည့်ကျ ကစားပါ။', 'Turn-taking games around a favorite topic.')],
    faq: [qa('စောစီးစွာ ပံ့ပိုးမှုက အကျိုးရှိပါသလား။', 'Does early support help?', 'ရှိပါသည် — စောစီးစွာ ပံ့ပိုးမှုက ဆက်သွယ်မှုနှင့် ကျွမ်းကျင်မှုကို အထောက်အကူပြုနိုင်သည်။', 'Yes — early support can help communication and skills.')],
    relatedLessons: ['lsn_special_needs_awareness'], relatedActivities: ['act_feeling_faces'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'speech_delay',
    title: b('စကားပြော နှောင့်နှေးမှု', 'Understanding Speech Delay'),
    overview: b('စကားပြောဖွံ့ဖြိုးမှု နှောင့်နှေးခြင်းဆိုသည်မှာ ကလေး၏ စကားသံနှင့် ဘာသာစကားဖွံ့ဖြိုးမှုသည် မျှော်မှန်းထားသည်ထက် နှေးနေခြင်း ဖြစ်သည်။ အကြောင်းရင်းအမျိုးမျိုး ရှိနိုင်ပြီး သင့်လျော်သော ပံ့ပိုးမှုဖြင့် တိုးတက်နိုင်ပါသည်။', 'Speech delay means a child’s speech/language is developing slower than expected. There are many causes and much room for progress.'),
    strengths: [b('လက်ဟန်/ပုံဖြင့် ဆက်သွယ်နိုင်မှု', 'Communicates well with gestures/pictures'), b('နားလည်မှု ကောင်းခြင်း', 'Often good understanding')],
    possibleSigns: [b('၂ နှစ်တွင် စကားလုံး အလွန်နည်းခြင်း', 'Very few words by age 2'), b('ညွှန်ကြားချက် နားလည်ရ ခက်ခြင်း', 'Difficulty understanding directions'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ယောက်ျားလေးတွေ နောက်ကျတာ ပုံမှန်ပဲ၊ စောင့်ရုံပဲ', '“Boys just talk late — only wait”', 'အချို့ နှေးနိုင်သော်လည်း အမြဲ “စောင့်” ခြင်းက အန္တရာယ်ရှိနိုင်သည် — အကြားအာရုံ စစ်ဆေးမှုက အရေးကြီးသည်။', 'Some are later, but simply “waiting” can miss a hearing issue — checking hearing matters.')],
    homeSupport: [b('နေ့စဉ်လုပ်ဆောင်ချက်များကို စကားဖြင့် ရှင်းပြပြီး ကလေးနှင့် မကြာခဏ စကားပြောပါ။', 'Talk a lot and narrate daily actions.'), b('ကလေးပြောသည့် စကားတိုကို စကားလုံးအနည်းငယ် ထပ်ဖြည့်ပြီး ပြန်ပြောပေးပါ။', 'Expand on what your child says.')],
    schoolSupport: [b('ပုံရိပ်များ သုံး၍ ဆက်သွယ်မှုကို အားပေးပါ။', 'Support communication with pictures.')],
    professionalSupport: [b('စကားပြောနှင့် ဘာသာစကားဆိုင်ရာ ပညာရှင်နှင့် တိုင်ပင်ပြီး အကြားအာရုံ စစ်ဆေးမှုလည်း ခံယူပါ။', 'See a speech therapist; get a hearing check.')],
    activities: [b('ရုပ်ပုံစာအုပ်ကို အတူကြည့်ပြီး ပုံများ၏ အမည်ကို ပြောကစားပါ။', 'Name-and-point book play.')],
    faq: [qa('ဘာသာစကား ၂ မျိုးက စကားပြောကို နှေးစေသလား။', 'Does bilingualism cause delay?', 'မဟုတ်ပါ — ဘာသာစကား ၂ မျိုးသည် နှောင့်နှေးမှု မဖြစ်စေပါ။', 'No — two languages does not cause delay.')],
    relatedLessons: ['lsn_talk_more'], relatedActivities: ['act_name_and_point'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'adhd',
    title: b('အာရုံစိုက်မှု/တက်ကြွမှု ကွဲပြားမှု (ADHD)', 'Understanding ADHD'),
    overview: b('အာရုံစိုက်မှုနှင့် တက်ကြွလှုပ်ရှားမှုဆိုင်ရာ ကွဲပြားမှုသည် အာရုံစိုက်ခြင်း၊ လှုပ်ရှားမှုနှင့် ရုတ်တရက် တုံ့ပြန်လုပ်ဆောင်မှုကို ထိန်းညှိရန် ခက်ခဲစေနိုင်သည်။ ငယ်ရွယ်သော ကလေးများတွင် သေချာအကဲဖြတ်ရန် ခက်ခဲသဖြင့် ကျွမ်းကျင်သူက ဂရုတစိုက် စစ်ဆေးရန် လိုသည်။', 'ADHD is a developmental difference affecting attention, activity level, and impulse control. It is hard to confirm in very young children and needs a careful approach.'),
    strengths: [b('စွမ်းအင်နှင့် စိတ်အားထက်သန်မှု', 'High energy and enthusiasm'), b('တီထွင်ဖန်တီးမှုနှင့် စိတ်ဝင်စားရာတွင် အာရုံစိုက်နိုင်မှု', 'Creativity and hyperfocus on interests')],
    possibleSigns: [b('အသက်အရွယ်ထက် ပို၍ လှုပ်ရှား/စောင့်ဆိုင်းရ ခက်ခြင်း', 'More movement or difficulty waiting than peers'), b('အာရုံ လွယ်ကူစွာ ပြောင်းသွားခြင်း', 'Easily distracted'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('မိဘက ကောင်းကောင်း မပြုစုလို့ ဖြစ်တာပါ', 'ADHD is caused by bad parenting', 'မဟုတ်ပါ။ ယင်းသည် ဦးနှောက်ဖွံ့ဖြိုးမှုဆိုင်ရာ ကွဲပြားမှုဖြစ်ပြီး မိဘ၏ အပြစ်မဟုတ်ပါ။', 'No — it is a difference in brain development.')],
    homeSupport: [b('ရှင်းလင်း၍ တိုတောင်းသော ညွှန်ကြားချက်၊ တသမတ်တည်း လုပ်ရိုးလုပ်စဉ်၊ လှုပ်ရှားချိန် ပေးပါ။', 'Give short clear instructions, steady routines, and movement breaks.')],
    schoolSupport: [b('ကောင်းသောအပြုအမူကို ချီးမွမ်း၍ လုပ်ငန်းများ အပိုင်းလိုက် ခွဲပါ။', 'Praise good behavior; break tasks into small steps.')],
    professionalSupport: [b('ကလေးဖွံ့ဖြိုးမှုဆရာဝန်/ကလေးစိတ်ပညာရှင်နှင့် တိုင်ပင်ပါ။', 'Consult a developmental pediatrician or child psychologist.')],
    activities: [b('ရုပ်ပိုင်း လှုပ်ရှားမှုများနှင့် အလှည့်ကျ ကစားနည်းများ။', 'Active games and turn-taking play.')],
    faq: [qa('ငယ်ရွယ်စဉ် အတည်ပြုနိုင်သလား။', 'Can it be confirmed early?', 'ငယ်ရွယ်စဉ် အတည်ပြုရ ခက်ခဲသည် — ကျွမ်းကျင်သူ၏ အကဲဖြတ်မှု လိုအပ်သည်။', 'It is hard to confirm early; a professional assessment is needed.')],
    relatedLessons: ['lsn_gentle_discipline'], relatedActivities: ['act_obstacle_course'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'down_syndrome',
    title: b('ဒေါင်းစင်ဒရုမ်း (Down Syndrome)', 'Understanding Down Syndrome'),
    overview: b('ဒေါင်းစင်ဒရုမ်းသည် မွေးရာပါ မျိုးရိုးဗီဇ အခြေအနေတစ်ခုဖြစ်သည်။ ကလေးများသည် မိမိအရှိန်ဖြင့် သင်ယူ၊ ကြီးထွား၍ ပျော်ရွှင်သော ဘဝများ ရရှိနိုင်သည်။', 'Down syndrome is a genetic condition present from birth. Children learn and grow at their own pace and can live happy, full lives.'),
    strengths: [b('လူမှုဆက်ဆံရေး နွေးထွေးမှု', 'Warm social connection'), b('ကြိုးစားမှုနှင့် အတုယူ သင်ယူနိုင်မှု', 'Persistence and learning by imitation')],
    possibleSigns: [b('ကြွက်သား နူးညံ့မှုနှင့် ဖွံ့ဖြိုးမှု အမှတ်တိုင်များ နှေးခြင်း', 'Low muscle tone and slower milestones'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ဒေါင်းစင်ဒရုမ်းကလေးတွေ သင်ယူလို့မရ', 'Children with Down syndrome can’t learn', 'မှားပါသည် — သင့်လျော်သော ပံ့ပိုးမှုဖြင့် များစွာ သင်ယူနိုင်ကြသည်။', 'False — with support they learn a great deal.')],
    homeSupport: [b('စောစီးစွာ ဖွံ့ဖြိုးမှုပံ့ပိုးပေးသည့် ဝန်ဆောင်မှုများနှင့် ပုံမှန် ကျန်းမာရေးစစ်ဆေးမှုများကို ခံယူပါ။', 'Access early intervention and regular health checks.')],
    schoolSupport: [b('ကလေးအားလုံး အတူပါဝင်နိုင်သော ပညာရေးပတ်ဝန်းကျင်နှင့် တစ်ဦးချင်းလိုအပ်ချက်အလိုက် ပံ့ပိုးမှုကို ရှာဖွေပါ။', 'Seek inclusive education and individual support.')],
    professionalSupport: [b('ကလေးဖွံ့ဖြိုးမှုဆိုင်ရာ ဆရာဝန်၊ ကိုယ်လက်လှုပ်ရှားမှု ပြန်လည်သန်စွမ်းရေးပညာရှင်နှင့် စကားပြောနှင့် ဘာသာစကားဆိုင်ရာ ပညာရှင်တို့နှင့် တိုင်ပင်ပါ။', 'Work with a pediatrician, physio and speech therapists.')],
    activities: [b('ကြွက်သားခိုင်မာမှုအတွက် ကစားနည်းများ (ကြီးကြပ်၍)။', 'Muscle-strengthening play (supervised).')],
    faq: [qa('ပြန်လည်သန်စွမ်းရေး လေ့ကျင့်မှုများက အကျိုးရှိပါသလား။', 'Does therapy help?', 'ရှိပါသည်။ ကိုယ်လက်လှုပ်ရှားမှုနှင့် စကားပြောဘာသာစကားဆိုင်ရာ လေ့ကျင့်ပေးမှုများက ကလေး၏ စွမ်းရည်တိုးတက်လာစေရန် ကူညီနိုင်သည်။', 'Yes — physio and speech therapy help build skills.')],
    relatedLessons: ['lsn_what_is_development'], relatedActivities: ['act_cup_stacking'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'cerebral_palsy',
    title: b('ဦးနှောက်ဆိုင်ရာ လှုပ်ရှားမှု ကွဲပြားမှု (Cerebral Palsy)', 'Understanding Cerebral Palsy'),
    overview: b('ဦးနှောက်ဆိုင်ရာ လှုပ်ရှားမှုကွဲပြားခြင်းသည် ကိုယ်လက်လှုပ်ရှားမှုနှင့် ခန္ဓာကိုယ်အနေအထား ထိန်းချုပ်မှုကို သက်ရောက်စေသော အခြေအနေတစ်ခု ဖြစ်သည်။ သက်ရောက်မှုပုံစံနှင့် အတိုင်းအတာသည် ကလေးတစ်ဦးနှင့်တစ်ဦး ကွာခြားပြီး သင့်လျော်သော ပံ့ပိုးမှုဖြင့် တိုးတက်နိုင်ပါသည်။', 'Cerebral palsy affects movement and posture. It varies widely, and many children make progress with support.'),
    strengths: [b('ဇွဲ၊ လိုက်လျောညီထွေ ဖြေရှင်းနိုင်မှု', 'Determination and adaptability'), b('စိတ်ခံစားမှုနှင့် ဆက်ဆံရေး ကောင်းမွန်မှု (မကြာခဏ)', 'Often strong communication and connection')],
    possibleSigns: [b('ကြွက်သား တောင့်တင်း/နူးညံ့ခြင်း၊ လှုပ်ရှားမှု အမှတ်တိုင်များ နှေးခြင်း', 'Stiff or floppy muscles; delayed motor milestones'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('CP က တိုးမြင့်လာ/ကူးစက်တတ်တယ်', 'CP is contagious or gets worse over time', 'မဟုတ်ပါ — ကူးစက်ခြင်း မရှိ၍ တိုးမြင့်ခြင်းလည်း မဟုတ်ပါ။', 'No — it is not contagious and not progressive.')],
    homeSupport: [b('ကုသရေးအဖွဲ့၏ လမ်းညွှန်အတိုင်း နေ့စဉ်လေ့ကျင့်ခန်းများ လုပ်ပါ။', 'Do daily exercises guided by the care team.')],
    schoolSupport: [b('ဝင်ရောက်လွယ်ကူသော ပတ်ဝန်းကျင်နှင့် ကိရိယာ ပံ့ပိုးမှု ရှာဖွေပါ။', 'Seek accessible settings and assistive equipment.')],
    professionalSupport: [b('ကိုယ်လက်လှုပ်ရှားမှု ပြန်လည်သန်စွမ်းရေးပညာရှင်၊ နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ပြန်လည်လေ့ကျင့်ပေးသည့် ပညာရှင်နှင့် ကလေးဖွံ့ဖြိုးမှုဆိုင်ရာ ဆရာဝန်တို့နှင့် တိုင်ပင်ပါ။', 'Work with physio, occupational therapy, and a pediatrician.')],
    activities: [b('ကုသရေးအဖွဲ့ ညွှန်ကြားသော ဟန်ချက်/လှုပ်ရှားမှု ကစားနည်းများ။', 'Balance/movement play as advised by the care team.')],
    faq: [qa('စောစီးစွာ ကုသမှုက အရေးကြီးသလား။', 'Is early therapy important?', 'အရေးကြီးသည် — စောစီးစွာ ကုသမှုက လှုပ်ရှားမှုနှင့် လွတ်လပ်မှုကို အထောက်အကူပြုသည်။', 'Yes — early therapy supports movement and independence.')],
    relatedLessons: ['lsn_what_is_development'], relatedActivities: ['act_obstacle_crawl'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'hearing_loss',
    title: b('အကြားအာရုံ ချို့တဲ့မှု', 'Understanding Hearing Loss'),
    overview: b('အကြားအာရုံ ချို့တဲ့မှုသည် ပြင်းအား အမျိုးမျိုး ရှိနိုင်သည်။ စောစီးစွာ ရှာဖွေတွေ့ရှိ၍ ပံ့ပိုးခြင်းက ဘာသာစကား ဖွံ့ဖြိုးမှုအတွက် အလွန်အရေးကြီးသည်။', 'Hearing loss ranges in degree. Early detection and support are very important for language development.'),
    strengths: [b('မျက်စိဖြင့် သတိပြု/လက်ဟန်ဖြင့် ဆက်သွယ်နိုင်မှု', 'Strong visual attention and gesture use')],
    possibleSigns: [b('ကျယ်သောအသံ/နာမည်ကို မတုံ့ပြန်ခြင်း၊ စကားပြော နှေးခြင်း', 'Not responding to loud sounds/name; delayed speech'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကလေး တစ်ခါတစ်ရံ တုံ့ပြန်ရင် အကြားအာရုံ ကောင်းတယ်လို့ ဆိုနိုင်တယ်', 'If a child sometimes responds, hearing is fine', 'မဟုတ်ပါ — တစ်စိတ်တစ်ပိုင်း အကြားအာရုံ ချို့တဲ့မှုလည်း ရှိနိုင်၍ စစ်ဆေးမှု လိုအပ်သည်။', 'No — partial hearing loss exists; a proper test is needed.')],
    homeSupport: [b('မျက်နှာချင်းဆိုင်၍ ရှင်းလင်းစွာ ပြောပါ။ လက်ဟန်/ပုံများ သုံးပါ။', 'Face the child, speak clearly, use gestures/pictures.')],
    schoolSupport: [b('ရှေ့တန်း ထိုင်ခုံနှင့် မျက်စိဖြင့် ပံ့ပိုးမှုများ ပေးပါ။', 'Front seating and visual supports.')],
    professionalSupport: [b('အကြားအာရုံဆိုင်ရာ ပညာရှင်ထံတွင် အကြားအာရုံ စစ်ဆေးမှုကို အမြန်ဆုံး ခံယူပါ။', 'Get a hearing test with an audiologist promptly.')],
    activities: [b('မျက်စိဖြင့် သတိပြုစေသော ကစားနည်းများ။', 'Games that use visual attention.')],
    faq: [qa('စောစီးစွာ စစ်ဆေးမှုက အရေးကြီးသလား။', 'Is early testing important?', 'အလွန်အရေးကြီးသည် — စောစီးစွာ ပံ့ပိုးမှုက ဘာသာစကားကို ကာကွယ်ပေးသည်။', 'Very — early support protects language development.')],
    relatedLessons: ['lsn_language_rich_home'], relatedActivities: ['act_sound_tracking'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'visual_impairment',
    title: b('မျက်စိအမြင် ချို့တဲ့မှု', 'Understanding Visual Impairment'),
    overview: b('အမြင်အာရုံ အားနည်းမှုသည် ကလေးတစ်ဦးနှင့်တစ်ဦး အတိုင်းအတာ ကွာခြားနိုင်သည်။ စောစီးစွာ သိရှိပြီး သင့်လျော်သော ပံ့ပိုးမှုရရှိပါက ကလေးများ ကောင်းစွာ ဖွံ့ဖြိုးတိုးတက်နိုင်သည်။', 'Visual impairment varies in degree. With early detection and support, children thrive.'),
    strengths: [b('အကြားအာရုံနှင့် ထိတွေ့ခံစားမှု ကောင်းမွန်မှု', 'Strong hearing and touch senses')],
    possibleSigns: [b('အရာဝတ္ထုများကို လိုက်မကြည့်ခြင်း၊ မျက်လုံး ပုံမှန်မဟုတ်ခြင်း', 'Not following objects; unusual eye movements'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('မျက်မှန်တပ်ရင် မျက်စိ ပိုဆိုးတယ်', 'Glasses make eyes weaker', 'မဟုတ်ပါ — သင့်လျော်သော မျက်မှန်က အမြင်ကို ကူညီသည်။', 'No — the right glasses help vision.')],
    homeSupport: [b('အသံ/ထိတွေ့မှုဖြင့် ဆက်သွယ်၍ ဘေးကင်းသော ပတ်ဝန်းကျင် ဖန်တီးပါ။', 'Connect through sound/touch; keep a safe, predictable space.')],
    schoolSupport: [b('အလင်းရောင် ကောင်း၊ ကြီးမားသော စာလုံး/ထိတွေ့ပစ္စည်းများ ပေးပါ။', 'Good lighting, large print or tactile materials.')],
    professionalSupport: [b('မျက်စိအထူးကုနှင့် စောစီးစွာ ပံ့ပိုးရေးဝန်ဆောင်မှုနှင့် တိုင်ပင်ပါ။', 'Consult an eye specialist and early-support services.')],
    activities: [b('ထိတွေ့ခံစားမှုနှင့် အသံဖြင့် ကစားနည်းများ။', 'Touch-and-sound play.')],
    faq: [qa('စောစီးစွာ ရှာဖွေတွေ့ရှိမှုက ကူညီသလား။', 'Does early detection help?', 'ကူညီသည် — စောစီးစွာ ပံ့ပိုးမှုက ဖွံ့ဖြိုးမှုကို အထောက်အကူပြုသည်။', 'Yes — early support aids development.')],
    relatedLessons: ['lsn_power_of_play'], relatedActivities: ['act_sound_tracking'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'global_developmental_delay',
    title: b('ဘက်စုံ ဖွံ့ဖြိုးမှု နှောင့်နှေးမှု', 'Understanding Global Developmental Delay'),
    overview: b('ဤသည်မှာ ဖွံ့ဖြိုးမှု နယ်ပယ် အများအပြားတွင် မျှော်မှန်းထားသည်ထက် နှေးနေခြင်းဖြစ်သည်။ အကြောင်းရင်း ရှာဖွေ၍ စောစီးစွာ ပံ့ပိုးခြင်းက အရေးကြီးသည်။', 'This is slower-than-expected development across several areas. Finding the cause and starting early support matter.'),
    strengths: [b('ကိုယ်ပိုင်အရှိန်ဖြင့် တိုးတက်နိုင်မှု', 'Progress at their own pace')],
    possibleSigns: [b('လှုပ်ရှားမှု၊ ဘာသာစကား၊ တွေးခေါ်မှု အများအပြားတွင် နှေးခြင်း', 'Delays in movement, language, and thinking together'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကြီးလာရင် အလိုလို ကောင်းသွားမယ်၊ ဘာမှ မလုပ်ဘဲ စောင့်ရုံပဲ', '“They’ll grow out of it — just wait”', 'အမြဲ “စောင့်” ခြင်းက စောစီးစွာ ပံ့ပိုးမှု အခွင့်အလမ်းကို လွတ်စေနိုင်သည်။', 'Simply waiting can miss the window for helpful early support.')],
    homeSupport: [b('နေ့စဉ်လုပ်ဆောင်ချက်များထဲ သင်ခန်းစာနှင့် ကစားခြင်း ထည့်ပါ။', 'Weave learning and play into daily routines.')],
    schoolSupport: [b('တစ်ဦးချင်း ပံ့ပိုးမှုနှင့် ပါဝင်စေသော ပတ်ဝန်းကျင် ရှာဖွေပါ။', 'Seek individual support and inclusive settings.')],
    professionalSupport: [b('ကလေးဖွံ့ဖြိုးမှုဆိုင်ရာ ဆရာဝန်၏ အကဲဖြတ်မှုကို ခံယူပါ။', 'Get an assessment from a developmental pediatrician.')],
    activities: [b('အသက်အရွယ်နှင့်လိုက်လျော၍ ရိုးရှင်းသော ကစားနည်းများ။', 'Simple, developmentally-matched play.')],
    faq: [qa('အကြောင်းရင်း ရှာဖွေသင့်သလား။', 'Should we look for a cause?', 'သင့်သည် — ကျွမ်းကျင်သူ၏ အကဲဖြတ်မှုက ပံ့ပိုးမှု လမ်းကြောင်းကို ရှင်းလင်းစေသည်။', 'Yes — a professional assessment clarifies the support path.')],
    relatedLessons: ['lsn_what_is_development'], relatedActivities: ['act_cup_stacking'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'learning_disability',
    title: b('သင်ယူမှု အခက်အခဲ', 'Understanding Learning Disability'),
    overview: b('သင်ယူမှု အခက်အခဲသည် ဉာဏ်ရည် နိမ့်ခြင်း မဟုတ်ဘဲ — အချို့ ကျွမ်းကျင်မှုများ (ဖတ်/ရေး/တွက်) ကို သင်ယူပုံ ကွဲပြားခြင်းဖြစ်သည်။ ငယ်ရွယ်စဉ် အတည်ပြုရ ခက်ခဲသည်။', 'A learning disability is not low intelligence — it is a different way of learning certain skills (reading/writing/math). It is hard to confirm at very young ages.'),
    strengths: [b('တီထွင်ဖန်တီးမှုနှင့် ပြဿနာ ဖြေရှင်းနိုင်မှု', 'Creativity and problem-solving')],
    possibleSigns: [b('ကျောင်းအရွယ်တွင် သီးခြား ကျွမ်းကျင်မှုတစ်ခု သင်ယူရ ဆက်တိုက် ခက်ခဲခြင်း', 'Ongoing difficulty with one specific skill at school age'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('သင်ယူမှု အခက်အခဲ ရှိရင် ဉာဏ်နည်းတယ်', 'Learning disability means low intelligence', 'မဟုတ်ပါ — ဉာဏ်ရည်နှင့် မသက်ဆိုင်ဘဲ သင်ယူပုံ ကွဲပြားခြင်းဖြစ်သည်။', 'No — it is unrelated to intelligence; just a different way of learning.')],
    homeSupport: [b('အားသာချက်ကို အသုံးပြု၍ သင်ကြားပါ။ ကြိုးစားမှုကို ချီးမွမ်းပါ။', 'Teach through strengths; praise effort.')],
    schoolSupport: [b('သင်ကြားမှု ပုံစံ ချိန်ညှိမှုနှင့် အချိန်ပို ပေးပါ။', 'Provide teaching adjustments and extra time.')],
    professionalSupport: [b('ကျောင်းအရွယ်တွင် ပညာရေးစိတ်ပညာရှင်နှင့် တိုင်ပင်ပါ။', 'At school age, consult an educational psychologist.')],
    activities: [b('ကစားရင်း သင်ယူသော အက္ခရာ/သင်္ချာ ကစားနည်းများ။', 'Playful letter/number games.')],
    faq: [qa('ငယ်ရွယ်စဉ် သိနိုင်သလား။', 'Can it be known early?', 'ငယ်ရွယ်စဉ် အတည်ပြုရ ခက်ခဲ၍ ကျောင်းအရွယ်တွင် ပို၍ ရှင်းလင်းလာတတ်သည်။', 'It is hard to confirm early; it usually becomes clearer at school age.')],
    relatedLessons: ['lsn_early_math'], relatedActivities: ['act_name_writing'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'sensory_processing',
    title: b('အာရုံခံစားမှု စီမံဆောင်ရွက်မှု ကွဲပြားမှု', 'Understanding Sensory Processing Differences'),
    overview: b('အချို့ကလေးများသည် အသံ၊ အလင်း၊ ထိတွေ့မှုနှင့် လှုပ်ရှားမှုတို့ကို အခြားကလေးများထက် ပိုမိုပြင်းထန်စွာ သို့မဟုတ် ပိုမိုလျော့နည်းစွာ ခံစားတတ်ကြသည်။ ယင်းက နေ့စဉ်ဘဝကို သက်ရောက်နိုင်သည်။', 'Some children feel sounds, light, touch, or movement more or less intensely. This can affect daily life.'),
    strengths: [b('အသေးစိတ် သတိပြုနိုင်မှုနှင့် ခံစားမှု ကြွယ်ဝမှု', 'Rich awareness and attention to detail')],
    possibleSigns: [b('အဝတ်အထည်/အသံ/အစားအစာ ဖွဲ့စည်းပုံကို ပြင်းထန်စွာ တုံ့ပြန်ခြင်း', 'Strong reactions to textures, sounds, or food'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကလေး အနိုင်ကျင့်နေတာ/ပျက်ပျက်လုပ်နေတာ', 'The child is just being difficult', 'မကြာခဏ ၎င်းသည် ခံစားမှု ကွဲပြားမှုကြောင့်ဖြစ်၍ အပြစ်တင်ခြင်းက အထောက်အကူ မဖြစ်ပါ။', 'Often it is a genuine sensory difference; blame does not help.')],
    homeSupport: [b('ခံစားမှု ပြင်းအားကို ချိန်ညှိပါ (တိတ်ဆိတ်နေရာ၊ နူးညံ့အဝတ်)။', 'Adjust the sensory load (quiet space, soft clothing).')],
    schoolSupport: [b('အနားယူ/ငြိမ်သက်နိုင်သော နေရာ ပေးပါ။', 'Offer a calm-down/break space.')],
    professionalSupport: [b('နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ပြန်လည်လေ့ကျင့်ပေးသည့် ပညာရှင်နှင့် တိုင်ပင်ပါ။', 'Consult an occupational therapist.')],
    activities: [b('ကလေး အဆင်ပြေသည့်အတိုင်း မျက်နှာပြင်အထိအတွေ့ မတူညီသော ပစ္စည်းများဖြင့် ဖြည်းဖြည်းချင်း ကစားပါ။', 'Gentle textured play at the child’s comfort level.')],
    faq: [qa('ဤသည် အမြဲတမ်းလား။', 'Is this permanent?', 'ပံ့ပိုးမှုနှင့် အချိန်ကြာလာသည်နှင့်အမျှ ခံစားမှု စီမံနိုင်စွမ်း တိုးတက်တတ်သည်။', 'With support and time, coping often improves.')],
    relatedLessons: ['lsn_big_feelings'], relatedActivities: ['act_water_pouring'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'dyslexia',
    title: b('စာဖတ်ခြင်း အခက်အခဲ (Dyslexia)', 'Understanding Dyslexia'),
    overview: b('စာဖတ်ခြင်းဆိုင်ရာ သင်ယူမှုကွဲပြားခြင်းသည် စာဖတ်ခြင်းနှင့် စာလုံးပေါင်းခြင်းကို ခက်ခဲစေနိုင်သည်။ ယင်းသည် ဉာဏ်ရည်နှင့် မသက်ဆိုင်ဘဲ ကျောင်းအရွယ်တွင် ပိုမို ထင်ရှားလာတတ်သည်။', 'Dyslexia is a learning difference affecting reading/spelling. It is unrelated to intelligence and usually becomes clearer at school age.'),
    strengths: [b('ဖန်တီးမှု၊ ပုံရိပ်ဖြင့် တွေးခေါ်နိုင်မှု', 'Creativity and big-picture thinking')],
    possibleSigns: [b('ကျောင်းအရွယ်တွင် အက္ခရာ/အသံ ဆက်စပ်ရ ခက်ခြင်း', 'At school age, difficulty linking letters and sounds'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('စာလုံးတွေကို ပြောင်းပြန်မြင်တာတစ်ခုတည်းပါ', 'Dyslexia is just seeing letters backwards', 'မဟုတ်ပါ။ အဓိကအားဖြင့် စကားသံနှင့် စာလုံးတို့ကို ဆက်စပ်နားလည်ရာတွင် အခက်အခဲရှိခြင်း ဖြစ်သည်။', 'That is a myth; it mainly involves sound–letter processing.')],
    homeSupport: [b('အသံ-စာလုံး ကစားနည်းများ၊ ကြားနာစာဖတ်ခြင်း လုပ်ပါ။', 'Play sound–letter games; read aloud together.')],
    schoolSupport: [b('အချိန်ပို၊ ကြားနာ/ပုံ ပံ့ပိုးမှုများ ပေးပါ။', 'Provide extra time and audio/visual supports.')],
    professionalSupport: [b('ပညာရေးစိတ်ပညာရှင်/စာဖတ်အထူးကုဆရာမနှင့် တိုင်ပင်ပါ။', 'Consult an educational psychologist or reading specialist.')],
    activities: [b('စကားလုံး ကာရန်/အသံ ကစားနည်းများ။', 'Rhyming and sound games.')],
    faq: [qa('စောစီးစွာ ပံ့ပိုးမှုက ကူညီသလား။', 'Does early support help?', 'ကူညီသည် — သင့်လျော်သော နည်းလမ်းများက စာဖတ်ခြင်းကို အထောက်အကူပြုသည်။', 'Yes — the right methods support reading.')],
    relatedLessons: ['lsn_reading_together'], relatedActivities: ['act_name_writing'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'developmental_coordination_disorder',
    title: b('လှုပ်ရှားမှု ညှိနှိုင်းမှု အခက်အခဲ (DCD)', 'Understanding Developmental Coordination Difference (DCD)'),
    overview: b('လှုပ်ရှားမှု ညှိနှိုင်းရေးဆိုင်ရာ ကွဲပြားမှုသည် အဝတ်ခလုတ်တပ်ခြင်း၊ ကတ်ကြေးဖြင့် ဖြတ်ခြင်းနှင့် ဘောလုံးဖမ်းခြင်းကဲ့သို့ ကိုယ်လက်လှုပ်ရှားမှုများကို ခက်ခဲစေနိုင်သည်။ ယင်းသည် ဉာဏ်ရည်နှင့် မသက်ဆိုင်ပါ။', 'DCD is a difference affecting movement coordination (e.g., buttoning, cutting, catching). It is unrelated to intelligence.'),
    strengths: [b('ဇွဲနှင့် ကြိုးစားမှု', 'Persistence and effort')],
    possibleSigns: [b('အသက်အရွယ်ထက် လှုပ်ရှားမှု ကျွမ်းကျင်မှုများ နှေးခြင်း/မတိကျခြင်း', 'Motor skills slower or clumsier than peers'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကလေးက ပျင်းလို့ သို့မဟုတ် ဂရုမစိုက်လို့ ဖြစ်တာပါ', 'The child is just lazy or careless', 'မဟုတ်ပါ။ ယင်းသည် ကိုယ်လက်လှုပ်ရှားမှုများကို ညှိနှိုင်းရာတွင် အခက်အခဲရှိခြင်း ဖြစ်သည်။', 'No — it is a real coordination difference.')],
    homeSupport: [b('လှုပ်ရှားမှု ကျွမ်းကျင်မှုများကို အပိုင်းလိုက် ခွဲ၍ လေ့ကျင့်ပေးပါ။', 'Break motor skills into small steps to practice.')],
    schoolSupport: [b('ရေးသားမှု/ကိုယ်လက်လှုပ်ရှားမှုတွင် အချိန်ပိုနှင့် ချိန်ညှိမှုများ ပေးပါ။', 'Allow extra time and adjustments for writing/PE.')],
    professionalSupport: [b('နေ့စဉ်လုပ်ဆောင်မှုစွမ်းရည် ပြန်လည်လေ့ကျင့်ပေးသည့် ပညာရှင် သို့မဟုတ် ကိုယ်လက်လှုပ်ရှားမှု ပြန်လည်သန်စွမ်းရေးပညာရှင်နှင့် တိုင်ပင်ပါ။', 'Consult an occupational therapist or physiotherapist.')],
    activities: [b('ဟန်ချက်နှင့် လက်-မျက်စိ ညှိနှိုင်းမှု ကစားနည်းများ။', 'Balance and hand–eye coordination play.')],
    faq: [qa('လေ့ကျင့်မှုက တိုးတက်စေသလား။', 'Does practice help?', 'ကူညီသည် — အပိုင်းလိုက် လေ့ကျင့်ခြင်းနှင့် ပံ့ပိုးမှုက ကျွမ်းကျင်မှုကို တိုးတက်စေသည်။', 'Yes — step-by-step practice and support build skills.')],
    relatedLessons: ['lsn_power_of_play'], relatedActivities: ['act_obstacle_course'],
    references: [REF_PENDING],
  }),
  specialNeed({
    key: 'selective_mutism',
    title: b('ရွေးချယ် အသံတိတ်ခြင်း (Selective Mutism)', 'Understanding Selective Mutism'),
    overview: b('အခြေအနေအလိုက် စကားမပြောနိုင်ခြင်းဆိုသည်မှာ ကလေးက အိမ်တွင် စကားပြောနိုင်သော်လည်း ကျောင်းကဲ့သို့ အချို့နေရာများတွင် စကားမပြောနိုင်ခြင်း ဖြစ်သည်။ ယင်းသည် ခေါင်းမာခြင်း မဟုတ်ဘဲ စိုးရိမ်ပူပန်မှုနှင့် ဆက်စပ်နိုင်သည်။', 'Selective mutism is when a child can speak at home but not in certain settings (e.g., school). It is not defiance — it is linked to anxiety.'),
    strengths: [b('ရင်းနှီးသော နေရာတွင် ဆက်သွယ်နိုင်မှု', 'Communicates well in comfortable settings')],
    possibleSigns: [b('အိမ်တွင် ပုံမှန်ပြော၍ ကျောင်း/အများနေရာတွင် ဆက်တိုက် စကားမပြောခြင်း', 'Speaks at home but consistently silent at school/in public'), b(NOT_DIAGNOSIS_MM, NOT_DIAGNOSIS_EN)],
    myths: [myth('ကလေးက ရည်ရွယ်ချက်ရှိရှိ စကားမပြောတာပါ', 'The child is refusing to talk on purpose', 'မဟုတ်ပါ။ စိုးရိမ်ပူပန်မှုကြောင့် ဖြစ်နိုင်ပြီး စကားပြောရန် ဖိအားပေးခြင်းက ပိုမိုခက်ခဲစေနိုင်သည်။', 'No — it is anxiety-driven; pressure makes it worse.')],
    homeSupport: [b('စကားပြောရန် ဖိအားမပေးဘဲ လုံခြုံစိတ်ချရသော အခြေအနေများ တဖြည်းဖြည်း ဖန်တီးပါ။', 'Don’t pressure speech; build safe situations gradually.')],
    schoolSupport: [b('ဆရာမနှင့် ပူးပေါင်း၍ ဖိအားနည်းသော ဆက်သွယ်နည်းများ (ခေါင်းညိတ်/ရေး) ခွင့်ပြုပါ။', 'Work with the teacher; allow low-pressure communication (nod/write).')],
    professionalSupport: [b('ကလေးစိတ်ပညာရှင်နှင့် တိုင်ပင်ပါ။', 'Consult a child psychologist.')],
    activities: [b('ရင်းနှီးသူ အနည်းငယ်ဖြင့် ဖိအားနည်းသော ကစားနည်းများ။', 'Low-pressure play with a few familiar people.')],
    faq: [qa('စကားပြောဖို့ တွန်းအားပေးသင့်သလား။', 'Should we push them to talk?', 'မသင့်ပါ — ဖိအားက စိုးရိမ်စိတ်ကို ပိုစေသည်။ တဖြည်းဖြည်း ယုံကြည်မှု တည်ဆောက်ပါ။', 'No — pressure increases anxiety. Build confidence gradually.')],
    relatedLessons: ['lsn_big_feelings'], relatedActivities: ['act_feeling_faces'],
    references: [REF_PENDING],
  }),
];
