// Story library — short, original, age-appropriate stories covering each story
// type. Simple language; clinical_review until approved. Audio/printable are
// architecture placeholders (see media refs).
import { story, type SeedItem } from '../types';

const b = (mm: string, en: string) => ({ mm, en });

export const STORIES: SeedItem[] = [
  story({
    slug: 'little_seed', storyType: 'picture', ageGroupKey: '2y',
    title: b('မျိုးစေ့ လေးရဲ့ ခရီး', 'The Little Seed’s Journey'),
    summary: b('မျိုးစေ့ငယ်လေးက မိုးရေ၊ နေရောင်ဖြင့် တဖြည်းဖြည်း ကြီးထွားလာပုံ။', 'A tiny seed slowly grows with rain and sun.'),
    readingLevel: 'Beginner', readingMinutes: 3,
    vocabulary: [b('မျိုးစေ့', 'seed'), b('မိုးရေ', 'rain'), b('နေရောင်', 'sunlight')],
    body: b('မျိုးစေ့ငယ်လေးက မြေအောက်မှာ အိပ်နေတယ်။ မိုးရေ ကျလာတော့ ခေါင်းလေး ထောင်လာတယ်။ နေရောင်လေး ထိတော့ အရွက်ငယ် ၂ ရွက် ပေါ်လာတယ်။ တဖြည်းဖြည်း ကြီးလာပြီး ပန်းလေး ပွင့်တယ်။', 'A little seed slept under the soil. When the rain fell, it lifted its head. When the sun touched it, two tiny leaves appeared. Slowly it grew, and a flower bloomed.'),
    questions: [b('မျိုးစေ့ ကြီးဖို့ ဘာတွေ လိုအပ်လဲ။', 'What did the seed need to grow?')],
    activities: [b('အိမ်မှာ ပဲစေ့ တစ်လုံး စိုက်၍ ကြည့်ပါ။', 'Plant a bean at home and watch it grow.')],
  }),
  story({
    slug: 'ba_ba_sounds', storyType: 'speech', ageGroupKey: '13_18m',
    title: b('“ဘ ဘ” အသံလေးများ', 'The “Ba-Ba” Sounds'),
    summary: b('ကလေးငယ်က အသံလေးများကို ပျော်ရွှင်စွာ လိုက်တုပြောသည့် ပုံပြင်။', 'A toddler joyfully copies simple sounds.'),
    readingLevel: 'Beginner', readingMinutes: 2,
    vocabulary: [b('ဘ', 'ba'), b('မ', 'ma'), b('ပ', 'pa')],
    body: b('မိုးမိုးက “ဘ ဘ” လို့ ဆိုတယ်။ မေမေက “ဘ ဘ” လို့ ပြန်ဆိုတယ်။ မိုးမိုးက ရယ်ပြီး “မ မ” လို့ ထပ်ဆိုတယ်။ အသံလေးတွေနဲ့ အတူ ကစားရတာ ပျော်စရာပဲ။', 'Mo-Mo said “ba-ba”. Mommy said “ba-ba” back. Mo-Mo laughed and said “ma-ma”. Playing with sounds together is fun.'),
    questions: [b('မိုးမိုး ဘယ်အသံတွေ ဆိုလဲ။', 'What sounds did Mo-Mo make?')],
    activities: [b('ကလေးနှင့်အတူ အသံလေးများကို အပြန်အလှန် လိုက်တုပြောကစားပါ။', 'Copy simple sounds together.')],
  }),
  story({
    slug: 'when_i_feel_angry', storyType: 'emotion', ageGroupKey: '3y',
    title: b('စိတ်ဆိုးတဲ့အခါ', 'When I Feel Angry'),
    summary: b('စိတ်ဆိုးတဲ့အခါ အသက်ပြင်းပြင်းရှူ၍ ငြိမ်အောင် လုပ်နည်း။', 'A gentle way to calm down when angry.'),
    readingLevel: 'Beginner', readingMinutes: 3,
    vocabulary: [b('စိတ်ဆိုး', 'angry'), b('ငြိမ်', 'calm'), b('အသက်ရှူ', 'breathe')],
    body: b('တစ်ခါတစ်ရံ မီမီ စိတ်ဆိုးတယ်။ ခန္ဓာကိုယ်လေး ပူလာတယ်။ မီမီက အသက်ကို ပြင်းပြင်း ရှူ၍ ၁-၂-၃ ရေတွက်တယ်။ ဖြည်းဖြည်းချင်း စိတ်လေး ငြိမ်သွားတယ်။ စိတ်ဆိုးတာ ပုံမှန်ပဲ — ငြိမ်အောင် လုပ်တတ်ရင် ရပါတယ်။', 'Sometimes Mimi feels angry. Her body feels hot. Mimi breathes in deeply and counts 1-2-3. Slowly, she feels calm. Feeling angry is okay — we can learn to settle it.'),
    questions: [b('စိတ်ဆိုးတဲ့အခါ မီမီ ဘာလုပ်လဲ။', 'What did Mimi do when angry?')],
    activities: [b('အတူတူ အသက်ပြင်းပြင်း ၃ ကြိမ် ရှူ ကြည့်ပါ။', 'Take three deep breaths together.')],
  }),
  story({
    slug: 'taking_turns', storyType: 'social', ageGroupKey: '3y',
    title: b('အလှည့်ကျ ကစားရအောင်', 'Let’s Take Turns'),
    summary: b('သူငယ်ချင်း ၂ ယောက် အလှည့်ကျ ကစားပြီး ပျော်ရွှင်ပုံ။', 'Two friends have fun by taking turns.'),
    readingLevel: 'Beginner', readingMinutes: 3,
    vocabulary: [b('အလှည့်', 'turn'), b('သူငယ်ချင်း', 'friend'), b('ဝေမျှ', 'share')],
    body: b('အေးအေးနဲ့ ဘိုဘိုက ဘောလုံးနဲ့ ကစားချင်တယ်။ အရင်တော့ ၂ ယောက်စလုံး ဆွဲယူချင်တယ်။ ပြီးတော့ “မင်းအလှည့်၊ ငါ့အလှည့်” လို့ လှည့်ကစားကြတယ်။ အလှည့်ကျ ကစားတော့ ၂ ယောက်စလုံး ပျော်ကြတယ်။', 'Aye-Aye and Bo-Bo both wanted the ball. At first they both pulled it. Then they said “your turn, my turn” and took turns. Taking turns made them both happy.'),
    questions: [b('၂ ယောက် ဘယ်လို ပျော်အောင် လုပ်လဲ။', 'How did they both become happy?')],
    activities: [b('ဘောလုံး လှိမ့်ပေး ကစားနည်းဖြင့် အလှည့်ကျ လေ့ကျင့်ပါ။', 'Practice turns by rolling a ball back and forth.')],
  }),
  story({
    slug: 'goodnight_moon_friend', storyType: 'bedtime', ageGroupKey: '2y',
    title: b('ကောင်းသောည လရဲ့ လေး', 'Goodnight, Little Moon'),
    summary: b('ည အိပ်ရာဝင်ချိန် ငြိမ်သက်စေသော ပုံပြင်လေး။', 'A calming bedtime story.'),
    readingLevel: 'Beginner', readingMinutes: 3,
    vocabulary: [b('ည', 'night'), b('လ', 'moon'), b('အိပ်', 'sleep')],
    body: b('နေဝင်သွားပြီ။ ကောင်းကင်မှာ ကြယ်လေးတွေ တဖျတ်ဖျတ် လင်းလက်နေတယ်။ ငှက်ကလေးတွေလည်း အိပ်ပျော်နေပြီ။ ကလေးငယ်က စောင်လေးခြုံပြီး မျက်လုံးမှိတ်လိုက်တယ်။ “ကောင်းသောညပါ” လို့ လမင်းကြီးကို နှုတ်ဆက်လိုက်တယ်။', 'The sun has set. The little stars twinkle. The little birds are asleep. The child pulls up the blanket and closes their eyes. “Goodnight,” they say to the moon.'),
    questions: [b('ညဘက် ဘယ်သူတွေ အိပ်ကြလဲ။', 'Who goes to sleep at night?')],
    activities: [b('အိပ်ရာမဝင်မီ ဤပုံပြင်ကို တိုးတိုးလေး ဖတ်ပြပါ။', 'Read this softly before bed.')],
  }),
  story({
    slug: 'waiting_at_clinic', storyType: 'waiting', ageGroupKey: '3y',
    title: b('စောင့်ဆိုင်းရတဲ့အခါ', 'While We Wait'),
    summary: b('စောင့်ဆိုင်းရချိန်ကို ငြိမ်သက်စွာ ဖြတ်သန်းနည်း။', 'Ways to pass a waiting time calmly.'),
    readingLevel: 'Beginner', readingMinutes: 3,
    vocabulary: [b('စောင့်', 'wait'), b('တန်းစီ', 'queue'), b('ငြိမ်', 'patient')],
    body: b('တီတီတို့ ဆေးခန်းမှာ စောင့်နေရတယ်။ ရှည်လျားတဲ့ တန်းလေးပါ။ တီတီက လက်ချောင်းလေးတွေ ရေတွက်တယ်။ ပြီးတော့ မေမေနဲ့ တိုးတိုးလေး စကားပြောတယ်။ စောင့်ရတာ ရှည်ပေမယ့် ကစားစရာ ရှာတတ်ရင် အချိန်လေး မြန်သွားတယ်။', 'Ti-Ti waits at the clinic. It is a long line. Ti-Ti counts her fingers. Then she whispers with Mommy. Waiting is long, but finding little games makes the time pass.'),
    questions: [b('စောင့်ရင်း တီတီ ဘာတွေ လုပ်လဲ။', 'What did Ti-Ti do while waiting?')],
    activities: [b('စောင့်ရချိန်တွင် ရေတွက်/ရှာဖွေ ကစားနည်းများ ကစားပါ။', 'Play counting/find-it games while waiting.')],
  }),
  story({
    slug: 'visit_to_doctor', storyType: 'hospital', ageGroupKey: '3y',
    title: b('ဆရာဝန် ဆီ သွားခြင်း', 'A Visit to the Doctor'),
    summary: b('ဆရာဝန်ပြခြင်းကို ကြောက်စိတ်မဖြစ်စေဘဲ ရင်းနှီးစေသော ပုံပြင်။', 'A reassuring story about seeing the doctor.'),
    readingLevel: 'Beginner', readingMinutes: 3,
    vocabulary: [b('ဆရာဝန်', 'doctor'), b('ကျန်းမာ', 'healthy'), b('စစ်ဆေး', 'check')],
    body: b('ကိုကိုက ဆရာဝန်ဆီ သွားတယ်။ ဆရာဝန်က ပြုံး၍ “မင်္ဂလာပါ” လို့ နှုတ်ဆက်တယ်။ နားကို ကြည့်၊ ရင်ဘတ်ကို နားထောင်တယ်။ နာကျင်တာ မရှိဘူး။ ကိုကို ကျန်းမာနေတယ်လို့ ဆရာဝန်က ပြောတယ်။ ကိုကို ရယ်ပြီး ပြန်လာတယ်။', 'Ko-Ko goes to the doctor. The doctor smiles and says hello. She looks in his ears and listens to his chest. It does not hurt. The doctor says Ko-Ko is healthy. Ko-Ko smiles and goes home.'),
    questions: [b('ဆရာဝန်က ဘာတွေ စစ်ဆေးလဲ။', 'What did the doctor check?')],
    activities: [b('အရုပ်ဖြင့် “ဆရာဝန်” ဟန်ဆောင် ကစားပါ။', 'Play pretend “doctor” with a doll.')],
  }),
  story({
    slug: 'first_day_school', storyType: 'school', ageGroupKey: '4y',
    title: b('ကျောင်း ပထမနေ့', 'My First Day at School'),
    summary: b('ကျောင်းပထမနေ့ စိုးရိမ်စိတ်ကို ရင်းနှီးမှုဖြင့် ကူညီသော ပုံပြင်။', 'Easing first-day nerves with warmth.'),
    readingLevel: 'Beginner', readingMinutes: 3,
    vocabulary: [b('ကျောင်း', 'school'), b('ဆရာမ', 'teacher'), b('သူငယ်ချင်း', 'friend')],
    body: b('ယနေ့ ဆုဆုရဲ့ ကျောင်း ပထမနေ့ပါ။ အနည်းငယ် ကြောက်တယ်။ ဆရာမက ပြုံး၍ ကြိုဆိုတယ်။ သူငယ်ချင်းအသစ်လေးနဲ့ အတူ ပုံဆွဲကြတယ်။ နေ့လယ်ရောက်တော့ ဆုဆု ပျော်နေပြီ။ မေမေ ပြန်လာခေါ်တော့ “မနက်ဖြန် ထပ်လာမယ်” လို့ ဆိုတယ်။', 'Today is Su-Su’s first day at school. She feels a little scared. The teacher smiles and welcomes her. She draws with a new friend. By noon, Su-Su is happy. When Mommy comes, she says, “I’ll come again tomorrow.”'),
    questions: [b('ဆုဆု ကျောင်းမှာ ဘာလုပ်လဲ။', 'What did Su-Su do at school?')],
    activities: [b('ကျောင်းအကြောင်း အပြုသဘော စကားပြောပါ။', 'Talk about school in a positive way.')],
  }),
  story({
    slug: 'sharing_mango', storyType: 'sharing', ageGroupKey: '3_5y',
    title: b('သရက်သီး ဝေမျှခြင်း', 'Sharing the Mango'),
    summary: b('ဝေမျှခြင်းက ပျော်ရွှင်မှုကို နှစ်ဆ တိုးစေပုံ။', 'Sharing doubles the joy.'),
    readingLevel: 'Beginner', readingMinutes: 3,
    vocabulary: [b('ဝေမျှ', 'share'), b('သရက်သီး', 'mango'), b('ပျော်ရွှင်', 'happy')],
    body: b('ဖြူဖြူမှာ သရက်သီး တစ်လုံး ရှိတယ်။ ညီမလေး ကြည့်နေတယ်။ ဖြူဖြူက ၂ ပိုင်း ခွဲ၍ ညီမလေးကို ဝေပေးတယ်။ ၂ ယောက်စလုံး စားရင်း ရယ်ကြတယ်။ ဝေမျှတော့ ပျော်ရွှင်မှုက ပိုများသွားတယ်။', 'Phyu-Phyu has one mango. Her little sister watches. Phyu-Phyu cuts it in two and shares. They both eat and laugh. Sharing made the joy bigger.'),
    questions: [b('ဖြူဖြူ ဘာကို ဝေမျှလဲ။', 'What did Phyu-Phyu share?')],
    activities: [b('ယနေ့ အစားအစာ တစ်ခုကို ဝေမျှ ကြည့်ပါ။', 'Share a snack together today.')],
  }),
];
