export const ACTIVITY_ILLUSTRATIONS: Readonly<Record<string, string>> = {
  act_texture_touch:
    '/activities/birth_2m/act_texture_touch.8b8fd36899.webp',
  act_lullaby_and_rock:
    '/activities/birth_2m/act_lullaby_and_rock.f4e2f5b20a.webp',
  act_first_book_share:
    '/activities/birth_2m/act_first_book_share.0b1174986f.webp',
  act_skin_to_skin_calm:
    '/activities/birth_2m/act_skin_to_skin_calm.c855280097.webp',
  act_gentle_bicycle_legs:
    '/activities/birth_2m/act_gentle_bicycle_legs.ef67d5c21e.webp',
  act_face_to_face_talk:
    '/activities/birth_2m/act_face_to_face_talk.6dcd162b62.webp',
  act_tummy_time_mirror:
    '/activities/birth_2m/act_tummy_time_mirror.15e0a5568d.webp',
  act_sound_tracking:
    '/activities/3_4m/act_sound_tracking.4cc5e73a1c.webp',
  act_copy_my_sound:
    '/activities/3_4m/act_copy_my_sound.0f2257dcb6.webp',
  act_reach_for_the_toy:
    '/activities/3_4m/act_reach_for_the_toy.70d1608428.webp',
  act_peek_a_boo_cloth:
    '/activities/3_4m/act_peek_a_boo_cloth.e45d080f3e.webp',
  act_picture_book_naming:
    '/activities/3_4m/act_picture_book_naming.4df4715aae.webp',
  act_rhythm_and_rock:
    '/activities/3_4m/act_rhythm_and_rock.547948f6a7.webp',
  act_texture_basket_infant:
    '/activities/3_4m/act_texture_basket_infant.e670cf7869.webp',
  act_babble_back_and_forth:
    '/activities/5_6m/act_babble_back_and_forth.f5cb049412.webp',
  act_roll_and_reach:
    '/activities/5_6m/act_roll_and_reach.ee83a6db44.webp',
  act_mirror_hello:
    '/activities/5_6m/act_mirror_hello.8b5bc4a6ec.webp',
  act_board_book_point:
    '/activities/5_6m/act_board_book_point.1f396ad081.webp',
  act_clap_and_sing_5_6m:
    '/activities/5_6m/act_clap_and_sing_5_6m.d81f12554d.webp',
  act_safe_touch_basket:
    '/activities/5_6m/act_safe_touch_basket.c953264aef.webp',
  act_drum_and_pause:
    '/activities/7_9m/act_drum_and_pause.86c0ba193b.webp',
  act_lift_the_flap_book:
    '/activities/7_9m/act_lift_the_flap_book.6c33f2de2d.webp',
  act_name_and_wait:
    '/activities/7_9m/act_name_and_wait.9e9a12625f.webp',
  act_peekaboo:
    '/activities/7_9m/act_peekaboo.03b58f4431.webp',
  act_sit_and_reach_ring:
    '/activities/7_9m/act_sit_and_reach_ring.305571520c.webp',
  act_two_texture_spoons:
    '/activities/7_9m/act_two_texture_spoons.f811d80c0a.webp',
  act_wave_bye_bye:
    '/activities/7_9m/act_wave_bye_bye.af8bd5d742.webp',
};

export function activityIllustration(slug: string): string | undefined {
  return ACTIVITY_ILLUSTRATIONS[slug];
}
